### ISSUE TITLE
Begin built code with a semicolon

### ISSUE THREAD

**Issue by WickyNilliams** [knockout/knockout#1007]
Currently knockout can cause issues when concatenating as it does not start with a semicolon or exclamation mark. A simple addition of a leading semicolon will fix this problem. 

Whilst it is technically caused by another file being concatenated before knockout, adding a trailing `;`/`!` will ensure there are never problems with other libraries misbehaving

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!

**Comment by WickyNilliams** [comment]
Forgot I'd ever opened this! Definitely focus your efforts elsewhere :)
