### ISSUE TITLE
IE 8 bug using Knockout with Modernizr and HTML5

### ISSUE THREAD

**Issue by davidmatson** [knockout/knockout#1011]
I’m running into a bug using Knockout on IE 8 when also using Modernizr and HTML 5 elements. A minimal repro appears at the end. Basically, it looks like the conditions are these:
1. Use both Knockout and Modernizr.
2. View the page on IE 8.
3. Inside a foreach binding, have an HTML5 element.
4. Have the existence of foreach controlled by Knockout (using if or with bindings on a parent element or virtual element).

A few more things I found:
- The bug does not occur with Knockout alone; it only occurs when also using Modernizr.
- Don’t use IE 8 mode from IE 10’s developer tools/F12; the bug doesn’t repro there.
- The bug only occurs with foreach; it does not occur when using a with binding to reference a specific item in the list (data-bind=”with: list[0]”).

In this circumstance, the HTML5 starting element is created as a text element in the DOM. A screenshot follows.
![bug](https://f.cloud.github.com/assets/3360277/682855/14df5450-d9d1-11e2-81c9-1fbd20e7e736.png)

David

```
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>Bug Repro</title>
    <script src="http://ajax.aspnetcdn.com/ajax/knockout/knockout-2.2.0.js"></script>
    <script src="http://modernizr.com/downloads/modernizr-latest.js"></script>
    <script>
        function AppViewModel() {
            var self = this;
            self.list = ["a", "b", "c"];
            self.visible = ko.observable(false);

            self.show = function () {
                self.visible(true);
            }
        }
    </script>
</head>
<body>
    <button data-bind="click: show">Show</button>
    <div data-bind="if: visible">
        <div data-bind="foreach: list">
            <section data-bind="title: $data">
                <span data-bind="text: $data"></span>
            </section>
        </div>
    </div>
    <script>
        ko.applyBindings(new AppViewModel());
    </script>
</body>
</html>
```

**Comment by mbest** [comment]
I'm going to close this based on its age and the fact that it only affects IE 8 (or possibly lower).
