### ISSUE TITLE
Trigger the validation

### ISSUE THREAD

**Issue by Rakesh-gene** [knockout/knockout#1028]
Hi Guys,
My scenario is, I have a value binding property on top of which I have written a rule, which will check whether the control value is empty or not.
The initial value is undefined i.e, 
MyviewModel.Value = ko.observable();
MyviewModel.Value.extend({rule});

Now the problem is form loads for the first time, user tabs out of the textinput control, the rule is not getting triggered. I know the value has not changed so the rule is not triggered, but since initial value was undefined and the new value is " ", I am expecting it to trigger the rule. 
If this is not possible any alternative way?

**Comment by SteveSanderson** [comment]
Thanks for posting - sorry it took forever to respond. Since this doesn't appear to be a bug, and you're probably not still waiting for a response, I'll close this. Please reopen if you disagree.
