### ISSUE TITLE
preprocessNode chaining

### ISSUE THREAD

**Issue by mbest** [knockout/knockout#1030]
Suppose you want to use two plugins that use `preprocessNode`: for example, one for  `{{expr}}` syntax and another for `<!--ko/ bindings..-->` syntax. Both plugins should be able to coexist since they deal with completely different node types (text and comment). But we haven't yet defined how this kind of situation should work.

One option is for the chaining logic to be coded in the plugin's `preprocessNode` function itself. It would be something like this:

```javascript
newProvider.preprocessNode = function(node) {
    var newNodes = previousProvider.preprocessNode && previousProvider.preprocessNode(node);
    if (!newNodes) {
        // do my stuff
    }
    return newNodes;
}
```

Another option would be to export a function that adds a preprocess function to the chain. The plugins could then use this and not worry about chaining themselves. Here is an example:

```javascript
ko.setNodePreprocessFunction = function(preprocessFn) {
    var provider = ko.bindingProvider.instance;
    if (provider.preprocessNode) {
        var previousPreprocessFn = provider.preprocessNode;
        provider.preprocessNode = function() {
            var newNodes = previousPreprocessFn.apply(this, arguments);
            if (!newNodes)
                newNodes = preprocessFn.apply(this, arguments);
            return newNodes;
        };
    } else {
        provider.preprocessNode = preprocessFn;
    }
}
```

A third option is to assume that no plugin implements chaining. Then a user who wants to use multiple plugins would have to do the chaining themselves:

```javascript
newProvider.preprocessNode = function(node) {
    var newNodes = pluginProvider1.preprocessNode(node);
    if (!newNodes) {
        var newNodes = pluginProvider2.preprocessNode(node);
    }
    return newNodes;
}
```

I don't like the third option since it makes it harder for the user to use these kinds of plugins. The second option is the easiest for the plugin authors, and is the one I think we should do. If we decide to go with the first option, we'd need to be sure to include this code in any examples that we publish.

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
