### ISSUE TITLE
Options binding - wrong value

### ISSUE THREAD

**Issue by MirandaBrazil** [knockout/knockout#1046]
Hi

See this : 

```
<td data-bind="with: SelectedState">
    <select data-bind='options: CitiesList, optionsText: "CityName",optionsValue: "CityID", optionsCaption: "Select...",value: $parent.SelectedCity'></select>
</td>
```
If i dont specificate attribute optionsValue the $parent.SelectedCity is an arrayObject the expected value, but when this options is set value of SelectedCity becomes the value of "optionsValue" , in this case the value of binding "CityID"

I searched over the web and older versions of knockout works fine , but in 2.* this problem ocurrs

Anyone can explain this?

Thx

In jsfiddle have a lot of examples , if you change knockout version from <= 1.7 to 2.0 the value of currentItem is the key

**Comment by SteveSanderson** [comment]
As @jrsearles comments, the behavior looks correct (and you're probably not still waiting for an answer after this long!), so I'll close this. Please reopen if you disagree :)
