### ISSUE TITLE
Global configuration

### ISSUE THREAD

**Issue by stijnherreman** [knockout/knockout#1056]
It'd be nice if there was a way to globally define configuration/options.

Take `ko.computed( evaluator [, targetObject, options] )` for example. I'd like to set `deferEvaluation` to always be `true` without passing an `options` object every time.

If there's an existing type of global configuration, I can make a pull request, but I didn't find any.

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
