### ISSUE TITLE
bug in Chrome with select with options height

### ISSUE THREAD

**Issue by khalilghenimi** [knockout/knockout#1061]
I have a select that won’t display the option clearly:

it is displayed good on firefox.

The bug is that Chrome calculates the height of the option that it's style is "display:none".

So if i have 150 options and only 6 options are displayed it will be bugged.

**Comment by SteveSanderson** [comment]
Thanks for reporting this. It does sound like a Chrome bug, but the good news is it seems fine in current Chrome, so I guess they fixed it.
