### ISSUE TITLE
Add a ko.computedArray function

### ISSUE THREAD

**Issue by twifkak** [knockout/knockout#1074]
I have some code that looks like this:

```js
ko.observable.fn.autoEdit = function() {
  var self = this;
  var computed = ko.computed({
    'read': self,
    'write': function(value) {
      self.beginEdit();  // This is a ko.editables thing.
      self(value);
    }
  });

  if (ko.isObservableArray(this)) {
    _(ko.observableArray.fn).functions().forEach(function(name) {
      computed[name] = function() {
        // We call beginEdit if _and only if_ the underlying function writes to
        // the array.
        var subscription = self.subscribe(function() {
          self.beginEdit();
        }, null, 'beforeChange');
        var value = self[name].apply(self, arguments);
        // Stop listening for beforeChange events. If people modify the
        // underlying observable without going through this computed, beginEdit
        // should not be called.
        subscription.dispose();
        return value;
      };
    });
  }

  return computed;
};
```

It is ridiculously hacky, and probably buggy. (I had to make changes to support read-only functions after the update to 2.3 caused the 'checked' binding handler to make use of ko.observableArray.fn.indexOf. There are probably other lurking bugs that future KO updates will reveal.)

This code would be _much_ simpler if there were a supported way of making a computed observableArray. @mbest made some mention of this in #695, but that feature request is a much bigger superset of this one. Ideally, I would write:

```js
ko.observable.fn.autoEdit = function() {
  var self = this;
  return (ko.isObservableArray(self) ? ko.computedArray : ko.computed)({
    'read': self,
    'write': function(value) {
      self.beginEdit();
      self(value);
    }
  });
}
```

(Perhaps, even, some notion of an observable "proxy" would be useful, with its own set of events to listen / modify. But that's another request for another day.)

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
