### ISSUE TITLE
Package knockout.debug.js separately

### ISSUE THREAD

**Issue by togakangaroo** [knockout/knockout#1078]
This is in practice the same issue as [this thread on knockout file naming](https://github.com/knockout/knockout/issues/437#issuecomment-13357857) but everyone there seems focused on naming convention and there's a far larger practical problem with packaging `knockout.debug`  and regular `knockout` together. 

**Package Managers**

I wrote [this binding to open/close dialogs based on a viewmodel property](https://gist.github.com/togakangaroo/6096040). Because it has to work similarly to the `with` binding it has to depend on the `ko.utils.cloneNodes` method. This is available in `knockout.debug` but NOT regular `knockout`.

So how then do I express the dependency to nuget/bower/npm? 

If I express it as "knockout" then people will reasonably assume they can just use the regular package and it won't work out of the box. I then have to put it in my documentation that they need to use the `knockout.debug` version which cdnjs doesn't even serve! By that time people have moved on.

The thing is, since the two versions have different APIs they are actually *two different releases* and should be packaged as such.

By the way you guys need a big thing on the website explaining the difference. It took me forever to figure out why my binding worked in my project but not any sample project I set up using a cdn.

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
