### ISSUE TITLE
Document ko.* helper functions

### ISSUE THREAD

**Issue by brigand** [knockout/knockout#1080]
For the first few months of using KO, I was writing plugins using $.each for object iterating, and a bunch of other things.  It would have been much better to use the functions provided by Knockout for these.  Are there docs for the utility functions available?  

If not, and I wrote some, would they be (potentially) accepted?

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
