### ISSUE TITLE
Value Binding Always Gives String

### ISSUE THREAD

**Issue by brigand** [knockout/knockout#1084]
Sometimes it makes sense to have a text input represent a non-string value.  For example, the HTML5 range selector is an element that represents a numerical value.  It kind of goes against the idea that HTML and data are separate if we have to explicitly cast strings to numbers after setting an observable to a number.

[fiddle with range slider](http://jsfiddle.net/UVpgM/1/) 

I suggest using the current constructor of the observable.  In JavaScript, this looks like

 ```javascript
new (observable().constructor)(stringData);
```

For Numbers, that's equivalent to `Number(stringData)`.  

For non-numbers, it becomes even more powerful.  It would enable this:

```javascript
function DateClass(strDate){
    parts = strDate.split("/");    
    
    this.month = Number(parts[0]);
    this.day = Number(parts[1]);
    this.year = Number(parts[2]);
}

DateClass.prototype.toString = function(){
    return [this.month, this.day, this.year].join('/');
}

var foo = ko.observable(new DateClass("10/44/77");
```

And we would always be able to trust that `foo()` would give us a DateClass object.

Here's [a fiddle](http://jsfiddle.net/LHtHp/) showing how the updating works.  It's just a JavaScript implementation, not using Knockout.  The basic idea is there, though.  

I really don't think this belongs in a plugin, because I believe it's a core construct that should be consistent.  Also, it isn't likely to break any sensible code.  The one exception is if people were setting objects to observables, and relying on `.toString`.  It would break those because they wouldn't be getting a string back.  But for numbers, you can call parseInt/parseFloat/Number on a number and it just returns the number.  Even passing a float to parseInt [gives you an integer](http://jsfiddle.net/FQPK9/), so there's no problem with Strings and Numbers.

**Comment by SteveSanderson** [comment]
Generally we recommend writable computeds as a powerful way to filter data going into and out of bindings. I'll close this for tidiness, but if anyone is still finding this inadequate please reopen with details of what you'd like tot change. Thanks :)
