### ISSUE TITLE
Observables should have a valueOf and toString method

### ISSUE THREAD

**Issue by mariusGundersen** [knockout/knockout#1090]
Currently you need to call an observable as a function without any arguments to get its value. But this gets clunky when using them in bindings, for example here:

    Positive <span data-bind="text: someNumber"></span>
    Negative <span data-bind="text: -someNumber()"></span>

Without the minus sign the observable can be used without the parethesis at the end. But with the minus sign, the parenthesis are needed. But it's very easy to make observables work without the parethesis, using the valueO and toString methods:

    ko.observable.fn.valueOf = function(){return this();}
    ko.observable.fn.toString = function(){return this();}

With this in place we can now use the observable like it was a primitive value:

    Positive <span data-bind="text: someNumber"></span>
    Negative <span data-bind="text: -someNumber"></span>

This also works in and with computed properties:

    ko.computed.fn.valueOf = function(){return this();}
    ko.computed.fn.toString = function(){return this();}

    var inverseNumber = ko.computed(function(){
        return 1/someNumber;
    });

    Inverse <span data-bind="text: inverseNumber"></span>
    Original <span data-bind="text: 1/inverseNumber"></span>

The only issue I have found with this is that the unary ! doesn't seem to work, since it tests the thruthiness of the observable, not the thruthiness of the value of the observable. So instead of `!someValue`, `someValue == false` must be used.

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
