### ISSUE TITLE
Rewrite makeTemplateSource method to be more useful

### ISSUE THREAD

**Issue by stalniy** [knockout/knockout#1091]
I found this comment in knockout sources:
```js
// ... overriding "makeTemplateSource" to return an instance of your custom template source.
```
Actually there is no need to rewrite `makeTemplateSource` method for every custom template source (it's a bit laboriously). I see a simple way how this can be changed for example in 3.0 version of knockout. 

If somebody wants to add custom template source he should register it and define function which checks if template source can be used:

```js
function MyTemplateSource() {
  // custom logic here
}
ko.templateSources.registerSource(function (template, doc) {
  if (template.indexOf('.html') !== -1)  {
    return new MyTemplateSource(template, doc);
  }
});
```

So, inside `makeTemplateSource` knockout will iterate through known template sources and check if filter-function returns an object:
```js
var sources = [];
function registerSource(filter) {
   sources.push(filter);
   return this;
}

function makeTemplateSource(template, doc) {
   var i = -1, count = sources.length, source;
   while (++i < count && !source) {
     source = sources[i](template, doc);
   }
   if (!source) {
     throw new Error("Unable to find appropriate template source for " + template);
   }
   return source;
}
```
In this case custom template source should be only registered with appropriate checking function and there is no need to override `makeTemplateSource` method.

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
