### ISSUE TITLE
IE - select will not show current selection when option elements hard coded with dynamic text

### ISSUE THREAD

**Issue by togakangaroo** [knockout/knockout#1095]
[Here is a reduced test case on jsfiddle](http://jsfiddle.net/ZqaBM/1/)

Consider this html

``` html
<div data-bind="with: model">
<p>Is this blank? It's set to an option with ko-bound selected text</p>
<select data-bind="value: 2">
    <option value=1>Not bound by KO</option>
    <option value=2 data-bind="text: someText"></option>
</select>
</div>
```

and the case where `applyBindings` is invoked before `model` is filled out.

``` javascript
var _vm = { model: ko.observable(null) };
ko.applyBindings(_vm);
_vm.model({
     someText: ko.observable("Bound by KO")
});
```

In all versions of IE (I assume - I've tested 9 and 10) the options will render properly, the selection will be correct in the dom, but the text visible initially in the selectbox will be blank!

Again, the jsfiddle demonstrating the issue: http://jsfiddle.net/ZqaBM/1/

**Comment by SteveSanderson** [comment]
Is anyone still finding this to be an issue? I appreciate it may well be a legitimate problem in some old IE versions that KO could take steps to work around, but given our limited time we need to focus our efforts on issues that are active problems for KO users, so it would be good to know how much (if any) pain this causes.

**Comment by ricardobrandao** [comment]
@SteveSanderson yes, this is happening to me on IE9. 

Are there any plans to fix this issue in the near future?

P.S. I'm using knockout 3.3.0.

**Comment by mbest** [comment]
This works in IE11. Closing due to age and low severity.
