### ISSUE TITLE
Radio Button Issue : checked binding not updated in the UI

### ISSUE THREAD

**Issue by Rakesh-gene** [knockout/knockout#1098]
We are using KO- 2.1 and Jquery 1.9.1, The issue is we are having a function which gets executed when B2.Value changes(B2.OnControlValue). The function is getting executed as expected, but the UI checked binding is not working when the B2.Value is getting changed. This will work when we a dummy click event is written.

JS Fiddle link
http://jsfiddle.net/Qa7n8/

Regards,
Rakesh

**Comment by Senthe** [comment]
This is still an issue 2.5 years later and with no `click` binding set on input.

**Comment by mbest** [comment]
@Senthe Can you elaborate?
