### ISSUE TITLE
Replacing ko.mapping

### ISSUE THREAD

**Issue by RoyJacobs** [knockout/knockout#1099]
Hi guys, I thought discussion about [ko.mapping](https://github.com/SteveSanderson/knockout.mapping)'s future as an official KO plugin would be appropriate as a 'planning' issue here. Feel free to move.

As I mentioned [here](https://groups.google.com/forum/?fromgroups#!searchin/knockoutjs/knockout.mapping/knockoutjs/0cZAAVloRDw/KeswfigPmpoJ) I currently am stretched too thin to work on ko.mapping in any large capacity. There are a fair amount of pull requests piling up and although I'd love to merge them all, they really need a bit more attention than that.

@mbest suggested that Dave Herren's [ko.viewmodel](https://github.com/coderenaissance/knockout.viewmodel) would be a suitable replacement and I tend to agree. Its design is less crufty than ko.mapping, especially in situations where people are mapping huge amounts of data. I always recommended against this use case, since it's just so slow, but there's a demand and I think ko.viewmodel solves this pretty well with its `makeNoncontiguousObjectUpdates` parameter.

Finally, I don't feel it's acceptable to just abandon the existing mapping plugin since there are plenty of users (my company included), so someone should ideally fork it or get commit access to the current repo. If nobody is found I can still take the occasional pull request every now and again.

Tasks:
- [ ] Make ko.viewmodel the official mapping plugin
- [ ] Get someone to fork or take over ko.mapping (or at least moved out of @SteveSanderson's repo, I guess?)
- [ ] Write documentation explaining how to migrate

I'd like to invite you to give some feedback.

**Comment by SteveSanderson** [comment]
Closing for tidiness, as there's no immediate action to be taken here. If anyone has interest in starting a new project in this 'mapping' area perhaps they could post to the KO forum to let people know :)
