### ISSUE TITLE
A 2 line documentation per folder

### ISSUE THREAD

**Issue by itissid** [knockout/knockout#110]
It would be really useful if you could put in a 2 line document per folder explaining what the contents of the package do and how they come together.  I feel an important part of making a project open source is letting other people know why your code is the way it is, how it all pieces together and what obstacles you over came  while making this wonderful framework..

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
