### ISSUE TITLE
Knockout Template Execution in IE 8

### ISSUE THREAD

**Issue by fasikk** [knockout/knockout#1107]
Hi

I am using knockout 2.2.1 library with jquery 1.8.2 in my mvc application.

My all knockout binding/rendering work fine in IE 9 and IE 10.

However i am having some issue in IE 8. One of them is attached, please can you see what is wrong here.

Regards
![knockout_template](https://f.cloud.github.com/assets/168743/1165464/3455d4ac-206d-11e3-9f84-5014bcb66427.JPG)

**Comment by SteveSanderson** [comment]
Sorry we didn't help you track this down. It's been so long since this thread was active that I don't think it's realistically possible that you're still waiting for help, so I'll close it for tidiness. Please reopen if there is still an issue that you think is a KO bug!
