### ISSUE TITLE
valueUpdate: 'afterkeydown' and Mobile Safari on iOS 7

### ISSUE THREAD

**Issue by ungripped** [knockout/knockout#1118]
I'm currently investigating an issue we're having on iOS 7, where an input with a value binding and valueUpdate: 'afterkeydown' is behaving... strangely?

From what I can tell, there seems to have been some changes in the event queue in mobile safari, and the behavior of setTimeout(func, 0) has changed. Either that or the update of HTMLInputElement.value has changed

I'm not getting a consistent result from my tests, it seems to be timing related.

Here's a basic Knockout JSFiddle: http://jsfiddle.net/bCm9f/1/

And a pure JS version that boils down the issue: http://jsfiddle.net/LpQ9u/5/

Log from the Safari debugger (entering the string "Test"):
    [Log] val: 'T' (show, line 26)
    [Log] val: 'T' (show, line 26)
    [Log] val: 'Te' (show, line 26)
    [Log] val: 'Tes' (show, line 26)

Increasing the timeout delay fixes the update problem, but that's obviously not a solution. Any ideas?

**Comment by stevepapa** [comment]
Can confirm `valueUpdate: ['input', 'afterkeydown']` resolves this issue on IOS8 also
