### ISSUE TITLE
Additional Warnings in the Debug Version

### ISSUE THREAD

**Issue by brigand** [knockout/knockout#1119]
There should be more checks and warnings in the debug version for common mistakes.  They can be added over time, but the framework can be set up now.  

Closure will remove dead code, which can be used to remove blocks of debug code.

We'd need two versions of the function wrapper: the debug and the production version.

Production:

```javascript
(function(undefined){
  var DEBUG = false;
  //...
```

Debug:

```javascript
(function(undefined){
  var DEBUG = true;

  // do this or oldIE will throw an error for console being undefined
  if (typeof console == "undefined") {
    console = {
        log: function () {},
        warn: function () {}
    };
  }
  //...
```

Then if you have a block of code like this:

```javascript
function add(a, b) {
    // NaN test
    if (DEBUG && isNaN(a) || isNaN(b)) {
        console.warn("add() called with arguments " + a + " and " + b);
    }
    return a + b;
}
```

... closure will remove the extra check in the production build, which reduces code size and performance cost; plus the dependency on console; which is undefined in oldIE.

I don't have a definitive list of warning level problems

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
