### ISSUE TITLE
toJSON hook for observables

### ISSUE THREAD

**Issue by jeffijoe** [knockout/knockout#1129]
I have run into a case where I found it necesary to implement a toJSON hook on observable-level.

Example: I wrote my own "observable", that just returns a computed with a read and write function, which reads and writes from an underlying object structure (don't ask, the requirement for this task is just ridiculous). Now, when I read and write from/to it using plain Knockout bindings, etc -  I just get and set strings. When I want to send my object graph to the server again, I need to not return strings, but the underlying structure.

So, I am proposing a toJSON hook that can be implemented per observable. Like so:

```javascript
// This is not the important part, this is up to the implementor.
ko.myCustomObservable = function(initialValue) {
   var computed = ko.computed(/*Read write methods, blah..*/);
   computed.toJSON = function() {
      return ko.toJSON(computed.underlyingObject);
   };
   return computed;
};
```

Here is how I made this happen, so my object structure that used this myCustomObservable did not have to implement a toJSON method for each model.

This is the changed stub from the ko.toJS method:

```javascript
        // We just unwrap everything at every level in the object graph
        return mapJsObjectGraph(rootObject, function(valueToMap) {
            // Loop because an observable's value might in turn be another observable wrapper
            for (var i = 0; ko.isObservable(valueToMap) && (i < maxNestedObservableDepth); i++) {
                if (valueToMap.toJSON instanceof Function)
                    valueToMap = valueToMap.toJSON();
                else
                    valueToMap = valueToMap();
            }
            return valueToMap;
        });
```
 Could this be considered for inclusion in ko core?

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
