### ISSUE TITLE
Add an ability to register helper functions which can be used inside data-bind definition [Internationalization]

### ISSUE THREAD

**Issue by stalniy** [knockout/knockout#1150]
It would be nice to have an ability to register helper functions which can be used inside `data-bind` definition. For example, just set up requirements for i18n  support:
1. I want to be able to translate nodes attributes, innerText and innerHtml
2. I want to be able change language without page reloading
3. It should be ease and transparent interface which then can be easily replaced  different i18n libraries.

So, in this case I need at least 3 custom data-bindings, but if I need to pass translated text into another custom binding I will have to created replacement for it with i18n support. Which is not really flexible.

So, I came with decision that it would be nice to have function `$t` inside my `data-bind` definitions. For example,
```html
<a href="/logout" data-bind="text: $t('logout')"></a>
```
In such case I can pass translated strings in any bindings.

It would be quite easy to achieve this goal if `ko.bindingContext` was exported in production version of knockout. In such case I can do like this:
```js
// translation.js

var currentLanguage = ko.observable();
function translate(string){
  currentLanguage(); // create dependecy which is handled by dependency tracker, so when language is changed all dependent bindings will be updated
  // some internal logic
}

ko.bindingContext.prototype.$t = translate;
```
Currently I'm using this approach on my project with modified version of knockout where `ko.bindingContext` is exported and it works great. However I think it would be nice to have support of this from the box.

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
