### ISSUE TITLE
"Performance" of splice

### ISSUE THREAD

**Issue by vamp** [knockout/knockout#1154]
Yep, it's all about perf.

1. http://jsperf.com/array-empty-splice-vs-length-0
it's about:
```
mappedNodes.splice(0, mappedNodes.length);
```
may be changed to:
```
mappedNodes.length = 0;
```
2. (pop of splice):
```
for (var i = disposalCandidates.length - 1; i >= 0; i--) {
    if (disposalCandidates[i])
        _subscriptionsToDependencies.splice(i, 1)[0].dispose();
}
```
may be changed to:
```
for (var i = disposalCandidates.length - 1, n = _subscriptionsToDependencies.length - 1; i >= 0; i--) {
    if (disposalCandidates[i]){
        ((i === n--)
            ? _subscriptionsToDependencies.pop()
            : _subscriptionsToDependencies.splice(i, 1)[0]).dispose();
    }
}
```

3. splice(0,1) or shift() ? http://jsperf.com/shift-vs-splice-0-1
```
while (continuousNodeArray.length && continuousNodeArray[0].parentNode !== parentNode)
    continuousNodeArray.splice(0, 1);
```

may be changed to:
```
while (continuousNodeArray.length && continuousNodeArray[0].parentNode !== parentNode)
    continuousNodeArray.shift();
```

(P.S. shim for Function.prototype.bind can be changed too.
http://jsperf.com/function-prototype-bind )

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
