### ISSUE TITLE
'if' binding handler should have a afterAdd/beforeRemove

### ISSUE THREAD

**Issue by jsgoupil** [knockout/knockout#1164]
Today, the 'if' binding handler can use "afterRender" to do any operations when it has rendered. However, if the 'if' resolves to false, no callbacks are being called.

It would be interesting to add "afterAdd" and "beforeRemove". It would allow developers to add animation as well.

In the meantime, the workaround is to use a 'foreach' binding handler with only 1 data.

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
