### ISSUE TITLE
Mobile Chrome multiple select bug

### ISSUE THREAD

**Issue by vbykov** [knockout/knockout#1185]
**Device used:** Galaxy S3, Nexus 7

**Description:**
Exist multiple select with `options` and `selectedOptions` bindings, and button "clear" with `click` binding, which cleared selectedOptions value (see [demo](http://jsfiddle.net/huqwH/))

if you try select some values in our select and then tap clear button, selectedOptions value will cleared, but first element on select will selected

if used 

```
$('[multiple] option:selected').parent().val([])
```

for "Clear" button, it works fine

**Comment by mbest** [comment]
Tested in latest version of mobile Chrome, and it works fine.
