### ISSUE TITLE
Backward compatibility omission (2.2.1 to 3.0.0)

### ISSUE THREAD

**Issue by RamIdeas** [knockout/knockout#1187]
I moved from 2.2.1 to 3.0.0rc in my app and everything seemed to work fine

/--
apart from a couple places where I was calling `applyBindings` multiple times (on Bootstrap Popovers). On a side note, it would be helpful to have a function to tell if an element has had `applyBindings` called already. That was an easy fix, but another took me a while to figure out.
--/

I have a list of (constructor-)functions/classes in my viewmodel:

```js
var array = [
    Func1,
    Func2,
    Func3
];
```

I iterate over these in a template

```html
<!-- ko foreach: array -->
    <button data-bind="text: $data.prototype.getName(), click: $root.createObject"></button>
<!-- /ko -->
```
where `$root.createObject` would accept the function as a parameter.

The markup in the `foreach` loop wasn't running. Instead, I was getting a (seemingly unrelated) error elsewhere in my code base.

Turns out, knockout 3.0 now calls functions passed to the `foreach` binding.

The weird error I was getting was my classes/constructor-functions were being called without `new`.

`ko.bindingContext` previously accepted `dataItem` as it's first parameter. Now it accepts `dataItemOrAccessor` and sets `var dataItem = isFunc ? dataItemOrAccessor() : dataItemOrAccessor;`.

Maybe this should be mentioned in the backward compatibility notes on the [knockout website](http://knockoutjs.com/upgrade-notes/v3.0.0.html)

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
