### ISSUE TITLE
Weird issue with setting class via "css"

### ISSUE THREAD

**Issue by goneale** [knockout/knockout#1189]
Hi guys,

When TitamItemNoFound=true, it sets class as "fa fa-times" correctly. However when it equals false, it only sets class as "fa-check" and not "fa fa-check". "fa" classes regard the Font Awesome 4.0 project.

Please take a look:
TitemItemNoFound=false:
```html
<i data-bind="css: { 'fa fa-spinner fa-spin': TitanItemNoLoading, 'fa fa-check': TitanItemNoFound, 'fa fa-times': TitanItemNoFound() != null &amp;&amp; !TitanItemNoFound() }" class="fa fa-times"></i>
```

TitemItemNoFound=true:
```html
<i data-bind="css: { 'fa fa-spinner fa-spin': TitanItemNoLoading, 'fa fa-check': TitanItemNoFound, 'fa fa-times': TitanItemNoFound() != null &amp;&amp; !TitanItemNoFound() }" class="fa-check"></i>
```

I couldn't imagine why (regardless of my knockout condition) why it would only pick up the 'fa-check' and not 'fa fa-check' just as it did 'fa fa-times'.

Graham

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
