### ISSUE TITLE
EcmaScript harmony & knockout

### ISSUE THREAD

**Issue by vamp** [knockout/knockout#1204]
Is any plans to use Object.observe/unobserve/notify/deliverChangeRecords in ko?

**Comment by NoelAbrahams** [comment]
Knockout has been getting [some bad publicity](https://www.codementor.io/reactjs/tutorial/reactjs-vs-angular-js-performance-comparison-knockout) with regard to performance.

Should this issue be revisited? 

> unfortunately [Object.observe] doesn't contain the fidelity needed to preserve Knockout's capabilities.

What capability would be lost if `Object.observe` were to be incorporated into knockout?

**Comment by jods4** [comment]
@NoelAbrahams More perf is always a good thing!

That benchmark you linked is very narrow. Mostly it completely re-creates a 1000 elements `foreach`, which is a known KO issue. See: #1669, #1638, #1600, #1584, #1073, #1194.

I think that if you want to improve this benchmark, this is the first thing to tackle.

I haven't seen anyone benchmarking how big a perf boost we can expect from `Object.observe`. My bet is that there's more to win on the DOM manipulation side (using document fragments, batching changes, etc.)

> Which capabilities would be lost if Object.observe were to be incorporated into knockout? 

The main issue was that Object.observe does not provide read detection, so a workaround to provide that functionality is required.

**Comment by NoelAbrahams** [comment]
@jods4,

> The main issue was that Object.observe does not provide read detection, so a workaround to provide that functionality is required

Yes, I saw that comment above. Does this only affect certain features (e.g. computed observables) or everything? If it were the former then maybe KO could provide a version `ko-ES7` that is based on `Object.observe`. I hazard a guess that a lot of people use KO for the core binding and templating, and if that functionality can be preserved then `ko-ES7` might be a hit.

The point is even if that particular benchmark is flawed we can't go wrong with delegating work to the native JS engine.

**Comment by jods4** [comment]
@NoelAbrahams 
I said the benchmark is very narrow, not flawed. By that I mean: there _are_ perf issues with `foreach` and I would like to see them fixed.

Regarding `Object.observe`, it's interesting and probably worthy of a prototype to see how much of a difference it does. I am really not sure what perf impact it will have (better, worse, none?).

One important aspect is that KO has always had compatibility in mind (back to IE6), so that would need to be taken into account (fallback, maintaining two KO versions?) given the non-existent support in browsers today.

**Comment by krnlde** [comment]
Since Object.observe in the meantime is a Strawman proposal for ECMAScript 7, we really should consider this as an improvement for new browsers. Older ones not supporting it could still behave the same. Knockout's binding can really be considered as a polyfill for Object.observe and we can build on top of that with no drawbacks. Object.observe de facto *is* a performance boost and *will* be standard so it's worth thinking about.

**Comment by NoelAbrahams** [comment]
>  Knockout's binding can really be considered as a polyfill for Object.observe

Knockout means a lot of things for lots of people. For some who [advocate a no-framework policy](http://bitworking.org/news/2014/05/zero_framework_manifesto) the binding polyfill is all that is needed.

We use KO as a simple binding mechanism. And its great for that. I'd really like to see `Object.observe` incorporated, at the expense of the more advanced (framework) capability that may need to be compromised. This would be effectively a forking of KO - perhaps "KO Lite".

**Comment by krnlde** [comment]
Why do you see this as a fork whos development will run in parallel to the original ko? Object.observe can be sensed and enabled on page load - once, after that it would behave like the original observable update mechanism that ko implements. I don't see a use case for a "KO Lite" tbh.

**Comment by NoelAbrahams** [comment]
Ideally, yes, `Object.observe` should be used under the covers if available. However, according to @SteveSanderson (see https://github.com/knockout/knockout/issues/1204#issuecomment-29029571), all of KO's capability cannot be preserved. Hence the request for a 'lite' version.

**Comment by krnlde** [comment]
Ah! thanks for this hint. Reading and changing could also be observed via [Proxies](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Proxy) or a combination of Proxies and O.o. These techniques are still pretty much work in progress though.

**Comment by Dmitri-Sintsov** [comment]
As IE6..8 are pretty much dead already, it would be nice to merge https://github.com/SteveSanderson/knockout-es5/ into Knockout.js core.

The plugin is very little known, I am developing with Knockout.js in years and only now discovered that it exists. It would get more promotion / popularity for Knockout if property based binding would be default one, described in official documentation, while functional binding a backward-compatible one.

Lots of the people who use Angular / Vue criticize Knockout for extra functional calls required to work with observables.

**Comment by brianmhunt** [comment]
Still in alpha but have a look at  https://github.com/knockout/tko/blob/master/packages/tko.computed/docs/proxy.md

**Comment by Dmitri-Sintsov** [comment]
Thank you @brianmhunt but isn't Proxy objects are not even supported in IE11? IE11 is default Windows browser till 2020 I think. While https://github.com/SteveSanderson/knockout-es5/ probably should support IE9 - I just found it and investigating whether I should update my code to use it.

**Comment by brianmhunt** [comment]
@dmitri-sibtsov- yes proxy will only work for modern browsers.

There are issues with ko-ES5, such as difficult access to the underlying observable to eg extend or subscribe to it.  It probably deserves a bit of a rework before including in ko/tko mainline.

Good to know there is interest in this vein of development

**Comment by Dmitri-Sintsov** [comment]
Proxy looks like a cleaner solution, but google says that it's impossible to polyfill Proxy in ES5 browsers like IE9..IE11:(  It's a bit strange policy that this repository is ultra-conservative to support out-of life cycle IE6..8 which almost nobody uses now (they are unusable at many sites), while tko is ultra-experimental even to drop current IE11 (which will be long time supported).

All of that probably negatively affects knockout popularity.

**Comment by brianmhunt** [comment]
Knockout 4 (which will be based on the tko packages) will not have support for proxy, and have support back to ie9.  The tko reference version will have proxy but in general be possible to customize as needed.

We would still need es5 for plain object wrapping & monitoring for ie11; there are some thoughts about this but the clearest course is not apparent.
