### ISSUE TITLE
Chrome Video Playback with Knockout

### ISSUE THREAD

**Issue by leavister** [knockout/knockout#1219]
Chrome and Knockout have an issue with HTML5 video playback.  The issue occurs under the following circumstances:

1) An HTML5 Video Element exists with its default values and controls
2) The video element exists inside a "ko with" block.  It doesn't matter if there are any data binding expressions on the video or anywhere else in the block.
3) The video needs to be large enough so that it cannot be fully buffered when loaded, or more than approximately 30 seconds.
4) Play the video once until it completes.  After completion, attempting to play the video again causes it to freeze.

See the following jsFiddle for a reproduction:
http://jsfiddle.net/VEL9G/

**Comment by mbest** [comment]
Works in latest Chrome. Must have been a Chrome bug.
