### ISSUE TITLE
ko.bindingHandlers.myBinding.preprocess isn't called when applying 'myBinding' via ko.applyBindingsToNode()

### ISSUE THREAD

**Issue by stefan-hausmann** [knockout/knockout#1227]
I wanted to use the new ko 3.0's binding preprocessing feature (mainly for extending the built-in value binding to have a valueUpdate: 'afterkeydown' binding attached automatically), but wondered why the ko.bindingHandlers.value.preproces() is never being called in my application.

I do not use the value-Binding in templates directly, but instead use a custom binding that internally applies the value-Binding via ko.applyBindingsToNode() to certain dom elements.

Is there a specific reason that the binding preprocessing isn't triggered on bindings applied via ko.applyBindingsToNode()?

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
