### ISSUE TITLE
`foreach` does not work with array of functions

### ISSUE THREAD

**Issue by bikeshedder** [knockout/knockout#1228]
When using the `foreach` binding handler to iterate over a list of functions it does no longer work.

http://jsfiddle.net/bikeshedder/eYZW9/

### HTML

```html
<ul data-bind="foreach: funcs">
    <li data-bind="text: NAME"></li>
</ul>
```

### JavaScript

```javascript
function a() {}
a.NAME = "a";

function b() {}
b.NAME = "b";

var model = {
    funcs: [a, b]
};

ko.applyBindings(model);
```

### Error message (Chrome):

```
Uncaught ReferenceError: Unable to process binding "foreach: function (){return funcs }"
Message: Unable to process binding "text: function (){return NAME }"
Message: NAME is not defined
```

This used to work in Knockout 2.3.0 and I don't see what is wrong with iterating over an array of functions. In my context I use this array to pick from a list of "classes" for creating new objects. I could wrap the functions in an object, but that would just add extra code for nothing.

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
