### ISSUE TITLE
Ability to retrieve an array of all dependencies for a ko.computed() variable.

### ISSUE THREAD

**Issue by gbmhunter** [knockout/knockout#1233]
e.g. ``ko.getDependencies(myComputedVar);``

This is because I want to perform some basic checking of all the dependencies before performing the calculation, but can't put these checks in the function passed when first calling ``ko.computed()``.

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
