### ISSUE TITLE
addTemplate with document.write + require.js not working

### ISSUE THREAD

**Issue by friesencr** [knockout/knockout#124]
I don't know why document.write isnt working but I changed the add template code with some guidance I found here:
http://requirejs.org/docs/why.html#8

the end result looks like this:

this.addTemplate = function (templateName, templateMarkup) {
	head = document.getElementsByTagName('head')[0],
	script = document.createElement('script');
	script.type='text/html';
	script.id=templateName;
	script.text = templateMarkup;
	head.appendChild(script);
	//document.write("<script type='text/html' id='" + templateName + "'>" + templateMarkup + "</script>");
}

**Comment by SteveSanderson** [comment]
Thanks for posting (so long ago!). I'll close this now to tidy up, since I don't think there's any action for us to take on it.
