### ISSUE TITLE
Feature request: Add in-line anonymous templates

### ISSUE THREAD

**Issue by aleksey-bykov** [knockout/knockout#1251]
An example of a problem: Say we have a dialog component which displays and manages some content. The component is responsible for rendering the dialog frame, backdrop, and buttons. As for the body and the header the dialog delegates rendering to whatever content it was given. Also it allows the buttons to be bound to some logic offered by the hosted content. So in order to make this setup work in the current version of Knockout we have to define the templates for content and header and pass them to the dialog so that it can use them for rendering.

With a lot of different dialogs having to define separate named templates for the content and header is tedious and litters the code. What I wish I could use instead is a new sort of binding that would look like this:
```
<!-- ko instance: 'dialogTemplate' -->
   <!-- ko where: 'header' -->
        This is the <span class="big">header</span> I am talking about.
   <!-- /ko -->
   <!-- ko where: 'body' -->
       <form>
           ......
       </form>
   <!-- /ko -->
   <!-- ko where: 'buttons' -->
        No buttons for this particular dialog
   <!-- /ko -->
<!-- /ko -->


<script id="dialogTemplate">
<div class="backdrop"></div>
<div class="dialog-container">
   <div class="dialog">
      <div class="dialog-header-container" data-bind="here: 'header'">No header</div>
      <div class="dialog-body-container" data-bind="here: 'body'"></div>
      <div class="dialog-buttons-container" data-bind="here: 'buttons'">
           <!-- ko foreach: buttons -->
               <button data-bind="click: action, text: text"></button>
           <!-- /ko -->
      </div>
   </div>
</div>
</script>
````
Honestly I needed this feature so bad so I went ahead and made it myself. Take a look: http://jsfiddle.net/m34wp/4/

The problem is that I am not an expert in the Knockout internals so odds are my code it awkward and the same can be done in a more elegant way. I believe this is a much wanted feature. It can solve a class of problems making UI programming more modular. Please consider implementing it in a new version.

**Comment by mbest** [comment]
Components can implement this type of composition since 3.3.0. I think we can close this issue now.
