### ISSUE TITLE
Redundant toArray (makeArray) in moveCleanedNodesToContainerElement

### ISSUE THREAD

**Issue by vamp** [knockout/knockout#1253]
I think makeArray() in moveCleanedNodesToContainerElement is redundant:
https://github.com/knockout/knockout/blob/master/src/utils.js#L173

Better to leave nodes "as is":
```javascript
        moveCleanedNodesToContainerElement: function(nodes) {
            if (!nodes) {
                nodes = [];
            }
            var container = document.createElement('div');
            if (nodes instanceof Array){
                for (var i = 0, j = nodes.length; i < j; i++) {
                    container.appendChild(ko.cleanNode(nodes[i]));
                }
            } else {
                while(nodes.length > 0){
                    container.appendChild(ko.cleanNode(nodes[0]));
                }
            }
            return container;
        }
```

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
