### ISSUE TITLE
Write warning if using a binding that doesn't exist

### ISSUE THREAD

**Issue by togakangaroo** [knockout/knockout#1263]
This would be incredibly helpful to catch spelling errors.

I just spent 45 minutes trying to track down why my 'collapsible' binding was never being triggered - I had written `data-bind="collpasible: true"`. I recommend a simple `console.log` in the `topologicalSortBindings` function if knockout is DEBUG mode to help catch this.

If you guys are ok with my suggestions I'll gladly do the pull request.

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
