### ISSUE TITLE
Issue with select element binding using options, optionsValue, and value

### ISSUE THREAD

**Issue by loesak** [knockout/knockout#1269]
Knockout 3.0.0

Assume the following:

I have a complex object (lets say Person) who has a reference variable (favoritePet) to another complex object (Pet). The value that can be held for the 'favoritePet' references comes from an asynchronous HTTP request. Meaning, if a value is populated in the 'favoritePet' reference, then the object selected is equivalent to another object in the fetched Pet instances, but is not the same object in memory. 

According to the documentation, I need to provide the binding for 'optionsValue' and I assumed this would work:

```
<select class="form-control" data-bind="{
        'options' : availablePets,
        'optionsText' : function(item) { 
            return item.name; 
        },
        'optionsValue' : function(item) { 
            return item.id; 
        },
        'value' : favoritePet,
        'optionsCaption' : 'Choose ...'
    }"></select>
```

However, I found that it does the following:
- when selecting a value, tries to assign the the selected pets 'id' to the reference variable instead of the pet instance itself
- when a pet instance is already assigned to the reference variable, does not show that value initially selected when the view is bound

I dug through the code and I believe this is because the code upon section, tries to determine the data object that was selected by comparing the option elements value with the list of available data objects and upon setting selection, tries to compare the elements option text with the observable value. So in both instances trying to compare the option elements value (a string) with the object (an object), which will never be equal.

I can resolve the second problem by changing the data-binding to: 

```
<select class="form-control" data-bind="{
        'options' : availablePets,
        'optionsText' : function(item) { 
            return item.name; 
        },
        'optionsValue' : function(item) { 
            return item.id; 
        },
        'value' : favoritePet().id,
        'optionsCaption' : 'Choose ...'
    }"></select>
```

Now when a value is assigned to the reference variable, then it can properly resolve which option to select by default because the assigned value for the binding is the observable values 'id' field, which eventually is equivalent to an the 'id' field of one of the instances of available pets.

However, this causes a different problem when there is no value assigned to the 'favoritePet' reference variable as 'favoritePet()' resolves to null, throwing an error.

I believe all this is again due to the code trying to determine the appropriate model to both select and assign by checking the equivalence of the value and the 'optionsValue' of each available data object.

Instead i think the code should be checking for equivalency between the values after begin passed through the 'optionsValue' method. Meaning this binding is valid:

```
<select class="form-control" data-bind="{
        'options' : availablePets,
        'optionsText' : function(item) { 
            return item.name; 
        },
        'optionsValue' : function(item) { 
            return item.id; 
        },
        'value' : favoritePet,
        'optionsCaption' : 'Choose ...'
    }"></select>
```

and equivalency is done by calling the 'optionsValue' function on BOTH the assigned value and the data object being compared.

Or Knockout should provide a means of letting the user define an equivalency method

```
<select class="form-control" data-bind="{
        'options' : availablePets,
        'optionsText' : function(item) { 
            return item.name; 
        },
        'optionsValue' : function(item) { 
            return item.id; 
        },
        'value' : favoritePet,
        'optionComparator' : function(val1, val2) {
            return val1.id === val2.id;
        }.
        'optionsCaption' : 'Choose ...'
    }"></select>
```

**Comment by KevinPan** [comment]
why it gives me an undefined after bind the value
<select data-bind="options: branchList, optionsText: 'name', optionsValue: 'value', value: *anything*" ></select>
*anything* here will always undefined after binding, why?

**Comment by mbest** [comment]
@KevinPan - Perhaps you need to add the option, `valueAllowUnset: true`. See http://knockoutjs.com/documentation/value-binding.html#using-valueallowunset-with-select-elements

**Comment by KevinPan** [comment]
@mbest Thank You!

**Comment by chadbengen** [comment]
This binding handler is working for me (so far):

```javascript
ko.bindingHandlers.valueByKey = {
    init: function (element, valueAccessor, allBindings, viewModel, bindingContext) {
        var value = allBindings().value;
        var valueKey = value()[valueAccessor()];
        var match = ko.utils.arrayFirst(allBindings().options(), i => {
            var listItemKey = i[valueAccessor()];
            return listItemKey == valueKey;
        });
        allBindings().value(match);
    },
};
```
```html
<select data-bind="options: $parent:countryTypes, value: country, valueByKey: 'id', optionsText:'countryName'></select>
```

**Comment by asfernandes** [comment]
I do have the same problem. Something like `optionsCompare: 'id'` binding working with `value` and `options` would be good.

**Comment by asfernandes** [comment]
I submitted a pull request https://github.com/knockout/knockout/pull/2157

**Comment by asfernandes** [comment]
Here is a less intrusive option which can be done without changing knockout core:

```
ko.bindingHandlers.objectSelect = {
    after: ['options', 'foreach'],

    init: function(element, valueAccessor, allBindingsAccessor) {
        var interceptor = ko.computed({
            read: function() {
                var value = ko.utils.unwrapObservable(valueAccessor());
                var optionsValue = ko.utils.unwrapObservable(allBindingsAccessor().optionsValue);
                return value && value[optionsValue];
            },

            write: function(value) {
                var optionsValue = ko.utils.unwrapObservable(allBindingsAccessor().optionsValue);
                var options = ko.utils.unwrapObservable(allBindingsAccessor().options);

                var obj = ko.utils.arrayFirst(options, function(item) {
                    return item[optionsValue] == value;
                });

                valueAccessor()(obj);
            }
        });

        ko.applyBindingsToNode(element, {
            value: interceptor
        });
    }
};
```

Then replace value by objectSelect and continue using optionsValue.

**Comment by ZzZombo** [comment]
@asfernandes, that enables us to use objects as values of the `SELECT` element, do I understand this right?

**Comment by mbest** [comment]
This has been around a while, and thinking about this now, I'm pretty sure I want to keep the bindings as they are without adding a "comparer" option. Why?

1. In Knockout, two objects that "look" the same can't actually be considered equivalent since they would likely have different observables.
2. The current methods makes it clear that the there should only be one object representing each viewmodel. Borrowing from the OP example, assigning to the value initially would be done with something like `ko.utils.arrayFirst(pets, function(p) { return p.id == "5678" })`;

**Comment by dcroe** [comment]
@mbest  please consider following example:
let's create a simple example:
user has roles , within the system there are several thousand roles and User A has let's say only 200 of them. 
The gui should manage the roles of the user with a select box.
if i understand you right , you propose to iterate over all thousand roles and replace the 200 user assigned roles with the the objects in the complete list?
what i think is missing here is an "entitymanager" which manages the instances, but for simplicity reasons i would realy like to see an identity comparison function.
the real question here is, how to keep object instances in sync between server and client if several calls to the server may return the same instance.

**Comment by mbest** [comment]
> the real question here is, how to keep object instances in sync between server and client if several calls to the server may return the same instance.

Correct. And I don't think it should be the binding that does this.

> if i understand you right , you propose to iterate over all thousand roles and replace the 200 user assigned roles with the the objects in the complete list?

If a select box is displaying 1000 values, iterating over those 1000 values already happens.
