### ISSUE TITLE
'as' parameter for 'with' binding

### ISSUE THREAD

**Issue by rclmenezes** [knockout/knockout#1277]
When I use the 'with' binding, I often end up with $parent/$parents soup. For example:

```
<div data-bind="with: container">
   <div data-bind="foreach: {data: rows, as: 'row'}">
      <div data-bind="foreach: {data: categories, as: 'category'}">
         <a data-bind="click: categoryClickFunc">This is clean syntax</a>
         <a data-bind="click: row.rowClickFunc">This is also clean</a>
         <a data-bind="click: $parents[2].containerClickFunc">This makes me sad :(</a>
      </div>
   </div>
</div>
```

It would be really nice to do something like this:

```
<div data-bind="with: {context: container, as: 'container'}">
   <div data-bind="foreach: {data: rows, as: 'row'}">
      <div data-bind="foreach: {data: categories, as: 'category'}">
         <a data-bind="click: categoryClickFunc">This is clean syntax</a>
         <a data-bind="click: row.rowClickFunc">This is also clean</a>
         <a data-bind="click: container.containerClickFunc">This is nice :)</a>
      </div>
   </div>
</div>
```

I couldn't find anything like this in the docs. If I'm wrong, please let me know. Otherwise, I'd be happy to build this and pull request it :)

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
