### ISSUE TITLE
CSS transition animation support

### ISSUE THREAD

**Issue by gaevoy** [knockout/knockout#1287]
Now only way to implement css transition is to use beforeRemove and afterRender callbacks. But it is not so easy to implement all possible transitions in a plugin unless wrap template binding (bad idea). Moreover, syntax to describe some animation now is ugly. I will show below:
```
<div data-bind="template: {if: visible, beforeRemove: ko.aminations.fadeIn.beforeRemove, afterRender: ko.aminations.fadeIn.afterRender}">
</div>
```
or how can it be much more simpler
```
<div data-bind="if: visible" class="fade-in">
</div>
```
Technicality, each binding (template-based: if, with, foreach) will add css classes: if-appearing, if-appeared, if-disappearing, foreach-item-appearing, etc. So every possible animation can be written in separated css file. In this case easy to apply animation for all if bindings of application, or inside some css selector.

**Comment by SteveSanderson** [comment]
TBH I've found CSS transitions to work quite simply with KO already, just by having KO mostly set up to modify CSS classes on elements. Then CSS animations are defined in terms of those CSS classes.

If at some point we get inspired about a design idea to simplify it further, we can definitely consider that. It's unlikely we'd have KO directly write hardcoded CSS class names to all your elements from your `if`/`foreach`/etc. bindings, though some other system for doing so might be viable (e.g., another binding, `animate`, that hooks into `if`/`foreach`/etc. and runs some globally-configured or registered-by-name callback where you can make your own CSS mutations).

I'll close this for tidiness, but I'm definitely happy to return to this whole area in the future if people are keen and want to propose a more detailed design.
