### ISSUE TITLE
Components design spec

### ISSUE THREAD

**Issue by SteveSanderson** [knockout/knockout#1290]
Following the lengthy discussion in #1273, here's a detailed description of what I have in mind. I've updated [my prototype](https://github.com/SteveSanderson/ko-custom-elems-test/) to implement most of this, though it's only a rough spike and we can no doubt be more streamlined!

In #1273, many people expressed concern that KO should not expand into a big framework that has dependencies on external libraries and/or forces you to do specific things on your server, even after we emphasised that we're not doing that. **DO NOT FEAR**. Nobody is proposing that! The following describes a notion of components that balances as much **simplicity and minimalism** as I think it can have while remaining useful out-of-the-box.
## Components

All components have a template and a viewmodel. Anything outside that pattern is not a component within this system.

A component's template is typically given as a DOM node array and works with KO's native template engine. But in general, a template is any object that works with whatever template engine you are using.

Component viewmodels are any object that works with the component's template.

Components can inherit from or compose with other components in various ways. Examples:
- Templates can contain component bindings that reference other components by name (i.e., nesting them)
- Since viewmodels are just objects, possibly created by a constructor function, it is possible for other components' viewmodels to inherit from those viewmodels.
  - For this to be possible, the base component must choose to make its viewmodel constructor publicly accessible in some manner (and in doing so, it is making its viewmodel API surface public, whereas otherwise its viewmodel API surface would be a private matter between itself and its template).
- The definition of a component can reference the template or viewmodel from a different component,
  thereby reusing its viewmodel or template without modification
## The component binding

Examples of use:

```
<div data-bind="component: { name: 'my-component', params: someData }"></div>
<!-- ko component: { name: 'other-component', params: { showAll: true, count: 10 } } --><!-- /ko -->
```

The component binding works asynchronously. It:
- Uses `ko.components.get` (see below) to obtain the component's template and viewmodel factory function asynchronously
- Injects the template into its element
- Calls the viewmodel factory, passing the following parameters:
  - `componentInfo` - a KO-supplied object containing:
    - `element` - the DOM element in which this component is being hosted. We are only making `element` available to viewmodel factory functions so it's possible to preprocess the DOM in a more convenient way than writing a custom binding. However, the resulting viewmodel should _not_ directly interact with the DOM element if you want to follow the MVVM pattern cleanly.
    - Any future data or callback objects we might choose to add. For example, we might one day want to add lifecycle callbacks like `onAfterRendered`. However the initial release will _not_ include any lifecycle notion (beyond disposal, described below) because it can be added in the future as real-world patterns emerge. We don't want to make the wrong guesses here.
  - `params` - The data supplied to the `component` binding
  - `callback` - A callback function to which you should pass your viewmodel instance when it is ready
- Binds the resulting viewmodel to the element's descendants
- Watches for disposal of the element, and when it happens, trigger's the `dispose` callback (see below)

The component binding is consistent with `template`, in that when its `update` handler fires, it rebuilds the component to keep the UI in sync with changes to `name` and/or `params`. Of course, exactly the same as `template`, it will not know or care if a value _inside_ `params` changes, as it's the responsibility of the component viewmodel and/or template to react to such changes.

**Disposal**

When the associated DOM element is removed, or when the `component` binding replaces the component instance, KO will look for a `dispose` function on the viewmodel instance, and will invoke it if it exists.

This is necessary so that you can dispose any subscriptions or computeds that have dependencies on external data.

If, at the time of disposal, the component's viewmodel factory has not yet supplied a viewmodel, then the `dispose` function can't be called (because the viewmodel doesn't exist yet). In this case, the framework will invoke the viewmodel's `dispose` function as soon as the viewmodel is supplied.

**Custom elements**

This is an additional feature being designed separately. It provides a much nicer syntax for inserting components into your markup. As such, the complexities of `data-bind` syntax for components - especially with virtual elements - will not be a troublesome pain point.

**Possible future extension**

It's not important enough to prioritise for the initial implementation, but it would be possible to supply the original child nodes to the component as an extra property on `componentInfo`. This would make it possible to build components that accept templates, e.g.,

```
<!-- ko component: { name: 'reorderable-list', data: values } -->
    <li data-bind="text: $data"></li>
<!-- /ko -->
```
## Registration

Registration is optional and merely a convenience (if you implement a custom loader, you can fetch component definitions asynchronously on demand from anywhere and need not pre-register anything). 

```
ko.components.register('my-component', {
    viewModel: ...,
    template: ...
});
```

Other config formats are possible (see below), e.g.,

```
ko.components.register('my-component', { require: 'someModule' });
```

This simply adds the config object to an internal registry without interpreting it in any way. Any non-null object is a legal config object. See below for how these are interpreted.

**Checking for registration**

```
ko.components.isRegistered('my-component');   // true
ko.components.isRegistered('something-else'); // false
```

This is useful if implementing a custom loader that only does something if the component is not preregistered.
## The default component loader

The default component loader should understand config objects of the following formats:

```
EITHER:
{
    // Zero or one of the following:
    viewModel: function(params) { /* This is a constructor function */ }
    viewModel: { instance: someObject }
    viewModel: { createViewModel: function(componentInfo, params) { ... } }
    viewModel: { require: moduleName } // See 'About AMD' below

    // Exactly one of the following:
    template: markupString
    template: domNodeArray
    template: { element: 'some-element-id' }
    template: { element: someElementInstance }
    template: { require: moduleName } // See 'About AMD' below
}

OR:
{
    require: moduleName // See 'About AMD' below. Module should be a config object of the form described above
    // Note that, with this config format, you must *not* specify viewModel or template
}

REMOVED CONFIG FORMATS
Earlier versions of this spec allowed for the following additional config formats, but I'm removing them for now because it's unclear what the use case would be (versus registering a custom loader):
{
    viewModel: { configProvider: function(callback) { /* Pass a viewmodel value (e.g., a constructor) to the callback  } }
    template: { configProvider: function(callback) { /* Pass a template value (e.g., DOM node array) to callback */ } }
}
OR
function(callback) { callback(someConfigObjectOfTheFormDescribedAbove); }
```

If the config ultimately resolves to only a `template` value, with no `viewModel` value, then it simply uses the component's `params` value as the viewmodel. This makes it trivial to use components as simple HTML-includes (in other words, asynchronously loaded templates).

These formats meet the goal of providing flexibility in straightforward synchronous/asynchronous loading scenarios, without being tied to any external libraries. We certainly make no assumptions about any URL patterns on your server. None of the default config formats even refer to URLs or natively do ajax requests.

Note that you can't supply templates as a markup string. This may seem inconvenient but is deliberate: if this was permitted, KO would have to parse the markup string every time the component was instantiated. Forcing the markup to be provided pre-parsed means that, in all cases (whether loaded via AMD or otherwise), the DOM fragment is already parsed and ready to be cloned as many times as the component is needed.
## About AMD

KO community members have emphasised we shouldn't take a hard dependency on `require.js` or any other external library. There's no debate about that &mdash; clearly we won't. There will be no requirement to use a module loader. You can always just specify `instance` or `element`/`domNodeArray` values to define components synchronously in terms of what is already in your page.

At the same time, AMD is a useful standard. It's independent of `require.js` or any other loader implementation, and its consumption is so trivial that there is no reason _not_ to have native understanding of it, especially considering how commonly used this will be.

So, `viewModel: { require: 'blah' }` or `template: { require: 'blah' }` are merely implemented as calls to: 

```
require(['blah'], function(module) {
    // Now interpret `module` as if it was the original `viewModel`/`template` config value
    // e.g., so it can be a constructor function, or an object with a 
    //       `createViewModel`/`instance`/`element` property, etc.
});
```

Whatever AMD module loader you are using should support this `require` call and supply values. We do not care what URLs (if any) the responses are fetched from.

**AMD and templates**

This obviously works trivially for viewmodels. But to load a template in this way, you need your module loader to supply a suitable template object - typically a DOM node array or a markup string that KO can parse. If you happen to be using `require.js` this is easy: use its `text` plugin, e.g., `require: 'text!someurl.html'`.

**Packaging components as single AMD modules**

From prototypes, it seems that the most productive way to use AMD with components is for each component to be encapsulated as a single AMD module (containing both viewmodel and view). This makes it trivial to optimise for production deployment, to share across projects, or just to consume in a black-box way without having to know where its viewmodel and template come from.

If you choose to follow this pattern, you would preregister components very simply as follows:

```
ko.components.register('my-component', { module: 'path/myComponent' });
```

.... and then the module file would look similar to:

```
define(["knockout", "text!./myTemplate.html", "some/other/dependency"], function(ko, templateMarkup, someOtherDependency) {
    function MyComponentViewModel(params) {
        // ...
    }

    return { viewModel: MyComponentViewModel, template: templateMarkup };
});
```

Following this pattern (treating the template as a `text!...` dependency) means that the `r.js` optimiser will automatically be able to inline template markup for production builds, though of course you can configure it not to if you prefer.
## Advanced: Retrieving a definition

This is only used when composing components using custom logic. Simply using a component does not require this.

```
ko.components.get('my-component', function(definition) {
    // Now you have:
    // - definition.createViewModel, a function of the form: function(componentInfo, params) { ... }
    // - definition.template, typically an array of DOM nodes but could be anything in the case of custom template engines
});
```

Uses the component loader(s) to asynchronously return a definition for the component. The default loader throws if none could be found.

Component definitions are supplied in this standard format (a `createViewModel`/`template` pair) so that you can always obtain viewmodel/template instances even if you don't know how the component was registered or loaded.

**You only load once (YOLO)**

Since many copies of the same component may be used (e.g., in a tight loop with a `foreach` binding), it's important for the `get` code path to be short and efficient in typical cases. So it should cache its result (there is only one definition for a given component name, and it doesn't change). If multiple `get` calls initially arrive at once, there should be only one underlying asynchronous load process for that component name, asynchronously satisfying all the requests.
## Advanced: Custom loaders

Simple applications won't need to define a custom loader, as the default one will often be adequate. However KO community members have expressed much interest in customising this, hence the comprehensive support described here.

Loaders are responsible either of the following:
- Retrieving the configuration for a component requested by name (so they can produce a configuration programmatically if required, e.g., for lazy-defined components following some naming convention)
- And/or: Given a component configuration object, retrieving a `{ createViewModel: function() { ... }, template: ... }` pair

Example:

```
ko.components.loaders.push({
    getConfig: function(name, callback) { ... },
    loadComponent: function(name, config, callback) { ... },
});
```

It's possible to add as many loaders to `ko.components.loaders` as you like. When any config/component is required, each of the loaders is invoked in turn and the first result is accepted. This makes it easy to write a custom loader plugin, e.g., to integrate with a third-party module loader, and trivially have it compose with other custom loader plugins. The `ko.components.loaders` array initially contains exactly one entry: the default loader, described above.

By controlling the order of entries in the `ko.components.loaders` array, you are defining in what order they are consulted.

**Callback functions**

Both functions are optional and asynchronous.
- `getConfig`
  - Optionally supplies a config object to match the requested component name.
    A config object is anything that can be interpreted by a `loadComponent` function.
    There is a standard config format understood by the default loader, but no requirement to use it.
  - To supply a result, pass it to the callback, e.g.,: `callback(myConfig)`
  - To supply no result, invoke the callback with `null`, e.g.,: `callback(null)`
    - In this case, KO will move on to the next loader (and so on, eventually finishing with the default loader).
    - Note: Inspiration for this async priority-order pattern comes from the [Express.js request handling system](http://expressjs.com/api.html), where it works very well.
- `loadComponent`
  - Optionally supplies a `{ createViewModel: ..., template: ... }` pair.
    - `createViewModel` is a function accepting `(componentInfo, params)`, which synchronously returns the actual viewmodel instance
    - `template` is either a DOM node array or markup string (which KO will parse only once - see YOLO above) or potentially some arbitrary object in the case of custom template engines
  - Again, supply a result by calling `callback({ createViewModel: ..., template: ... })` or no result by calling `callback(null)`.
# Action plan

Once the KO core team has rough consensus on this, and the community seems happy, we can go ahead and implement. I expect @mbest and I will distribute that work between us (or I'm happy to take it all - it's not really that much). Hopefully this can ship in KO 3.2.

**Comment by johnjerrico** [comment]
Hi @SteveSanderson , I'm just wondering is it possible to write the component like the following, if yes could you please give me a few hints why isn't it rendering? many thanks  

MODEL

<CODE>
export default { viewModel: {
	createViewModel:function(params,componentInfo) {
		var components = []; 
		var tabs = [];
		for (component in componentInfo.templateNodes) {
			 var temp = componentInfo.templateNodes[component];
			 var $temp = $(temp);
			 var nodeName = $temp.prop("nodeName");
			 if ( nodeName !== undefined ) {
			 	 var id = $temp.attr('id'); 
			 	 tabs.push({id:id,ref:'#'+id});
			 	 components.push({element:$temp[0],data:{title:ko.observable('hello')}});
			 }
		}
		console.log(tabs); 
		console.log(components);
		return {
			tabs:tabs,
			components:components
		}
	},
	dispose:function(){

	}
}, template: templateMarkup };
</CODE>
TEMPLATE MARKUP 

`<div class="tab">
	<ul class="tab-bar" data-bind="foreach:tabs">
		<li class="tab-bar-item"><a href="#" data-bind="attr:{href:ref},text:id"></a></li>
	</ul>
	<ul class="tab-containers" data-bind="foreach:components">
		<li class="tab-container">
			<div data-bind="template:{nodes:element,data:data},click:function(){console.log($data); console.log(typeof(element)); console.log(data.title())}"></div>
		</li>
	</ul>
</div>`

USAGE

`
<tab-bar>
	<span id="title1" data-bind="text:title"></span>
	<a id="title2" href="#" data-bind="text:title"></a>
</tab-bar>
`
