### ISSUE TITLE
Event delegation on "checked" binding

### ISSUE THREAD

**Issue by vamp** [knockout/knockout#1296]
I suggest single event handler for all checked bindings... 
using ```var delegated = false, dataKey = "__ko_checked__";``` outside binding

and 

```
        if (!delegated) {
            delegated = true;
            ko.utils.registerEventHandler(document.documentElement || document.body, "click", function(e){
                var elementUpdateModel = ko.utils.domData.get(e.target || e.srcElement, dataKey);
                if (elementUpdateModel) {
                    elementUpdateModel();
                }
            });
        }
        ko.utils.domData.set(element, dataKey, updateModel);
```

inside binding instead of ```ko.utils.registerEventHandler(element, "click", updateModel);``` for each element

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
