### ISSUE TITLE
Add 'hasEvaluated() : bool' to computed observables

### ISSUE THREAD

**Issue by lcorneliussen** [knockout/knockout#1300]
Currently, I need to check `isActive` + `getSubscriptionCount` in order to check if an observable has been evaluated. Would be great to have a direct function for that.

Especially since now even a subscribe evaluates a lazy computed.

**Comment by lcorneliussen** [comment]
what about this one?

**Comment by brianmhunt** [comment]
@lcorneliussen - Something seems missing from your comment - a link or more details, perhaps? Cheers

**Comment by lcorneliussen** [comment]
My usecase is still that i want to avoid peeking a computed if it hasn't evaluated yet - or in case of pureComputeds if it is sleeping. In combination with #1511 this makes perfect sence, because i'm then able to subscribe to awake and perform my work as soon as the computed gets a value the first time.

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
