### ISSUE TITLE
Possible Writable Computed Bug

### ISSUE THREAD

**Issue by cpobuda** [knockout/knockout#1311]
I ran across an issue today whereby the observable value will not reflect what is selected in a select element when that observable is wrapped in a writable computed. Calling valueHasMutated on the original observable within the writable function is the only way I could find to correct for it.

Please see http://embed.plnkr.co/OL4gPVMXID6ksjJQ1ABb/preview

It was suggested I submit an issue here.

**Comment by brianmhunt** [comment]
Thanks for the report @cpobuda ; I believe @jrsearles has given the correct solution to this (`valueAllowUnset`), so I will close this issue. Please advise if you feel we have overlooked something and we can re-open and review. Cheers
