### ISSUE TITLE
Adding a "Max" Value to the ForEach Binding

### ISSUE THREAD

**Issue by alericmckearn** [knockout/knockout#1317]
This is mainly to give a global fix to inline search of Arrays.  If you have a large dataset, listing all of the values can take forever for the UI to update as you do the inline search.  This optional value would put a ceiling on the number of loops that the foreach binding would do.

Basically, it would be a more optimized version of the following (since the foreach block would stop looping after 15

&lt;ul data-bind="foreach:foo"&gt;<br />
&lt;!-- ko if: $index &lt; 15 --&gt;<br />
&lt;li&gt;&lt;/li&gt;<br />
&lt;!-- /ko --&gt;<br />
&lt;/ul&gt;

Would become
&lt;ul data-bind="foreach:{data:foo, max:15}"&gt;<br />
&lt;li&gt;&lt;/li&gt;<br />
&lt;/ul&gt;<br />

**Comment by michaeldevenney** [comment]
Why didn't I think of that? ^^^
