### ISSUE TITLE
Html Entities in data-bind expressions inside templates

### ISSUE THREAD

**Issue by eirikurn** [knockout/knockout#132]
Since `memoizeBindingAttributeSyntax` uses a regexp to find data-binds in plain-text templates, and extracts it cleanly into the template JS, it fails if the data-bind expression has html entities. 

```html
<div data-bind="visible: isApplicable() &amp;&amp; someInt() &gt; 20"></div>
```

So again, this doesn't work for bindings inside templates but it does works for bindings in normal DOM and is even reccomended for a couple of symbols: &<>" 

This is especially annoying for me since my server-side templating language actually forces this kind of escaped attribute values, even in templates. :)

I realize that it's impractical to make this work for all html entities (short of dumping the value into a document fragment and reading the text contents). But manually handling these 3-4 entities would solve 95% of the issues, I'd say.

**Comment by SteveSanderson** [comment]
Thanks for the long-ago discussion :) I think we can close this now because there's basically nobody still using string-based templates since the native template engine took over years ago.
