### ISSUE TITLE
Autofill doesn't trigger for drop-down menus in Safari

### ISSUE THREAD

**Issue by webdev** [knockout/knockout#1320]
I have an observable on the drop-down that doesn't get evaluated (looks like the event doesn't get triggered) in Safari 7.

I see a lot of similar posts online, and hacky workarounds, but I was hoping there was a specific event Safari 7 emits on autofill.

Does anybody know what's the "good" way to address the issue? If the event is documented for Safari 7, maybe patch Knockout, rather than implementing polling, manual value retrieval, etc.

**Comment by mbest** [comment]
If there is no event, there's not much Knockout can do.
