### ISSUE TITLE
Add component.json support

### ISSUE THREAD

**Issue by matchdav** [knockout/knockout#1324]
Please add support for https://github.com/component/

I have a working example here: 

https://github.com/matchdav/knockout

But I think it would be great to support component here at the mothership so when the library updates, component users can pull from source.

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
