### ISSUE TITLE
Consider a toggle binding

### ISSUE THREAD

**Issue by mokkabonna** [knockout/knockout#1330]
Something like this:

http://mokkabonna.github.io/knockout.bindingHandlers.toggle/

It toggles an observable, good for having expand/collapse in views. It works with any value. Any value that is not a boolean will be converted to one. myobject (is truthy) => false => true

**Comment by mokkabonna** [comment]
Any progress on this? I use it all the time (obviously, I created it), but it makes viewModels simpler simpler because of not having to create toggle functions for everything. Or worse, create inline functions in the view. I can imagine many can benefit from this. I would be happy to create a PR if desired.

**Comment by stalniy** [comment]
@mokkabonna please read comment in #1420

**Comment by mokkabonna** [comment]
Well that's fair, it do make it easier to use with other things like events etc. Think I'll use and extension myself though, not an extender. Will make it available with no extra syntax on each observable, although with a small performance hit I guess.

At least the hidden binding seems to be wanted, just taking a while :) https://github.com/knockout/knockout/pull/968
