### ISSUE TITLE
IE10 'x' clear input and valueUpdate: 'afterkeydown'

### ISSUE THREAD

**Issue by Kiwironic** [knockout/knockout#1332]
Hey,

There is another issue with IE10 and what a surprise that is!! 

IE10 puts a little 'x' inside input fields, so that by "clicking" on them it clears the field. 

When using the valueUpdate: 'afterkeydown' binding for a field, let's imagine the following scenario:
1- Users enters an invalid data into field
2- validation message pops up 
3- user clicks on the 'x' to clear field.
4- Since there are no keyboard interaction, the 'afterkeydown' does not trigger value update. 
5- user tries to submit or move to another field, while the wrong validation error is still there.

I just wanted to make sure you guys know about this. I have found this simple work around by adding the following styling to the element's ::-ms-clear pseudo-element .

.someinput::-ms-clear {
    display: none;
}

This solution was found here: http://stackoverflow.com/questions/14007655/remove-ie10s-clear-field-x-button-on-certain-inputs

**Comment by MrCsabaToth** [comment]
So does Knockout.js senses when the user clicks that clear button?
