### ISSUE TITLE
Problem with null values from json and options binding

### ISSUE THREAD

**Issue by milaan-muc** [knockout/knockout#1335]
Hi!

Im importing json data from a server into my view model with the knockout mapping plugin and every property which is empty is set to null on the server when generating the json.
Now when i bind the value for "customer_id" to a select menu and use the options binding, the null value is replaced by "undefined". Alle other input text fields use the "null" value from other properties, so i guess only the options binding is doing something different.

```
<select name="customer_id" data-bind="options: customers, optionsCaption: '', optionsValue: 'id', optionsText: 'customer_name', value: customer_id, select2: {}"></select>
```

My problem is that i use knockout reactor for tracking changes and this causes trouble as my view thinks there are changes...

**Comment by maxim-boligatov** [comment]
If somebody needs alternative default value for select and options/value binding he can use the following trick:

```js
ko.selectExtensions.readValue = (function () {
    var original = ko.selectExtensions.readValue;

    var readValue = function (element) {
        var value = original(element);

        if (ko.utils.tagNameLower(element) == 'select') {
            if (value === undefined)
                return null;
        }

        return value;
    };

    return readValue;
})();
```

**Comment by blocka** [comment]
Unfortunately, this does not work when minified. Knockout has its own private version of `ko.selectExtensions.readValue`. When not minified, the symbols are the same, so the override works. Once minified, any internal knockout code will wind up only using the private symbol.

**Comment by maxim-boligatov** [comment]
@blocka, I agree it does not work in minified version. I got this issue some weeks ago. So I have minified debug version myself (using some of online tools). Of course it requires more space 74KB instead of 55KB and it is still trick... at least until it is officially fixed. But it works and I hope it could be temporarily solution.

**Comment by codymullins** [comment]
@mbest I would imagine `valueAllowUnset: true` would be better as a default. When wouldn't you want this enabled?
