### ISSUE TITLE
Batch removing nodes in emptyDomNode

### ISSUE THREAD

**Issue by rosieks** [knockout/knockout#1336]
`emptyDomNode` iterate over all child nodes and remove them one by one. But it can be made in one step by setting innerHTML to empty string:

    emptyDomNode: function (domNode) {
        for (var i = 0, j = domNode.childNodes.length; i < j; i++) {
            ko.cleanNode(domNode.childNodes[i]);
        }
        domNode.innerHTML = '';
    }

In my case it decrese almost 3 times, execution's time.

**Comment by brianmhunt** [comment]
This patch will not work for virtual elements, but it looks like virtual elements have their own branch anyway, here:

https://github.com/knockout/knockout/blob/master/src/virtualElements.js#L87

The performance speedup is substantial and the change is simple, so I will flag this for 3.4 (whether it is ultimately accepted or not I think it is fair to evaluate and cross it off the list in this cycle).

**Comment by mbest** [comment]
This won't work properly, at least not in IE:

http://stackoverflow.com/questions/28741528/is-there-a-bug-in-internet-explorer-9-10-with-innerhtml
https://support.microsoft.com/en-us/kb/276228?wa=wsignin1.0

**Comment by brianmhunt** [comment]
Thanks Michael. Here's another SO reference on point: http://stackoverflow.com/a/5402600/19212 

If performance were a huge issue, one could test for IE and use the slower `removeNode` version, otherwise default to using `innerHTML`.

**Comment by IanYates** [comment]
From what I'm seeing on SO, `innerHTML` is slower anyway.  Answer here http://stackoverflow.com/a/13798847, which references jsperf test here http://jsperf.com/cached-firstchild-check.  Also, `innerText` and `innerHTML` of `table` and `tr` elements are read-only according to https://msdn.microsoft.com/en-us/library/ms532998(v=vs.85).aspx#TOM_Create.

**Comment by mbest** [comment]
@IanYates That perf test is flawed. The nodes to be removed are removed after the first test is run once. All other iterations remove nothing. Compare to http://jsperf.com/cached-firstchild-check/3.

**Comment by IanYates** [comment]
Ha - good to know.  Thanks for pointing out the flaw.  You can't trust everything you read on the Internet :smiley: 

Does innerHTML being readonly for table & tr still apply to this discussion?
