### ISSUE TITLE
Two knockout instances causes isObservable to be false for an observable

### ISSUE THREAD

**Issue by mokkabonna** [knockout/knockout#1344]
I load knockout with amd and use squire to create different contexts. Meaning in my tests I have one instance of knockout and in the module under test I have another.

So my module have a viewmodel

```
define(['knockout'], function(ko) {
  'use strict';
  return function() {
    this.foo = ko.observable();
  };
});
```

and I try test that in my test like this

```
define(['squire', 'knockout'], function(Squire, ko) {
  'use strict';

  describe('home', function() {
    var home;
    var injector;
    beforeEach(function(done) {
      injector = new Squire();
      //injecting real ko if not things like ko.isObservable in the tests will fail
      injector.require(['viewmodels/home'], function(Home) {
        home = new Home();
        done();
      });
    });

    it('should have foo observable', function() {
      expect(ko.isObservable(home.foo)).to.be(true);
    });

  });

});
```

This makes the test fail. I can sove it by injecting the same knockout used in the test to the module under test. Like this:

```
injector.mock('knockout', ko).require(['viewmodels/home'], function(Home) {
    home = new Home();
    done();
});
```

But I think it would be nice if isObservable works across instances of knockout. I assume this also affects other functions.

**Comment by brianmhunt** [comment]
One way around this might be to use the global registry i.e. `Symbol.for` as

```javascript
```

**Comment by mbest** [comment]
I'm not in favor of making Knockout work with multiple instances. It raises the problem of trying to work across versions. Instead, I think we can have Knockout throw an error if you try to work across instances.
