### ISSUE TITLE
Computed Write Dependency Evaluation

### ISSUE THREAD

**Issue by tyrsius** [knockout/knockout#1348]
I'm not sure if this make sense, but I figured this would be the place to float the idea. I was working with Ryan's `numeric` extender, adding a `max` and `min` option, and thought about what it would take to make them observable options. 

The extender uses a `computed` that has a guarded `write` function. You can obviously read observable inside this function, but by default only the `read` function of a `computed` is re-evaluated when dependencies are updated. So, for example, if the `max` value was lowered, we would want the original extended to be shrunk down to the new maximum. To get a `write` to re-trigger, you would have to take some manual steps though, it won't re-run just because an observable was accessed in the `write` function. The first thing that came to mind was writing a subscription for each of them that just tried to re-write the current value, but I was wondering if just using the same dependency detection for `write`s made sense. I think it would be pretty handy for the value to try to re-write itself, but I may be biased by the problem in front of me =)

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
