### ISSUE TITLE
What about suspendRender option for template binding?

### ISSUE THREAD

**Issue by DzenisevichK** [knockout/knockout#1358]
Several test cases:

1. jQueryMobile multi-page application (http://view.jquerymobile.com/master/demos/pages-multi-page/) where changes on one page case re-rendering template on another page. It will be good to re-render the second page on showing with this:
```js
{
  data: data,
  suspendRender: !active()
}
```

2. When page have two modes: viewing and filtering (here filters selection and data statistics). Better to re-render filtered data after switching from filtering to viewing mode:
```js
{
  data: data,
  suspendRender: filtering
}
```

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
