### ISSUE TITLE
Knockout 3.1.0 and Opera 11.64 bug

### ISSUE THREAD

**Issue by mirbuf** [knockout/knockout#1361]
Opera 11.64 doesn't support __proto__ assignment correctly (bugged?), so KO 3.1.0 doesn't work with it.

To fix it I set canSetPrototype to false, so to use extend function, in case Opera 11 is found:

    var canSetPrototype = ({ __proto__: [] } instanceof Array);
    // Fix for Opera 11.64 not supporting __proto__ fully
    if (navigator && /Opera.*Version\/11\./i.test(navigator.userAgent)) canSetPrototype = false;

**Comment by Epaminaidos** [comment]
Today, one of our users had the same problem on the current version of Opera Mobile Classic:
https://play.google.com/store/apps/details?id=com.opera.browser.classic

**Comment by mbest** [comment]
I tested with Opera Mobile (thanks for the links) and figured out a workaround.
