### ISSUE TITLE
Add the ability to subscribe when creating the observable

### ISSUE THREAD

**Issue by levmatta** [knockout/knockout#1379]
Add a second parameter of some sort to pass the subscriber function (maybe a option object would be best).
Here is what I did:
```javascript
ko['subscribedObservable'] = function (initialValue, subscriber) {
        var ret = ko.observable(initialValue);
        if (subscriber) ret.subscribe(subscriber);
        return ret;
    };
```
I believe this has great value, and I hope the idea helps. Fill free to reject it.
Thanks

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!

**Comment by levmatta** [comment]
To supply a pull request I need at least a arquitecture review of the proposal.
What would be best: second parameter, or a config object ????

**Comment by AdamWillden** [comment]
I must say I see the benefit of being able to subscribe on creation. The issue I see with the approach above is that we loose the ability to dispose of the subscription. I'm not sure of a solution to that problem as obviously we must return the observable.

**Comment by IanYates** [comment]
I reckon you could return an array, where the first element is the observable and all subsequent elements (if this was extended to allow multiple subscriptions!?) would contain the subscriptions.  With the new destructuring syntax coming in ES6, TypeScript, etc this wouldn't be too bad.  

The alternative, if you just allow a single subscription, is to return an object of the form {observable, subscription}

One more alternative...  The subscription is accepted as the 2nd parameter and a 3rd parameter something like a promise, such that when it's resolved the subscription is disposed.

I don't know if this would ever make it into KO core though since it's easy enough to patch in if you want it yourself.

**Comment by levmatta** [comment]
I would avoid changing the return.
What I can do is make the parameter a function that receives the observable itself (full power to the people). So the usage would be something like:

```javascript
var subscribed;
var value = ko.observable("Initial value", function(obs) {
   subscribed = obs.subscribe(function() {
   // code
   }
};
```
As visible in the example the subscribe method return can be captured this way, also multiple subscribes are possible.

Thanks

**Comment by stalniy** [comment]
@levmatta and what is the diff between you suggestion and:
```js
var observable = ko.observable('init');
observable.subscribe(...)
```
?
My example is shorter and there is no extra function declaration.

**Comment by levmatta** [comment]
Perfect @stalniy, but the problem I am trying to solve is doing it in a single line. What would a nice acceptable syntax for that be?
One might not agree with the problem statement, but please consider it fully since it is very awkward the way it is now.

**Comment by reflectiveSingleton** [comment]
@levmatta I don't know that we need a special style of code for make an initial subscription. That would muddy the interfaces to observables a bit...I would personally prefer consistency.

FWIW, this should get you what you want:

```javascript
var koObservable = ko.observable;
ko.observable = function(initialValue, subCallback) {
 var observable = koObservable(initialValue);
 if(typeof subCallback === 'function') {
   observable.subscribe(subCallback);
 }
 return observable;
};
```

Note that one issue this style of subscribe-on-create causes is that now we lose access to the subscription reference (or I suppose you could return an object map containing the subscription and the observable - but thats getting icky IMO). Without the subscription reference we cannot clean it up when disposing of the observable (ie: we leak memory).
