### ISSUE TITLE
Ability to initialize or extend a bindingContext at applyBindings before binding occurs.

### ISSUE THREAD

**Issue by mrswain** [knockout/knockout#1399]
It would be good if there was a way, during the initial applyBindings, to extend the binding context similar to the extend method on a binding context, or a way to create a binding context before applying the bindings.

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
