### ISSUE TITLE
Possible New Bindings Any & Empty

### ISSUE THREAD

**Issue by osbornm** [knockout/knockout#1401]
I find myself frequently checking the length of an array in an if binding. Basically there is some markup that has a list of stuff and if the user doesn't have any items I want to display a link that says something like 'click here to create something'. 

The following Gist has an example and a crud implementation. If its something worthwhile I'll clean up the implementation and do a PR. 

https://gist.github.com/osbornm/487e5346d397ffa66260

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
