### ISSUE TITLE
Knockout removing item from observableArray throwing error in IE8/IE10

### ISSUE THREAD

**Issue by sympmarc** [knockout/knockout#1421]
See https://groups.google.com/forum/#!topic/knockoutjs/WjZzoGsoSXc for a more details. 

When using .remove() in IE8/IE10, white space around rows must be removed when reordering using jQueryUI's sortable. This seems to have to do with the different way IE vs. other browsers deal with empty TextNodes. mapData.mappedNodes does not get the "closing" TextNode, which leads to an error around line 4438 in knockout-3.1.0.debug.js. The error traces back to fixUpContinuousNodeArray, line 301.

**Comment by mbest** [comment]
I'd have to say that this is not a bug in Knockout, since the `foreach` binding is not meant to work with something like "sortable" that messes with the nodes.
