### ISSUE TITLE
Debug version  throw  currentFrame.callback is not a function  when try unwrap collection observable

### ISSUE THREAD

**Issue by mogadanez** [knockout/knockout#1424]
With minified version i have not this problem.

stack:

```
registerDependency(subscribable=observable())knockout.debug.js (line 1194)
observable()knockout.debug.js (line 1240)
_onCollectionChange()knockback.js (line 1983)
```
currentFrame in this case is empty function, "function () {}" not an object

**Comment by DirkBoer** [comment]
I'm encountering the same issue. I am using deferred upates. Are there any workarounds?

**Comment by mbest** [comment]
Related issue: mbest/knockout-deferred-updates#30

I'd like to be able to fix this, but I'm not sure how to duplicate the problem.
