### ISSUE TITLE
Bug: data-bind="css: ('   ')" crashes the application

### ISSUE THREAD

**Issue by aleksey-bykov** [knockout/knockout#1431]
In this case `ko.utils.arrayForEach` in `toggleDomNodeCssClass` gets null and fails with null reference exception.

**Comment by npbee** [comment]
I came across this one recently and put together a quick PR.  Here's a super simple fiddle to show the error:  http://jsfiddle.net/npbee/2w00yq6w/

**Comment by IanYates** [comment]
I see what you mean by the fiddle - nice find :)

**Comment by stalniy** [comment]
Check this http://jsfiddle.net/2w00yq6w/1/

**Comment by npbee** [comment]
@stalniy Yeah that's a good workaround and it's what I ended up doing for now.  Regardless, I think the css binding should have a catch for handling the non-empty string so it doesn't crash the app.  Thanks!
