### ISSUE TITLE
package.json is pointing to the debug file

### ISSUE THREAD

**Issue by mikekidder** [knockout/knockout#1440]
If I am installing with "npm install", I would except that main entry is not pointing to the debug file.

```
  "main": "build/output/knockout-latest.debug.js",
```

**Comment by jgoz** [comment]
IMO, the `main` entry in `package.json` should point to an unminified build that does not define a `DEBUG` var internally. Minification and toggling the debug flag should be up to consumers of the package, who are presumably using a module bundler of some sort if they're using knockout via npm.

**Comment by brianmhunt** [comment]
There's some related discussion in #1369 and, when the time comes, #1360

**Comment by lieut-data** [comment]
As another data point, consider this issue in tandem with https://github.com/SteveSanderson/knockout.mapping/issues/102, which breaks `ko.isComputed` and `ko.isWriteableObservable` when the debug version of knockout is used with `knockout.mapping`.
