### ISSUE TITLE
select dropdown of observable objects

### ISSUE THREAD

**Issue by navels** [knockout/knockout#1446]
Ran into this when trying to populate a select object with a knockoutfire observable.  Here's a jsfiddle which uses straight-up knockout (3.0 but I reproduced with 3.1):

http://jsfiddle.net/navels/232Ft/

The problem being, I've got an observable array, consisting of observable objects, with observable properties, like so:

    var red = ko.observable('red');
    var color = ko.observable('{id: 1, name: red}');
    var options = ko.observableArray([color]);

(the fiddle has a more thorough example).  Now I can data-bind='foreach' to create a table of color names, that works just fine.  But passing this array as the options into a select does not give the desired result, I get "observable" instead of the color name.

If I make this one change, to have the array objects be not observable:

    var color = {id: 1, name: red};

everything works.

I looked in the knockout code and see that the problem might be in the applyToObject() function in the update handler.  It needs some ko.utils.unwrapObservable() calls around the "object" and "defaultValue" variables.  But I'm very unfamiliar with the knockout code and have no idea if this is even a bug or by design and if a bug what exactly the right fix is.  Or maybe the fix is on knockoutfire to not put observable objects in the observableArray, but only objects with observable properties.

Cheers,
Lee

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
