### ISSUE TITLE
Add "createTemplate" to Component Templates analogous to createViewModel

### ISSUE THREAD

**Issue by sccooper** [knockout/knockout#1458]
I would like custom elements to be allowed to define just a view model and leave the template up to a 3rd party designer on a per element basis, so templates for components could use the html between the custom element tags or be specified as a parameter, e.g.:

```
<my-component>
<span data-bind="text: foo"></span>
</my-component>
```

or:

```
<my-component params="custom-template: 'custom-id'"></my-component>
```

I added this functionality by allowing templates to have a createTemplate property when registering custom elements that is a function that takes (data, info) like createViewModel does.

I can then implement the functionality I want like this:

```
ko.components.register("my-component", {
    viewModel: { ... },
    template: {
        createTemplate: function (data, info) {
            if (data["something"]) {
                return "<something></something>";
            } else {
                return {
                    element: info.element
                };
            }
        }
    }
});
```

I think this approach is generally useful, but it does affect loaded configs which now have a createTemplate property when resolved, not a template property that is an array of nodes. I have tried to handle existing loaders by first looking for the template property. 

Would you like to see the patch or is there a better way of doing this?

**Comment by silviustd** [comment]
I don't get why need createTemplate to build based on ViewModel info when you can bind everything to ViewModel info and can define own bindings
What I am trying to say, maybe need to look again and use what provided by ko

**Comment by nayan-mistry** [comment]
I second @iratherscribble for the requirement that he is working on! I am having a similar requirement where in i have to tell ko that my template is dynamic. Hence the best place to say ko about a value that's going to change as per user need is via viewmodel. I have a need where i am allowing the user to mention template url, to load the template from, in the view model and if it's not provided then my component would load a default template markup. Hence i also need a view model parameter in the loadTemplate loader method signature. 
Is this feature gonna materialize in the coming version?

**Comment by brianmhunt** [comment]
@nayan-mistry This will likely not be in 3.5, but I can see how it would be useful so fingers crossed :)

**Comment by mbest** [comment]
This can done without any modification to Knockout by defining a custom loader. If anyone is interested, I can put together an example of this loader.

**Comment by iratherscribble** [comment]
It won't work with a custom loader. View previous comments for details, but custom component loaders are not allowed to return anything synchronously and ko.bindingHandlers.component.init attempts to call cloneTemplateIntoElement before making a call to create the viewmodel. There is always an error that the component does not have a template. This occurred with the default component loader and with a custom component loader.

**Comment by mbest** [comment]
Here it is. I'll add an usage example soon.

```javascript
ko.components.loaders.unshift({
    loadComponent: function(componentName, config, callback) {
        function newCallback(definition) {
            if (config.createTemplateForViewModel && definition.createViewModel && (!definition.template || !definition.template.length)) {
                callback({
                    template: [],
                    createViewModel: function(params, componentInfo) {
                        var componentVM = definition.createViewModel.call(this, params, componentInfo);
                        var template = config.createTemplateForViewModel.call(this, componentVM, componentInfo);
                        if (typeof template === 'string') {
                            template = ko.utils.parseHtmlFragment(template);
                        }
                        ko.virtualElements.setDomNodeChildren(componentInfo.element, template);
                        return componentVM;
                    }
                });
            } else {
                callback(definition);
            }
        }
        if (typeof config.require === 'string') {
            require([config.require], function(newConfig) {
                ko.components.defaultLoader.loadComponent(componentName, config = newConfig, newCallback);
            });
        } else {
            ko.components.defaultLoader.loadComponent(componentName, config, newCallback);
        }
    }
});
```

**Comment by mbest** [comment]
My little custom loader shows how this could be done right now and provides an idea of how we might implement this functionality in Knockout. Like `createViewModel`, this must return the template synchronously.

**Comment by mbest** [comment]
I'm closing this since there's a suitable way to extend Knockout to get the desired functionality.
