### ISSUE TITLE
IE8 + text-transform: uppercase bug

### ISSUE THREAD

**Issue by vkrol** [knockout/knockout#1459]
Hi!

I have found an issue with text-transform CSS property in IE8. I have created the gist to reproduce this bug https://gist.github.com/VKrol/5e15f81994cf33583eb2 When I click on the radio button, value in div with text-transform is not updated.

I use the latest version of the Knockout.

**Comment by garrypas** [comment]
I tried this out on both IE8 and IE6 and it worked okay for me... ?

**Comment by vkrol** [comment]
I don't think there's any point in fixing that anymore.
