### ISSUE TITLE
Disposing of Knockout Extenders

### ISSUE THREAD

**Issue by kmalakoff** [knockout/knockout#1464]
I received the following [issue](https://github.com/kmalakoff/knockback/issues/124) and started looking into extenders and memory management.

It looks like there are no hooks to dispose the composed observable. Would the following addition to Knockout be the correct solution?

```
function applyExtenders(requestedExtenders) {
    var target = this;
    if (requestedExtenders) {
        ko.utils.objectForEach(requestedExtenders, function(key, value) {
            var extenderHandler = ko.extenders[key];
            if (typeof extenderHandler == 'function') {
                target = extenderHandler(target, value) || target;
            }
        });
    }

    // release the extended observable
    if (this !== target && this.dispose) {
        var extended = this;
        target.dispose = function() {
            !target.dispose || target.dispose();
            extended.dispose();
        };
    }

    return target;
}
```

If not, how would you recommend correct memory management of extended observables?

Thank you!

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
