### ISSUE TITLE
css binding: Computed Observable set to null doesn't update GUI

### ISSUE THREAD

**Issue by stevennnd** [knockout/knockout#1468]
I have found that if a computed observable is set to some value, and is then re-evaluated and returns `null`, that the previous computed value is being used in bindings/the GUI isn't updating. This doesn't seem like the expected behaviour.

An example (http://jsfiddle.net/LkqTU/18081/):

I am using a computed observable to return a class name used in a `css` binding. The binding can be a class name or no class at all. The template:

    <p data-bind="css: textColour">Coloured text</p>

The computed observable first evaluates to 'green', and the coloured text turns green (I've defined the css for class 'green'). When the computed observable re-evaluates and returns `null`, the text colour remains green however.

    that.success = ko.observable(true);
    that.textColour = ko.computed(function() {
        if (that.success()) {
            return 'green';
        } else {
            return null;
        }
    });

I return null to remove the class from the binding, however this doesn't work and it seems to me that it should. I have found that if I return `undefined`, nothing at all (also `undefined`), or "", that the binding updates as expected and the green colour is removed.

**Comment by mbest** [comment]
Fixed with #1530.
