### ISSUE TITLE
Option to allow view model to be set to initial server values

### ISSUE THREAD

**Issue by jonswaino** [knockout/knockout#1473]
I had a requirement to allow the view model to be set based on the initial value of the server control itself rather than the value defined on the view model.

I got around this by creating a new binding handler called "valueInit" that checks the element value and then calls the ko.observable to set that value.

I then had another scenario where a series of radio buttons required the initial checked value to be set if the value of the control is already checked. So I created another binding handler called checkedInit, which checks if the element is checked and then again sets the observable on the view model.

I want to use KO with a legacy system where all controls are set from the server initially but then have the power and flexibility of the view model post rendering stage.  However, I don't like having to pollute my markup with x-init() binding calls for every different type of binding.  I was wondering if there is something that could be added to the framework that could be enabled to handle this?  Perhaps a switch which could be turned on and is then checked inside the main binding handlers.

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
