### ISSUE TITLE
add noConflict support

### ISSUE THREAD

**Issue by anasnakawa** [knockout/knockout#1478]
we're building a product that will be injected into running websites, part of this product is built using knockout.

since the website might end up with two different versions of knockout, there should be a decent way to avoid those conflicts ( think of a developer who does an applyBinding to the whole page! )

I guess the simplest solution is to provide a decent way to rename the `data-bind` attribute as well as the virtual element keyword `<!-- ko -->`.

**Comment by hanifbbz** [comment]
+1 we are building a web component that uses knockout but we don't want to "pollute" the namespace of the page that "imports" our web component.

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!

**Comment by msallin** [comment]
I implemented a very simple `noConflict` Method which can be used at least to support the requirement from @hanifbbz. Of course it does not handle the conflict when two different versions applies bindings to the same scope.

Since I'm not a good JS I just want to check whether the following code fits for you.
If it does, I can create a pr.

```
// [3] No module loader (plain <script> tag) - put directly in global namespace
// Save the previous version of ko to support noConflict.
var previousKO = window['ko'];
factory(window['ko'] = {});

// Add a noConflict function so ko can be removed from the global namespace.
window['ko'].noConflict = function () {
	var newKo = window['ko'];
	window['ko'] = previousKO;
	return newKo;
};
```

The code would go here:
https://github.com/knockout/knockout/blob/master/build/fragments/amd-pre.js
