### ISSUE TITLE
Customising or overriding the behaviour of toJS

### ISSUE THREAD

**Issue by IanYates** [knockout/knockout#1489]
Hi,
I've searched and not found a similar request elsewhere apart from @SteveSanderson mentioning supporting this would be neat in #278 (unable to override toJSON on arrays).  Issue #867 (ko.toJSON optimisation) also skirted around this.

I have had occasion to override ko.toJS (and thus affecting toJSON).  Specifically, the "Knockoutjs context debugger" in Chrome uses ko.toJS to display its version of the knockout context available to a selected DOM element.

Unfortunately I have one view model where we're using @rniemeyer 's excellent Knockout-Kendo library and its ability to give our view model access to the Kendo widget.  In one case we need to do some heavy customisation to a chart and this was the most expedient approach.  However calling toJS results in a HUGE object graph which crashes spectacularly :)  I modified KO's toJS to check if the object its called with has a toJS method, and if so, to call that instead of doing the work itself.

I then implemented the toJS on my view model by using the mapping plugin's toJS method and its ability to ignore specified properties.

I appreciate this is using a global solution to a local problem.  However it seems useful to let the object that's the subject of the toJS call (or one of its children since the call is recursive) control its observable->non-observable transformation and this seemed like a nice way to do it.  Is there a better way or could something like this find its way into KO 3.3 (although I appreciate it's technically a breaking change albeit for code that's probably behaving unexpectedly at the moment anyway).

Thanks

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
