### ISSUE TITLE
The custom two-way binding does not write a value to view model property

### ISSUE THREAD

**Issue by San4es** [knockout/knockout#1491]
I faced a problem - my custom two-way binding does not write a value to view model property. Example here: http://jsfiddle.net/ubsazekv/.
As I understand, the problem is related to ko.expressionRewirting, which does not create property writers for a property that is bound in the view's markup as follows:

    <div data-bind = "myCustomBinding: {...}"> </ div>

because of the following regular expression:

    var javaScriptAssignmentTarget = /^(?:[$_a-z][$\w]*|(.+)(\.\s*[$_a-z][$\w]*|\[.+\]))$/i;

**Comment by SteveSanderson** [comment]
We have discussed making a proper public API for binding property writers a few times. I would like that feature too.

I think this duplicates #1557, so I'll close it in favour of that (where there's more discussion), but please reopen if you think this is not a duplciate.
