### ISSUE TITLE
Pass component inner html to viewModel constructor

### ISSUE THREAD

**Issue by xavierzwirtz** [knockout/knockout#1494]
It would be great if the html contents of a component were passed to the viewModel constructor function.

For instance, if I had a element on page like so:

```
<search-results params="dataSource: model, inputControl: 'SearchText', dataItemUrl: 'Url'">
   <div>
      <span data-bind="text: name"></span>
   </div>
</search-results>
```

and a component declaration like so:

```
ko.components.register('search-results', {
        viewModel: function(params, elementContent) {
             //elementContent would be a string equal to the innerHtml of the search-results element
        },
        template: '...'
    });
```

Would make it very easy to customize on a per use basis some of the contents of a component. Might resolve @andersekdahl issue #1483 in a cleaner way.

**Comment by ds160607** [comment]
What if I would like to create, for example, a myTabsComponent and I want to use it like this:
```html
<myTabsComponent>
   <div>tab#1 content</div>
   <div>tab#2 content</div>
   <div>tab#3 content</div>
</myTabsComponent>
```
So, knockout could detach those DOM elements from the page and pass it to the viewModel.

**Comment by VoiceOfWisdom** [comment]
@ds160607 see [my comment](https://github.com/knockout/knockout/issues/1592#issuecomment-72609220) on #1592 for an interoplation method that uses knockout 3.3.
