### ISSUE TITLE
Version 3.2 JS file is named .latest.js, not standard

### ISSUE THREAD

**Issue by beeftornado** [knockout/knockout#1498]
The naming convention of your dist JS file changed from previous versions. It used to be knockout.min.js but has changed to knockout.latest.js. This is counterintuitive because it is not always going to be the latest version. This is also not a standard convention and unfortunately, cdnjs.com can't accept the latest version of knockout because of this.

https://github.com/cdnjs/cdnjs/pull/3762

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
