### ISSUE TITLE
How to register jQuery UI widgets as components?

### ISSUE THREAD

**Issue by fadilmamedov** [knockout/knockout#1520]
I used the custom binding handlers as adapters for jQuery UI components. After the release of 3.2 version I was very interested in the new web components syntax and I decided to migrate to it. I faced with a problem: component interface has a 'model' and 'template' (both required) and 'template' must be used for component content rendering. But my custom binding handlers used the "controlsDescendantBindings" option and the component renders own content itself.

I found a workaround for this issue, but it looks bad. Spike solution link: http://jsfiddle.net/msa0h2sq/

Is there a right way to get around the issue with the template? Maybe, it would be nice to expand the component registration API for such cases?

**Comment by San4es** [comment]
Is any chance this case will be improved?
