### ISSUE TITLE
Split out Knockout Components from core into a separate module

### ISSUE THREAD

**Issue by kmalakoff** [knockout/knockout#1525]
Regarding https://github.com/knockout/knockout/issues/1517, I've been giving it some more thought and believe you should consider removing the components framework from Knockout core and releasing it separately.

The scope of Knockout core should be more around data-binding rather than application architecture.

**Comment by kmalakoff** [comment]
@stalniy I really do believe I should have to dive into the internals of the Knockout build system to use the Knockout library. 

If you provide a way to bower install and npm install your proposal, I'll take it.

**Comment by brianmhunt** [comment]
@kmalakoff I'm with you — it'd be delusional to expect users to recompile Knockout to remove components. As awesome as components are, I am also on "team-component-plugin". That said it's not practical to rip it out now. What *can* be done is keeping this issue in mind and making sure that the knockout components code remain at least nominally loosely coupled in future patches.

Speculating, it'll probably be 4.0 or later before that happens, and if components are someday transformed into a plugin it'll probably (and not to be presumptuous, but just thinking out loud) coincide with a change in the nature of plugins e.g. #1589 .

Over time I have come to notice based on my own practices that there are some “first-class” plugins that make sense to bundle with the core package (e.g. components, knockout-punches, knockout-projections), and a slew of ”second-class” packages that are hosted elsewhere. The delineation between first and second class should only ever be hosting-for-convenience, with no special design privileges in the core that prejudice the second-class. (In this sense I feel "first" and "second" class may be derogatory language already ... maybe "core" plugins and just "plugins", but for the purpose of this paragraph, it's illustrative).

That said, I do not know what the other maintainers are thinking the direction of knockout components ought to be, but I'm sure it'll come up in discussion, and I'll raise this if no-one else does. :)

**Comment by rniemeyer** [comment]
Backwards compatibility has always been a key concern and goal for KO, so it is not practical to pull components into a plugin in the short-term. 

Including this functionality in core vs. as a plugin was discussed during the original design. In the end, we wanted the components functionality to be light and extensible (plugins can be built on top of it), but available to new/all KO developers from day one as a pattern for development vs. new folks commonly ending up with large, hard-to-maintain view models as their application grows.  It has always been possible to write modular, reusable code with KO, but the barrier was often high for those that were new to KO.

**Comment by kmalakoff** [comment]
In Knockback, I provide two versions: 1) core 2) full. 

Users can then choose...a full version with the major plugins bundled or start from core and add the plugins they want. 

Easy peasy.
