### ISSUE TITLE
feature request: if, ifnot, and visible bindings - adding the afterRender callback

### ISSUE THREAD

**Issue by andreykl** [knockout/knockout#1529]
Sorry guys for editing.

Just tryed to use afterRender (ko 3.2), it does not work for me. And the issue #556 is very old I think. So, may be it is still feature reqeust for adding afterRender to if, ifnot and visible bindings.

Thanks.

---------------------------------

Just checked the issues and found that issue #556 is what I wanted. But there is no any information about afterRender for if, ifnot and with in documentation (at least I was not able to find it on this pages http://knockoutjs.com/documentation/if-binding.html , http://knockoutjs.com/documentation/ifnot-binding.html , http://knockoutjs.com/documentation/with-binding.html).

So, I think this is may be the documentation issue.

Thanks.

=================

Hello everybody,

I think it will be good and usefull if ko will have `afterRender` for `if`, `ifnot`, and `visible` bindings (and may be for any binding that renders something). Just like for the `foreach` binding. Just for the same purposes.

Thank you,
Andrey

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!

**Comment by hardhub** [comment]
@brianmhunt 

Brian, do you have it in TKO?

**Comment by brianmhunt** [comment]
Not yet but now that we have promise callbacks we can do this for async bindings too (ie properly)

**Comment by brianmhunt** [comment]
... pls feel free to open an issue on tko

**Comment by hardhub** [comment]
I think I need to investigate current tko promise callbacks first... I tried to search any documents about difference between current knockout and tko but not found anything.. It's a bit difficult to suggest/discuss issues without enough background.

**Comment by brianmhunt** [comment]
Docs are next on chopping block - otherwise it's really the commit log :/ 

But this issue can be addressed before release I think - so long as it's not lost in the shuffle 😀
