### ISSUE TITLE
Bindings do not work when model is from Chrome extension background page

### ISSUE THREAD

**Issue by jylin** [knockout/knockout#1560]
In Chrome extensions, you can reference js variables from from different pages. So, in a standalone options.html page, you can reference JS objects from a background.html page like so:

```
// In background.js
window.myObj = { a: ko.observable('test'); };

// In options.js
var obj = chrome.extension.getBackgroundPage().myObj;
```

However, when I try to apply the model to my options.html page, it seems to not work correctly if I use the object from the background page.

```
ko.applyBindings(chrome.extension.getBackgroundPage().myObj);
// input box contains "function d(){if(0<argum..."
```

If I just do it with a local object, it works correctly.

```
ko.applyBindings({ a: ko.observable('test'); });
```

I've inspected both objects (the one referenced from the background page and the local one) in the console, and they look completely identical. Why does knockout not apply the bindings correctly when using the object from the background page?

Doesn't seem to be a timing issue either as I've tried unapplying and reapplying the model manually from the console. Works fine if I give it the model as a local object, but never works correctly when referencing the model from the background page.

I can provide an example/test extension if needed.

**Comment by genbtc** [comment]
This worked for me! Thanks! My final code ended up looking like this:

```
    var backgroundWindow = chrome.extension.getBackgroundPage();
    ko = backgroundWindow.ko;
    //ko.bindingProvider.instance = new ko.secureBindingsProvider({});
    ko.applyBindings(vm,  document.body);
```
