### ISSUE TITLE
possible improvement to loadTemplate extension

### ISSUE THREAD

**Issue by gilesbradshaw** [knockout/knockout#1567]
loadTemplate(name, templateConfig, callback)

gives you the what would might be better named the loadedConfig in templateConfig - ie with your default loader it is the text of the customelement before conversion into dom nodes.

it would be nice if we could have the (real) templateConfig too - ie the configuration of the template.  I intercept some of my customelements because they end up making SVG nodes but I leave everything else the same.

Thus I have a custom loader which does:
````
loadTemplate: function(name, loadedConfig, callback) {
        var content, doc, element;
        if (name.indexOf('sigylsvg-') !== 0) {
          return callback(null);
        } else {. // do my thing!
````

if I also had the templateConfig I could do....
````
loadTemplate: function(name, loadedConfig, callback,templateConfig) {
        var content, doc, element;
        if (!templateConfig.svg) {
          return callback(null);
        } else { // do my thing!!!!
````

having registered my customelement with...
````
ko.components.register('any-name-I-like', {
        viewModel: {
          require: "view"
        },
        template: {
          svg:true,
          require: "the template"
        }
````

Just hacking about with your code but this seems to work...
(in resolveConfig)
````
        if (templateConfig) {
            possiblyGetConfigFromAmd(errorCallback, templateConfig, function(loadedConfig) {
                ko.components._getFirstResultFromLoaders('loadTemplate', [componentName, loadedConfig], function(resolvedTemplate) {
                    result['template'] = resolvedTemplate;
                    tryIssueCallback();
                },undefined,templateConfig);
            });
````
````
    function getFirstResultFromLoaders(methodName, argsExceptCallback, callback, candidateLoaders,templateConfig) {
        // On the first call in the stack, start with the full set of loaders
        if (!candidateLoaders) {
            candidateLoaders = ko.components['loaders'].slice(0); // Use a copy, because we'll be mutating this array
        }

        // Try the next candidate
        var currentCandidateLoader = candidateLoaders.shift();
        if (currentCandidateLoader) {
            var methodInstance = currentCandidateLoader[methodName];
            if (methodInstance) {
                var wasAborted = false,
                    synchronousReturnValue = methodInstance.apply(currentCandidateLoader, argsExceptCallback.concat(function(result) {
                        if (wasAborted) {
                            callback(null);
                        } else if (result !== null) {
                            // This candidate returned a value. Use it.
                            callback(result);
                        } else {
                            // Try the next candidate
                        	getFirstResultFromLoaders(methodName, argsExceptCallback, callback, candidateLoaders,templateConfig);
                        }
                    }).concat(templateConfig));
````

obv u could do the same with the other extension points.

(I think I'll just rely on my naming convention as I don't really want a hacked version of knockout)

**Comment by SteveSanderson** [comment]
This seems reasonable. Would you be interested in submitting a pull request?

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
