### ISSUE TITLE
issue with computed observable and deferred evaluation

### ISSUE THREAD

**Issue by devteamexpress** [knockout/knockout#1568]
I am defining an observable computed liked this through durandal observable plugin
observable.defineProperty(this, 'NationalMode', function(){
return this.ActiveRegion.Name == "National" ? true: false;
});

works great

However if i try to subscribe to it or event assign it to another variable both the subscription and the original compute doesn't update.

this.test= this.NationalMode
or
observable(this,"NationalMode").subscribe(function(val){
if(val == true)
that.dataSource.ShowColumn("RegionName")
else
that.dataSource.HideColumn("RegionName");
return;
});

this seems to only happen when deferred evaluation is true
Any ideas why this breaks

**Comment by SteveSanderson** [comment]
I'll close this since we didn't get any further clarification, and it sounds like it's possibly an external issue anyway. But please reopen if you can clarify what you think KO is doing wrong.
