### ISSUE TITLE
update width on document template

### ISSUE THREAD

**Issue by studgeek** [knockout/knockout#157]
This is a minor issue, but it would be great if you could update the width for the document template you are using. For most examples and pages you have to scroll every code sample (e.g. http://knockoutjs.com/documentation/options-binding.html).

I think optimally index column should be aligned left and the content column should use remaining available space.

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
