### ISSUE TITLE
Expose virtualElements.virtualNodeBindingValue

### ISSUE THREAD

**Issue by brianmhunt** [knockout/knockout#1575]
Right now `ko.virtualElements.virtualNodeBindingValue` is a private function. To support virtual elements in knockout-secure-binding (or theoretically any custom binding provider), I have to duplicate the following code:

```
  var commentNodesHaveTextProperty = document && document.createComment("test").text
     === "<!--test-->";
  var startCommentRegex = commentNodesHaveTextProperty 
    ? /^<!--\s*ko(?:\s+([\s\S]+))?\s*-->$/ : /^\s*ko(?:\s+([\s\S]+))?\s*$/;

  function _virtualNodeBindingValue(node) {
    var regexMatch = (commentNodesHaveTextProperty ? node.text :
       node.nodeValue).match(startCommentRegex);
    return regexMatch ? regexMatch[1] : null;
  }
```

It would be better if `virtualNodeBindingValue` were exposed publicly, so that binding providers could re-use the existing (and future) code for getting binding values from virtual elements.

Cheers

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
