### ISSUE TITLE
export ko.utils.cloneNode

### ISSUE THREAD

**Issue by marcopeg** [knockout/knockout#1578]
this symbol is not exported right now but it is a useful utility for developing custom bindings.

**Comment by SteveSanderson** [comment]
Do you mean `ko.utils.cloneNodes` (i.e., plural)? I don't see any function `ko.utils.cloneNode` (singular).

**Comment by marcopeg** [comment]
Hi @SteveSanderson it's a while now I do not code with KO, I think you're right and it was the plural signature. However there are a bunch of utility methods that are private to KO but should be exposed to make things easier to developers and reduce library redundancy in an application.

**Comment by SteveSanderson** [comment]
help us focus on more highly-prioritised issues, we are tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, see [here](https://github.com/knockout/knockout/issues/1754). Thanks for posting or commenting on this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!

**Comment by SteveSanderson** [comment]
help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. [More info here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!

**Comment by SteveSanderson** [comment]
help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. [More info here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. [More info here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!

**Comment by dregre** [comment]
+1

**Comment by dregre** [comment]
I've created a [PR to that effect](https://github.com/knockout/knockout/pull/2248).
