### ISSUE TITLE
Consider adding bindingContext as argument to component's viewModel constructor

### ISSUE THREAD

**Issue by joutsen** [knockout/knockout#1581]
We are implementing inheritance hierarchy for our Knockout components. In case ancestor component's viewModel does something useful with $root, $data or $parent, all descendant implementations need to pass these parameters via params. This creates lots of boilerplate code in the templates like 

```
<my-descendant-component   params="root: $root, data: $data, parent: $parent">...
```

Instead of doing this we'd prefer to receive the bindingContext object as a second argument for a viewModel constructor.

Then we can do this in the ancestor component:

```javascript
function AncestorViewModel (params, bindingContext) {
            this.root = bindingContext.$root;
            this.data = bindingContext.$data;
            this.parent = bindingContext.$parent;
}
```

Similar approach is used in [knockout-components](https://github.com/lelandrichardson/knockout-components) library. Also bindingContext is passed to custom binding's 'init' and 'update' methods.

The following diff makes the fix for us, but I'm not sure this is the correct way to modify the Knockout.

```
<<< knockout-3.2.0.debug.js
>>> knockout-3.2.0.debug.js patched
3236,3237c3236,3237
<             callback(function (params /*, componentInfo */) {
<                 return new viewModelConfig(params);
---
>             callback(function (params, unused1, bindingContext) {
>                 return new viewModelConfig(params, bindingContext);
3475c3475
<                     var componentViewModel = createViewModel(componentDefinition, element, componentParams),
---
>                     var componentViewModel = createViewModel(componentDefinition, element, componentParams, bindingContext),
3498c3498
<     function createViewModel(componentDefinition, element, componentParams) {
---
>     function createViewModel(componentDefinition, element, componentParams, bindingContext) {
3501c3501
<             ? componentViewModelFactory.call(componentDefinition, componentParams, { element: element })
---
>             ? componentViewModelFactory.call(componentDefinition, componentParams, { element: element }, bindingContext)
```

**Comment by SteveSanderson** [comment]
Thanks for the suggestion - closing in favour of #1666 where there is more discussion on this subject.
