### ISSUE TITLE
Components parameters as multiple attributes

### ISSUE THREAD

**Issue by unsafecode** [knockout/knockout#1582]
Apologies if this has already been discussed, but we tried out v3.2-alpha earlier this year and much appreciated the **component syntax that allowed custom elements' attributes** to be passed to _createViewModel_ function as the component configuration.

As of v3.2-stable, I found no trace of that syntax anymore,nor in the docs: is there a reason? Furthermore, is there a way to enable it in the current release, like custom loaders can replace the default behavior?

**Comment by matths** [comment]
@unsafecode did you come along with the plugin, and would you male it available to others? I think, this still could be a nice feature, as custom elements with custom attributes could be very useful in some cases. The 'boolean' problem could possibly be avoided in some of those cases by conventions.

**Comment by unsafecode** [comment]
@matths I had it working till v3.3.0, but starting from 3.4.0-rc it doesn't work properly anymore... I'll try to investigate and provide the code anyway

**Comment by matths** [comment]
Any news on that, @unsafecode ? Ihave again some time and mood to play with knockout.js again, and I'm coming back to this problem. There's few documentation on how to write a custom binding provider. There's documentation for custom binding handlers, only.
And most of the examples that go into the right direction are for knockout 2+, but now we have 3.4

So, I would like to be pointed into the right direction, on how to start writing such plugin. I read about the preprocessNode hook way. But what is the best way to write such a plugin?

**Comment by mbest** [comment]
Take a look at https://github.com/SteveSanderson/ko-custom-elems-test/blob/master/lib/knockout-customElements.js

**Comment by matths** [comment]
At last I understood it and found the time for an example (http://matths.github.io/knockout-experiments/).

**Comment by mbest** [comment]
@matths Looks nice (https://github.com/matths/knockout-experiments for the source).
