### ISSUE TITLE
Appending items to a list rendered with `foreach` is O(n)

### ISSUE THREAD

**Issue by wjbuys** [knockout/knockout#1584]
It looks like the `foreach` binding doesn't use the more efficient O(1) array tracking introduced in 3.0.0 to determine updates to a `ko.observableArray`. This means that applications that append chunks of data incrementally to a long list exhibit O(n<sup>2</sup>) performance.

It looks like [`renderForEach`](https://github.com/knockout/knockout/blob/master/src/templating/templating.js#L196) throws away any potential tracking data by unwrapping the array to be rendered before [passing it on to `setDomChildrenFromArrayMapping`](https://github.com/knockout/knockout/blob/master/src/templating/templating.js#L207).

That then [uses the O(n) `compareArrays` function](https://github.com/knockout/knockout/blob/master/src/binding/editDetection/arrayToDomNodeChildren.js#L42) to actually generate the edit script.

[Here](http://jsperf.com/slow-knockout-appends)'s a JSPerf demonstrating the behaviour, and this is what the CPU profile looks like when doing the last 4 test cases from there:
![image](https://cloud.githubusercontent.com/assets/31602/4659198/c5d9dd34-5509-11e4-9418-c99cbc4e2149.png)

**Comment by ale-grosselle** [comment]
Hi @mbest, When will the 4.0 version with the foreach improve?

**Comment by homer2** [comment]
[knockout-fast-foreach](https://github.com/brianmhunt/knockout-fast-foreach) produced a huge improvement for me. Rendering went from 900ms to 4ms. The only code change is simple replace on forEach to fastForEach

**Comment by matthew-dean** [comment]
Why not just roll fastForEach into Knockout?

**Comment by brianmhunt** [comment]
@matthew-dean - I am not aware of any resistance to that conceptually. IMO fastForEach needs some testing and love before it'd be suitable (it is missing a few features), and it would need to be better tested for backwards compatibility with the browsers that KO targets.

There are other issues that we may wish to roll in as well, some noted in #1730.

Based on the number of issues and demand for a solid foreach binding, I expect fastForEach, or some comparable alternative, will probably make the cut for KO 4, at the latest.

Cheers

**Comment by skendrot** [comment]
What's the status here? `foreach` is still incredibly slow. Way too slow for any data over 1000

**Comment by chrisknoll** [comment]
So, considering the historical timeline here, perhaps it would be worthwhile to understand what featureset is missing from fast-for-each that would prevent it from being incorporated into the core.  My preference would be for 3.0 compatibility considering the 4.0 release has taken much longer than anticipated to get into an official release.

**Comment by mbest** [comment]
> It looks like the foreach binding doesn't use the more efficient O(1) array tracking introduced in 3.0.0 to determine updates to a ko.observableArray. This means that applications that append chunks of data incrementally to a long list exhibit O(n2) performance.

This is coming in 3.5.0, which you can try already by using the 3.5.0-rc version. See #2324
