### ISSUE TITLE
isObservable returns false in nodeJS with multiple knockout requires

### ISSUE THREAD

**Issue by grofit** [knockout/knockout#1624]
I am still not 100% sure whats causing it but I have some express middleware which basically acts like the ASP MVC autobinding mechanism, then it uses knockout validation to validate the model.

Now the problem is that seemingly randomly `toJS` does not seem to work and after spending a while debugging it the failure stems from `isObservable` which for some reason returns false.

As it is NodeJS I tend to require knockout js wherever needed, although I assumed that under the hood it always just cached the module and re-used it. However I am at a bit of a loss as to how to solve this problem. I saw another issue related to this which seemed to imply that the issue was down to when ko is included multiple times it does not compare the `ko.observable` correctly so returns false.

So is this a known issue and is there any way to fix it?

**Comment by mbest** [comment]
@grofit, Did using `peerDependencies` work for you? If so, is there any need to keep this open?

**Comment by grofit** [comment]
It did work, so this issue is fixed, however if I remember rightly certain other knockout libs were not so happy to work with peerDependencies. It was a while back when I was in this space though so can offer no worthwhile information as to what didnt play nice.

**Comment by SteveSanderson** [comment]
@grofit - great to hear that `peerDependencies` sorted this out!
