### ISSUE TITLE
"Unable to process binding" error message should not contain the wrappnig function

### ISSUE THREAD

**Issue by mariusGundersen** [knockout/knockout#1632]
If you have an error in your binding, like referring to a non-existing value, then the error message produced does not match what was enterd in the binding. For example, the binding `data-bind="text: notDefinedInViewModel"` will produce the error:

```
Uncaught ReferenceError: Unable to process binding "text: function(){ return notDefinedInViewModel }"
Message: notDefinedInViewModel is not defined
```

This is slightly confusing, since the function wrapping the value of the binding was added by Knockout, not by the developer. It would therefore be great if the binding value was unwrapped, so it produced an error like this:

```
Uncaught ReferenceError: Unable to process binding "text: notDefinedInViewModel"
Message: notDefinedInViewModel is not defined "
```

**Comment by 9560026742ravi** [comment]
Uncaught ReferenceError: email is not defined
Uncaught ReferenceError: Unable to process binding "submit: function (){return firstTimeLoginData }"
Message: firstTimeLoginData is not defined

**Comment by 9560026742ravi** [comment]
email is the id of parent html page and same id is coming to child html .
