### ISSUE TITLE
Moving from knockout observables to rx observables?

### ISSUE THREAD

**Issue by grofit** [knockout/knockout#1643]
I have been wondering for a while why the internal ko.observables do not make use of something like rx under the hood, this would allow for far better use cases where we can make use of the optional libraries available to rx while also having that greater functionality at the observable level for more data intensive apps.

Do not get me wrong I am more than happy with knockout in its current form, but I was wondering if it was something others thought about before and if there was a reason they did not decide to delegate the internals of the `ko.observable(10)` to just wrap `Rx.Observable.of(10)`.

https://github.com/Reactive-Extensions/RxJS

Anyone have any opinions? it just seems it would make knockout a bit more extensible if its observables were not bespoke (however I know that in the future js should have its own observables under the hood, so I am not sure if they were the integration goal further down the line).

**Comment by homer2** [comment]
this exists... https://github.com/Igorbek/knockout.rx
