### ISSUE TITLE
renderTemplate behaviour?

### ISSUE THREAD

**Issue by grofit** [knockout/knockout#1651]
So I am just working on a simple template engine, and as the template content is retrieved asynchronously it just returns the text as populated when it gets it, much like how the existing knockout external template loader works:

https://github.com/ifandelse/Knockout.js-External-Template-Engine

However for some reason even though I am passing back the template content (and I have proved this via debug outputs) it never appears on the screen. I am still a bit confused as to how this all works within knockout, but my `renderTemplate` call seems to get invocated a number of times and the first few it does not have any content then on the last one it does however if I follow it through the call stack as best I can it goes to `executeTemplate` which seems to be then calling back to some other methods, and if I debug it sometimes goes well and shows *some* of the templates, as if the async is causing an issue which I would expect. However this seems to be the same process used by the other external template author, where he basically delegates to a custom template source which sets the `template` observable when the data is returned from his ajax request. I am doing the same process just with a slightly different code set and it seems to just ignore it.

It is still very much a work in progress but the source can be seen here:
https://github.com/grofit/knockout.externalTemplateEngine

In the example the foreach works fine, and so does the general templates, however when I use it in a real world scenario it just seems to fail and I am baffled as to why as the fundamentals are the same as the existing library (which works) and as it seems to be a heisenbug, trying to study its behaviour yields different results.

Anyone have any ideas?

**Comment by SteveSanderson** [comment]
Thanks for posting! I'm afraid I don't have any immediate suggestions, other than to use the browser debugger to step through KO's own working implementation carefully and try to identify where it differs from your template engine. This is not something I'm able to track down for you - hope that's OK :)

I'll close this now as it's not either a KO bug or feature request, but please reopen if you do end up finding any issues in KO itself.
