### ISSUE TITLE
Lazily force re-evaluation of computed observable

### ISSUE THREAD

**Issue by VoiceOfWisdom** [knockout/knockout#1653]
I have a computed observable that I want to lazily execute, instead of executing immeaditly and always returning that value.

``` js
var result = ko.computed({
    read: function () {
      console.log('foo');
      return new Date();
    },
    write: function (newValue) {
        //not relevant
    },
});

//foo has been logged

setTimeout(function(){
  console.log(result().toString());
  //foo is not logged, and the value is the value that was initially returned.
}, 2000)
```
[JSBin](http://jsbin.com/yolazejane/1/edit?js,console,output)

Is there any way to tell knockout to re-evaluate this on the next call?
Looking at the source, there is the _needsEvaluation variable, however there is no way to force that to true that I can see.

**Comment by VoiceOfWisdom** [comment]
@mbest, you were correct about changing the event type allowing me to fix my issue. I have been able to get most of my tests passing by calling subscribe with a `spectate` event type. 

I am running into one remaining issue, I need to manually call `trackChanges` on the `trackArrayChanges` extender. It is not exposed on the computed once you extend it. Would a PR making it public be acceptable?

**Comment by mbest** [comment]
> I need to manually call `trackChanges` on the `trackArrayChanges` extender.

Can you explain this more? Have you looked at the changes made in #1634?

**Comment by VoiceOfWisdom** [comment]
Sure.

I have a lazy observable object, that I dont want to eval until requested, even when subscribed to.
I still want it to support the `arrayChange` event. The `trackArrayChanges` extender calls `subscribe`
inside `trackChanges`, so I need to defer the execution of that function until the `computed` is read.
I can do this by overwritting the `subscribe` function, however without `trackChanges` being public
I cant ever call it to manually set up change tracking.

In #1634 you change to using `beforeSubscriptionAdd` to start tracking changes. While I could do some
tomfoolery with calling `beforeSubscriptionAdd` and intercepting its call to `underlyingBeforeSubscriptionAddFunction`
I think exposing `trackChanges` when you call `trackArrayChanges` is a clean and simple api change.

``` js

console.clear();

var makeLazy = function () {
    var holder = ko.observableArray();

    var needsArrayTracking = false;
    var setupArrayTracking = function () {
        if (needsArrayTracking) {
            needsArrayTracking = false;
            result.trackChanges();
        }
    };

    var notify = function (newValue) {
        result.notifySubscribers(newValue, 'spectate');
    };

    var hasAccessed = false;
    var result = ko.computed({
        read: function () {
            console.log('reading');
            hasAccessed = true;
            setupArrayTracking();
            return holder();
        },
        write: function (newValue) {
            hasAccessed = true;
            setupArrayTracking();
            holder(newValue);
        },
        deferEvaluation: true
    });

    originalSubscribe = result.subscribe;

    result.extend({
        "trackArrayChanges": true
    });

    result.subscribe = function (callback, callbackTarget, event) {
        if (event === 'arrayChange') {
            if (hasAccessed) {
                needsArrayTracking = true;
                setupArrayTracking();
            } else {
                //setup change tracking once target is accessed for the first time.
                needsArrayTracking = true;
            }
        } else {
            event = 'spectate';
        }
        return originalSubscribe.call(this, callback, callbackTarget, event);
    };

    var proxy = function (name, shouldNotify) {
        result[name] = function () {
            holder[name].apply(holder, arguments);
            if (shouldNotify) notify(result());
        };
    };

    proxy('push', true);
    proxy('remove', true);
    proxy('removeAll', true);
    proxy('indexOf', false);

    return result;
};

var lazy = makeLazy();

lazy.subscribe(function (changes) {
    console.log(changes);
}, null, 'arrayChange');
console.log('reading should not have fired yet')

lazy.push('foo');
lazy.push(['bar', 'baz']);

```
[jsbin of above using the knockout.3.3.0.alpha modified to expose trackChanges.](http://jsbin.com/ditawufeto/1/edit?js,console,output)

Apologies for being difficult, solving this problem in a clean way has proved somewhat difficult.

**Comment by mbest** [comment]
I've finally taken the time to look over your code and think I figured out a way for you to do what you want without any further changes to Knockout. The main change is in your `setupArrayTracking` function:

```javascript
  var setupArrayTracking = function () {
    if (needsArrayTracking) {
      needsArrayTracking = false;
      result.extend({trackArrayChanges: true});
      originalSubscribe.call(result, function(){}, null, "arrayChange").dispose();
    }
  };
```

The second change is to remove the `extend` call from the `makeLazy` function. You can see it working here (using the latest "master" code): http://jsbin.com/dofayopaza/1/

**Comment by VoiceOfWisdom** [comment]
:+1: 
You are the man @mbest. My code had moved a bit from what was on jsbin, but that enabled me to fix the issue.

I had to play hot potato with the subscribe functions, but all my specs are passing with latest master knockout 3.3.0, the knockout build from @mbest's jsbin.
```js
var needsArrayTracking = false;
var arrayTrackingSetup = false;
var setupArrayTracking = function () {
    if (!hasAccessed && !_pokableLoaded.value) {
        throw new Error('cant setupArrayTracking when not loaded');
    } else if (!hasAccessed) {
        result();
    }
    if (needsArrayTracking && !arrayTrackingSetup) {
        arrayTrackingSetup = true;

        var sub = result.subscribe;
        result.extend({
            trackArrayChanges: true
        });
        var arrChangeSubscribe = result.subscribe;
        result.subscribe = sub;

        arrChangeSubscribe.call(result, function () {}, null, "arrayChange")
            .dispose();
    }
};
```

[The monstrous full implementation](https://gist.github.com/VoiceOfWisdom/b99d46ca2ce365cf1107), handles all kinds of corner cases so that the onDemandObservable works exactly like a knockout observable.

**Comment by mbest** [comment]
The latest version of `arrayChange` doesn't modify the `subscribe` function, so you shouldn't need to save and restore it like you're doing. Otherwise, wow, you certainly have put a lot of work into this!

**Comment by VoiceOfWisdom** [comment]
Heh, ya. Its a pretty important component of my app. We have large arrays of data that we need to lazy load after the rest of the app has loaded. Making an observable that loads after the rest of the initial load makes structuring the pages a lot easier.
