### ISSUE TITLE
Signature to control utils.triggerEvent bubbling

### ISSUE THREAD

**Issue by mryellow** [knockout/knockout#1671]
https://github.com/knockout/knockout/blob/d0e0d9ae87126ce4c5545c974b415c348b980884/src/utils.js#L374

I'm trying to work around an `checked` binding issue with radio inside label.

This results in label capturing the `click` event and the radio not being triggered.
```
	<div data-bind="foreach: options">
		<label>
			<input type="radio" name="option_id" data-bind="checked: $parent.option_id, checkedValue: $data.id" />
			<span data-bind="text: $data.name"></span>
		</label>
	</div>
```

I'm attempting to work around this by passing the `click` event manually from the parent to the child.

```
	<div data-bind="foreach: options">
		<label data-bind="click: function(data, event) {
				ko.utils.triggerEvent(event.currentTarget.children[0], 'click');
			}">
			<input type="radio" name="option_id" data-bind="checked: $parent.option_id, checkedValue: $data.id" />
			<span data-bind="text: $data.name"></span>
		</label>
	</div>
```

Problem is now there is recurrsion as the radio click bubbles back and retriggers the label event.

Extra signature params for `triggerEvent` with the ability to control bubbling and other options would be nice.

**Comment by mryellow** [comment]
Moved to pattern of setting the value directly from the label. Seems the label still gets triggered with click events even when using the keyboard... Still control of bubbling would be handy, noticed you just added it to the delegatedEvents plugin.

**Comment by jods4** [comment]
I'm unsure what your issue was. I tried to reproduce in a jsfiddle but it works -- at least in IE11.
http://jsfiddle.net/ews0rcpx/

**Comment by mryellow** [comment]
Thanks for looking, I've boiled it down too far and rushed a little it seems, obvious now looking at it that there is nothing to handle the click. 

Bootstrap in combination, `data-toggle` on a parent element is the issue.

Change `datatoggle` to `data-toggle` on the `li`'s and it stops working.
http://jsfiddle.net/h2uwbewo/

Maybe this Bootstrap issue would change this behaviour, though Knockout may still not play nice with it looking for `click` event.
https://github.com/twbs/bootstrap/issues/8816

Probably worth leaving this open, not a bad idea to add the ability to control the bubbling.

**Comment by mbest** [comment]
> Probably worth leaving this open, not a bad idea to add the ability to control the bubbling.

Knockout works with three different event systems: Modern, jQuery, and old-IE. Only the modern system allows one to control the bubbling. So this is not an easy feature to add.

**Comment by mryellow** [comment]
Close it if you like, only left open for someone more across the code-base to see if it was worthy.

**Comment by brianmhunt** [comment]
Many thanks @mryellow
