### ISSUE TITLE
textInput  binding  problem

### ISSUE THREAD

**Issue by ourfeel** [knockout/knockout#1672]
ctrl + z  and  ctrl + y  don‘t  fire  the ’input‘ 、 ’selectionchange‘、’propertychange‘  event when your browser is IE9 .
when IE9，  can use  Object.defineProperty .

**Comment by brianmhunt** [comment]
Thanks @ourfeel -- could you be so kind as to put together a sample jsFiddle, please?

**Comment by mbest** [comment]
In my testing, it fires the `selectionchange` event for ctrl-z. ctrl-y doesn't do anything anyway.
