### ISSUE TITLE
repo removed from Google search

### ISSUE THREAD

**Issue by gdi2290** [knockout/knockout#1674]
repo
https://www.chillingeffects.org/notices/10275257#infringing_url_598767449
and org
https://www.chillingeffects.org/notices/10275257#infringing_url_598767449

**Comment by cvrebert** [comment]
Some additional context: https://news.ycombinator.com/item?id=8848544

**Comment by brianmhunt** [comment]
Thanks @gdi2290 & @cvrebert 

I have taken the liberty of writing Take Down Piracy on behalf of the project and projects held by @rniemeyer @mbest and @SteveSanderson (whom I hope do not feel I have overstepped here, and I apologize if you feel I have); for future reference, the content of my letter (minus some personal details):

> To: marketing@takedownpiracy.com
> Date: Wed, Jan 7, 2015 at 9:33 AM EST

> Dear Sirs,

> It has recently come to my attention that your firm has filed a DMCA notice to Google identifying copyright infringement for works to which I am personally associated. I apologize if this email is not directed to the correct address, but it was the only address apparent to contact your company and I would be grateful if you could forward this message appropriately or direct me accordingly.

> The notice that has come to my attention includes the details from the web-site as follows:

>    https://www.chillingeffects.org/notices/10275257

> This site identifies Takedown Piracy LLC as an agent of Wicked Pictures sending a DMCA notice to Google. The notice apparently references the following works, which works appear to have since been removed from the results of searches via the Google search engine:

> https://github.com/SteveSanderson/knockout-es5
> https://github.com/rniemeyer/knockout-delegatedEvents
> https://github.com/rniemeyer/knockout-amd-helpers
> https://github.com/Knockout-Contrib/Knockout-Validation
> https://github.com/knockout/knockout
> https://github.com/knockout

> These works are entirely software and are in no way associated with Wicked Pictures, nor do they contain any adult material whatsoever (which I understand to be the preponderance of copyright held by Wicked Pictures).

> Through the above-referenced DMCA notice your firm has stated that I have committed or endorsed copyright infringement, as well as associated me with republishing the works of the adult industry.

> [As a software developer], I am sure you can appreciate that the above implication and association could cause serious harm to my reputation.

> I trust you will not mind issuing an appropriate revocation of appropriate portions of the DMCA notices to Google and any other recipient that may have received a notice referencing the above content, as well as similarly revoking and white-listing from any future notices any work referred to with a URL containing the following:

>   github.com/knockout
>   github.com/SteveSanderson
>   github.com/mbest
>   github.com/rniemeyer
>   github.com/brianmhunt

> ​Again, these repositories contain entirely software and are clearly not the intended target of your operation​, which you can readily confirm by navigating to them in a web browser.

> ​Many thanks for your co-operation on this matter, and I would be grateful for your ​confirmation that the DMCA notices have been appropriately revoked. If by February 7th, 2015 it is apparent that the DMCA notices have not been revoked, I will be obliged to pursue appropriate legal action, and will hold your firm responsible for all associated legal costs.

> ​Kind regards,

> Brian​

I noted that others have filed counter-notices.

I expect this company will be receiving a flood of email for this and other projects on GitHub, but this format should get their attention in a productive way.

Any other thoughts on what could be done? I will post any reply.

**Comment by rniemeyer** [comment]
@brianmhunt - Thanks Brian, much appreciated. Not sure what else to do. I wonder if GitHub will get involved or needs to get involved as the owner of the site.

**Comment by brianmhunt** [comment]
My pleasure, Ryan.

It is hard to say if GitHub will get involved. On the one hand they are losing potential search results, which diminishes the value of the site. On the other hand they would be sticking their neck out to vouch for their content.

**Comment by rniemeyer** [comment]
Pretty annoying and unfortunate situation.

**Comment by brianmhunt** [comment]
Fixed.
