### ISSUE TITLE
textInput misses one change in IE

### ISSUE THREAD

**Issue by jods4** [knockout/knockout#1678]
I hate having to write that, but I found yet one more edit that is apparently not notified by IE 11.

In IE, by default ESC in a textbox cancels your changes and sets the control back to what they were when the controls received focus. This edit is not caught by `textinput`.

JsFiddle: http://jsfiddle.net/fru3bhza/2/

Moreover, previous releases of IE had this behavior where hitting ESC twice clears the field (first IE11 releases) or the whole form (IE10-). This also seems to be undetected by KO. To be honest, I'm not sure how you'd detect the whole form clear for every input on the page... :(

I always found this behavior annoying and unwanted. I usually disable the form-clear behavior (`preventDefault` at form level) and I replace the field-undo by a real field-clear (handling ESC at the input level).

Not sure if this should be fixed in KO, reported to IE team, or nothing at all? It's very easy to run into the single ESC bug at least. Type something, hit ESC. You think you cancelled but your app state is inconsistent.

**Comment by mbest** [comment]
Reporting this to the IE team would definitely be good. I'll look into whether we can work around this in Knockout.

**Comment by mbest** [comment]
See https://connect.microsoft.com/IE/feedback/details/881670/ie11-esc-key-changes-value-of-input-type-text-but-does-not-fire-input-event

**Comment by mbest** [comment]
It's possible that we can catch this update using the `keydown` event.
