### ISSUE TITLE
Input not updateing when using auto-complete in Safari

### ISSUE THREAD

**Issue by Fredrik-Oberg** [knockout/knockout#1679]
Using safari 7.1 on Mac OSX* the inputs is not updating when the auto-complete is triggered. 
This is not the auto-fill but rather the other "auto-complete", were a list of previously inputted options is available to choose from. 

http://jsfiddle.net/rhULc/80/
Input a value, trigger submit, reload. 
Input beginning of same value choose from list press tab.

*Edited IOS -> Mac OSX

**Comment by Fredrik-Oberg** [comment]
Tested with all options [valueUpdate](http://knockoutjs.com/documentation/value-binding.html) has and tried to change it to [textInput](http://knockoutjs.com/documentation/textinput-binding.html) with no luck

**Comment by brianmhunt** [comment]
Just for reference, the other auto-fill bug #1564

**Comment by mbest** [comment]
I also found this when testing with Safari on Windows. It doesn't generate any event for autocomplete. If there's no event, there's no way for Knockout to know that something's changed (except by polling, perhaps).

**Comment by brianmhunt** [comment]
Seeing as this is an upstream Safari/Windows problem, and @mbest is aware of it, it would appear that this is not something we here could fix (I don't think polling is a very practical option - is it?).

On that basis, if you do not mind @Fredrik-Oberg - and I have not overlooked something, I will close this. Should a solution come available we should of course re-visit.

Thanks for the report @Fredrik-Oberg .
