### ISSUE TITLE
How to get the DOM object to which the view model is bound?

### ISSUE THREAD

**Issue by pravin-d** [knockout/knockout#1681]
applyBindings(viewModel, dom-element);
How to get the DOM object to which the view model is bound?

**Comment by rniemeyer** [comment]
From a DOM element, you can retrieve the data associated with it or the binding context (an object with `$data`, `$parent`, etc.). Check out this [documentation](http://knockoutjs.com/documentation/unobtrusive-event-handling.html) for further details.

You can't go from a view model directly to a DOM element. A view model could be bound to multiple DOM elements. You would have to keep track of the DOM elements that you call applyBindings against in your application.

Please let me know if I misunderstood your question. Thanks!

**Comment by brianmhunt** [comment]
@pravin-d You might have more success on StackOverflow.com, as what you are asking is more a support question and not an issue with Knockout per-se.  Cheers.
