### ISSUE TITLE
ko.isObservable(ko.observable(1)) === false!

### ISSUE THREAD

**Issue by Epaminaidos** [knockout/knockout#1683]
The statement above worked perfectly fine in version 3.0 in all browsers I tested.
A few days ago, I updated my site from 3.0 to 3.2 and there, "ko.isObservable(ko.observable(1))" evaluates to "false" in Opera Mobile.

You can check it using the following jsFiddles:
Version 3.0: http://jsfiddle.net/0syx0qkj/ --> true
Version 3.1: http://jsfiddle.net/byynLdd1/1/ --> false
Version 3.2: http://jsfiddle.net/swz2yd46/1/ --> false

You can download an emulator here: http://www.opera.com/de/developer/mobile-emulator
The current version in the play-store:
https://play.google.com/store/apps/details?id=com.opera.browser.classic

Will this be fixed?

**Comment by Epaminaidos** [comment]
I looked a bit throug the code and the issue seems to be the handling of the prototypes.
If I force "canSetPrototype" to false, everything works find and as expected. So I guess, the check in line 75 does not return the real truth for Opera Mobile:
var canSetPrototype = ({ __proto__: [] } instanceof Array);

**Comment by yesley** [comment]
I think, it's important issue. I use knockout for Smart TV development and found that it doesn't work on Opera TV engine 3.3 and below which is used in Sony Smart TV & BDP

**Comment by mbest** [comment]
I've reopened #1361 where we can continue this discussion.

**Comment by mbest** [comment]
I tested with Opera Mobile (thanks for the links) and figured out a workaround.
