### ISSUE TITLE
compoent bind the child of obervableArray, if the obervableArray  is [], it's lead to Endless Loop

### ISSUE THREAD

**Issue by zhouhoujun** [knockout/knockout#1686]
e.g.

html:

    <div data-bind="with: components">
        <div data-bind="component:{name: tree.componentName, params:{node: tree}}"></div>
    </div>

compoent template 1:  this will endless loop  tree binding

              '<div class="tree-Container ">\
                    <ul data-bind="foreach: visualChildren, css:{line: context.showLine}" class="kotree">\
                        \
                    </ul>\
                 </div>'

compoent template 2: this template to  be work correctly.

              '<div class="tree-Container data-bind="if:visualChildren()">\
                    <ul data-bind="foreach: visualChildren, css:{line: context.showLine}" class="kotree">\
                        \
                    </ul>\
                 </div>'

**Comment by mbest** [comment]
Can you provide an complete example, in jsFiddle or jsBin?

**Comment by zhouhoujun** [comment]
@mbest , I just check version 3.3.0, this bug is fixed. Thank you!
