### ISSUE TITLE
New value binding break possibility to refresh widgets

### ISSUE THREAD

**Issue by DzenisevichK** [knockout/knockout#1687]
With previous knockout 3.1.0 version it was possible to override `update` handler and call `refreshWidget` on each `update`. In new version we only have `init` handler and I did not find way to override it to have correct widget refreshing. I currently need to copy-paste implementation and insert `refreshWidget` in `updateFromModel` after every `ko.selectExtensions.writeValue`.

May be we need to add `valueOnChanged` callback supporting for `value` binding?
Some other ideas?

**Comment by DzenisevichK** [comment]
Also it's not possible using copy-pasted version of `value` binding with minified knockout version because of not public functions:

  - `ko.expressionRewriting.writeValueToProperty`,
  - `ko.utils.stringStartsWith`,
  - `ko.dependencyDetection.ignore`

So I need help :-)

**Comment by brianmhunt** [comment]
Hi @DzenisevichK -- thanks for the report. I am little unclear on where you are experiencing the problem - perhaps you could put together a jsFiddle?

**Comment by mbest** [comment]
It shouldn't be too hard. Here's one way to do it.

```javascript
ko.bindingHandlers.myValue = {
    preprocess: function (value, key, addBinding) {
        addBinding('value', value);
        return value;
    },
    update: function (element, valueAccessor) {
        ko.unwrap(valueAccessor());
        refreshWidget(element);
    }
};
```

**Comment by DzenisevichK** [comment]
@mbest 

Thanks for example!

But currently `value` binding has one case where your version will not work:

```js
            if (elementValueBeforeEvent !== null && newValue === elementValueBeforeEvent) {
                setTimeout(updateFromModel, 0);
                return;
            }
```

In this case `refreshWidget` will called too early...

**Comment by DzenisevichK** [comment]
@mbest 

There is also the second `setTimeout` in `updateFromModel`:

```js
setTimeout(applyValueAction, 0);
```

**Comment by mbest** [comment]
@DzenisevichK, The first `setTimeout` only comes into play if you've bound to a rate-limited observable and are using an `after...` event. The second one just applies the same value that's already been applied (and only applies to `<select>` elements). Also your original technique wouldn't know about those either.

**Comment by DzenisevichK** [comment]
@mbest 

Will try to implement `update` handler as you suggested.

Thanks!
