### ISSUE TITLE
Knockout removes adjacent select element when using more than one select next to each other

### ISSUE THREAD

**Issue by jccounihan** [knockout/knockout#1689]
Hi everyone,

Using knockout 3.2.0, I have an issue where I am trying to bind to two different select elements using the options binding. Each binding is independent, with different options arrays and value observables. 

However when you call applyBindings, the 2nd select is removed from the DOM, and the label for the 2nd select is merged into the options of the first select.

I have created a fiddle to demo my problem: http://jsfiddle.net/crazyJ/0459frzt/1/

Thanks.

**Comment by jccounihan** [comment]
Oops, my bad the html selects were not closed correctly. *blush*

Fixed fiddle: http://jsfiddle.net/crazyJ/0459frzt/8/

**Comment by brianmhunt** [comment]
Thanks for the report and closure, @jccounihan :)
