### ISSUE TITLE
Knockout Components: “component: function () { return componentBindingValue; }" Message: Component 'myComponent': Uses require, but no AMD loader is present”

### ISSUE THREAD

**Issue by jamespchadwick** [knockout/knockout#1690]
I am currently working in a Durandal project and researching the use of Knockout Components in my application. I'm building using Gulp and the gulp-durandal plugin and have it configured to use almond.

I'm running into an issue where I receive the following error when navigating to one of my pages which uses the newly registered components:

**component: function () { return componentBindingValue; }" Message: Component 'myComponent': Uses require, but no AMD loader is present**

Here is the Gulpfile I am using:

``` javascript
var gulp = require('gulp');
var durandal = require('gulp-durandal');

gulp.task('durandal', function() {
    durandal({
        baseDir: 'app',
        main: 'main.js',
        output: 'main-built.js',
        almond: true,
        minify: true,
        rjsConfigAdapter: function (rjsConfig) {
            rjsConfig.paths = {
                'text': '../Scripts/text',
                'durandal': '../Scripts/durandal',
                'plugins': '../Scripts/durandal/plugins',
                'transitions': '../Scripts/durandal/transitions',
                'dataservice': 'domain/dataservice'
            };

            return rjsConfig;
        }
    }).pipe(gulp.dest('build'));
});
```

**Comment by brianmhunt** [comment]
Thanks for the report @JamesChadwick – do you think this might be related to issue #1526?

**Comment by JamesChadwick** [comment]
@brianmhunt I'll be honest I'm not too sure.  I pulled down the master branch a few days ago (1/29/15), built it, and replaced the version of Knockout I was working with at the time (3.2) with the newly built master branch.  Correct me if I am wrong, but It looks like the fix for 1526 was merged into master long before that.

I apologize for not having much more information than that.  I haven't really dove into almond / require.js / AMD that much as it was all setup long before I came on the project.

**Comment by mbest** [comment]
@JamesChadwick Is this an error that didn't occur with 3.2?

**Comment by JamesChadwick** [comment]
@mbest No, the error occurred with 3.2 as well.  Sorry for not making that more clear.

**Comment by M-Sivanraj** [comment]
+1,
I also facing same issue, but i have used Weyland to build my app, and i have used knockout 3.2 which is not included #1526 issue fixes.

**Comment by JamesChadwick** [comment]
@M-Sivanraj I noticed this issue in 3.2 as well and was building my app using Weyland at the time. Since Weyland has been discontinued decided to upgrade to Gulp. An educated guess would lead me to believe that Almond and Knockout just aren't playing nice together.

**Comment by nuclearwessel** [comment]
The issue appears to be related to the use of the *wrap* option on r.js when building. It's encapsulating Almond's attempts to assign the require/define globals inside an IFFE, which means Knockout can't see them on the window object when it goes looking.

You can tweak the *rjsConfig.wrap* definition in *rjsConfigAdapter* to remove the IFFE construct. But it's probably easier to just add require/define to the window object first thing in your application code. Neither option sounds like the right answer, though. Knockout needs a more graceful way of finding require when needed.

```javascript
requirejs.config(config);
window.require = require;
window.requirejs = requirejs;
window.define = define;
```

**Comment by mbest** [comment]
Knockout first tries to get the `require` function using AMD, as `define(['exports', 'require'], factory);`. It seems that this should be compatible with Almond. Any thoughts?

**Comment by someyoungideas** [comment]
Any updates on this? Was the issue solved from @nuclearwessel suggestion, or fixed in the referenced issue #1526?

**Comment by jamespchadwick** [comment]
@someyoungideas the issue was solved from @nuclearwessel suggestion.

**Comment by mbest** [comment]
Closing since there's a decent workaround, and there doesn't seem to be a problem with Knockout specifically.
