### ISSUE TITLE
Scoping CSS within components

### ISSUE THREAD

**Issue by DegreeDev** [knockout/knockout#1692]
One of the most important pieces of web components in my opinion is the ability to completely sandbox pieces of code. We are currently able to sandbox the functionality with JavaScript and it's structure with templates. We are NOT currently able to sandbox the CSS from bleeding out of the component. 

For example: 
```javascript 
ko.components.register("counter-component", {
   template: { element : "counter-component"},
   viewModel : function(params){
      var self = this; 
      self.count = ko.observable(0);
      self.increment = function(){
        self.count(self.count() + 1); 
      }; 
   }
});
ko.applyBindings();
```
```
<span> Better not be blue </span>
<counter-component></counter-component>
   
<script type='text/html' id="counter-component">
  <style>   span {   color: blue;   }  </style>
  <label>Count:</label>
  <span data-bind="text: count"></span>
  <button data-bind="click: increment">+1</button>
</script>
```
[JsBin](http://jsbin.com/huremikeka/3/edit)

Notice the span above is colored blue. 

Now the same code written in Polymer does not bleed out of the component (assuming because it uses the shadow dom and knockout does not). 

[JsBin](http://jsbin.com/foyukijoqa/3/edit)

Any thoughts?

All this being said, I love the components and I'm very excited to see where they will progress to.

**Comment by jods4** [comment]
As far as I know, Polymer polyfills the web component scoped styles by parsing your style and automatically prefixing the CSS selectors.
For instance, in your example it would parse and rewrite the style to:
```html
<style> counter-component span { color: blue; }</style>
```

The question is then: does the KO team want to include a style rewriter (it's more tricky than it looks)? Is this something that could be performed by an optional polyfill? Or should the users write the "polyfilled" css themselves?

A related topic is: what is the roadmap for KO with respect to native web components? How will the two technologies work together?

**Comment by mbest** [comment]
Not exactly the same, but related idea: #1444.

**Comment by SteveSanderson** [comment]
This is a cool idea, but I think it's beyond the scope of anything we could take action on any time soon. As @jods4 points out, rewriting CSS entirely is a huge task, big enough to warrant an open source project all on its own.

Long term, Shadow DOM should give this to you, and that should work well in your KO app. Shorter term, you may want to look for some CSS-specific library to handle this sort of thing.

I'll close now, but if someone has clever ideas about how KO could handle this in a simple but robust way, please reopen :)

**Comment by m-rakic** [comment]
I know that this issue is closed but want to say that encapsulation of css in web components is beneficial for lazy loading of css styles only loaded when component is loaded. Don't have to worry about loading CSS on global scope. In big projects (like we do :) ) and bigger teams this can be beneficial for maintenance and organization. 

For start the web component can have possibility like a template to be defined like

StyleCss: '/css/component.css' or StyleCss:'<style> my-component .style { color: red; } </style>'

we can keep adding component name that in future can be automatic, but for start we achieved a goal that we don't have to worry if CSS is there or not (we can notify if file is not there)... and can be lazy loaded. 

I will try to do that in registration of component part. 

Encapsulation of CSS is one of part of re-usability of web component.

**Comment by JoshWhite** [comment]
Hey, although this project is in it's infancy, I've had some success using this binding in combination with the native components. Interested to see what you think:

https://github.com/JoshWhite/knockoutCSSComponents

**Comment by IanYates** [comment]
@JoshWhite - pretty clever solution.

**Comment by chrisknoll** [comment]
Hey, all, 
  I'm not arguing against the idea, but I do have a little voice of dissent towards the idea of having component-localized styles:

I've been working on my own application that has reusable components (that could be used by external applications unbeknownst to me) and the question of having component-specific styles applied to the component vs. applying styles but letting the containing application define those styles came up.

The reason why I'd argue against the approach described in this thread is that if you're going to embed your component in some other application, the're going to have their own styles and themes that the're going to want to use to make the component look more seamless in their own applications. If you force your styles into their application, you're left with something akin to a Windows 3.1 dialog box (with beveled, square buttons) showing up in a sleek Mac OSX application.  Not attractive.  So while I understand why you might want to do this, I think the more forward thinking approach is to publish a style guide that applies to your component and let the consumer of the component provide the definitions of these styles.  When you have CSS rewriting things in there, it becomes more challenging to know what styles you should be overriding.  

On the other hand, I guess with a Chrome DOM browser you can identify what styles were applied to a component and set up a higher level CSS overide, but that's a bit of effort to do this on the part of the consumer vs. having a guide describing what CSS classes are being used.

**Comment by JoshWhite** [comment]
Thanks @IanYates. It's inspired in part by postcss-modules:
https://github.com/css-modules/postcss-modules/blob/master/README.md

My collegue mentioned it would be good to somehow use postcss as the parser (rather than Regex as it is now), then you'd have benefits like SASS etc. However, the binding obviously only happens at run-time, so I'd be worried about performance. 

@chrisknoll I can see arguments for both. This binding was developed to solve a problem in a single (massive) project, where having totally self contained components was really useful. I can see your point however... It would be good to turn this on/off.

**Comment by m-rakic** [comment]
Hi,

I made a example like I think can be implemented. The approach is same like https://github.com/JoshWhite/knockoutCSSComponents 

that is reading style tag from template and put it in head and remove it from template. 

I'm just adding it to a head, but defining it like object (maybe less overhead in DOM manipulation but maybe less intuitive to write). 

The encapsulation of variables is not new to the programmers world, now is coming for CSS with shadow DOM that will be a standard I think. Encapsulation of styles is not new is used internally in browsers web component.

So we are now trying to emulate new standard and try to use it and see if can be a value in it. Encapsulation of CSS does not mean that we will totally hide web component styles we just wont to avoid collision with global styles and expose some if needed.

I made a example here:
https://jsfiddle.net/marko_rakic/m5dj54wq/23/

I'm using a same class in web component and global scope (container). With adding a "namespace" to web component classes I'm avoiding a collision with global "container". I can directly style web component thought renamed web component classes.
This is not a hard encapsulation in kind of light encapsulation with prefix (namespace).

This way we can avoid collision and less worry if we included a CSS file or not.

**Comment by m-rakic** [comment]
Hi, I made one more example. The default web component class is applied with "short guid" to prevent collision and I'm generating web component class that can be accessed from outside.

https://jsfiddle.net/marko_rakic/j51eenv4/15/

I have default component black and white, and custom component style base on class added to web component. 

So in that case the web component styles is well encapsulated but steel we can change it look from outside.
