### ISSUE TITLE
I have a question about "if"

### ISSUE THREAD

**Issue by woshiwenzhijie** [knockout/knockout#1693]
this is my jsfiddle url.
http://jsfiddle.net/3cdv3auw/

**Comment by nmehlei** [comment]
Error 404, question not found

But apart from that, I think it would be better to post this to StackOverflow.

**Comment by brianmhunt** [comment]
I agree with @nmehlei – @woshiwenzhijie you'll probably get a faster and better response on StackOverflow.

I will close this issue on that basis. However if the issue is with Knockout, please do re-open with details of the issue.

Cheers
