### ISSUE TITLE
Issue with bindinghandler and component

### ISSUE THREAD

**Issue by webm0nk3y** [knockout/knockout#1694]
I have an app which I am modifying to use components along with requirejs (used yo ko example) and I am having a problem with a bindinghandler for a bootstrap modal within a component which is the template and viewmodel for the modal.

I have created a simple example here: https://github.com/webm0nk3y/knockout-component-test

The problem is when navigating to other pages, the callback from addDisposeCallback is getting called and throws and error.

I would also like to know why the images keep on loading after the modal is closed and even when navigating away from the page.

**Comment by rniemeyer** [comment]
It looks like bootstrap's modal doesn't support a "destroy" method like some of the other widgets.  From what I can tell, Knockout removing the element should be sufficient, as the plugin does not add any handlers or data outside of itself. Hope that helps!
