### ISSUE TITLE
Knockout DOM data leaks, if element removed by jQuery

### ISSUE THREAD

**Issue by San4es** [knockout/knockout#1695]
See sample: http://jsfiddle.net/6e52o541/

If a DOM node is removed by ko.removeNode, jQuery data for this node is cleaned, but if it removed by $.remove() - it is not.

**Comment by brianmhunt** [comment]
@San4es – Thanks for the report.

Is it possible that the data remains attached after `$.remove` pending garbage collection? That would be my first thought; whereas `ko.removeNode` deletes the data explicitly, jQuery waits for gc. That's just the first theory that came to mind to explain the problem.

Is this issue exhibiting as some sort of problem you are experiencing?

Cheers.

**Comment by San4es** [comment]
@brianmhunt,

These data will not be cleared automatically by GC, while it has alive reference on it.

**Comment by rniemeyer** [comment]
@San4es - I am not sure that I understand the issue clearly. Are you seeing an issue in a certain browser? I see that called `.remove` clears the jQuery specific data in both Chrome and Firefox.  jQuery's `.remove` would have no way to know to remove the data that Knockout adds (`ko.utils.domData`). Unless something alive referenced something in the domData for the element, it would not prevent the element from being garbage collected though. Thanks!

**Comment by San4es** [comment]
@rniemeyer,

"jQuery's .remove would have no way to know to remove the data that Knockout adds (ko.utils.domData)."

Yes, until Knockout does not tell about it to jQuery ;)

I created the ticket to jQuery bug trackerhttps://github.com/jquery/jquery/issues/2088 about lacking 'remove' event and got an answer, that the way to know when node is removed is wrap native $.cleanData method as jQuery UI does.

So, I think, that jQuery is  enough popular library, that Knockout can clean data on jQuery.remove(), if user use jQuery an Knockout in the same time.

**Comment by rniemeyer** [comment]
I am not sure how far down that road that Knockout core would want to go (replacing/wrapping a jQuery method). Is there a reason in your application that you need to use `$.remove` vs. using KO's normal templating / control-flow (which does the clean up for you) or using the `ko.removeNode` API directly? Just want to understanding your scenario fully.

**Comment by IanYates** [comment]
Also, usually in the MVVM pattern it's best/easiest to let the binding engine in use (knockout) control the updating of the DOM, or at least have the updates happen in coordination via binding handlers.  Is it a third party control that's using $.remove?  If so, could you incorporate that cleanup into your binding handler?

**Comment by SteveSanderson** [comment]
Agreed with @rniemeyer and @IanYates - it would not be ideal for KO to mess with jQuery in that way.

@San4es, if you can get what you want by wrapping `$.cleanData`, have you considered doing that in your application code, and calling `ko.cleanNode` from your wrapper?

Closing because this seems out of scope for Knockout, but please reopen if you disagree.
