### ISSUE TITLE
controlsDescendantBindings broken

### ISSUE THREAD

**Issue by seigoryu** [knockout/knockout#1699]
When using `applyBindings` on an element and a sub element, `controlsDescendantBindings` does not seem to work well when accessing a property with the same name in two different view models.

http://jsfiddle.net/f1bn5r3x/
Changing the username *Bob*, the input field and display field of the **inner** part is updated, but not the display field of the **outer** part.

http://jsfiddle.net/f1bn5r3x/1/
When using different property names (`model`, `model1`) for inner and outer view model, the behavior is as expected.

Found out that the issue exists on the knockout versions 3.0.0, 3.2.0 and 3.3.0 alpha, in FF, Chrome and IE 11.

**Comment by brianmhunt** [comment]
Thanks so much for the detailed report, @seigoryu 

You seem to be missing the `new` operator;  Here is a jsFiddle demonstrating the fix: http://jsfiddle.net/f1bn5r3x/2/

Simply, I changed:

```
ko.applyBindings(function(){
    this.model = new Model('Inner', 'Steve');
    // ^^^ <-- this === window; this.model === window.model
}, document.querySelector('.childNode div'));
```

to 

```
ko.applyBindings(new (function(){
    this.model = new Model('Inner', 'Steve');
   // ^^^ this is the instance constructed by the function
})(), document.querySelector('.childNode div'));
```

The issue here does not appear to be with Knockout per-se, so I will close this issue, but please advise if I have made a mistake or overlooked something and we can re-open.

Cheers

**Comment by rniemeyer** [comment]
or in your case, you can just pass an object literal in like:

```js
ko.applyBindings({
    model: new Model("Outer", "Bob")
}); 

ko.applyBindings({
   model: new Model("Inner", "Steve")
}, document.querySelector(".childNode div"));
```

**Comment by seigoryu** [comment]
Thanks for the fast reply. I didn't see that ...
