### ISSUE TITLE
Create a Gitter.com room for Knockout.js

### ISSUE THREAD

**Issue by rstellar** [knockout/knockout#1700]
Working well for Aureal team.

**Comment by brianmhunt** [comment]
Thanks @rstellar -- (I trust you mean gitter.im?) 

How's gitter compare to slack.com?

**Comment by stormpat** [comment]
I recommend gitter as well, its a very good option to irc/so/etc.

**Comment by exe-dealer** [comment]
:+1:

**Comment by rstellar** [comment]
Ties in with GitHub directly and natively. Less commitment than Slack. Like
IRC for the modern developer. Really enjoying it for the Aureal team.

**Comment by brianmhunt** [comment]
Thanks @rstellar — good to know.

**Comment by brianmhunt** [comment]
Given it seems fairly low maintenance (and easy to opt out of notifications, etc.), potentially quite a useful forum, and the endorsements here, I've gone ahead and set up a gitter.im channel for Knockout.

**Comment by hellboy81** [comment]
Is there alternative speaking rooms?
