### ISSUE TITLE
Embedding markup within virtual component bindings

### ISSUE THREAD

**Issue by gilesbradshaw** [knockout/knockout#1706]
(this uses knockout punches but the same applies to comment style virtual bindings)

I have lots of virtual component bindings in my application..

so when I add some markup to them like this ...

    {{#component:{name:'ce.links.named-link', params:{context:formula, field:'Value'}}}}
        <h1>the name is... {{Name}}</h1>
    {{/component}}

the unbound embedded markup flashes up for a moment and then disappears/gets bound

atm I am resorting to this horribleness...

    {{#component:{name:'ce.links.named-link', params:{context:formula, field:'Value'}}}}
        <div style="display:inline" data-bind="attr:{style:'display:inline'}"><h1>the name is... {{Name}}</h1></div>
    {{/component}}

Although with classes not embedded styles but you get the idea...

Not a major problem but is there/could there be a better way round this?

**Comment by gilesbradshaw** [comment]
actually just tried this with a custom element and i get the same effect

**Comment by brianmhunt** [comment]
Thanks for the report @gilesbradshaw - I think I see what you're saying, but it might help if there were a jsFiddle/jsBin demonstrating this.

**Comment by gilesbradshaw** [comment]
ok here you go http://jsfiddle.net/GilesBradshaw/qcm60843/4/

it's v fast on the fiddle but hopefully you see the red flash. much more apparent in my app i guess because I have lots of components.

**Comment by gilesbradshaw** [comment]
ok here you go.  Sorry about the hacked about demo - it is much more apparent in my app and I oput lots of widgets in to slow it down.  The red flash indicates the embedded html is momentarily in the displayed dom you might have to click the button a few times to catch it

http://jsfiddle.net/GilesBradshaw/qcm60843/15/

**Comment by brianmhunt** [comment]
Thanks @gilesbradshaw -- My first inclination (and it's probably wrong, but just to help me understand the issue) is to add css like this:

```css
widget2 {
    display: none;
}
```

IIRC, the `widget2` tag will otherwise have roughly the same CSS as a `span`.

I'm still sorting out what might be going on here, and so the CSS might be totally off base. But it's a first off-hand suggestion that comes to mind. :)

**Comment by gilesbradshaw** [comment]
Hi yes have resolved it for my app using css however just pointing out it doesn't seem right the embedded content is displayed at all - can be got round - so not too serious

**Comment by brianmhunt** [comment]
Thanks @gilesbradshaw . I think (but may be wrong) that this is by design. I will leave this issue open for a bit though to see what the opinions are. :)

**Comment by wgebczyk** [comment]
Is this "by design" (was designed to behave in this way) or "way it works" (side effect of implementation)?

**Comment by AdamWillden** [comment]
I've used this 'bug' to my advantage to show content while a component is being fetched. In my case it has stopped the scroll from jumping around when changing page (i.e. showing next 15 items) on a tabular component.

In fact I show that usage in the markup in #1638

**Comment by gilesbradshaw** [comment]
@AdamWillden   fair enough - whether a 'bug' or by design it's there now so changing it woulkd be breaking and can be got round with css display:none + data-bind to change to display:inline

suggest we close this unless anyone disagrees?

**Comment by SteveSanderson** [comment]
Agreed to close
