### ISSUE TITLE
Binding property of observable updates object but doesn't notify subscribers

### ISSUE THREAD

**Issue by redbmk** [knockout/knockout#1711]
When you have an observable object inside a `with` or `foreach`, you can bind properties of that object to input boxes, which will in turn update the object itself. However, it does not notify subscribers of that object that it has been updated.

Here's a [jsfiddle](http://jsfiddle.net/tkhwjgws/1/) showing this in action. The first two tables are bound using knockout, and the third table is updated using a setInterval. You can see that the actual data is changing as you modify either of the first two tables, but the two tables that are bound to knockout do not stay in sync.

**Comment by mbest** [comment]
Making an object observable doesn't make its properties observable. You need the properties to be observable, not the object: http://jsfiddle.net/tkhwjgws/2/

**Comment by brianmhunt** [comment]
Just FYI, [knockout-es5](https://github.com/SteveSanderson/knockout-es5) could be of use here. Cheers.
