### ISSUE TITLE
Shouldn't textInput binding take input type="number" into account?

### ISSUE THREAD

**Issue by cervengoc** [knockout/knockout#1713]
Hello guys, currently I'm working on a project where I use numeric inputs in many places. I have lots of troubles and "parseInts" everywhere because the browser doesn't restrict input type="number" to be a real number.

I was thinking wether it would be possible to rely on knockout in this regard, so that when a textInput or value binding is applied to an input type="number", knockout would strip non-numeric characters (which I know it's easier said than done) and convert the element value to a number, so the observable would hold a number instead of a string.

It would be a great feature I think, what do you think?

Thanks,
Zoltan

**Comment by stormpat** [comment]
Basically you could write a extender and extend the observables you need as numeric, and always have them parsed as floats.

**Comment by cervengoc** [comment]
I rather chose the custom binding approach. I managed to solve it with a custom "numberInput" binding. I use the jquery.numeric plugin in this custom binding to restrict the input to numeric values, and I also intercept the bound observable with a writable computed, which processes the numeric (or empty) string, and writes the parsed float into the observable. Then finally I call the value binding's init method. 

I chose not to use textInput for this, because it's not exactly suitable for numeric input, as a number can be treated only in its entire form (the update with every keystroke can cause problem for dxmaple with decimal point, etc.).

Here is my code for anyone's interest (not completely tested, use it with caution). The code is TypeScript, but easily adoptable to JS with a few changes.

˙˙˙
ko.bindingHandlers.numberInput = {
  init(element, valueAccessor, allBindings, root, context) {

    $(element).numeric();

    var interceptor = ko.computed<any>({
      read() {
        return ko.unwrap(valueAccessor());
      },
      write(value) {
        var observable = valueAccessor();
        if (!ko.isWriteableObservable(observable))
          throw new Error("Expected a writable observable for number binding");
        if (typeof value === "undefined" || value === null || typeof value === "number") {
          observable(value);
        } else if (typeof value === "string") {
          var strValue = <string>value;
          strValue = strValue.replace(/[^0-9\+\-\.\,]/, "");
          if (!strValue)
            observable(null);
          else
            observable(parseFloat(strValue));
        } else throw new Error("Failed to process number binding write: " + value + ", " + (typeof value));
      },
      disposeWhenNodeIsRemoved: element
    });
    
    ko.bindingHandlers.value.init(element, function () { return interceptor; }, allBindings, root, context);

    ko.utils.domNodeDisposal.addDisposeCallback(element,
      () => {
        $(element).removeNumeric();
      });
  }
}
˙˙˙
