### ISSUE TITLE
Knockout 3.3.0 tests failing

### ISSUE THREAD

**Issue by cstigler** [knockout/knockout#1716]
In Chrome 41.0.2272.76, tests are failing on the production build of Knockout 3.3.0. I ran them on the knockoutjs.com hosted tests ([link](http://knockoutjs.com/spec/runner.html?src=downloads/knockout-3.3.0.js)). It shows 2 specs failing:

* Observable Array change tracking Skips the diff algorithm when the array mutation is a known operation.
* Expression Rewriting Should be able to cope with malformed syntax (things that aren't key-value pairs).

**Sidenote:** I was investigating this because I found some issues with IE10 on 3.2.0+. It appears that the new Closure Compiler is changing some behavior in the compiled versions, and it broke our web app (the debug version of KO works fine). I'll try to investigate more into that and file a separate ticket, but any ideas would be welcome!

**Comment by mbest** [comment]
The tests at that link are from version 3.1.0. The failing tests represent some slight implementation changes between 3.1 and 3.3.

**Comment by cstigler** [comment]
@mbest Good call! Sorry about the false positive, then. It looks like the bug I'm experiencing is actually with the deferred-updates plugin, so I'll report it there.

**Comment by rniemeyer** [comment]
@cstigler - I updated the specs for the doc site.
