### ISSUE TITLE
google closure compiler ends with a warning

### ISSUE THREAD

**Issue by odungern** [knockout/knockout#1717]
Thanks for your work .... knockout is concise and very useful !

Nothing dramatic, I just wanted to let you know that the Google Closure Compiler issues:

Number of warnings: 1
JSC_SUSPICIOUS_SEMICOLON: If this if/for/while really shouldn't have a body, use {} at line 10 character 252
...++a+"]><i></i><![endif]--\x3e",c[0];);return 4<a?a:p}(),m=/\S+/g;return{Bb...

**Comment by SteveSanderson** [comment]
Thanks for the report! If supressing this warning is important to you, can you send a pull request?

**Comment by mbest** [comment]
I think he is trying to use Google Closure Compiler on the minified code, so this isn't something we have that much control over.

**Comment by odungern** [comment]
.. indeed, we took the delivery package. The developer has submitted all modules (includuding our own) which had no *.min.* in their names to the Closure Compiler to create minified versions. Indeed, looking into the knockout-3.3.0.js shows that it is already minified.
Passing already minified code through the Closure Compiler does not make much sense.
I could have looked myself instead of stealing your time - we apologize.

**Comment by brianmhunt** [comment]
Thanks for the update and clarification, @odungern – much appreciated. :beers:
