### ISSUE TITLE
Building Knockout From Sources Aborted

### ISSUE THREAD

**Issue by someyoungideas** [knockout/knockout#1719]
Attempted to run Grunt task to build Knockout JS from the README and the attempt was aborted. The following is my npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose install where, deps [ 'E:\\Projects\\KnockoutJS',
5 verbose install   [ 'grunt', 'grunt-cli', 'closure-compiler' ] ]
6 verbose install where, peers [ 'E:\\Projects\\KnockoutJS', [] ]
7 info preinstall knockout@3.3.0
8 verbose already installed skipping grunt-cli@~0.1.0 E:\Projects\KnockoutJS
9 verbose already installed skipping closure-compiler@~0.2.1 E:\Projects\KnockoutJS
10 verbose already installed skipping grunt@~0.4.1 E:\Projects\KnockoutJS
11 silly install resolved []
12 info build E:\Projects\KnockoutJS
13 verbose linkStuff [ false, false, false, 'E:\\Projects' ]
14 info linkStuff knockout@3.3.0
15 verbose linkBins knockout@3.3.0
16 verbose linkMans knockout@3.3.0
17 verbose rebuildBundles knockout@3.3.0
18 verbose rebuildBundles [ '.bin', 'closure-compiler', 'grunt', 'grunt-cli' ]
19 info install knockout@3.3.0
20 info postinstall knockout@3.3.0
21 info prepublish knockout@3.3.0
22 verbose unsafe-perm in lifecycle true
23 info knockout@3.3.0 Failed to exec prepublish script
24 verbose stack Error: knockout@3.3.0 prepublish: `grunt`
24 verbose stack Exit status 3
24 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
24 verbose stack     at EventEmitter.emit (events.js:110:17)
24 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
24 verbose stack     at ChildProcess.emit (events.js:110:17)
24 verbose stack     at maybeClose (child_process.js:1008:16)
24 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
25 verbose pkgid knockout@3.3.0
26 verbose cwd E:\Projects\KnockoutJS
27 error Windows_NT 6.3.9600
28 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
29 error node v0.12.0
30 error npm  v2.5.1
31 error code ELIFECYCLE
32 error knockout@3.3.0 prepublish: `grunt`
32 error Exit status 3
33 error Failed at the knockout@3.3.0 prepublish script 'grunt'.
33 error This is most likely a problem with the knockout package,
33 error not with npm itself.
33 error Tell the author that this fails on your system:
33 error     grunt
33 error You can get their info via:
33 error     npm owner ls knockout
33 error There is likely additional logging output above.
34 verbose exit [ 1, true ]

**Comment by mbest** [comment]
You need to have Java installed.

**Comment by someyoungideas** [comment]
Thanks :+1:
