### ISSUE TITLE
ko.applyBindings() returns undefined?

### ISSUE THREAD

**Issue by CoDEmanX** [knockout/knockout#1721]
I found several examples on the web that say `ko.applyBindings()` would return a reference to the instantiated viewmodel, which can be used to access the observables from outside:

    var vm = ko.applyBindings(new MyViewModel());
    vm.myObservable(); // read an observable

`vm` however is undefined - and I tried 2.3, 3.0, 3.2 and 3.3. Was this ever supported in above way?

This is apparently the only way it works:

    var viewModel = function(){
        var self = this; // otherwise "this.* not a function" errors will be raised
        self.accountNumber = ko.observable("...");
        // ...
    }
    var vm = new viewModel(); // declare vm first and assign view model instance
    ko.applyBindings(vm); // then apply bindings on vm or it will fail!
    console.log(vm);

**Comment by simonmurdock** [comment]
Creating the vm first is a fine way to do it. 

looking at http://knockoutjs.com/downloads/knockout-3.3.0.debug.js, apply bindings definitely does not return anything.

**Comment by SteveSanderson** [comment]
Pretty sure `applyBindings` has never returned the viewmodel.
