### ISSUE TITLE
jQuery click on radio buttons doesn't trigger observable on first try

### ISSUE THREAD

**Issue by shri3k** [knockout/knockout#1722]
This relates to PR #1191. 
I'm using the following libraries:- 
`Knockout > 3.0.0 < 3.3.0`
`jQuery > 1.9.1 < 2.0.0`

Not sure if this is the expected behavior but whenever I try to simulate `jQuery.click()` on radio buttons the checked binding doesn't update the `observable` it's bound to. So, let's say I have a `view model` as follows:-

```
var vm = {
    test: ko.observable()
};
ko.applyBindings(Object.create(vm));
```

And in my `html` I have it bound to a radio button with `checked` binding as below:-

```
<input id="test1" type="radio" name="check" value="test1" data-bind="checked:test"/>
<input id="test2" type="radio" name="check" value="test2" data-bind="checked:test"/>
```

Whenever I click on either one of the radio button and check the `test` observable it will have the `value` of the one selected. (This is working as intended)

But now, when I try to simulate the click on radio button with `jQuery` it doesn't change the `observable`. However, it changes when I perform the `jQuery` click twice.  
I'm using `jQuery("#test1").click()` on my jQuery to simulate the click.

Here's the [bin](http://jsbin.com/yinare/4/edit?html,js,output) to show this behavior.

Also, reverting the `knockout` back to `3.0.0` solves this issue.  Could also be that I'm doing something wrong maybe.

**Comment by Senthe** [comment]
I have kind of reverted issue. When I click on radio button, observable changes but `checked` state of input doesn't. It works only on second click. And when I go for jQuery `click()`, it works fine right away. Very strange.

**Comment by mbest** [comment]
The workaround is to call `click` on the element, instead of using jQuery's: `$("#maleID")[0].click()` instead of `$("#maleID").click()`. Also I tried the above test with various versions of jQuery and/or Knockout and never saw the desired behavior. 

Reported to jQuery: https://github.com/jquery/jquery/issues/3423
