### ISSUE TITLE
Components not working in IE8

### ISSUE THREAD

**Issue by novascreen** [knockout/knockout#1723]
When using component bindings it seems like any element unknown to IE, even HTML5 elements like `header` become sth. like `<:header>` and are therefore not styleable (even when using html5shiv)

If I use `<!-- ko template: { nodes: $componentTemplateNodes } --><!-- /ko -->` it breaks down like this:

```html
<DIV id=page class=container data-bind="component: { name: route().page, params: route }" __ko__1425969223232="ko11">
    <:header class=home__panel __ko__1425969223232="ko12">
        <:gll-card params="locations: locations, map:map" __ko__1425969223232="ko13">
            <!--  ko template: { nodes: $componentTemplateNodes }  -->
            Text - <:gll-search params="locations: locations, map:map">
            </:gll-search __ko__1425969223232="ko16"/>
            <!--  ko if: locations().length  -->
            <!--  /ko  -->
            <!--  /ko  -->
        </:gll-card>
    </:header>
</DIV>
```

It also looks like root level custom components like the `<nav-bar>` in the `ko` yeoman generator don't get styled unless explicitly using `document.createElement` in `<head>`. i thought knockout took care of this?

Full example can be found here:
https://github.com/novascreen/getlatlong

possible duplicate with #1636, just wanted to make it obvious that right now this is not usable in IE8 at all

**Comment by vamp** [comment]
Try to use something like
```
<!--[if lt IE 9]>
<script>
var d = document;
d.createElement("header");
d.createElement("gll-card");
d.createElement("gll-search");
</script>
<![endif]-->
```

at the head section of your document

**Comment by novascreen** [comment]
would it at least be possible to support HTML5 elements? jQuery.fn.clone does that, doesn't work with custom elements, which can be worked around with the component binding

i'll try that for the components and report back if i still have problems with this part:
```

**Comment by novascreen** [comment]
so if i use component bindings for everything it works perfectly. 

i tracked down the issue to the use of `cloneNode`. Unless you're willing to change that and use something like jQuery does (making use of documentFragment if i remember correctly) my alternative route would be to have a crack at a small conversion tool (as a grunt/gulp task or sth). 
So you could write and share knockout components as custom elements, but always provide a legacy version where your template and css is changed in order to support component bindings for IE8 supporting projects.

For example you could write a component `my-map` that uses a `ko-gmap` component:

Template
```html
<ko-gmap params="map: map"></ko-map>
```
Stylesheet
```css
my-map ko-gmap {  width: 100%; height: 100%; }
```
and automatically convert it to this:

Template
```html
<div class="ko-gmap" data-bind="component: { name: 'ko-gmap', params: { map: map } }"></div>
```
Stylesheet
```css
.my-map .ko-gmap {  width: 100%; height: 100%; }
```
and then you could use the version that suits your projects' needs.

I think changing the way templates are processed right now would not be a small deal, so i'd be curious to know if you think this direction could be a way to make it easy for everyone to share knockout components and use them in any environment?

**Comment by SteveSanderson** [comment]
Could you clarify:

 * Did you follow [the documented suggestions](http://knockoutjs.com/documentation/component-custom-elements.html#note-custom-elements-and-internet-explorer-6-to-8) and it still doesn't work?
 * Or are you saying you would like it to work even without following those suggestions?

**Comment by novascreen** [comment]
i was using your yeoman generator, so component registration should happen before it IE parses the rest of the page, right? I also added a script tag in `<head>` to do the old `document.createElement` for all my components, but this weird `:element` behavior still happened.
I wouldn't mind this, could probably auto-generate it somehow, but right now it's not working.

**Comment by SteveSanderson** [comment]
No, sorry, the yeoman template (generator-ko) doesn't support IE < 9. If you want to make it support IE8, you'll need to use the [documented suggestions](http://knockoutjs.com/documentation/component-custom-elements.html#note-custom-elements-and-internet-explorer-6-to-8).

**Comment by novascreen** [comment]
i'm still seeing the `<:` issue. here is my example: http://bl.ocks.org/novascreen/431664ce9e248ea8500d

the output is this:
```html
<:header __ko__1433060110177="ko12">
    <INPUT value=test data-bind="textInput: test" __ko__1433060110177="ko13" jQuery111309727910641428483="1">
    <SPAN data-bind="text: test" __ko__1433060110177="ko15">test</SPAN>
</:header>
<:main __ko__1433060110177="ko16">
    <:ko-widget params="message: test" __ko__1433060110177="ko17">widget:
        <STRONG data-bind="text: message" __ko__1433060110177="ko18">test</STRONG>
    </:ko-widget>
</:main>"
```

I've made sure to load HTML5Shiv, create the custom elements with `document.createElement` and 
register them with `ko.components.register` before the parser gets to the first custom element. It still adds those colons at the beginning of those tags.

If i don't load jQuery then Knockout throws an error:
`Unexpected call to method or property access.   knockout.debug.js, line 280 character 21`

It would be really great to have just one example with a component binding where the template includes HTML5 and custom elements which fully works in IE8 (including styling)
