### ISSUE TITLE
Include deferred updates in Knockout core

### ISSUE THREAD

**Issue by mbest** [knockout/knockout#1728]
My Deferred Updates plugin has been quite popular as a means of improving the performance of Knockout applications. But it's quite a hassle to keep it updated with each new version of Knockout, while maintaining backwards compatibility with previous versions. This is mainly because it replaces some of Knockout's internal components such as `ko.computed`.

I think the framework is already in place within Knockout now, with the rate-limit and version features, to make deferred updates a very simple addition.

**Comment by rniemeyer** [comment]
I am all for it. Sounds like a great idea.

**Comment by reflectiveSingleton** [comment]
+1 for this

**Comment by brianmhunt** [comment]
Great suggestion @mbest; I like the idea of this functionality being in core, though I am mindful enough of SteveSanderson's [comment](https://github.com/knockout/knockout/pull/1543#issuecomment-70330822) to note it here:

> We have so much functionality around computeds by now that the logic in `dependentObservable.js` is really intricate... I think we've done a great job of keeping it robust by having such extensive test coverage, but it's absolutely at the limit of what I think is practical to maintain.

Which is not to deter merging this – only that we should be mindful of the possibility that we are travelling down the path of a monolithic design pattern, that may prove a challenge to maintain and evolve.

One option may include eventually decoupling the observable system from the binding system.

:+1:

**Comment by mbest** [comment]
@brianmhunt You are right that we need to be cautious, but my hope is that the changes to `dependentObservable.js` will be very minimal.

I'd like to use this space to do a little brainstorming about this feature. I think a good way to start is to go through parts of the plugin and examine if they should be ported to Knockout.

* In the plugin, all pending deferred updates are added to a queue and handled by a single scheduled processing function. In other words, it includes a task manager. If we were running only in Node.js, `process.nextTick` might be a sufficient replacement, but there isn't any equivalent facility in browsers. So I think this will be a necessary feature, which could also prove useful for other areas of Knockout, such as components (see #1659).

* The plugin allows you to turn deferred updates on and off. The feature is on by default, but it can be later turned off, either globally or for a specific computed observable. We'll definitely need some sort of API to enable deferred updates, and using `ko.computed.deferUpdates = true;` might be a good enough method. But I'm more inclined towards a one-way action that requires calling a function, such as `ko.computed.enableDeferredUpdates();`

* The plugin defers all `change` subscriptions. `rateLimit` also does this by delaying the `change` notification, so this should just work naturally. But it does mean that all observables will need to be "deferred".

* The plugin uses a custom event, `dirty`, to signal computed observables that they will need to be updated. We might be able to instead use the observable versioning added in 3.3 to accomplish the same thing, but we should, I think, compare both options to pick the one that works the best.

**Comment by reflectiveSingleton** [comment]
@brianmhunt fwiw I would personally prefer it to be globally off by default with opt-in on a per computed basis (basically as you describe near the top of the README for knockout-deferred-updates).

ie: preserve the current behavior (synchronous resolution) in favor of BC.

**Comment by SteveSanderson** [comment]
In principle I'd be happy for us to work towards this. Significant performance improvements are certainly valuable!

Along the lines that @brianmhunt mentions, I'd be interested in making sure we perform whatever refactoring is necessary for it to be possible for such changes not to push us into increasing realms of complexity. For example, the dependent observable code is already beyond the number of code path permutations that I can hold in my head at once or remember the reasoning behind, so I'd not like to see that get even more intricate. If we are talking about a big refactoring like fully decoupling observability into a standalone library, and we can do so with full back-compatibiltiy and producing better-factored-out code, I'm open to that. But if we're talking about adding a load more cases to existing observable/computed/subscribable (etc) code and/or backwards-incompatible changes, I'm less keen :)

> In other words, it includes a task manager ... I think this will be a necessary feature,

New side-by-side features like that (assuming not huge, but doesn't seem like it would be) sound absolutely fine and good to me.

> But it does mean that all observables will need to be "deferred".

Not sure how to interpret that. In the case where a developer isn't using deferred updates, presumably we wouldn't be causing breaking changes to the behavior of every observable in their system.

@mbest - if you have a sense of the minimal set of changes that would be needed for this, and/or the way we'd approach it if we were taking it as a big foundational change such as decoupling observability completely for KO 4.0, that might help to direct the planning.

**Comment by mbest** [comment]
I've created a pull request, #1738, that includes the base functionality for deferred updates: a task scheduler and `deferred` extender.

**Comment by mbest** [comment]
With #1738, we now have a task scheduler and a `deferred` extender that allows for functionality like @reflectiveSingleton has suggested--to opt-in on a per computed basis.

The next step to match the functionality of the plugin is to provide a way to make Knockout use deferred updates for all observables. Obviously this must be an opt-in feature since many applications could depend on synchronous updates or on being notified of each update. Even if an application can mostly work with asynchronous updates, it might need some to happen synchronously (e.g. when [updating the bound array in knockout-sortable](https://github.com/rniemeyer/knockout-sortable/blob/master/src/knockout-sortable.js#L245)). In my [Deferred Updates plugin](https://github.com/mbest/knockout-deferred-updates), I included multiple ways to accomplish this, which I'll review here.

1. `ko.computed.deferUpdates = true | false` - Sets the default behavior of all observables and subscriptions, and is initially `true`. I suggest setting this value once when initializing your application, although you could toggle it later on to make some updates synchronous.

2. `ko.processAllDeferredBindingUpdates( )` - Runs all currently scheduled tasks (originally it only ran tasks that were associated with a binding). When an application contains code that depends on the normally synchronous updates, this method is usually the easiest way to "fix" it.

3. `ko.tasks.processImmediate( callback )` - Runs the callback function and then runs any tasks that were scheduled during that time. This allows the tasks to run asynchronously from the point of view of the callback function and synchronously from the calling code.

I don't think we need anything like `ko.tasks.processImmediate`, but I do think we need something like the other two methods.

1. As implemented in #1738, turning on deferred updates for an observable involves applying the `deferred` extender to it. If we want to have the extender applied to all observables (conditionally), we could include code like `if (<deferUpdates>) { ko.extenders.deferred(observable, true); }`. Setting that condition could be done directly, like `ko.computed.deferUpdates` or using a function, such as `ko.enableDeferredUpdates()`. Another option is to have default extenders for observables, which would be used like `return observable.extend(<defaultExtenders>);`. With either method, turning off deferred updates would only affect observables created afterwards.

2. In #1738, I had originally included a `ko.tasks.runTasks` method that worked like `ko.processAllDeferredBindingUpdates`, but I took it out because it didn't have any obvious use without deferred updates being a default behavior. As the discussion between @brianmhunt and myself shows, we need to be careful to make sure people know that they don't normally need to call this.

**Comment by mbest** [comment]
#1753 includes the next steps for full support for deferred updates: an option to make it the default behavior, and a method to run pending tasks early.

**Comment by SteveSanderson** [comment]
Hey, awesome work! Sorry I didn't repond to the earlier pull request at the time, but I now got chance to read throught it all in detail. Overall this looks like fantastic functionality and I'm really glad we're putting this into the core.

I've put some comments inline into #1738 and #1753 (even though #1738 is already merged and closed), and have some more general remarks here:

 * Why have `deferred` as an extender, and not just a bool property you can toggle, or a `setDeferred` method you can call? These other two approaches both seem more obvious, plus they make it clearer that you're mutating the observable in place, rather than leaving it alone but constructing a new 'deferred' observable that wraps the underlying one. I've always felt bad about the extenders API being unclear whether you're mutating in place or not.
 * Do we definitely want this new functionality to be called "deferred"? I appreciate there's some history here and @mbest especially might feel a bit attached to that name. But we already have the feature `deferEvaluation` which is completely separate, and this clash of names might lead to a lot of confusion. If I was to suggest a name for the new functionality, I'd propose "batch" or "batched", since that's becoming common terminology in front-end web dev and has a meaning exactly matching what benefits this new feature offers - people will get it and adopt it more readily I suspect. I'm not fixated on calling it that, but just offering this for discussion.

**Comment by mbest** [comment]
Thanks, Steve, for the appreciation! I see you've been working hard at sorting and clearing out old issues. Thank you!

> Why have deferred as an extender, and not just a bool property you can toggle, or a setDeferred method you can call?

Currently that's the API we have for modifying the behavior of an observable after it's created, which we already use in a similar way with `notify` and `rateLimit`. Also, since I want to be able to turn *off* deferred updates, it works well to have the extender take a boolean value. Using a property would be complicated to implement since turning on deferred updates requires calling the `limit` function, which would have to be triggered somehow.

> Do we definitely want this new functionality to be called "deferred"?

I personally like "deferred" more than "batched". But I'm open to other views. And if a different name will be more appealing to users, I'm all for it.

**Comment by mbest** [comment]
Part 3 is ready for review: #1795.

**Comment by mbest** [comment]
I've completed this as far as I had originally planned (in three parts). @SteveSanderson has brought up some good points in #1758 that we may want to discuss and resolve before the release.

**Comment by brianmhunt** [comment]
Awesome work here, @mbest. :)

**Comment by mbest** [comment]
Thanks. :smile:

**Comment by PaulHuizer** [comment]
@mbest indeed ... +1 +1
