### ISSUE TITLE
Debugging: Expose computed options (including read/write functions)

### ISSUE THREAD

**Issue by lcorneliussen** [knockout/knockout#1731]
When debugging it helps a lot to be able to see a computeds options (read, write, e.g.) in the developer tools.

    if (readFunction && typeof readFunction == "object") {
        // Single-parameter syntax - everything is on this "options" param
        options = readFunction;
        readFunction = options["read"];
    } else {
        // Multi-parameter syntax - construct the options according to the params passed
        options = options || {};
        if (!readFunction)
            readFunction = options["read"];
    +    else
    +       options.read = readFunction;
    }
    if (typeof readFunction != "function")
        throw new Error("Pass a function that returns the value of the ko.computed");

    + if (DEBUG) dependentObservable._options = options;

**Comment by SteveSanderson** [comment]
Fixed by #1732.
