### ISSUE TITLE
Fiddles are not working in the async observables wiki page

### ISSUE THREAD

**Issue by cauburtin** [knockout/knockout#1734]
https://github.com/knockout/knockout/wiki/Asynchronous-Dependent-Observables

**Comment by SteveSanderson** [comment]
Thanks - I've removed the bad links. They are quite outdated (they use the ancient string-templating mechanism!) so probably not the best examples to copy from, though the wiki page itself is fine.

If someone wants to recreate jsFiddles from the information in the wiki page they can do so and add links.
