### ISSUE TITLE
`myItems().count` on introduction page

### ISSUE THREAD

**Issue by hasenj** [knockout/knockout#1736]
The [introduction page](http://knockoutjs.com/documentation/introduction.html) gives the following example under "How is knockout different?":

`There are <span data-bind="text: myItems().count"></span> items`

As far as I can tell, there's no `count` property neither on the `observableArray` nor on the built in array.

**Comment by stormpat** [comment]
Should probably be ```myItems().length```

**Comment by SteveSanderson** [comment]
Thanks - fixed!
