### ISSUE TITLE
Please provide the native event as a parameter to `subscribe`

### ISSUE THREAD

**Issue by NoelAbrahams** [knockout/knockout#1737]
Hi,

```html
<input data-bind="value: foo, valueUpdate: 'afterkeydown' " />
```

```javascript
this.foo = ko.observable();
this.foo.subscribe(function(value, event) {
});
```

The request is for the `event` parameter to be populated in the subscribe callback.

**Comment by stalniy** [comment]
Do you suggest to mix concepts (data and DOM, i.e Model & View)?

**Comment by NoelAbrahams** [comment]
I see where you're coming from, but this is already done for other bindings, e.g. [the click binding](http://knockoutjs.com/documentation/click-binding.html):

> In some scenarios, you may need to access the DOM event object associated with your click event. Knockout will pass the event as the second parameter to your function, as in this example:

I wouldn't consider the event object as a case of messing with the DOM. It is actually a mechanism for separating the model from the view. (I wouldn't have put `event.currentTarget` in there, but so long as you don't abuse it, it has its uses.)

**Comment by stalniy** [comment]
`subscribe` is a method of an observable. Observable can be updated inside code according to business logic(e.g. by retrieving data from server) not by user input. What should be passed in that scenario as second argument?

**Comment by NoelAbrahams** [comment]
Undefined I'd expect. 

Ideally the library should surface all available information. It's up to the person writing the code how they use it.

**Comment by hasenj** [comment]
I think this approach would be rather clumsy. The beauty of observables is that they are completely independent of the DOM.

If you want to react to certain keystrokes, why not just add a binding for the keydown event?

http://knockoutjs.com/documentation/event-binding.html

For example, to blur the field on "esc":

     <input data-bind="textInput: textValue, event: { keydown: handleKeys }, hasFocus: hasFocus">

     // javascript .. assuming the view model is `vm`
     vm.textValue = ko.observable();
     vm.hasFocus = ko.observable();
     vm.handleKeys = function(event) {
        if(event.keyCode === 27) {
            vm.hasFocus(false);
        }    
     }

**Comment by SteveSanderson** [comment]
Thanks for the suggestion. I'm going to agree with @hasenj, @stalniy and others who prefer to keep the separation of concepts clean. Knockout observables themselves are entirely separate from the DOM and DOM events.

I would recommend that, if you are trying to feed information from a DOM event into your view model, you catch the DOM event from inside a custom binding and from your event handler supply whatever information you want to your viewmodel.
