### ISSUE TITLE
Components - Dispose

### ISSUE THREAD

**Issue by carlosagsmendes** [knockout/knockout#1739]
I want to follow @rniemeyer suggestion in order to properly handle disposing:

[Cleaning Up After Yourself in Knockout.js](http://www.knockmeout.net/2014/10/knockout-cleaning-up.html)

Inside my component I want to maintain a **disposables** array that I need to clean up when a component is unloaded.

How can I know that a component is about to be unloaded in order to trigger the cleaning process?

Thanks in advance

**Comment by rniemeyer** [comment]
@carlosagsmendes - If your component's view model has a `dispose` function, then Knockout will call it when your component is being tore down. You can find some documentation and an example [here](http://knockoutjs.com/documentation/component-binding.html#disposal-and-memory-management).  Closing, but feel free to respond, if you have remaining concerns about disposal. Thanks!
