### ISSUE TITLE
arrayRemoveItem doesn't work with observable array

### ISSUE THREAD

**Issue by mirik123** [knockout/knockout#1743]
```
this.arr = ko.observableArray();
var itm = ko.utils.arrayFirst($this.arr(), function(itm) { return itm.id === 0; });
```

this code doesn't work because the ko.utils.arrayIndexOf must receive unwrapped value:
`ko.utils.arrayRemoveItem($this.arr, itm);`

and this code removes the item but doesn't notify the observable:
`ko.utils.arrayRemoveItem($this.arr(), itm);`

so, I have to do it manually:
```
var index = ko.utils.arrayIndexOf($this.arr(), itm);
 if (index > 0) {
     $this.arr.splice(index, 1);
 }
 else if (index === 0) {
     $this.arr.shift();
 }
```

**Comment by StrahilKazlachev** [comment]
If you want to remove an item and trigger notification why not use [observableArray.remove](http://knockoutjs.com/documentation/observableArrays.html#remove-and-removeall)?

**Comment by mirik123** [comment]
Great thanks for pointing to **remove** method but the problem with **arrayRemoveItem** still remains in air.
**arrayRemoveItem** doesn't work as expected so there need to be added a validation code that throws error or all possible argument types (regular/wrapped observable/unwrapped observable) should be supported.

**Comment by schellem** [comment]
Yea this bit me in the Azz for about an hour today.
