### ISSUE TITLE
incorrect grammar in headings for Tutorial "single page application"

### ISSUE THREAD

**Issue by lwgray** [knockout/knockout#1745]
1.  Mail is both singular and plural -mails is not the plural form of mail
2.  Email is both singular and plural but emails is an acceptable plural form

**Comment by SteveSanderson** [comment]
Thanks for the suggestion! Although I appreciate the feedback, I don't think this is consequential enough to warrant changing. Since I'm processing a large number of issues at the moment I need to focus resources elsewhere. Hope that's OK!
