### ISSUE TITLE
ko.toJS not outputting empty observables

### ISSUE THREAD

**Issue by grofit** [knockout/knockout#1747]
I am not sure if this is a recent thing, but I noticed today that a bit of functionality was not working, which I believe was historically working.

The gist of it is if you were to have an observable which had no data in it and called `ko.toJS` the field would not be output. Here is an example showing what I mean:

https://jsfiddle.net/0x0vcx2q/

I am not sure what the desired behaviour is but I would have assumed all fields would be outputted but would just have an empty string if it was empty. Feel free to ignore if this is the expected behaviour.

**Comment by rniemeyer** [comment]
Hello- the behavior that you are seeing is from `JSON.stringify`. `undefined` properties will not appear in the final output. If the value is an empty string or `null`, then it would still appear. Thanks!

**Comment by grofit** [comment]
Most interesting, thanks for clearing that up.
