### ISSUE TITLE
Documentation for ko.computedObservable

### ISSUE THREAD

**Issue by wallymathieu** [knockout/knockout#1748]
The [documentation](http://knockoutjs.com/documentation/computedObservables.html) for computed obserable does not mention that computed is not needed in many cases. Since it looks like computed is used internally when binding expressions and properties to a view.

```
this.fullName = function() {
    return this.firstName() + " " + this.lastName();
};
```
using:

```
The name is <span data-bind="text: fullName()"></span>
```

Also there are some issues with using computed willy nilly:
[knockout-cleaning-up](http://www.knockmeout.net/2014/10/knockout-cleaning-up.html)

Perhaps some additional documentation on the page computed observable section?

**Comment by waldheinz** [comment]
When doing it the suggested way, the `fullName` won't be updated when either `firstName` or `lastName` change, which in my understanding the main selling point for using `computed`s. But I admit there may be "fire and forget" scenarios where this can be a valid thing to do. Albeit it will be a pain to debug when the requirements change.

**Comment by wallymathieu** [comment]
Well, it looks like it is updating in : http://jsfiddle.net/ozzymcduff/t1cafytg/

**Comment by waldheinz** [comment]
Oh wow, ok, so the magic happens in the `text:` part of `data-bind='text: fullName()'`. Good to know!

**Comment by wallymathieu** [comment]
It's nothing special for the text binding. You can get the same behavior for your custom bindings. Try out this example by making the name longer than 10 characters: http://jsfiddle.net/ozzymcduff/k9zk0721/

**Comment by SteveSanderson** [comment]
Thanks for the suggestion. I haven't found many people to be confused by the existing docs, so I don't think it necessary to prioritise changing this. If you do feel strongly please consider submitting a pull request on those docs - in the meantime I'll close this to tidy up. Thanks the the feedback though!

**Comment by wallymathieu** [comment]
I don't feel strongly about it. I have met a lot of confusion about it
though. People starting to program knockout that start by thinking that
they need to use computed.
