### ISSUE TITLE
Computed doesn't update its value

### ISSUE THREAD

**Issue by chebum** [knockout/knockout#1749]
Hi,

Not sure if this considered an issue, so problably @mbest or @brianmhunt could take a look at this. In 3.3.0 setting new computed value doesn't actually update computed value if none observables were fired. 
Is it expected behavior?
Here is a quick demo: https://jsfiddle.net/jxpmecme/

**Comment by rniemeyer** [comment]
@chebum - in your scenario, `prop` would need to be an observable or your computed's write method would need to write to `ko1` itself. The notifications in Knockout are triggered off of writes to an observable, so accessing an observable and modifying a property would not cause any notifications. Thanks!

**Comment by brianmhunt** [comment]
Just for ease of access @chebum - there's a lengthy discussion in #1019 that may be illuminating.

**Comment by chebum** [comment]
@rniemeyer Ryan, thanks a lot!
