### ISSUE TITLE
Meta: Proposal to tidy up labels

### ISSUE THREAD

**Issue by SteveSanderson** [knockout/knockout#1755]
I think some of the labels attached to issues might not still be used for anything. I know I've started one or two efforts to apply certain labels (like the `N-*` ones) that I later stopped using.

The labels I'm aware currently serve a purpose are:

 * `severity.*`
 * `type.*`
 * `affected.*`
 * `close`
 * `api` and `breaking` (though these aren't applied totally consistently)
 * `waiting` (though to be honest, I have no workflow for taking action on these after some time has elapsed)

For all the others, if you are still using them as part of some workflow, could you say so? There's a lot of colourful noise and clutter in the issue backlog with inconsistently applied labels. It would be great to be able to trust that when something has some labels, those labels make a difference to how we handle it :)

**Comment by brianmhunt** [comment]
@SteveSanderson – I think the list of labels with a purpose is quite workable, and it would be good to delete a bunch of the others.

Would we want (and is it practical) to transpose older labels to a new equivalent e.g. `Cosmetic` ⇒ `type: feature`? It probably is not too difficult to re-add labels as items are reviewed/triaged.

**Comment by SteveSanderson** [comment]
> e.g. Cosmetic ⇒ type: feature

We can certainly do that, but I'm not sure it's necessary. All issues are now triaged, which means they already have a `type` label. Or are there some that this doesn't cover?

**Comment by brianmhunt** [comment]
I think you're right. The few edge cases look to be already triaged.

I just went through, and I feel like it's safe to delete

- `Cosmetic`,
- `Documentation`
- `Enhancement`,
- `N-*`,
- `declined`
- `duplicate`
- `not-a-bug`
- `vFuture`

I don't think removing those tags will result in any perceptible loss of information from the system.

#### Tags I was uncertain about

**api** and **breaking** — What do the `api` and `breaking` labels signify? They seem interchangeable, and I am not sure entirely what they indicate – other than that a merge may perhaps ought to wait for a major version change. I think they're fine to keep; the fact that they are not applied consistently indicates some clarity in naming/thinking may go a long way.

**waiting** — A dozen issues had this tag. How does it help?

#### Two tags that could be kept/added

**needs-review** — Just a quick way for devs to look over the list of things that are close to merging.

**support-request** — One tag that could be useful is `support-request` (or `not-a-bug`), which would be applied to cases that clearly are, or at first glance look like, a user-problem as opposed to a library bug. If possible, it would be great if this tag coincided with a possibly-automatic message that indicated that the issues on GitHub are for bugs, and that there are other places for support (stackoverflow, mailing list, gitter.im, etc.).

**Comment by SteveSanderson** [comment]
> api and breaking — What do the api and breaking labels signify?

`api` was meant for nonbreaking changes that would additively affect the API surface and hence require documentation. `breaking` changes require a lot more justification and potentially need to be grouped into major-version releases. But since there's no real workflow that does anything with `api` or `breaking` in aggregate (they don't affect triage scores), those labels aren't giving us much value it seems.

> waiting — A dozen issues had this tag. How does it help?

I suppose in theory, every month or so, someone could sweep the `waiting` items and close them if they were inactive (i.e., we've asked for more info to clarify whether a certain bug report really is a bug, but no info was provided).

> needs-review — Just a quick way for devs to look over the list of things that are close to merging.

No objection to having the label. TBH my contribution habit is more influenced by email - if I see a conversation is going on, I'm inclined to check it out. I might not regularly be reviewing a `needs-review` list, but if others feel they would, that's great.

> support-request — One tag that could be useful is support-request (or not-a-bug)

If possible I'd prefer to close issues that are support requests, and maintain the clarity that the issue tracker is for bugs and feature requests. Often it's possible to provide a one-sentence response with a link to relevant docs when closing such issues. But if others feel they have capacity to regularly track and respond to support requests this way I'm perfectly OK with it :)

**Comment by brianmhunt** [comment]
>  But since there's no real workflow that does anything with api or breaking in aggregate (they don't affect triage scores), those labels aren't giving us much value it seems

Just to clean up the labels, I'd be happy to see `api` and `breaking` go, unless there's a more concrete workflow they can be part of.

> I suppose in theory, every month or so, someone could sweep the waiting items and close them if they were inactive 

Got it. Is it worthwhile/possible to automate the pruning of `waiting` tasks where there have been no follow-up comments for a couple months? It's not a huge hassle to have the `gulp` build system do this, incidentally (and should be easy enough to add it to a cron job).

> I might not regularly be reviewing a needs-review list, but if others feel they would, that's great.

@mbest @rniemeyer – do either of you follow the `needs-review` tag? I'm okay nixing it, since the volume of content that needs review is pretty short so it's usually clear. I'm happy with it being around too, if there's demand. It's all good. :)

> If possible I'd prefer to close issues that are support requests, and maintain the clarity that the issue tracker is for bugs and feature requests.

Sorry I was unclear – I agree with closing `support-request` issues. The idea with using this tag is to have an automated process that closes the issue and adds a comment along the lines of:

*Thank you for submitting this issue. It appears that the issue you have submitted is a support question, and you may have more help and better luck on stackoverflow.com, gitter.im, google groups, etc. If you believe we are mistaken about this being a support issue (i.e. you believe there is a problem with the Knockout library that must be fixed), please post a comment and we can re-open this issue.*

**Comment by rniemeyer** [comment]
@brianmhunt - I don't specifically follow the `needs-review` tag

**Comment by SteveSanderson** [comment]
OK great. I've been through and removed the labels that @brianmhunt listed for removal, plus a few others where no issues were using them or they just duplicated other labels. The ones that remain all seem to have clearly distinct meanings, even if there isn't an obvious workflow associated with all of them.

I haven't yet removed `api`/`breaking` because I'd also have to update triage.knockoutjs.com, and I've left `waiting` because this conversation didn't yet settle on what we're doing with it.

> Is it worthwhile/possible to automate the pruning of `waiting` tasks

If you want to set that up then great. TBH I'm OK with continuing the manual approach, since it's not like we're dealing with dozens of these a week.

> [Brian] do either of you follow the needs-review tag? I'm okay nixing it
> [Ryan] I don't specifically follow the needs-review tag

OK, I dropped it. It wasn't really in use. We can bring it back if it seems necessary.

**Comment by brianmhunt** [comment]
Wonderful. It's a much cleaner list of labels now.

I think it is probably worth keeping `waiting` around, just to see if it fits into the workflow of anyone.

On automating `waiting`, once a gulp-based build system is in place, and if there's any demand, I'd be happy to have a stab at it.
