### ISSUE TITLE
Options binding won't update the selected value on Android >= 5 anymore

### ISSUE THREAD

**Issue by aspnetde** [knockout/knockout#1762]
Hi guys,

I ran into an issue that seems to appear in the Android browser starting from Android 5 aka Lollipop. In all other browsers (Android versions below, iOS, Desktop etc.) it's still working fine.

Tested knockout.js versions: 2.2.1 and 3.3.0.

What happens?

When binding a list of complex objects to a `<select />`, the `<select />` will still fire an update, so all subscribers get notified, but it won't update the HTML element anymore. So if you select something from the list, it won't reflect that selection in the element - it just doesn't display that selection.

Here's a working failing test:

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script type='text/javascript' src='http://knockoutjs.com/downloads/knockout-3.3.0.js'></script>
</head>
<body>
    <p>
        Destination country:
        <select id="client" data-bind="options: availableCountries,
                                           value: selectedCountry,
                                           optionsText: 'name',
                                           optionsCaption: 'Please select'"></select>
    </p>

    <script type="text/javascript">
        var viewModel = {
            // These are the initial options
            availableCountries: ko.observableArray([
            {
                name: 'Germany',
                id: 1
            },
            {
                name: 'USA',
                id: 2
            },
            {
                name: 'Brasil',
                id: 3
            }]),
            selectedCountry: ko.observable(null)
        };

        viewModel.selectedCountry.subscribe(function (country) {
            if (country) {
                alert(country.name);
            }
        });

        ko.applyBindings(viewModel);
    </script>
</body>
</html>
```

**Comment by aspnetde** [comment]
That may be related: http://stackoverflow.com/questions/28282206/android-knockout-select-problems-chrome-and-native-browser

**Comment by brianmhunt** [comment]
Thanks for the report and link to SO, @aspnetde – it sounds like this is a browser issue. What version of Chrome are you testing with? 

:beers:

**Comment by aspnetde** [comment]
You're welcome @brianmhunt. Actually it's not Chrome I tested with, but the built-in browser that comes with the plain-vanilla Android 5. But it seems also to be reproducable with Moto G (5.0.2) and HTC One (5.0.2) running a hybrid Cordova app (no idea if the browser view inside that cordova app is delivered by Chrome or not).

**Comment by brianmhunt** [comment]
@aspnetde Got it, thanks. We've a testing system set up where we can run against that platform live on BrowserStack, but it's not in gear yet ... when it is, we'll see what issues become visible on Lollipop, and hopefully we can root this out.

If it is browser-upstream, it may be that there's no easy workaround. Do you know if there is a bug report on Lollipop about this that we can track and see if the discussion indicates a workaround?

**Comment by aspnetde** [comment]
@brianmhunt Glad to hear about the test setup. I am not aware of any bug report on the Google side, nope.

**Comment by aspnetde** [comment]
Hey,

Any updates on this?

Cheers.

**Comment by jesulink2514** [comment]
Any updates on this with the version 3.4.0?

Cheers.

**Comment by magicpotion** [comment]
Seems recent **Chrome Version 51.0.2704.63** 
also breaks optionsText, I thought I introduced some error, but on FF works fine.
I also saw few fiddles with the same error occuring.
This one for example: [http://jsfiddle.net/jLbct/](url)
![screenshot](https://cloud.githubusercontent.com/assets/14107724/15959890/95602e9a-2f2f-11e6-8045-4dc171faf6f5.png)

I think it makes it critical?

**Comment by sumitkm** [comment]
@magicpotion That fiddle seems fine on Chrome 51 for windows, is that OSX
or Linux?

[image: Inline image 1]

**Comment by magicpotion** [comment]
Linux

**Comment by sumitkm** [comment]
my bad! Missed the Android bit...

**Comment by mbest** [comment]
Given that this a browser-specific issue, I will close this.
