### ISSUE TITLE
foreach binding on custom component

### ISSUE THREAD

**Issue by kaleb** [knockout/knockout#1766]
I would like to be able to have a custom component that can optionally have content generated programtically with a foreach binding.  Something such as:

    <custom-element>
      <span>item 1.1</span>
      <span>item 1.2</span>
      <span>item 1.3</span>
    </custom-element>
 
OR
 
    <custom-element data-bind="foreach: { data: ['item 2.1', 'item 2.2', 'item 2.3'], as: 'item' }">
      <span data-bind="text: item"></span>
    </custom-element>

Example: https://gist.github.com/kaleb/f90a79e3275fe5dc21c8

I am attempting to make an accordion component using this technique, but currently it is not possible.  I would like to request this feature be added.  I am currently looking into internals to see how to implement this, so my pull request is not ready yet, but I wanted to see if this was some desired behavior.

**Comment by frankabbruzzese** [comment]
You can achieve the same result by passing just the item template as a content to the component(that is just one prototypal element). Then you may perform the foreach inside the component code itself as shown in this example:
http://knockoutjs.com/documentation/component-custom-elements.html#passing-markup-into-components

**Comment by kaleb** [comment]
My demonstration was a simplification, but check out https://angular-ui.github.io/bootstrap/#/accordion .

In their example, you can see that they have static content surrounding dynamic content using pre-existing templating mechanisms.  I updated my example to include another dynamic scenario:

    <custom-element>
      
      <span data-bind="text: item"></span>
      
    </custom-element>

But take this example to have both static and dynamic like the angular example:

    <custom-element>
      <span>foo</span>
      
      <span data-bind="text: item"></span>
      
      <span>bar</span>
    </custom-element>

How is one to use a scenario like this?

**Comment by frankabbruzzese** [comment]
It should work as it is. custom-element content is used just as a template so it is processed by knockout.js binding engine. This means that also dynamic content should work, for the same reason nested foreach works.

**Comment by kaleb** [comment]
@frankabbruzzese take a look at my second example with the foreach inside. This errs. I added a sub-component branch to that gist to demonstrate.

**Comment by kaleb** [comment]
@frankabbruzzese by the way, I appreciate you taking your time to respond.

**Comment by kaleb** [comment]
I have found an acceptable solution. Thanks again, @frankabbruzzese

**Comment by frankabbruzzese** [comment]
In fact, your previuos attempts were wrong!
