### ISSUE TITLE
Question: composable components

### ISSUE THREAD

**Issue by akuz** [knockout/knockout#1768]
I would like to build a custom component called `<side-menu-view>`, which would contain two panels inside it, menu and content, and which could contain arbitrary elements (defined when the menu is used). The side-menu-view component would provide the necessary functionality of showing and hiding the side menu, that's it. Here are the examples of how it could be used:

    <side-menu-view>
    
      <menu>
        <h1>Menu</h1>
        <ul>
          
        </ul>
      </menu>
    
      <content>
        <h1>Content</h1>
        <p>Some text here</p>
      </content>
    
    </side-menu-view>

I've asked the question on StackOverflow and the best solution I got is to define the custom components for the menu and content again, and then bind them within the side-menu-view. But that's not good, because I would have to define custom components for anything I want to put into the view...

I also looked at the $componentTemplateNodes, but I don't feel like that would also be an easy way out...

Any better suggestions would be appreciated.

**Comment by sumitkm** [comment]
HI me again :-) couldn't help a bit of self plug here, does this help? https://sumitmaitra.wordpress.com/2014/12/24/part-7-sharing-data-in-knockout-components-12-building-a-tree-component/

**Comment by akuz** [comment]
Hi Sumit, thanks a lot, that's very impressive! However, I think it doesn't really solve the problem I described. Your tree component would just take data tree as an input and render it. But what I want to do is to be able to give my side-menu-view component other components, which it should render in the menu and content sections. However, what's going to be in menu and content area cannot be predefined (like you have a tree node predefined). I guess an analogy with your code would be: if you try to build a tree component, but let the user specify how to render the node. For example such tree could be used as:

    <magic-tree>
      <node-template>
        NODE!
      </node-template>
    </magic-tree>

This would be easy to solve with $componentTemplateNodes, because there is only one child node. Bt imagine you want users to customise the title and body of each node. Then you would have to do something like this:

    <magic-tree>
      <node-title>
        NODE!
      </node-title>
      <node-body>
        BODY!
      </node-body>
    </magic-tree>

I should be able to put anything within the inner tags, and HTML or other Knockout components...

**Comment by sumitkm** [comment]
You could bind component by name. So if you have a ViewModel that has the name of the component you want rendered (node/body/body-1/body-n), then you can data bind it on the fly. http://knockoutjs.com/documentation/component-binding.html or self plug again https://sumitmaitra.wordpress.com/2014/09/25/part-6-custom-componentstabs/. Check how I am binding tabpanel based on which tab is selected. 

That said I haven't use $componentTemplateNodes directly so not sure if that's an easier/cleaner approach.

**Comment by frankabbruzzese** [comment]
Markup contained in the component call is not only available in $componentTemplateNodes, but it is also passed to the  [createViewModel function](http://knockoutjs.com/documentation/component-registration.html#a-createviewmodel-factory-function), in the componentInfo.templateNodes parameter.
When you receive your nodes there you may process them to extract both menu and content, so you can put them in two different ViewModel observables. Then you can bind them to your component markup with the help of the template binding as shown in this example:
http://knockoutjs.com/documentation/component-custom-elements.html#passing-markup-into-components

**Comment by akuz** [comment]
Hi Francesco, I guess that would work with simple html, but what if I put another Knockout components within the subparts like so?

    <side-menu-view>

      <menu>
        <nice-menu-component></nice-menu-component>
      </menu>

      <content>
        <fancy-content-displayer></fancy-content-displayer>
      </content>

    </side-menu-view>

**Comment by frankabbruzzese** [comment]
No It should work anyway, since once nodes are used by a template binding they are processed by knockout.js for bindings, so components contained inside them are discovered and processed properly.

**Comment by akuz** [comment]
That sounds too good to be true, but if it works that would be awesome! Let me try and share something in one of these example sharing thingies...

**Comment by akuz** [comment]
So far, I can't even get createView called...
http://jsfiddle.net/or280298/2/

**Comment by frankabbruzzese** [comment]
Your syntax is wrong. With the right syntaxt below, it works:
```javascript
ko.components.register('menu-view', {
    viewModel:
    {
            createViewModel: function(params) {
                alert(1);
            }
    },
    template: { element: 'menu-view-template' }
});
```

**Comment by akuz** [comment]
It does work! http://jsfiddle.net/or280298/7/  Quite amazing, thank you!
Not sure about data binding to the `custom-menu` yet, I need to read more...
