### ISSUE TITLE
Random weird generated code after upgrading to 3.30

### ISSUE THREAD

**Issue by cablepuff** [knockout/knockout#1769]
Hi i am getting this weird code after upgrading to 3.30 from 3.20

unction d(){if(0<arguments.length)return d.Wa(c,arguments[0])&&(d.X(),c=arguments[0],d.W()),this;a.k.Ob(d);return c}

on my ui i have 

<div id="myDiv">
<span data-bind="text: $data.name" id="mySpan"/>
</div>

my model is like this

function MyViewModel() {
     var self = this;
     self.name = ko.observable("");
}

var myModel
head.load(
                "/js/knockout-min.js",
                "/js/forwardModel-min.js", 
                    function() {
                        "use strict";
                        var myDiv = document.getElementById("myDiv");
                        if (myDiv) {
                             myModel = new MyViewModel();
                             ko.applyBindings(myModel, myDiv);
                        }
                    }
                );

If i happen to include using regular javascript include and than call the function using anonymous self executing function, than it works. 

When i debug the instance the value of name is "012 - ABC" using myViewModel.name()

** This used to work with 3.2.0 version.

**Comment by cablepuff** [comment]
For your information this only happens with chrome.

**Comment by Rakesh-gene** [comment]
I think this should work,
function MyViewModel() {
var self = this;
self.name= ko.observable("");
}

**Comment by cablepuff** [comment]
Tried it, still the same problem. 

Actually i found out the problem is integerating with 1.0.2 version of head.js library.

**Comment by SteveSanderson** [comment]
Closing since you say it's an issue with head.js, but please reopen if I'm misinterpreting!
