### ISSUE TITLE
Breaking change in behavior for subscribe

### ISSUE THREAD

**Issue by CraigCav** [knockout/knockout#1770]
A project i'm working on makes pretty extensive use of computed observables with the `deferEvaluation: true` option in order to avoid costly operations unless/until the computed observable is actually read.

In Version 3.0.0, one could observe the following behavior:

``` js
// in Version 3.0.0:

var comp = ko.computed({ 
  read: function() { 
    console.log('running expensive operation'); 
    return true; 
  },
  deferEvaluation: true
});

// the following line does NOT trigger `comp.read`
comp.subscribe(function(val) { 
  console.log('my value has changed'); 
});

// now read the computed observable
comp();

// output
> running expensive operation
> my value has changed
> true
```

This meant that the expensive operation isn't triggered until the deferred computed observable was actually read, after which the manual subscription is called (and logs to the console that the value has changed). 

Since Version 3.1.0 (potentially due to PR #1272), the following behavior can be observed:

``` js
// in Version 3.1.0:

var comp = ko.computed({ 
  read: function() { 
    console.log('running expensive operation'); 
    return true; 
  },
  deferEvaluation: true
});

// the following line does now triggers `comp.read`
comp.subscribe(function(val) { 
  console.log('my value has changed'); 
});

// output
running expensive operation

// now read the computed observable
comp();

// output
> true
```

Unfortunately this means that the expensive operation is always being triggered (via the subscribe), where previously the expensive operation was deferred until a consumer read from the deferred computed observable.

Another side effect is that in the Version 3.1.0 example, the `console.log` from the subscribe block is not called for the first evaluation of the expensive operation.

Is there a way (subsequent to Version 3.1.0) that I can set up a subscription to be notified ONLY if/when the value of `comp` is evaluated? I want to be able to keep the evaluation of the expensive operation deferred until the very last moment (i.e. when the `comp` observable is read).

**Comment by mbest** [comment]
I think that the difficulty of the change in #1272 is that `deferEvaluation` was meant to solve a different problem--to be able to initialize a view model automatically (like with knockout.mapping) without concern for the order of computed observables.

For a possible solution, take a look at #1735, and let us know what you think.

**Comment by SteveSanderson** [comment]
It is unfortunate that we had this breaking change between 3.0.0 and 3.1.0 without recognising it at the time - sorry about that!

As for the best thing to do now, @mbest would you agree that we'd want to keep the current 3.1.0+ behaviour? Given that 3.1.0 and newer versions of KO have been out in the wild for a long time, it's not like we could revert to the 3.0.0 behaviour without that being another breaking change for even more people.

@CraigCav, I'm not sure what would be the easiest way for you to get back the behaviour you want. Does @mbest's suggestion help?

**Comment by CraigCav** [comment]
First of all, thank you very much for the quick replies! 

If i'm following the chain of PRs correctly, it sounds like the #1735 could be used to solve this problem like this:

```js
comp.subscribe(function(val) { 
  console.log('my value has changed'); 
}, null, 'cache');
```

The subscription now wouldn't cause the expensive operation to fire (since a pure computed only wakes when a `change` subscription is registered), and the subscribe callback would be called once the `comp` observable is read/peeked/unwrapped and whenever the value of `comp` changes.

It seems like a pretty simple means to achieve similar behavior to the pre 3.1.0 version, so  it gets my :+1: 

It also looks like the changes made in @mbest made as part of #1576 could also be used to work around my problem (although not quite as succinctly):

```js
// in Version 3.1.0:

var comp = ko.computed({ 
  read: function() { 
    console.log('running expensive operation'); 
    return true; 
  },
  deferEvaluation: true
});

function log(val) {
}

// the following line does NOT trigger `comp.read`
comp.subscribe(function(val) { 
  // log once when the observable "wakes"
  log(val);
  // now the observable is awake, log any subsequent change event
  // the subscribe won't trigger the expensive operation to be evaluated
  // as `comp` is already awake and the value is cached
  comp.subscribe(log);
}, null, 'awake');

// now read the computed observable
comp();

// output
> running expensive operation
> my value has changed
> true
```

**Comment by NeuwirthD** [comment]
Is there another workaround or a compatibility option planned for the next version? We use defered computed observable in our extender for lazy loading which we use a lot and we also subscribe to them quite a lot which causes them to load early.

Now we use version 3.0.0 but we would like to update to 3.3.0.

**Comment by mbest** [comment]
I believe the "spectate" event that can be used based on https://github.com/knockout/knockout/pull/1511#issuecomment-56913452 is a good workaround.
