### ISSUE TITLE
The "visible" binding has an issue.

### ISSUE THREAD

**Issue by linder0209** [knockout/knockout#1771]
When I use the  "visible" binding with the "$index" in foreach,
the ko computed has a wrong to do not show the message. Please see the following example:

&lt;h4&gt;People&lt;/h4&gt;
        &lt;ol data-bind="foreach: people"&gt;
            &lt;li&gt;
                Name at position &lt;span data-bind="text: $index"&gt;&lt;/span&gt;:
                &lt;span data-bind="text: name"&gt;&lt;/span&gt;
                &lt;a href="#" data-bind="click: $parent.removePerson"&gt;Remove&lt;/a&gt;
                &lt;span data-bind="visible: $index == 0"&gt;first&lt;/span&gt;
                &lt;span data-bind="visible: $parent.people().length-1 == $index"&gt;last&lt;/span&gt;
            &lt;/li&gt;
        &lt;/ol&gt;

        <script type="text/javascript">

            function AppViewModel() {
                var self = this;

                self.people = ko.observableArray([
                    {name: 'Bert'},
                    {name: 'Charles'},
                    {name: 'Denise'}
                ]);

            }

            ko.applyBindings(new AppViewModel());

       </script>

The above example "first" and "last" don't display as expected effect.
In addition, hope to provide $last $first ect. binding context.
Thanks.

**Comment by mbest** [comment]
`$index` is an observable, so you must use it like `visible: $index() == 0`.

**Comment by linder0209** [comment]
Thank you very much.



王彦军
 
From: Michael Best
Date: 2015-04-15 16:38
To: knockout/knockout
CC: linder0209
Subject: Re: [knockout] The "visible" binding has an issue. (#1771)
$index is an observable, so you must use it like visible: $index() == 0.
