### ISSUE TITLE
simpleHtmlParse() fails to parse components having names beginning with thead, tbody, tfoot, tr, th and td

### ISSUE THREAD

**Issue by birkestroem** [knockout/knockout#1772]
If your custom component is named ```<traffic-map></traffic-map>```, it will generate invalid HTML that gets discarded by innerHTML.

This is also the case for other nested table elements.

**Comment by birkestroem** [comment]
Fix and tests suggested in #1773

**Comment by brianmhunt** [comment]
While we are here, is it worth noting that [`<div>` and other non-inline tags are hoisted out of `<p>`](http://stackoverflow.com/q/8397852/19212) tags? Is this a place where we can or would want to fix this?

**Comment by brianmhunt** [comment]
This ought to be fixed in the PR for #1880 ; I'm closing this just to clean it up – on the basis that it's being worked on and covered by those.  But @birkestroem please comment if you feel there's a reason to keep this issue open!  Thanks!
