### ISSUE TITLE
How to dispose a computed inside a component (potential memory leak?)

### ISSUE THREAD

**Issue by sateffen** [knockout/knockout#1777]
Hey guys,

I didn't find anything like this, so I hope this is nothing duplicated.

When defining a computed inside a component, and the component gets cleaned, the computed has no chance of getting cleaned as well, in a nice way.

In custom bindings, I can use the `disposedWhenNodeIsRemoved` for computeds, but in the component I don't have a reference or something. This fiddle makes it clear:

https://jsfiddle.net/aav4hp3d/2/

Here the computed in the binding gets cleaned up, when the binding is cleaned up, but the computed inside of the component never gets cleaned up (because I simply don't know how do to is cleanly. I could create a custom way by using a binding inside the component that has disposal logic that disposes all elements in given array, but that's not a good way).

Is there something I'm missing?

**Comment by mbest** [comment]
Take a look at this part of the docs: http://knockoutjs.com/documentation/component-binding.html#disposal-and-memory-management
