### ISSUE TITLE
IE 11 - Binding: Hasfocus Should not unnecessarily focus or blur an element that is already focused/blurred

### ISSUE THREAD

**Issue by brianmhunt** [knockout/knockout#1780]
The above-noted test fails on IE 11.0.0 (Windows 8.1) (at least in the #1360 branch).

**Comment by TK182** [comment]
It seems to be passing in the current build of IE 11 on Windows 10. Is it still an issue?

**Comment by brianmhunt** [comment]
Thanks @TK182; I will close this but we can re-open if it regresses.
