### ISSUE TITLE
Fixed: IE8/IE9 cannot use `<template id="my-template">` instead of `<script id="my-template">`

### ISSUE THREAD

**Issue by franktopel** [knockout/knockout#1783]
Wrapping templates in `<template>`-tags instead of `<script type="text/html">`-tags does not work in Internet Explorer 8 and 9.

Supporting IE 8 and 9 in your knockout project forces you to use `<script>`-tags to wrap your templates. Using `<template>`-tags leads to these templates being evaluated at page load rather than when the template is being instantiated at run-time - which ofc leads to the bindings within the template failing because in most cases there will not yet be data/the objects being used available.

**Comment by mbest** [comment]
Implementation note: This should be as simple as adding `<template>` to the list of elements to skip while binding, in addition to `<script>` and `<textarea>`.

**Comment by franktopel** [comment]
I've tested your suggestion and it looks like that's all that must be done.

I've forked `bindingAttributeSyntax.js` and implemented your suggested fix in the fork:

https://github.com/knockout/knockout/blob/32628d0d8ce1089555eccfcfdacb8fc860edcbf2/src/binding/bindingAttributeSyntax.js

**Comment by franktopel** [comment]
I've added a pull request for the fix: https://github.com/knockout/knockout/pull/1785/files

**Comment by mbest** [comment]
Fixed.
