### ISSUE TITLE
$component context lost within foreach binding

### ISSUE THREAD

**Issue by davetropeano** [knockout/knockout#1787]
Fiddle demonstrating issue: http://jsfiddle.net/davetropeano/58vm9r6g/

The value of $component (and $parent) do not seem to be correct within a foreach binding inside a component. 

template:
```
<template id="kv-list">
    <input type="text" placeholder="key" data-bind="textInput: k">
    <input type="text" placeholder="value" data-bind="textInput: v">
    <button data-bind="click: add">Add</button><br>
        
    <table>
        <thead>
            <tr>
                <th data-bind="text: keyHeading"></th>
                <th data-bind="text: valueHeading"></th>
                <th></th>
            </tr>
        </thead>
        <tbody  data-bind="foreach: items">
            <tr>
                <td data-bind="text: k"></td>
                <td data-bind="text: v"></td>
                <td><a href="#" data-bind="click: $component.delete">delete</a></td>
            </tr>
        </tbody>
    </table>
</template>
```

js:
```
function KVPairList(params) {
    this.items = params.items;
    this.keyHeading = params.keyHeading || 'Key';
    this.valueHeading = params.valueHeading || 'Value';
    this.k = ko.observable();
    this.v = ko.observable();   
}

KVPairList.prototype.add = function () {
    this.items.push(new KV(this.k(), this.v()));
};


KVPairList.prototype.delete = function (item) {
    this.items.remove(item);
};
```

The scope of ```$component``` should be the ```KVPairList``` viewmodel. In the example it stays scoped to the item itself.

**Comment by rniemeyer** [comment]
@davetropeano - Hello - it looks like you are running into an issue with the value of `this`. When you bind click against `$component.delete`, you are passing just a reference to the function. When Knockout calls it, it no longer knows that it came from `$component` and uses the current `$data` as the value of `this`.

There are several ways to handle this:

- you can bind it in the binding like `click: $component.delete.bind($component)`
- you can bind it in your view model (in your case, you could either define it in the constructor or bind it in the constructor like `this.delete = this.delete.bind(this);` which would ensure that each instance had a bound version of the prototype function). 
- you could also use [knockout.punches](http://mbest.github.io/knockout.punches/) which can handle this binding for you automatically (and has a ton of other great features) or if you had a lot of nested event handlers you could use my [delegated events](https://github.com/rniemeyer/knockout-delegatedEvents) binding that would also handle it.

Here is an updated fiddle with it bound: http://jsfiddle.net/rniemeyer/9qd1f30d/
