### ISSUE TITLE
Unable to change delegated property by child component (ES5).

### ISSUE THREAD

**Issue by sugatov** [knockout/knockout#1789]
It is impossible to change delegated property by child component. Is this is supposed behavior?
Im using `knockout-es5` and I have the following structure:
```html
<datagrid params="items: categories, columns: columns, page: 1, pageCount: 10, onPageChange: console.log"></datagrid>
```

datagrid:
```html
<gridview params="items: items, columns: columns"></gridview>
<paginator params="page: page, count: pageCount, onChange: onPageChange"></paginator>
```

gridview:
```html
<table class="ui table">
    <thead>
        <tr data-bind="foreach: columns">
            <th data-bind="text: $data.displayName"></th>
        </tr>
    </thead>
    <tbody data-bind="foreach: {data: items, as: 'item'}">
        <tr data-bind="foreach: {data: $parent.columns, as: 'column'}">
            <td data-bind="text: item[column.name]">
            </td>
        </tr>
    </tbody>
</table>
```

paginator:
```html
<div class="ui menu">
  <div class="item">
    <div class="ui labeled icon button" data-bind="click: backward">
      <i class="left chevron icon"></i>
      туда
    </div>
  <div class="item">
    <div class="ui transparent input">
      <input placeholder="страница" type="text" data-bind="textInput: page">
      <div class="ui label" data-bind="text: '/ ' + count"></div>
    </div>
  </div>
  <div class="item">
    <div class="ui right labeled icon button" data-bind="click: forward">
      сюда
      <i class="right chevron icon"></i>
    </div>
  </div>
  </div>
</div>
```

`paginator` component has an event listener for 'page' attribute changes, but component cannot change that property by model methods and cannot trigger this event. But if this property has been changed from a `datagrid` component, this property change will be mirrored in view and event will trigger.
Is there any workaround for this?
Thank you!

**Comment by theredhead** [comment]
I'm having the same problem where a dropdown cannot delegate its selected value back to the main viewmodel with a message: [Error] Error: Cannot write a value to a ko.computed unless you specify a 'write' option. If you wish to read the current value, don't pass any parameters.
	(anonymous function) (knockout-3.3.0.js, line 83)
	dispatch (jquery.min.js, line 3)
	handle (jquery.min.js, line 3)

unfortunately, the ko.computed referred to isn't a ko.computed at all, but an ES5 property:

Typescript ViewModel:

        enum Backend {
            Sqlite,
            MySql,
            MSSqlServer,
            Oracle
        }
        class MyViewModel {
            public backend:Backend = Backend.MySql; // this is the property.
            
            constructor() {
                ko.track(this);
            }
        }

In the html view:

        <dropdown params="value: backend, options:[{value:Backend.Sqlite, label:'Sqlite'}, {value:Backend.MySql, label:'MySql'}]"></dropdown>
        <div>
            <span type="text" data-bind="text: backend" ></span>
        </div>

The component:

        DropdownViewModel = function(params) {
            this.value = params.value; // an observable ES5 property
            this.options = params.options || ko.observableArray([]);
            this.selectedOption = ko.observable({ value: -1, label: 'Choose…' }); // some initial default
            
            this.selectOption = function (opt) {
                this.selectedOption(opt);
                this.value(opt.value); // doesn't work
            }.bind(this);
            
            return this;
        };
        
        ko.components.register('dropdown', {
            viewModel: DropdownViewModel, 
            template: '\
        <div class="btn-group">\
            <span class="btn btn-default" data-bind="text: selectedOption().label"></span>\
            <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">\
                <span class="caret"></span>\
            </button>\
            <ul class="dropdown-menu" data-bind="foreach: options">\
                <li><a class="clickable" data-bind="click: $parent.selectOption, text: label"></a></li>\
            </ul>\
        </div>'
        });

**Comment by sugatov** [comment]
Im solved this using  `ko.track(this, ['someProperty'` with properties that should be tracked. The problem was because delegated property became a dependentObservable. Once property became tracked it should not became it again, otherwise it became dependentObservable and it's value cannot be rewritten. Try this.

**Comment by theredhead** [comment]
That does not seem to make any difference. the error is the same:

        [Error] Error: Cannot write a value to a ko.computed unless you specify a 'write' option. If you wish to read the current value, don't pass any parameters.
	(anonymous function) (knockout-3.3.0.js, line 83)
	dispatch (jquery.min.js, line 3)
	handle (jquery.min.js, line 3)

**Comment by sugatov** [comment]
Seems like this is an error `this.value(opt.value); // doesn't work`, obviously. You should write this like
`this.value = opt.value;` because it is not a ko.observable, it's ES5 property. But im think this also would not work, because something is not right with this variable.

**Comment by IanYates** [comment]
When using the ES5 plugin you really need to consciously consider what Knockout is able to see.  When binding your component, KO runs your binding expression through eval().  All it's going to see is the `value` of your observable (the result of the property getter that KO-ES5 creates).  It won't actually know it's observable.
So your component is just getting a value, which is wrapped up in a computed for convenience / consistency by KO.
You want the underlying observable to find its way through to the component, so you need to call `ko.getObservable($data, 'backend')` to get the observable behind the property.  Give that a try :)
