### ISSUE TITLE
Allow Attribute Binding to Handle Title Carriage Returns

### ISSUE THREAD

**Issue by someyoungideas** [knockout/knockout#1793]
It is possible to use Ascii Table carriage returns in the title attribute of an element.

http://stackoverflow.com/questions/358874/how-can-i-use-a-carriage-return-in-a-html-tooltip

When using an `attr: { 'title': theBinding }` binding for a title attribute in knockout and the binding has a carriage return it shows it as a string. Would it be possible to allow this to work as an expected carriage return?

**Comment by mbest** [comment]
Can you provide a complete example?

**Comment by someyoungideas** [comment]
Here is a [jsfiddle](http://jsfiddle.net/someyoungideas/v8wqfkeg/) example

**Comment by mbest** [comment]
Thanks for the example. As you say, it won't work to use Html entities within the string in JavaScript. You need to use JavaScript escaping. So instead of `'First String&#13;Second String'`, you'll use `'First String\nSecond String'`. http://jsfiddle.net/mbest/v8wqfkeg/2/

**Comment by someyoungideas** [comment]
Wonderful! Thanks!
