### ISSUE TITLE
If an afteradd fails then the element is reappended

### ISSUE THREAD

**Issue by giacmir** [knockout/knockout#1794]
[This stackoverflow question](http://stackoverflow.com/questions/30236830) reveals a bug in the way that the afterAdd works.

The asking person tried to use the code provided in the [foreach documentation page](http://knockoutjs.com/documentation/foreach-binding.html) and the code was failing in a strange way because the code assumed the use of jquery.

The example had a list of item and a button that adds an item to the list providing a highlight effect to the added element. 

Without jquery the new element is added, but the afteradd function fails because $ is undefined.
If the user clicks again the button then two elements are appended, three for the next click and so on.

see the [Fiddle](http://jsfiddle.net/shubhambhave/jkrxv8e8/) provided in question.

**Comment by brianmhunt** [comment]
Great report, thanks @giacmir!

**Comment by mbest** [comment]
Thanks. This is fixed now.
