### ISSUE TITLE
problem with amdclean

### ISSUE THREAD

**Issue by tadjik1** [knockout/knockout#1797]
Hello there. We have a huge problems when using amdclean. This is the related issue:
https://github.com/gfranko/amdclean/issues/74

Why are you using a "non-standart" UMD definition?

**Comment by mbest** [comment]
The problem would appear to be with AMDclean. It's perfectly valid AMD to attach properties to `exports` and not return anything.

Reference: https://github.com/amdjs/amdjs-api/blob/master/AMD.md#using-require-and-exports
