### ISSUE TITLE
Typescript definition file for Knockout version 3.3

### ISSUE THREAD

**Issue by Eisenspalter** [knockout/knockout#1799]
Does exist a typescript definition file for Knockout Version 3.3? I can only find one for Version 3.2.

**Comment by ThomasMichon** [comment]
There seems to be an outstanding work item to make one, if someone wants to take the time.

note borisyankov/DefinitelyTyped#4288

**Comment by IanYates** [comment]
I've been keeping my type definition file reasonably up to date with the KO changes.  I'll see if I can do something about creating a PR for it this weekend.

**Comment by chinaniit** [comment]
I'm compare source code, and update d.ts.
https://github.com/chinaniit/knockout-3.3.0.d.ts/blob/master/knockout.d.ts
