### ISSUE TITLE
Add support for formatted observables

### ISSUE THREAD

**Issue by rosenfeld** [knockout/knockout#180]
Suppose a boolean observable:

    viewModel.myBoolean = ko.observable(false)

I want myBoolean() to return false, but want data-bind="text: myBoolean" to use "No" instead.

Not sure what would be the best way to design this API, but here are some alternatives:

    ko.observable(false).extend(myBooleanFormatter)

myBooleanFormattter could introduce a new "formatted" function to do the job. The convention in the views would be to call any formatted() method on the observable if the method exists, instead of calling toString() in the value of the observable.

For simplifying this, an option could be:

    ko.observable(false).formatter(myBooleanFormatter)

where myBooleanFormatter would get the raw value and return a string representation.

This would allow me to have clean views using data-bind="text: myBoolean" instead of data-bind="text: myBoolean().formatted()".

Does it make sense?

**Comment by SteveSanderson** [comment]
I'm tidying up old issues and think this one can be closed, because these days it can be done pretty cleanly with techniques like knockout-punches. If anyone still thinks we should make changes here, please let us know!
