### ISSUE TITLE
mapData.dependentObservable.dispose is not defined

### ISSUE THREAD

**Issue by LuoPQ** [knockout/knockout#1800]
a observableArray bind a div and select ,when change the array, get error mapData.dependentObservable.dispose is not defined

    for (var i = 0, editScriptItem, movedIndex; editScriptItem = editScript[i]; i++) {
        movedIndex = editScriptItem['moved'];
        switch (editScriptItem['status']) {
            case "deleted":
                if (movedIndex === undefined) {
                    mapData = lastMappingResult[lastMappingResultIndex];

                    // Stop tracking changes to the mapping for these nodes
                    if (mapData.dependentObservable)
                        mapData.dependentObservable.dispose();

                    // Queue these nodes for later removal
                    nodesToDelete.push.apply(nodesToDelete, ko.utils.fixUpContinuousNodeArray(mapData.mappedNodes, domNode));
                    if (options['beforeRemove']) {
                        itemsForBeforeRemoveCallbacks[i] = mapData;
                        itemsToProcess.push(mapData);
                    }
                }
                lastMappingResultIndex++;
                break;

            case "retained":
                itemMovedOrRetained(i, lastMappingResultIndex++);
                break;

            case "added":
                if (movedIndex !== undefined) {
                    itemMovedOrRetained(i, movedIndex);
                } else {
                    mapData = { arrayEntry: editScriptItem['value'], indexObservable: ko.observable(newMappingResultIndex++) };
                    newMappingResult.push(mapData);
                    itemsToProcess.push(mapData);
                    if (!isFirstExecution)
                        itemsForAfterAddCallbacks[i] = mapData;
                }
                break;
        }
    }

**Comment by mbest** [comment]
Can you provide an example to reproduce this (in jsFiddle, for example)?
