### ISSUE TITLE
Check for CommonJS 'require' not needed in UMD wrapper

### ISSUE THREAD

**Issue by jgoz** [knockout/knockout#1810]
The current UMD wrapper checks that all of `require`, `module`, and `exports` have been defined in order to export knockout as a CommonJS module ([relevant line](https://github.com/knockout/knockout/blob/master/build/fragments/amd-pre.js#L6)).

This causes a problem with some module bundlers (such as webpack) because `require` may not be defined as a function if a module has no dependencies, as is the case with knockout. If `require` is not defined, knockout's UMD logic will fall through to the 'global' export method rather than CommonJS.

Since `require` is not actually used by knockout (again, no dependencies) it is unnecessary to check for its existence; `module` and `exports` should be sufficient to detect CommonJS.

**Comment by brianmhunt** [comment]
I am under the impression that we would be going for [`returnExportsGlobal`](https://github.com/umdjs/umd/blob/master/returnExportsGlobal.js) style wrapper. Or are we aiming for (is there a reason to aim for) something more [lodashy](https://github.com/lodash/lodash/blob/master/lodash.src.js#L12476)?

Incidentally, as @jgoz points out, it's okay to not check `require`; the jQuery library only checks `module` and `exports`.

**Comment by jgoz** [comment]
@brianmhunt 

> I am under the impression that we would be going for returnExportsGlobal style wrapper. Or are we aiming for (is there a reason to aim for) something more lodashy?

I'm not familiar with all of knockout's supported execution environments, but I would think the ['simplified' `returnExports`](https://github.com/umdjs/umd/blob/master/returnExports.js#L41-60) would be a closer match to what you have now, while still resolving this issue.

**Comment by brianmhunt** [comment]
@jgoz Right you are. Thank you.

**Comment by Oyamasiphula** [comment]
I'm using node I always encounter an error  message which goes like object #bject is undefined isn't there a better way to read csv files using Fs mode. How to easily use other functions reasults insteead of methods? #looking for some good mentos as I'm learning JS and I anticipated to its fundamentals and concepts . You can check out codeX-academy repo
