### ISSUE TITLE
visible binding should use unwrap to unwrap the binding value

### ISSUE THREAD

**Issue by swiperthefox** [knockout/knockout#1812]
I am trying to create a custom binding, and want to hide the element under some conditions. So in the custom binding's update function, I use

    ...
    ko.bindinghandlers.visible.update(element, a_boolean_value)

to show or hide the element.

But this doesn't work, because in visible's update function, the binding value is assumed to be an observable:

    var value = ko.utils.unwrapObservable(valueAccessor());

So I suggest that visible should use ko.unwrap instead for more flexibility.

Thanks.

**Comment by rniemeyer** [comment]
`ko.unwrap` is an alias for `ko.utils.unwrapObservable`, so it is the same functionality. The `init` and `update` functions for a binding expect a valueAccessor (a function that returns the value) as the second argument. So, you would have to wrap your boolean value in a function that returns it, if you wanted to use an existing binding's init/update. Hope that makes sense!

**Comment by swiperthefox** [comment]
Yes, it totally make sense. I was using the same method as you suggested.
Thanks for your prompt and detailed explanation.
