### ISSUE TITLE
about use colspan attr

### ISSUE THREAD

**Issue by Sir0xb** [knockout/knockout#1813]
...data-bind="attr: { colspan: 4 }"...
In IE6 Invalid

**Comment by rniemeyer** [comment]
@Sir0xb - `attr: { colSpan: 4 }` works properly in IE6

**Comment by Jorgelig** [comment]
work?
    attr: { 'colspan': 4}

**Comment by IanYates** [comment]
Ryan has a capital 'S' - try that perhaps?
