### ISSUE TITLE
'arrayChange' subscriptions is not documented

### ISSUE THREAD

**Issue by hasenj** [knockout/knockout#1814]
Steve Sanderson's blog post about the 3.0 release candidates mentions a new feature where you can subscribe to 'arrayChanges', but it's not documented on the Knockout's website/documentation.

Unless your curiosity leads you to Steve's blog, you might not know about this feature.

http://blog.stevensanderson.com/2013/10/08/knockout-3-0-release-candidate-available/

To quote:

> Whenever you have an observableArray, you can now subscribe to its new arrayChange notifications:
> ```
> var myArray = ko.observableArray(["Alpha", "Beta", "Gamma"]);
>  
> myArray.subscribe(function(changes) {
>  
>     // For this example, we'll just print out the change info
>     console.log(changes);
>  
> }, null, "arrayChange");
> ```
> Now if you add/remove/reorder its contents, you’ll be given a concise description of what happened. For example, if you add an item (e.g., changing ['Alpha', 'Beta', 'Gamma'] to ['Alpha', 'Beta', 'Gamma', 'Delta']):
> ```
> myArray.push("Delta");
> // Console output: [{ index: 3, status: 'added', value: 'Delta' }]
> ```

**Comment by brianmhunt** [comment]
Thanks @hasenj – agreed that this should be documented better.

Cheers

**Comment by brianmhunt** [comment]
This should be fixed in #1827 ; closing in lieu of that.

You can check out where we are with the new site at https://brianmhunt.github.io/knockout

**Comment by emimull** [comment]
Hi. I'm looking for documentation on this. Can't find it as of August 2016. Also, urls mentioned in previous post does not exist.
