### ISSUE TITLE
Applying KO bindings to resulting view of html binding

### ISSUE THREAD

**Issue by codingtwinky** [knockout/knockout#1816]
It would be nice to apply current vm's data binding to resulting view of html binding.  My use cases is something similar to below example code.

```
viewModel = {
  htmlSrc: "<span data-bind='text: value'></span>'
  value: ko.observable("init");
}

....

<div data-bind="html: htmlSrc"> </div>
```

Workaround
----------------
One can achieve this via manually change html content of inner div on htmlSrc change and do below.
```
viewModel = {
  htmlSrc: ko.observable("<span data-bind='text: value'></span>');
  value: ko.observable("init");
}
viewModel.htmlSrc.subscribe(function() {
   $('#test').html(viewModel.htmlSrc());
   ko.cleanNode($element);
   ko.applyBindings(viewModel, $element);
}

....

<div id="test" data-bind=""> </div>
```

**Comment by mbest** [comment]
You can try this:

```html
<div data-bind="template: {nodes: ko.utils.parseHtmlFragment(htmlSrc)}"></div>
```

**Comment by codingtwinky** [comment]
`<div data-bind="template: {nodes: ko.utils.parseHtmlFragment(htmlSrc())}"></div>`

So above does partially what I want.  However, my problem is that it doesn't observe on htmlSrc.  template reparsing doesn't happen when htmlSrc is changed.

**Comment by brianmhunt** [comment]
@codingtwinky consider creating a computed observable like-so:

```javascript
html_content_template = ko.computed(function () {
  return {nodes: ko.utils.parseHtmlFragment(htmlSrc()) }
})
```

then in the HTML

```html
<div data-bind="template: html_content_template"></div>
```

This should recompute when any observable dependencies in `htmlSrc` are updated.

**Comment by mbest** [comment]
@brianmhunt, that won't work either. The `template` binding saves a copy of the nodes in the `init` function, so they can't be updated later.

**Comment by mbest** [comment]
@codingtwinky Perhaps [this custom binding](http://stackoverflow.com/a/17756777/1287183) will work for you.
