### ISSUE TITLE
Custom limit function for ko.subscribable?

### ISSUE THREAD

**Issue by ThomasMichon** [knockout/knockout#1818]
The `rateLimit`, `deferred`, and `throttle` extenders all make use of a `limit` function attached to `ko_subscribale_fn`. However, `limit` itself is not exported, so if anyone wanted to make an extender that used an alternate means of rate-limiting (for example, deferring an update until the next animation frame), it would not be possible to take advantage of the built-in behavior.

I think all that would be required to make this happen would be to add this line:

``` js
ko.exportProperty(ko_subscribable_fn, 'limit', ko_subscribable_fn.limit);
```

I's submit a PR, but I wanted to determine first if there is a reason this functionality is not publicly-consumable.

**Comment by mbest** [comment]
There's always an extra burden when making something a public API. I think the main reason for not making `limit` public was to avoid that burden without knowing there was a need for it.

**Comment by ThomasMichon** [comment]
I'd like to revisit this. The most pressing need I have in my project is to replace the default `rateLimit` extender with one which uses our framework's wrapper for `setTimeout`. Notably, we have a version which is scheduled and disposable, and the fact that observables go directly to `window.setTimeout` is a cause of performance problems in our controls.

Another reason is that without the ability to call `limit`, there is no way to write extenders which, for example, defer the update to a call to `window.requestAnimationFrame` or `setImmediate`. Or to write an extender which waits for an event to complete, such as a transaction or promise.

Unless the issue with `limit` is that invoking the current method requires special and arcane knowledge (I see some code saves the old `limit` function in order to restore or invoke it in some cases), I think exposing it would strongly benefit consumers of the library.

**Comment by brianmhunt** [comment]
@mbest I agree.  Subject to any further comments, I think we can close this.
