### ISSUE TITLE
No easy way to move an element with bindings in the DOM

### ISSUE THREAD

**Issue by nathggns** [knockout/knockout#1821]
I found that when writing a modal I had to move it in the DOM after its bindings had been applied, and there's (as far as I can tell) no way to do this built in the library. You can do it though, so I propose the following method being added.

```js
ko.moveBoundNode = function(node, target) {
    if (node.parentNode === target) {
        return;
    }

    var model = ko.contextFor(node).$root;
    ko.cleanNode(node);
    target.appendChild(node);
    ko.applyBindings(model, node); 
};
```

**Comment by frialex** [comment]
Would it be possible to do something like:


``` javascript
var modalNode = $('<button data-bind="click: openModal">Open modal</button>')[0];
var vm = { openModal: function(){ /* do something */ } };

ko.applyBindings(vm, modalNode)

//Now that KO has taken control of modalNode insert into DOM
$("#container").append(modalNode)

//Everything works as expected so far..

//At a later point in time you decided that you want to remove it and put it somewhere else
$("#container #TheModal").remove()

//It fails here since removing the node from the DOM seems to also clean out the knockout bindings..
//so this might not work for you.. unless you have a function that gives you back a bound node.
$("#somewhereElse").append(modalNode)


````

**Comment by nathggns** [comment]
No because I'm using a library that uses knockout, i'm not binding my viewmodels manually. 

I basically wrote my own wrapper that does what my example showed, but i had to work for quite a while to figure out how to do it. I think that it should be built in.

**Comment by brianmhunt** [comment]
Unless I misunderstand (and I very well may :wink:) this depends on #910 / #1455 (linking for reference)

**Comment by mbest** [comment]
What happens if you move a node after bindings are applied?

**Comment by acasaccia** [comment]
I think all you need to do in this case is to select your DOM element with jQuery and append it where you need, **without** removing it before. Default jQuery behaviour is to move it if it's already in the DOM. This way all bindings should be preserved.

**Comment by 0liver** [comment]
Thanks @acasaccia! You're perfectly right.

In my case I simply replaced:

    $element.replaceWith(placeholder);
    $body.append($element);

... with:

    $element.after(placeholder);
    $body.append($element);

... and now the KO bindings stay intact!

Thanks for posting your idea here, it's saved me a lot of time and headache :-)

**Comment by acasaccia** [comment]
@0liver good, glad it helped. Additionally, this doesn't really need jQuery, it can be done simply with `Node.appendChild()` or `Node.insertBefore()`. See a test here: http://jsfiddle.net/acasaccia/tdsp1zph/
I suppose this means *there is* a way to move an element with bindings in the DOM?

**Comment by 0liver** [comment]
Yes, there definitely *is* a way to move elements in the DOM with applied bindings.

It's like you said in your comment above: one simply *must not remove* the elements from the DOM, then all attached handlers will stay intact, incl. all knockout bindings.

I would vote to close this issue.
