### ISSUE TITLE
Maximum call stack size exceeded with nested $componentTemplateNodes

### ISSUE THREAD

**Issue by resident-uhlig** [knockout/knockout#1824]
I don't know if this is a bug, a missing feature or if I use the components feature wrong.

There are two nested components, both use $componentTemplateNodes
http://jsfiddle.net/0L8L0g3x/1/

Result: An infinite loop halting with the error "Maximum call stack size exceeded". The inner markup is repeated indefinitely (until the error occurs) and the outer markup is not used at all.

Expected: The inner component uses the markup provided from the outer component and the outer component uses the markup provided in the document root.

So the complete markup (without knockout markup) should look like this:
```html
<div>
<p>You failed.</p>
<button type="button">Ok</button>
</div>
```

Knockout 3.3.0
Chrome 43

**Comment by mbest** [comment]
When using `$componentTemplateNodes`, the nodes are provided to the component before binding and are then bound in the context of the inner template. There is a way to make this work, even if it might not be intuitive:

    <jquery-ui-dialog>
        
	    <button type="button">Ok</button>
    <jquery-ui-dialog>

http://jsfiddle.net/mbest/0L8L0g3x/2/

**Comment by resident-uhlig** [comment]
Thank you, $parentContext works. I only had tried $parent.componentTemplateNodes before but this is wrong obviously.

However it is really not intuitive. I think this implementation requires <error-dialog> to know about the internals of <jquery-ui-dialog> too much.
