### ISSUE TITLE
Knockout component template depend on viewModel

### ISSUE THREAD

**Issue by hoquangthaiholy** [knockout/knockout#1829]
I have a problem, but i coun't find the way to solve with knockout component.

I want to write a form-control component, I using AMD to register component on demand

```javascript
define(['knockout'],function(ko){
    var template = '<div></div>';
    function Control(params){
        this.editor = params.editor;
    };
    
    Control.prototype.dispose = function() { };
    
    return { viewModel: Control, template: template};
});
```

Please help me, I want to use ajax call to load template depend on editor from viewModel, I think that could be load from template DOM ID element, but that's not a good solution in this case.

**Comment by mbest** [comment]
Since this is a support question, please try asking on [StackOverflow](http://stackoverflow.com/questions/tagged/knockout.js) or [Google Groups](https://groups.google.com/forum/#!forum/knockoutjs) instead.
