### ISSUE TITLE
Unable to properly escape script tags in knockout templates

### ISSUE THREAD

**Issue by Dmitri-Sintsov** [knockout/knockout#1837]
I have knockout template foreach binding for Django inline formsets. These formsets may have custom form field widgets that include javascript code in script tags. These scripts are executed too early from the html template source when page is loaded instead of executing during knockout foreach afterRender. I was googling for the solution but only found unresolved angularjs issue:

https://github.com/angular/angular.js/issues/2820

How can I escape the content of knockout script template so it will not be executed during page load? For example I can encode html entities at server-side, then decode it via jQuery:

	App.htmlEncode = function(value) {
		return $('<div/>').text(value).html();
	};

	App.htmlDecode = function(value) {
		return $('<div/>').html(value).text();
	};

Do I need to write custom binding provider to do that? Can an expert explain please?

**Comment by Dmitri-Sintsov** [comment]
I tried to wrap knockout.js template into template tag instead of script tag. It worked in Chrome, but now the serverside-generated script inside the template is not executed at all. And I thought it will execute during afterRender. That's strange?

**Comment by brianmhunt** [comment]
To really be sure to it's escaped (i.e. lazy), I use Base64 atob/btoa (you'll need an IE9 shim).

**Comment by Dmitri-Sintsov** [comment]
@brianmhunt I found https://github.com/beatgammit/base64-js which will work in IE6. I can easily encode tempate source to base64 at server side, but what's the proper place of code to decode it at client-side? How can I hook into the template fetching of knockout.js?

**Comment by mbest** [comment]
@Dmitri-Sintsov, If you want to execute some scripting during binding, use a custom binding.

**Comment by Dmitri-Sintsov** [comment]
@mbest, but aren't that a bug that it does not support script tags within templates? I know that it's really bad design to generate form inputs with duplicate script code parts for them but server-side developers often are unaware of best practices of client-side development.

https://github.com/digi604/django-smart-selects/blob/master/smart_selects/widgets.py#L92

 I implemented custom binding many times but I do not want to competely re-create foreach binding on my own, I thought that I'll be able to re-define only template loading. If that was my code I'd hook it into afterRender and actually I call my own client-side handlers in afterRender. But that is not my code.

**Comment by mbest** [comment]
I'm thinking you could do something like this:

```
<!--ko foreach: items-->
    <div data-bind="smartSelect: $data"></div>
<!--/ko-->
```

Now your `smartSelect` binding would do all the work of inserting the widget using code that specifically works with the widget.

**Comment by Dmitri-Sintsov** [comment]
It's not just one widget. It's a widget that can be added and removed. Here's a jinja2 template with knockout.js bindings:

        {% for formset in formsets %}
            <div class="formset default-padding">
                <div class="management-form">
                    {{ formset.management_form }}
                </div>
                {% if not html['inline_title'] %}
                    {% do html.update({'inline_title': formset.model._meta.verbose_name}) %}
                {% endif %}
                {% for form in formset %}
                    {% include 'bs_formset_form.htm' %}
                {% endfor %}
                <div data-bind="template: {name: 'empty_form_{{ loop.index }}', foreach: forms, afterRender: afterFormRendered}"></div>
                <template type="text/html" id="empty_form_{{ loop.index }}">
                    {{ formset.knockout_template|safe }}
                </template>
                <button class="btn btn-info btn-sm" data-bind="click: addForm, visible: hasMoreForms">Add</button>
            </div>
        {% endfor %}

Note that it has foreach and Add form button. How can I make a binding that will be a template and foreach and include that
                    {{ formset.knockout_template|safe }}
which may unfortunately contain script tags?

I guess that binding
    <div data-bind="smartSelect: $data"></div>
should be placed into
https://github.com/digi604/django-smart-selects/blob/master/smart_selects/widgets.py#L92
but that's not my code and there are another Django widgets may have server-side generated script for example rich editors.

**Comment by Dmitri-Sintsov** [comment]
Can anyone tell what's wrong with my custom binding?

    ko.bindingHandlers.html5template = {
        init: function(element, valueAccessor, allBindings, viewModel, bindingContext) {
            $.each(allBindings(), function(k, v) {
                if (k === 'template') {
                    var template = document.getElementById(v.name);
                    if ('content' in document.createElement('template')) {
                        var clone = document.importNode(template.content, true);
                        var script = document.createElement('script');
                        script.setAttribute('type', 'text/html');
                        while (clone.hasChildNodes()) {
                            script.appendChild(clone.removeChild(clone.firstChild));
                        }
                        template.parentNode.replaceChild(script, template);
                        script.id = v.name;
                    }
                    return false;
                }
            });
        },
        update: function(element, valueAccessor, allBindings, viewModel, bindingContext) {
        },
    };

It does not generate any errors, just when new value is pushed into knockout.js template foreach observableArray it produces template with empty text such as some nodes were lost. I use latest Chrome in Ubuntu 14.04 LTS.

**Comment by mbest** [comment]
There's no need for `$.each(allBindings(), function(k, v) {  if (k === 'template') {`. You can use instead `var v = allBindings.get('template');`

**Comment by Dmitri-Sintsov** [comment]
@mbest, Thanks, it shortened binding handler. Still the template was evaluated to empty string - even though it seems that I correctly moved the nodes from template documentfragment into newly created script[type="text/html"] with the same id. I downloaded debug version of knockout.js 3.3.0 and tried to watch template load in Chrome. it turned out that template load is long and really complex with deferrables. I wasn't able to figure out why it fails to expand correctly - even though it found newly created script DOM element without visible problems. It also turned out that knockout.js supports anonymous templates, I never heard of before. Finally I found this definition:

    // The following element types will not be recursed into during binding. In the future, we
    // may consider adding <template> to this list, because such elements' contents are always
    // intended to be bound in a different context from where they appear in the document.
    var bindingDoesNotRecurseIntoElementTypes = {
        // Don't want bindings that operate on text nodes to mutate <script> and <textarea> contents,
        // because it's unexpected and a potential XSS issue
        'script': true,
        'textarea': true
    };

and switched my formset.empty_form template container to textarea with css class display:none. Also content was html quoted (no |safe) so script is not executed before the binding starts (no XSS).

But still script inside formset.empty_form template isn't executed when new empty_form is dynamically added via push'ing element into observableArray :( Is there any way to make knockout.js to execute it?

But at least it's no XSS now and textarea template is officially supported by knockout.js. It's much better already even though is not perfect.

**Comment by mbest** [comment]
As far as I can tell, running inline scripts within a "template" isn't a simple task. jQuery does do this if you use it to insert a script node, but although Knockout will use jQuery, if available, to parse the template source, it doesn't use jQuery to insert the nodes. But you could probably use a simple custom binding to do it. Here's what I think it could be (but I haven't tested it):

```html
<div data-bind="foreach: forms">
    <div data-bind="djangoWidget: 'empty_form_{{ loop.index }}'"></div>
</div>
```

```javascript
ko.bindingHandlers.djangoWidget = {
    init: function(element, valueAccessor, allBindings, viewModel, bindingContext) {
        var templateId = valueAccessor(),
            templateElement = document.getElementById(templateId),
            templateContents = templateElement.value;
        $(element).append(templateContents);
    }
};
```

**Comment by Dmitri-Sintsov** [comment]
@mbest, thanks. I did not know that script nodes are not automatically evaluated when added. But I am mostly back-end developer.

jQuery expansion is a good approach together with textarea which is supported even in old IE's and is not vulnerable to early XSS. textarea should be official recommended container to include knockout.js templates, not the script tag. template tag is a bit too modern.

May I ask a question is it possible to load knockout.js template in 'foreach' or 'template' binding via class selector, not via 'name' id selector? Because I do not want to generate ID's for all the formset widgets (there are many and if I have two formsets for the same back-end model their DOM id's can be conflicting).

I just want to have my custom jQuery (or at least DOM) lookup of knockout.js template via it's css class by searching it via XPATH or jQuery expression, not a simple getElementById(). Is that possible?

**Comment by mbest** [comment]
Using a custom binding to load and insert the template means you can find it however you want.

**Comment by Dmitri-Sintsov** [comment]
@mbest I tried to do custom binding to make custom template lookup. Here is the code, again it has no errors but template is not expanded (not loaded). Why is it that?

                <div data-bind="anonymous_template: {
                        'template-index': {{ loop.index0 }},
                        'base-selector': '.formsets'
                    },
                    template: {
                        name: '',
                        foreach: forms,
                        afterRender: afterFormRendered
                    }"></div>

    ko.bindingHandlers.anonymous_template = {
        init: function(element, valueAccessor, allBindings, viewModel, bindingContext) {
            // Get value of template binding for the same element.
            var templateAccessor = allBindings.get('template');
            if ((typeof templateAccessor['name'] !== 'undefined' &&
                    templateAccessor['name'] !== '') ||
                typeof templateAccessor['nodes'] !== 'undefined' ) {
                return;
            }
            var $textarea = $(element).parents(valueAccessor()['base-selector']).find('.ko-template').eq(valueAccessor()['template-index']);
            templateAccessor['nodes'] = $.parseHTML($textarea.val());
        }
    };

Is there a simpler way to get rid of template lookup by id? Or can you point to error in my code, please? I am not front-end guru and wasted a lot of time on it. It's strange why template binding does not have a callback not for template name but for template lookup via custom function.

**Comment by mbest** [comment]
Did you try to use the binding example I gave you? Since you need to execute the embedded `<script>`, why are still trying to use the `template` binding directly?

Anyway, you can't modify the actual binding of a sibling binding. You need to use a different approach, for example, using `ko.applyBindingAccessorsToNode`. Here's an example: http://jsfiddle.net/mbest/DCz5r/8/

**Comment by Dmitri-Sintsov** [comment]
@mbest I tried to use your binding just now and it works great. I did not use it before because I thought that altering template binding is better idea but now I understand I was wrong. Here's working code (including javascript execution) that I use now:

                <div data-bind="foreach: {data: forms, afterRender: afterFormRendered}">
                    <div data-bind="anonymous_template: {'base-selector': '.formsets', 'template-index': {{ loop.index0 }}}"></div>
                </div>
                <button class="btn btn-info btn-sm" data-bind="click: addForm, visible: hasMoreForms">Add "{{ formset.model._meta.verbose_name }}"</button>

    ko.bindingHandlers.anonymous_template = {
        init: function(element, valueAccessor, allBindings, viewModel, bindingContext) {
            var $textarea = $(element)
            .parents(valueAccessor()['base-selector'])
            .find('.ko-template')
            .eq(valueAccessor()['template-index']);
            $(element).append($textarea.val());
        }
    };

Thank you a lot for answering to my questions. Still it would be great if template binding was able to support all of this directly.
