### ISSUE TITLE
How to bind the registered viewmodel to its corresponding template?

### ISSUE THREAD

**Issue by lzl124631x** [knockout/knockout#1843]
I have lots of separate template & viewmodel pairs, each of which stands for a single page. I registered them and want to call `applyBindings` to bind their viewmodel to template respectively, rather than a global ko.applyBindings(). How can I achieve it?

Some of the template & viewmodel pairs are fetched dynamically via AMD. So a global ko.applyBindings() can't affect those newly fetched templ & vms.

**Comment by lzl124631x** [comment]
Currently I have to call `ko.applyBindings({}, document.getElementById('loading-component'));` to apply the bindings for `<loading id="loading-component"></loading>`. This is trivial.

**Comment by lzl124631x** [comment]
A global `ko.applyBindings()` can be only called once (once one dom element can only be bond once), which makes me have to applyBindings for each component respectively.

**Comment by mbest** [comment]
Have you looked at components? http://knockoutjs.com/documentation/component-overview.html

**Comment by lzl124631x** [comment]
@mbest  Yes, but none of the examples gives me clue to my question. As for the example in the page you mentioned, can you suggest me how to *call* the `like` or `dislike` function from outside the viewmodel of `like-widget`?

**Comment by IanYates** [comment]
Three approaches come to mind
a) It's a bit gross, but you could use `ko.dataFor( <htmlElementHere> )` to get the view model that's applying to the element in question.  Then you can call your methods
b) What I'd do is have some contract object with my component that I pass in, and perhaps the component adds some functions to that passed-in contract object so that the outside view model (that original created the contract object to pass in) can call some of those added functions
c) Use something like ko.postBox to allow one part of your page to publish messages and another part of your page receive messages

The level of coupling changes.  Postbox allows for very loose coupling but you'd want some good documentation so you can keep an accurate 'big picture'.  The contract object, particularly when using TypeScript interfaces, can make for a nice self-documenting API although you need to be wary of object reference leaks, etc.  DataFor is a bit of a hack but if your use-case is simple it could be what you want.

**Comment by lzl124631x** [comment]
@IanYates  Thanks for your reply. I've tried the first approach but met some problem.

        // HTML
        <foo id="foo"></foo>
        // foo.html
        <div id="inner">blabla</div>
        // foo.js
        define(['knockout', 'text!./foo.html'], function(ko, fooTemplate) {
        function FooViewModel() {}
        return { viewModel: FooViewModel, template: fooTemplate};
        });
        // startup.js
        define(['knockout'], function(ko) {
                ko.components.register('foo', { require: 'components/foo/foo' });
                ko.applyBindings({}, document.getElementById('foo'))
                ko.dataFor(document.getElementById('foo')); // Returns {} which is useless
                ko.dataFor(document.getElementById('inner')); // Throws Error because the inner DOM element is not inserted at this point.  <---
        });

**Comment by mbest** [comment]
@lzl124631x Components are bound asynchronously. One way is to include some sort of callback in your component parameters:

```
<foo id="foo" params="{callback: fooCallback}"></foo>
```

**Comment by lzl124631x** [comment]
@mbest 

* Is there a simple way to add a callback into applyBindings? Something like `ko.applyBindings(viewModel, document.getElementById('id'), function () { ... });`, whose third parameter is a callback function. This callback function might be useful.
* How about returning the viewModel of component after calling `ko.applyBindings`? As @IanYates said, there could be some tricks to achieve this, but those tricks are not straightforward.

**Comment by lzl124631x** [comment]
@mbest  If it's possible please re-open this issue to let more people see it. thx.

**Comment by brianmhunt** [comment]
@lzl124631x you might enjoy a look at the demo next KO home page via brianmhunt.github.io/knockout - it's a single page app via KO

**Comment by lzl124631x** [comment]
@briandipalma  Thanks for your link! That page looks great! However, it also has a issue that I care.

Normally, KO uses templates to change between views, but that change occurs instantly, which means that you cannot add transition between the page changes. I need some transitions like those in [jquery mobile](http://demos.jquerymobile.com/1.4.5/transitions/) which will make your app feel more native. So I tend to preserve multiple components in DOM at the same time, and change between those pages.

As for your example, only the `div.main` changes instantly as the template/component changes. That's great for a desktop web app, but my mobile web app wants more.

I learnt from [Architecting large Single Page Applications with Knockout.js](http://blog.stevensanderson.com/2014/06/11/architecting-large-single-page-applications-with-knockout-js/) by Steve Sanderson. The framework also uses a single div and changes component being bond. This framework doesn't support transitions, especially transitions that have two pages appearing at the same time.

That's the reason why I'm building my own framework.

**Comment by simonmurdock** [comment]
There are definitely ways to do what you want with knockout & CSS3 animations.You just need to manage which pages you have in your SPA and making the relevant one animate-in and animate-out. You just need to build into your base viewmodel the concept of different pages which can then have the animations applied to them.

**Comment by briandipalma** [comment]
@lzl124631x I don't think you need to build your own framework to transition between page with animations, check out this [talk from ReactEurope](https://www.youtube.com/watch?v=Q6Kczrgw6ic) at about 17:35 it starts off a demo showing transitions. [Here is a great talk on animation](https://www.youtube.com/watch?v=1tavDv5hXpo) at the same conference. Building your own framework is time consuming I would check out alternatives first.

**Comment by brianmhunt** [comment]
@lzl124631x I've made the page transitions on the [demo site](http://brianmhunt.github.io/knockout) animated; it's crude but I think it [illustrates the basics](https://github.com/brianmhunt/knockout/blob/gh-pages/src/bindings-animatedTemplate.js).

**Comment by lzl124631x** [comment]
@sibartlett Yes, there are ways. I'm using CrossRoads.js as router, Animate.css as transitions. But I met some aforementioned problems.

**Comment by lzl124631x** [comment]
@briandipalma I don't want to either. I just didn't find any good SPA example using KO before. Thanks for your link. I've have a look. But all of those are based on React? Do I have to drop KO? I haven't used React before.

**Comment by lzl124631x** [comment]
@brianmhunt Thanks for you update! Now it's getting better. I've look into it.

(Hope you won't feel me too fussy -- your updated demo site can only show one page during transitions, right? I hope I can make one page push another out of screen and you can see those two pages appearing during the transition. That's more like a native app).

**Comment by briandipalma** [comment]
You don't have drop KO, you can use React to wrap your KO pages. React is a better fit for complex apps with data changing over time, I don't know what you are building though.

**Comment by brianmhunt** [comment]
@briandipalma Just curious, what advantages do you see to React? (There's a convo on this over at https://gitter.im/knockout/knockout)   Cheers

**Comment by lzl124631x** [comment]
```
var data = { a: { b: 1} };
var vm = ko.mapping.fromJS(data);
console.log(vm.a.b());
```
Why `vm.a` is not an observable? http://knockoutjs.com/documentation/plugins-mapping.html#how-things-are-mapped

**Comment by lzl124631x** [comment]
https://jsfiddle.net/Richard_Liu/pauzy5wL/

Why error occurs if I specify 'observe' setting which doesn't include the nested inner object `b`?

**Comment by simonmurdock** [comment]
You should probably create a new issue, rather than tack this onto a closed one.

**Comment by lzl124631x** [comment]
@simonmurdock a new issue created.

**Comment by simonmurdock** [comment]
#1895 is the ticket
