### ISSUE TITLE
Use `WeakMap` for `domData` if available 

### ISSUE THREAD

**Issue by brianmhunt** [knockout/knockout#1846]
The [domData implementation](https://github.com/knockout/knockout/blob/master/src/utils.domData.js) could achieved with a `WeakMap`.

The benefits of this are:

1. We don't go modifying the DOM;
2. A `WeakMap` implementation is simpler; and
3. A `WeakMap` implementation may be faster.

We cannot use a regular Map or it'll be a memory leak for items that are removed from the DOM and otherwise dereferenced.

Whether KO should include a WeakMap implementation for DOM data is, in my eyes, dependent upon how much of a performance improvement there is. If there is little to no performance improvement, then just the current implementation is probably preferable for backwards compatibility. I will run some empirical tests to see what I get.

**Comment by brianmhunt** [comment]
A better alternative might to be to use a `Symbol` instance for the property name, since then it will be by default non-enumerable on newer browsers.

**Comment by juuxstar** [comment]
WeakMap is very slow in current implementations unfortunately.  100x slower than accessing a regular object dictionary.  Check out: https://jsperf.com/property-access-object-array-map-weakmap

**Comment by brianmhunt** [comment]
Thanks @juuxstar – that is slow. :) I'm closing this on that basis.

As an aside, it might be appropriate if the `domData` were a `Symbol` property.
