### ISSUE TITLE
Flashing of element when using widgets

### ISSUE THREAD

**Issue by piuccio** [knockout/knockout#1849]
Hi, I've created [this fiddle](http://jsfiddle.net/r2uudnsy/) to show the problem.

I'm dealing with an observableArray, and for some reasons I end up calling something that looks like this
```
observableArray.removeAll()
if (certain conditions...) {
   observableArray([...]);
}
```

This works fine when you're using templates, but it start flashing when you use components.

In the fiddle, click on shuffle, you'll see that the column on the right flashes from time to time, while the one on the left doesn't. I have a more complex DOM structure in my components and it flashes all the times.

Is there a way around this?

**Comment by brianmhunt** [comment]
@piuccio I wonder if you would experience the the problems with either:

1. knockout 3.4 (esp. with `ko.options.deferUpdates = true`)
2. the knockout-fast-foreach plugin

Just some thoughts.

Cheers.

**Comment by mbest** [comment]
This is fixed with Knockout 3.4.0: http://jsfiddle.net/r2uudnsy/2/

With 3.3.0, a workaround is to use rateLimit: http://jsfiddle.net/r2uudnsy/1/

**Comment by piuccio** [comment]
Didn't try `3.4` because it's not releases yet and I can't push it to production so it's not a solution for me.

I tried to use `rateLimit` and I still get the flashing. The fiddle is not good enough to replicate the exact issues.

The good news is that I managed to find the cause and fix it.

It all happens [here](https://github.com/knockout/knockout/blob/v3.3.0/src/components/loaderRegistry.js#L17), components by default are asynchronous, so they get applied after a `setTimeout`. The solution is to change the component definition and add `synchronous: true`.

Looking at the code on [master](https://github.com/knockout/knockout/blob/846025a8b092444516d70fd80edd7742a801be38/src/components/loaderRegistry.js#L17) I'd say that my specific issue is not fixed, but it doesn't really matter.

Is there a reason why components are async by default? It might be nice to add a global option to turn all components to `synchronous`.

**Comment by brianmhunt** [comment]
Component loading must be async in some cases eg RequireJS. For more background on why it should always then be an async process, Google "releasing zalgo" 😀

**Comment by mbest** [comment]
@piuccio It's still asynchronous by default in 3.4.0, but the method is different, so that updates happen before the next browser redraw.

**Comment by webketje** [comment]
I've been presented with a similar problem, although mine was causing both flashing and page locking (for a big observableArray rendered on the page). My 'solution' to this was to first create a temporary 'buffer' with the array contents, empty the array, and per interval (0-50 ms) push the items back into it. Together with jQuery's animation capability this gives quite a nice result

Modified fiddle code:

```````

ko.applyBindings({
    list: ko.observableArray([1,2,3,4,5,6,7,8,9,10]),
    shuffle: function () {
        var self = this
          , buffer = this.list();
        buffer.sort(function () {
            return Math.random() - Math.random();
        });
        this.list([]);
        var push = setInterval(function() {
            self.list.push(buffer.shift());
            if (buffer.length === 0)
                clearInterval(push);
        }, 0);
    },
    animateRemove: function(el) {
        $(el).slideUp('fast');
    },
    animateAdd: function(el) {
        $(el).hide();
        $(el).slideDown('fast');
    }
}, container);
``````
In action: http://jsfiddle.net/kevinvanlierde/r2uudnsy/5/
