### ISSUE TITLE
3.4.0 breaks Knockout beta website

### ISSUE THREAD

**Issue by brianmhunt** [knockout/knockout#1850]
When I run 3.4.0 on the beta website it throws a `cannot apply bindings twice` error.

It may be that I'm using KO incorrectly somehow, but others may be similarly using KO incorrectly and 3.4 would break their sites, too.

More information coming when I get a chance. In the mean-time you can also replicate the problem by 

1. checking out `gh-pages` from `brianmhunt/knockout`, 
2. switch the knockout library included from 3.3 to 3.4 (I just copy knockout.js 3.4 over `node_modules/knockout/build/output/knockout-latest.js`; alternatively edit `config.yaml`'s `libs.js` to point to 3.4)
3. run `gulp server`
4. open the server at `localhost:8900`

**Comment by mbest** [comment]
I just tried all of this and did not get any error.

**Comment by brianmhunt** [comment]
I'm looking at it now. Will post more info shortly.

**Comment by brianmhunt** [comment]
Michael: Thanks for checking this out.

I have uploaded a version using KO 3.4 and the problem occurs for me at http://brianmhunt.github.io/knockout/ using Chrome Beta (45).

I am hoping to look at this more later today, but of course any thoughts and feedback you have in the mean time would be very helpful. :grin:

**Comment by mbest** [comment]
The error happens because you've overwritten `ko.applyBindings` with one that overrides the `node` argument. When linked with the release version of Knockout, this doesn't affect Knockout's internal use of `ko.applyBindings`, but because you linked with the debug version, it does. When I tested with 3.4.0 on my computer, I used the release build and so didn't see any error.

**Comment by brianmhunt** [comment]
That's it, thanks @mbest.

I can reproduce the problem by using the 3.3 debug build, so 3.4 is not the issue, and in any case it'd be really strange for folks to be overwriting `ko.applyBindings` in the wild.

**Comment by michaelaird** [comment]
Just a note: Knockout validation overrides ko.applyBindings

https://github.com/Knockout-Contrib/Knockout-Validation/blob/master/src/ko.extensions.js

it would be a good idea to test 3.4 with ko validations just to make sure...

**Comment by brianmhunt** [comment]
Thanks @michaelaird - I tested 3.4 with KO.validation; no issues.

**Comment by brianmhunt** [comment]
Incidentally, @michaelaird Is there a hook KO could do that could be a substitute for overloading `ko.applyBindings`?

**Comment by michaelaird** [comment]
I'm not too sure. I'm not a contributor on KO.Validation, I just happened to be watching this issue and I knew that it did override applyBindings.

@crissdev is probably a better person to ask.

**Comment by crissdev** [comment]
@brianmhunt Great work! Just one small bug I noticed - see image below. Refreshing the page displayes the correct page though.

![animated](https://cloud.githubusercontent.com/assets/822571/9563656/998de4bc-4e93-11e5-8509-213c235950d8.gif)

Regarding Knockout-Validation, it shouldn't break anything, unless KO adds breaking changes. :smile:

---
Animated image created with https://screentogif.codeplex.com/
Chrome Version 44.0.2403.157 m

**Comment by tomdowbelkin** [comment]
I have a scenario where a validatedObservable is not being fired under KO 3.4. This works in 3.3:

```javascript
function watchValidatedObservables(viewModel) {
    // .validators is a validatedObservable
    return ko.computed(function() {
        if (ko.validation.utils.isObservableArray(viewModel.fieldSet)) {
            return viewModel.fieldSet().every(function(fields) {
                return fields.validators.isValid();
            });
        }

        return viewModel.fieldSet.validators.isValid();
    });
}
```

Things are fired when first requested, but not as fields are changing under 3.4. Any ideas?

**Comment by crissdev** [comment]
@tomdowbelkin If possible, please create a jsfiddle(https://jsfiddle.net/) and post it in the [Knockout-Validation](https://github.com/Knockout-Contrib/Knockout-Validation/issues) issue tracker. Thanks.
