### ISSUE TITLE
3.0.4 alpha/beta

### ISSUE THREAD

**Issue by EricSmekens** [knockout/knockout#1853]
Since the milestone of 3.0.4 is cleared, could there be a 3.0.4 alpha/beta release soon?
I would like to test this version, also because of the performance improvements. But I would like to do that on a version that is released through github. (Not build myself).

**Comment by brianmhunt** [comment]
@EricSmekens Yes, I believe 3.4 is on the horizon.

Once it is out the version will be accessible in a number of places (including CDNs). In the mean time, you can download it here: https://raw.githubusercontent.com/brianmhunt/knockout/7a3c345d0f48a42ca2ce3ab4fdfbce22e386718a/knockout-3.4-pre.js  (bear in mind that `ko.version` will be "3.3.0-debug", just in case that matters for you.)
