### ISSUE TITLE
Buf: 'name' attr binding does not remove attribute if undefined

### ISSUE THREAD

**Issue by conficient** [knockout/knockout#1857]
If the `name` attribute of an element is set using an `attr` binding, I believe that Knockout is supposed to **remove** the attribute from the element if the bound value is _undefined_, _false_ or _null_?

This does not appear to be the case, as I am finding a leftover tag in the element, e.g.
```<input type="text" data-bind="value: Value, attr: { name: Name }" name>```

Example: https://jsfiddle.net/Quango/tt2332et/

**Comment by mbest** [comment]
According to Knockout's spec, this is working as designed:

https://github.com/knockout/knockout/blob/master/spec/defaultBindings/attrBehaviors.js#L22

**Comment by conficient** [comment]
Chrome was showing an error about focus for blank name attributes in the error log.. I've had to create two versions of my component, one without a name binding and one with to work around this issue.

**Comment by brianmhunt** [comment]
I feel like removal of an attribute when the observed value is either `undefined`, `null` or `false` (or maybe even some `Symbol` we make up) would be an improvement here.

@SteveSanderson @rniemeyer Any thoughts on this?

**Comment by brianmhunt** [comment]
Thanks @mbest :grin:

**Comment by mbest** [comment]
If this behavior is causing a problem in Chrome, we should take a look at it. The current behavior is related to workarounds needed for IE 6-7. BTW, the `attr` binding will remove the attribute when the value is `undefined` for any attribute other than `name`.

**Comment by mbest** [comment]
@conficient Can you provide more details on the error you were getting and how to reproduce it?

**Comment by mbest** [comment]
> Chrome was showing an error about focus for blank name attributes in the error log.

Using your fiddle, I don't see any error. Perhaps this was a bug in Chrome that is now fixed?

**Comment by conficient** [comment]
I've just tested the fiddle on the current Chrome version and yes the error has gone, so I think you're right. I'll close this issue.
