### ISSUE TITLE
Memory consumption - foreach binding with beforeRemove callback 

### ISSUE THREAD

**Issue by adammatthewsmith** [knockout/knockout#1860]
Using version 3.3.0.  Adding and removing several items from a list via a template or foreach with beforeRemove callback uses drastically more memory than using foreach without a beforeRemove callback. Yes, I'm removing the nodes in the callback. 

http://jsfiddle.net/fhqgwh91/4/

The html in the fiddle includes several different ways to bind a list to the DOM.  Using a pure foreach without any callbacks results in about .3 mb of memory increase after 10 repetitions of 'add 500' -> 'clear'.  Using any of the versions with callbacks increases memory utilization by about 15mb.  In the chrome memory profiler I sometimes see domData hanging on to detached nodes, but it is not always the case.  When there are no detached nodes in memory, the allocation deltas do not add up to the difference between profiles.  

In the beforeAdd, I'm using a simple node.parentNode.removeChild(node) to remove the DOM node.  From reading the source code, I believe it is not necessary to call 'cleanNode', but I tested it anyway with no effect on memory consumption.

**Comment by mbest** [comment]
I tried your test and did see the memory increase. But if after those 10x "add 500/clear", I click "Add", the memory goes back down.
