### ISSUE TITLE
valueUpdate: 'blur' broken with 3.3

### ISSUE THREAD

**Issue by adbre** [knockout/knockout#1861]
I cannot get knockout-validation to work when the input control loses focus with Knockout 3.3.
This fiddle http://jsfiddle.net/29ucZ works perfectly with knockout 2.3.0, 3.0, 3.1 and 3.2.
But once I change the framework to a 3.3 version it no longer works.

**Comment by adbre** [comment]
nevermind...

**Comment by mbest** [comment]
Is there an open issue for knockout-validation that we can reference?

**Comment by adbre** [comment]
No, it was my bad. I was very tired...

mån 31 aug 2015 08:04 Michael Best <notifications@github.com> skrev:
