### ISSUE TITLE
ko.utils.registerEventHandler does not catch events without jQuery

### ISSUE THREAD

**Issue by blazkovicz** [knockout/knockout#1862]
If knockout does not use jquery for event binding it stops catching change / unput (may be other) events and most bindings (value, textInput) can not pick up user changes.
Tested in Chrome 44.0.2403.157 with knockout 3.3.0.

**Comment by brianmhunt** [comment]
@blazkovicz Thanks for the report.  Are you able to reproduce this in e.g. a jsFiddle?

The problem you are reporting is pretty unlikely to be in Knockout because this is pretty core and well tested functionality.  That said, it would be good to know what's happening.  Cheers :)

**Comment by blazkovicz** [comment]
I can not really state that knockout contains errors, I just occasionally noticed that event handlers set with element.addEventListener and not by $(element).bind (inside ko.utils.registerEventHandler) do not catch events.
I use jQuery with knockout and am able to run my app event if you close this issue without further examination. 
I just wonder, could recent chrome updates break some old and well tested core functionality of ko?

**Comment by brianmhunt** [comment]
Thanks @blazkovicz – if you find the error is reproducible, please do re-open or re-post.

Cheers

**Comment by dev-mraj** [comment]
+1 its happening to me as well

**Comment by brianmhunt** [comment]
@dev-mraj Is it reproducible, ideally in a jsFiddle?

**Comment by brianmhunt** [comment]
(Leaving closed until we have a reproducible example)
