### ISSUE TITLE
observableArray becomes regular observable when passed via component params

### ISSUE THREAD

**Issue by moyesm** [knockout/knockout#1863]
If I pass an observableArray as a param to a component, it becomes a regular observable inside the component. This seems to happen if the observableArray is a property of an observable. Ex:
```javascript
<my-component params="items: observableContent().myObservableArray"></my-component>
```

in 'my-component' viewModel:

```
params.items.remove === undefined
```
jsfiddle here:
http://jsfiddle.net/moyesm/ddnj951n/

**Comment by mbest** [comment]
You can get the original observableArray like this:

```
var items = params.$raw.items();
// "items" is the observableArray 
```

Reference: http://knockoutjs.com/documentation/component-custom-elements.html#advanced-accessing-raw-parameters
