### ISSUE TITLE
Knockout binding syntax

### ISSUE THREAD

**Issue by nullptr128** [knockout/knockout#1865]
Hello! I am going to write an gretting essay in first paragraph, skip it for tl;dr.

I am using KO.js on few very large projects (250k+ php code). KO is my personal favourite when it comes to ui libraries. I've tried many of them, binders and full stack spa frameworks like angular, but in my opinion knockout wins with them to a great degree. Comparing to other frameworks, KO "just works", auto dependency tracking is awesome, there are not much perf bottlenecks and it can be used both with SPA and tradional apps. I would want to congratulate every developer who made this fantastic tool.

The problem with KO I have is that data-bind syntax is long and unreadable on some nodes that needs many bindings. I would want to propose different syntax, instead of 1. i wuold prefer alternative 2.

http://pastebin.com/RLgetMJX

(yes it is angular-influenced). Here are the reasons:

1. Its a bit shorter and easier to maintain when node has a lot of bindings (we have few places where one node has 5+ different bindings).

2. IDEs and editors are highlighting attribute key-value pairs, and most of them will show "ko-click" part in one color and "something" in the other color. It REALLY increases readability of whole html sources.

Looking at bindingsProvider.js I think it would not be hard to add this type of feature. I think I am even able to contribute to project creating this feature.

Thanks in advance for answering!

**Comment by simonmurdock** [comment]
Can you show an example of waht you mean?

**Comment by nullptr128** [comment]
Sorry, I've ran into trouble with GitHub formatting feature and it removed my html tags. I edit comment and added pasebin: http://pastebin.com/RLgetMJX

**Comment by brianmhunt** [comment]
Thanks for the suggestion @nullptr128 ; I hope to be able to address this if/when #1602 makes it in i.e. binding handlers could set an e.g. `dataTag` property like this.

```javascript
ko.bindingHandlers.click = function clickBindingHandler(params) {
}
ko.bindingHandlers.click.prototype = {
  dataTag: 'click'
}
```

then in the code one would reference it with:

```html
<node ko-click="callback"></node>
```

where the `callback` in this case is passed as the `value` property of the `params`.

Which is getting a bit ahead of ourselves, but all-to-say, I agree this should be in, and it should hopefully be possible. :)

**Comment by nullptr128** [comment]
Thank you and wish good luck with developing!

**Comment by IanYates** [comment]
@brianmhunt - that would be nice :)

**Comment by chinaniit** [comment]
It's like angularjs, e.g. 
ng-model="cost"
ng-click="do"

**Comment by nullptr128** [comment]
@chinaniit indeed, I have noted it in first comment. This and {{ }} are two features I really after moving from Angular, but {{ and }} can be supported with helper package Knockout Punches which I recommend.

**Comment by rniemeyer** [comment]
@nullptr128 - If you want to try something like this now, you could use a [custom binding provider](http://www.knockmeout.net/2011/09/ko-13-preview-part-2-custom-binding.html).  I had a binding provider that I was working with a while back that allowed you to map bindings to any attribute. I cleaned it up and pushed it to a repo here, if you want to give it a shot: https://github.com/rniemeyer/knockout-attributeBinder. It can enable all of the existing bindings to use this syntax. Hope this helps!

**Comment by nullptr128** [comment]
@rniemeyer Thank you! It was really kind to share this code. I actually jumped into KO internals yesterday and tried to override default binder with new one and I did success (though it was bad "just check if it will work" code, nowhere near being clean module). Your binding provider is very clean and I will give it a try! I would want to ask you about one thing:

https://github.com/knockout/knockout/blob/846025a8b092444516d70fd80edd7742a801be38/src/templating/templateRewriting.js

In this file, there is a regexp that fetches data-bind attributes. I do not understand what this code is for, but will your custom binding provider work correctly with asynchronously loaded components? Thats what I am afraid of.

And second question, will your module work correctly with Knockout Punches package? Because this one I would want to try as well. As far as I see, it should not be problem because you are overriding just a way a binding string is extracted from dom, while KO-Punches manipulates over already extracted data, isnt it?

**Comment by rniemeyer** [comment]
@nullptr128 - The template rewriting code only applies to certain template engines (like the old `jquery.tmpl` one included with KO). This custom binding provider would work fine with loaded components.

Punches augments the existing binding provider to add the awesome interpolation functionality. These two can work together, but you would want to install the attribute binder first and then enable punches like: https://jsfiddle.net/rniemeyer/ae67LLvo/.
