### ISSUE TITLE
end to end testing framework

### ISSUE THREAD

**Issue by brendonco** [knockout/knockout#1867]
What end to end testing framework that works well with Knockout aside from Karma.

**Comment by brianmhunt** [comment]
@brendonco – Any client-side testing framework should work just fine with Knockout, if it provides a reasonable DOM.  So Intern, Nightwatch.js, Phantom/CasperJS, Protractor, etc., all should work fine.

Is there any particular criteria you had in mind?

Will close this on the basis that there's no issue with the knockout library per se, but please let me know if you think there's something we can improve and we can discuss/reopen. :)  Cheers

**Comment by brendonco** [comment]
Thanks Brian. Since We can't create a question in github we can tag this as a question? :D Are there tutorials on how to setup e2e, I don't see such document and forum that does well. Also I want to integrate the test runner on CI such as Teamcity or Jenkins.
