### ISSUE TITLE
"data-bind" on native HTML elements and custom elements feels inconsistent

### ISSUE THREAD

**Issue by devpunk** [knockout/knockout#1869]
I would like to express my issue as a user story: *As a provider of a custom element I want users of my custom element to be able to bind to my element's properties with the same syntax they use when binding to an HTML element's properties.*  

Instead of writing
```html
<my-element param="value:viewModelProp"></my-element> 
```
users of `<my-element>` should be able to write
```html
<my-element data-bind="value:viewModelProp"></my-element>
```
which is the syntax they also use when binding to the value property e.g. of a native `<input>` element. As author of `<my-element>` I don't want a *value* binding handler to be triggered for custom elements. Instead the `<my-element>` constructor or factory should get a reference to `viewModelProp` (which might be an observable in the current binding context) via a `value` *parameter*. 

Rationale:
User's of custom elements shouldn't have to make a difference between "parameterizing" a custom element or "binding" to a native element because in fact, it *feels* to be the same. The fact that `data-bind="text:..."` or `data-bind="value: ..."` involves *binding handlers* is more of a technical detail and not something e.g. (view-) template authors should be aware of, should they?
At least, to me it seems, the names of these binding handlers were intentionally chosen to provide template authors with the feeling of binding to a *property* of the target element rather than providing them with the feeling of *invoking a binding handler*. 

With respect to custom elements, the knockout documentation states, that *data-bind* can be used on custom elements but "*it does not make sense to use bindings that would modify the element’s contents, such as the text or template bindings, since they would overwrite the template injected by your component*". (See http://knockoutjs.com/documentation/component-custom-elements.html)

I don't see why authors of custom elements should not decide on their own how `data-bind="text:..."` affects the appearance/behavior of the custom element. I belief, in terms of custom elements, binding handlers should be bypassed completely. Instead `data-bind="prop:propBc"` on a custom element should be treated as a binding between a custom element's VM property `prop` and a property/observable `propBc` in the  binding context in which a custom element is used (e.g. a view's view model).

Example: Definition of an element 'my-element':
```javascript
define([...], function() {
    var MyElementViewModel = function() {
         this.value = null;
    };
    var createViewModel = function(..., dataBindParams) {
         var myVM = new MyElementViewModel();
         myVM.value = dataBindParams.value; // desired: get hold of 'myProp' provided via  data-bind="value:myProp".
    };
    return {
          createViewModel: createViewModel,
          template: '<div><input data-bind="value: value"></input></div>' // keep on using KO value binding for native elements
    };
});
```
When the element user writes
```html
<my-element data-bind="value:myProp"></my-element>
```
then a reference to `myProp` should be passed to the element constructor or factory. The example above shows how to "bind through" from a `<my-element>` binding context to the `<input>` element it wraps. Its just an example. The main point is the inconsistency in using data-bind on native and custom elements.

I can imagine, template authors using custom elements can get easily confused because they attempt to use custom elements like a native html element (which ironically is what we want them to do when providing them with custom elements, do we?)

1. Have other authors of custom elements come across similar issues/ideas?
2. Is there a chance of aligning the syntax?
3. Is there a chance of getting a reference within a custom element constructor/factory to values bound via `data-bind`?

**Comment by chrisknoll** [comment]
I am in the process of writing reusable components, and I don't think that it is unreasonable for component authors (and consumers) to understand the difference between the 'params' attribute of a component and a 'data-bind' attribute of a DOM element.  params is about passing information into an entity.  data-bind is about assocating some data with an actual dom element.  To mix these concepts would make people think that the following should do something meaningful:

~~~~html
<my-custom-component data-bind="text: observableValue"></my-custom-component>
~~~~

Looking at the above, it makes it look like the text binding handler should actually take action and do something with this element. That is not the case.  

The thing you have to understand about the components (and the custom tags) is that you're generating _new_ DOM elements for which to bind to.  Your component has a local 'view model' that is available just to the component, which is a powerful feature when looking to package up reusable bits of functionality in an app.  This is much different then designing a new databinding.  And I believe the syntax for either of those should be as dissimilar as possible.

**Comment by devpunk** [comment]
Thank you @chrisknoll for your feedback. I was quite new to knockout when I posted the issue. It felt a bit odd to me, to make custom component users aware that they should please *not* write `<my-comp data-bind="text:...">`  even if my custom component has a text parameter, because the text handler in fact *does* take action and overwrites my custom component template ;-)

In the meantime I have changed my mind and come to see that I took the concept of bindings/binding handlers much too narrow. I focused too much on those bindings which can be used as if one binds directly to an element property (thinking of the `value` or `options` or `click` bindings here) which is not the case, though.

Having to use the *params*-binding for custom components is quite consistent when compared to the *attr*-binding for ordinary HTML elements. If you want to bind to arbitrary HTML element attributes you have to write `data-bind="attr: { key:value}"`, too, so it seems okay to write `data-bind="params: { key:value}"` for custom components as well.

I think this issue can be closed.
