### ISSUE TITLE
foreach et al

### ISSUE THREAD

**Issue by AndyObtiva** [knockout/knockout#1874]
Here is a list of issues I am encountering:

1) nested foreach "as" variable does not work but $data works:
The following markup fails:
```
  <tbody data-bind="foreach: {data: products, as: 'product'}">
    <tr>
      <td data-bind="text: product.model.name"></td>
      <td data-bind="foreach: {data: $parent.recommendationActions, as: 'recommendationAction'}">
        <a data-bind="attr: {href: ''}, text: recommendationAction">Action</a>
      </td>
    </tr>
  </tbody>
```
Uncaught ReferenceError: Unable to process binding "text: function (){return recommendationAction }"
Message: recommendationAction is not defined

The following markup succeeds by using $data instead of recommendationAction:
```
  <tbody data-bind="foreach: {data: products, as: 'product'}">
    <tr>
      <td data-bind="text: product.model.name"></td>
      <td data-bind="foreach: {data: $parent.recommendationActions, as: 'recommendationAction'}">
        <a data-bind="attr: {href: ''}, text: $data">Action</a>
      </td>
    </tr>
  </tbody>
```

2) comment-based nested foreach does not see $parent variable:
The following markup fails:
```
  <tbody data-bind="foreach: {data: products, as: 'product'}">
    <tr>
      <td data-bind="text: product.model.name"></td>
'data-method': 'delete', rel: 'nofollow'}">Destroy</a></td>
      <!-- ko foreach: {data: $parent.recommendationActions, as: 'recommendationAction'} -->
        <td><a data-bind="attr: {href: ''}, text: $data">Action</a></td>
      <!-- /ko -->
    </tr>
  </tbody>
```

Uncaught ReferenceError: Unable to process binding "foreach: function (){return {data:$parent.recommendationActions,as:'recommendationAction'} }"
Message: $parent is not defined

The following markup succeeds by using $root instead of $parent:
```
  <tbody data-bind="foreach: {data: products, as: 'product'}">
    <tr>
      <td data-bind="text: product.model.name"></td>
'data-method': 'delete', rel: 'nofollow'}">Destroy</a></td>
      <!-- ko foreach: {data: $root.recommendationActions, as: 'recommendationAction'} -->
        <td><a data-bind="attr: {href: ''}, text: $data">Action</a></td>
      <!-- /ko -->
    </tr>
  </tbody>
```

3) Comment-based nested foreach does not allow recommendationAction unless I add an unrelated HTML comment above it:
The following markup fails:
```
  <tbody data-bind="foreach: {data: products, as: 'product'}">
    <tr>
      <td data-bind="text: product.model.name"></td>
'data-method': 'delete', rel: 'nofollow'}">Destroy</a></td>
      <!-- ko foreach: {data: $root.recommendationActions, as: 'recommendationAction'} -->
        <td><a data-bind="attr: {href: ''}, text: recommendationAction">Action</a></td>
      <!-- /ko -->
    </tr>
  </tbody>
```

Uncaught ReferenceError: Unable to process binding "text: function (){return recommendationAction }"
Message: recommendationAction is not defined

The following markup succeeds when adding an unrelated comment above <!-- ko foreach...:
```
  <tbody data-bind="foreach: {data: products, as: 'product'}">
    <tr>
      <td data-bind="text: product.model.name"></td>
'data-method': 'delete', rel: 'nofollow'}">Destroy</a></td>
      <!-- COMMENT FOREACH LOOP -->
      <!-- ko foreach: {data: $root.recommendationActions, as: 'recommendationAction'} -->
        <td><a data-bind="attr: {href: ''}, text: recommendationAction">Action</a></td>
      <!-- /ko -->
    </tr>
  </tbody>
```

4) nested foreach content does not see 'as' variable for outer foreach:
The following markup fails:

```
  <tbody data-bind="foreach: {data: products, as: 'product'}">
    <tr>
      <td data-bind="text: product.model.name"></td>
      <!-- COMMENT FOREACH LOOP -->
      <!-- ko foreach: {data: $root.recommendationActions, as: 'recommendationAction'} -->
        <td><a data-bind="attr: {href: product.model.name}, text: recommendationAction">Action</a></td>
      <!-- /ko -->
    </tr>
  </tbody>
```

Uncaught ReferenceError: Unable to process binding "foreach: function (){return {data:$root.recommendationActions,as:'recommendationAction'} }"
Message: Unable to process binding "attr: function (){return {href:product.model.name} }"
Message: product is not defined

The following markup also fails when attempting to use $parent instead of product:
```
  <tbody data-bind="foreach: {data: products, as: 'product'}">
    <tr>
      <td data-bind="text: product.model.name"></td>
      <!-- COMMENT FOREACH LOOP -->
      <!-- ko foreach: {data: $root.recommendationActions, as: 'recommendationAction'} -->
        <td><a data-bind="attr: {href: $parent.model.name}, text: recommendationAction">Action</a></td>
      <!-- /ko -->
    </tr>
  </tbody>
```

Uncaught TypeError: Unable to process binding "foreach: function (){return {data:$root.recommendationActions,as:'recommendationAction'} }"
Message: Unable to process binding "attr: function (){return {href:$parent.model.name} }"
Message: Cannot read property 'name' of undefined

Strangely, this markup succeeds when I use $parent but without going 2 levels deep by stopping at $parent.model:

```
  <tbody data-bind="foreach: {data: products, as: 'product'}">
    <tr>
      <td data-bind="text: product.model.name"></td>
      <!-- COMMENT FOREACH LOOP -->
      <!-- ko foreach: {data: $root.recommendationActions, as: 'recommendationAction'} -->
        <td><a data-bind="attr: {href: $parent.model}, text: recommendationAction">Action</a></td>
      <!-- /ko -->
    </tr>
  </tbody>
```

I've recommended and used knockout.js at a large company, and have provided consulting for it to another client because I thought it helps in writing elegantly simple JavaScript UI data-binding code with pure HTML (no handlebars syntax nonsense nor Angular complexities). It would be a shame if I stop recommending its use just because of a few small bugs here and there. I would really look forward to getting this functionality fixed, and would be happy to help contribute to the project if needed (I've done the same when I proposed changes to selfish.js a while back).

Cheers everyone and keep up the good work.

Andy Maleh

**Comment by mbest** [comment]
None of your examples include a `<table>` tag. Have you tried adding a `<table>` tag?

**Comment by AndyObtiva** [comment]
Yes, that was just part of the markup to keep the issue write-up terse for your convenience. 

Here is an example including the full table markup (Rails erb format):
```Erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="11"></th>
    </tr>
  </thead>
  <tbody data-bind="foreach: {data: products, as: 'product'}">
    <tr>
      <td data-bind="text: product.model.name"></td>
      <td data-bind="text: product.model.description"></td>
      <td><a data-bind="attr: {href: '/products/' + product.model.id}">Show</a></td>
      <td><a data-bind="attr: {href: '/products/' + product.model.id + '/edit'}">Edit</a></td>
      <td><a data-bind="attr: {href: '/products/' + product.model.id, 'data-confirm': 'Are you sure?', 'data-method': 'delete', rel: 'nofollow'}">Destroy</a></td>
      <!-- COMMENT FOREACH LOOP -->
      <!-- ko foreach: {data: $root.recommendationActions, as: 'recommendationAction'} -->
        <td>
          <a data-bind="attr: {href: $parent.model.id}, text: recommendationAction">Action</a>
        </td>
      <!-- /ko -->
      <%# ProductsController::RECOMMENDATION_ACTIONS.reject {|action| action.start_with?('un')}.each do |action| %>
        <%# unless current_user.send(action + 's?', product) %>
          <!-- <td><%#= link_to action.humanize, send("#{action}_product_path", product), method: :post %></td> -->
        <%# else %>
          <!-- <td><%#= link_to ("un" + action).humanize, send("un#{action}_product_path", product), method: :post %></td> -->
        <%# end %>
      <%# end %>
    </tr>
  </tbody>

  <button id="show-recommendations" data-bind="visible: !recommendations()">Show Recommendations</button>
  <button id="show-all" data-bind="visible: recommendations">Show All Products</button>
</table>
```

I intentionally left in the commented parts since they might be causing the bug and thought you might find interesting to test on your side.

Here is the model and binding:
```JavaScript
  var recommendationActions = JSON.parse($('#recommendation-actions').val());
  var viewModel = {
    products: ko.observableArray([]),
    recommendations: ko.observable(false),
    recommendationActions: ko.observableArray(recommendationActions)
  }
  ko.applyBindings(viewModel);
```

Here is another case that doesn't work:

```Erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="11"></th>
    </tr>
  </thead>
  <tbody data-bind="foreach: {data: products, as: 'product'}">
    <tr>
      <td data-bind="text: product.model.name"></td>
      <td data-bind="text: product.model.description"></td>
      <td><a data-bind="attr: {href: '/products/' + product.model.id}">Show</a></td>
      <td><a data-bind="attr: {href: '/products/' + product.model.id + '/edit'}">Edit</a></td>
      <td><a data-bind="attr: {href: '/products/' + product.model.id, 'data-confirm': 'Are you sure?', 'data-method': 'delete', rel: 'nofollow'}">Destroy</a></td>
      <!-- COMMENT FOREACH LOOP -->
      <td data-bind="foreach: {data: $parent.recommendationActions, as: 'recommendationAction'}">
        <a data-bind="attr: {href: ''}, text: recommendationAction">Action</a>
      </td>
      <%# ProductsController::RECOMMENDATION_ACTIONS.reject {|action| action.start_with?('un')}.each do |action| %>
        <%# unless current_user.send(action + 's?', product) %>
          <!-- <td><%#= link_to action.humanize, send("#{action}_product_path", product), method: :post %></td> -->
        <%# else %>
          <!-- <td><%#= link_to ("un" + action).humanize, send("un#{action}_product_path", product), method: :post %></td> -->
        <%# end %>
      <%# end %>
    </tr>
  </tbody>
</table>
```

One curious thing I just noticed while experimenting is if I remove the comment  , then that case works (case #1 above). So, maybe part of the issue is knockout's handling of comments. Cases #2, #3, and #4 still do not work regardless of what I do with comments (except for the case in which I mention I add that comment to fix it)

Sorry to dump all of this on you. No pressure. I realize it's corner cases, but this is the 2nd time I ran into them in a project when needing to use the comment-based nested foreach, so I would imagine solving the issues might help many other people too.

I am not in a hurry though since my current project is an experimental personal project (not a client/company project). 

Cheers,

Andy

**Comment by brianmhunt** [comment]
@AndyObtiva Is this the same problem as here: https://github.com/knockout/knockout/issues/1759

**Comment by mbest** [comment]
I tried your second example and it works fine: http://jsfiddle.net/83hm72kb/
And also your first example: http://jsfiddle.net/83hm72kb/1/

**Comment by AndyObtiva** [comment]
Thanks for the share brianmhunt, and thanks a lot for trying things out mbest. It seems jsfiddle is working because it does not evaluate <% %> tags when they are in comments, and yet my page had more markup below the table:

```Erb
<!-- <h1>Recommended Products Based On User Interests</h1>
<%= render 'products', products: current_user.recommended_products %> -->
```
Apparently ERB (Erubis) evaluates <%= ... %> inside , resulting in the following HTML:

```Erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="11"></th>
    </tr>
  </thead>
  <tbody data-bind="foreach: {data: products, as: 'product'}"></tbody>
</table>

<button id="show-recommendations" data-bind="visible: !recommendations()">Show Recommendations</button>
<button id="show-all" data-bind="visible: recommendations" style="display: none;">Show All Products</button>

<!-- <h1>Recommended Products Based On User Interests</h1>
<input type="hidden" id="recommendation-actions" value="[&quot;like&quot;,&quot;dislike&quot;,&quot;bookmark&quot;,&quot;hide&quot;]" />
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="11"></th>
    </tr>
  </thead>
  <tbody data-bind="foreach: {data: products, as: 'product'}">
    <tr>
      <td data-bind="text: product.model.name"></td>
      <td data-bind="text: product.model.description"></td>
      <td><a data-bind="attr: {href: '/products/' + product.model.id}">Show</a></td>
      <td><a data-bind="attr: {href: '/products/' + product.model.id + '/edit'}">Edit</a></td>
      <td><a data-bind="attr: {href: '/products/' + product.model.id, 'data-confirm': 'Are you sure?', 'data-method': 'delete', rel: 'nofollow'}">Destroy</a></td>
      <!-- ko foreach: {data: $parent.recommendationActions, as: 'recommendationAction'}-->
      
        <a data-bind="attr: {href: '/products/' + product.model.id + '/' + recommendationAction, 'data-method': 'post'}, text: recommendationAction">Action</a>
      
      
        <a data-bind="attr: {href: '/products/' + product.model.id + '/un' + recommendationAction, 'data-method': 'post'}, text: 'un' + recommendationAction">Action</a>
      
      <!-- /ko -->
    
  


<button id="show-recommendations" data-bind="visible: !recommendations()">Show Recommendations</button>
<button id="show-all" data-bind="visible: recommendations">Show All Products</button>
 --&gt;
```

In effect, knockout evaluated foreach in the 2nd (commented) table markup (resulting in an error) and ignored the first (uncommented) table, resulting in an empty looking page on the browser. 

The main cause of the problem: the  showed up in the middle of another HTML comment, which is considered developer error. Here is an example of what I'm talking about: http://jsfiddle.net/AndyMaleh/4g5yj5xc/3/

So yes, I take full responsibility for causing that, and will watch out for it happening again in the future. And, I take back any doubts I had about the functionality of knockout. It is working very well under the right circumstances (no clashing comments), so I am sorry about my earlier comments if they were offensive in any way.

Still, I wonder if this raises a usability issue for knockout developers. Perhaps there is an alternative to using comments for foreach loops, such as the solution I saw in (batman.js)[http://batmanjs.org/examples.html] at one point (another pure-HTML data-binding MVVM library, alas deprecated now) 

Instead of writing the following:

```Html
      <!-- ko foreach: {data: $parent.recommendationActions, as: 'recommendationAction'}-->
      <td data-bind="visible: !product['current_user_'+recommendationAction+'s_product']">
        <a data-bind="attr: {href: '/products/' + product.model.id + '/' + recommendationAction, 'data-method': 'post'}, text: recommendationAction">Action</a>
      </td>
      <!-- /ko -->
```

An alternative possible syntax could rely on "foreachself" placed directly on the element that needs to be multiplied based on a data-bound collection:

```Html
      <td data-bind="foreachself: {data: $parent.recommendationActions, as: 'recommendationAction'}, visible: !product['current_user_'+recommendationAction+'s_product']">
        <a data-bind="attr: {href: '/products/' + product.model.id + '/' + recommendationAction, 'data-method': 'post'}, text: recommendationAction">Action</a>
      </td>
```

This would avoid the need for container elements when not needed, and would avoid having to worry about clashing comments elsewhere in the code, especially when reusing partial markup and later disabling via a comment around everything.

Regardless, thanks a lot again for making knockout.js a possibility and a very effective library at writing clean, maintainable, and elegant JS MVVM data-bound code.

**Comment by rniemeyer** [comment]
@AndyObtiva - it is not part of core, but @mbest does have a `repeat` binding that functions similarly to what you described: https://github.com/mbest/knockout-repeat

**Comment by AndyObtiva** [comment]
That's awesome! I'm beginning to see why the word "best" is in @mbest's name. ;) Cheers and thanks for the quick response with a great life-saving tip.
