### ISSUE TITLE
Rebinding element - lost context

### ISSUE THREAD

**Issue by Wayofthesin** [knockout/knockout#1878]
I am trying to create more performance scrolling-list (that romoves invisible elements from DOM). Because append is expensive operation I just precreate some elements and use translate3D to move them. It's working great. The problem appears when I try to bind them...

There are some bindings that needs context to work properly (like foreach and if). When I clean bindings it may happen that I will stay with modified template. Lets say we have foreach items binding:

```html
    <div data-bind="foreach: items"><span>$data</span></div>
```

The item got rendered with specified data. When Im clearing knockout bindings I can stay with:

```html
    <div data-bind="foreach: items"><span>item1</span><span>item2</span></div>
```

After rebinding it for viewmodel with 2 items I'll receive:

```html
    <div data-bind="foreach: items"><span>item1</span><span>item2</span><span>item1</span><span>item2</span></div>
```

What's obviously not expected behaviour. I can see two solutions:
  - Change binding handlers to use $binding context to store static binding variables. Then we can use binding context to bind viewmodel to another element and we will still have old variables accessible.
  - Extend ko.cleanNode to really clean it (bring it back to the state before bindings) what's rather worse solution.

**Comment by brianmhunt** [comment]
There are a few related issues discussed in #910 and related.

**Comment by Wayofthesin** [comment]
I saw it but the problem isn't related to event listeners but to the context the bindings are handled within.

In if binding handler we can see:

```javascript
// Makes a binding like with or if
function makeWithIfBinding(bindingKey, isWith, isNot, makeContextCallback) {
    ko.bindingHandlers[bindingKey] = {
        'init': function(element, valueAccessor, allBindings, viewModel, bindingContext) {
            var didDisplayOnLastUpdate,
                savedNodes;
            ko.computed(function() {
                var dataValue = ko.utils.unwrapObservable(valueAccessor()),
                    shouldDisplay = !isNot !== !dataValue, // equivalent to isNot ? !dataValue : !!dataValue
                    isFirstRender = !savedNodes,
                    needsRefresh = isFirstRender || isWith || (shouldDisplay !== didDisplayOnLastUpdate);
                    // .....
```

For me it should looks like:

```javascript
// Makes a binding like with or if
function makeWithIfBinding(bindingKey, isWith, isNot, makeContextCallback) {
    ko.bindingHandlers[bindingKey] = {
        'init': function(element, valueAccessor, allBindings, viewModel, bindingContext) {
            ko.computed(function() {
                var dataValue = ko.utils.unwrapObservable(valueAccessor()),
                    shouldDisplay = !isNot !== !dataValue, // equivalent to isNot ? !dataValue : !!dataValue
                    isFirstRender = !bindingContext.internal[bindingKey].savedNodes,
                    needsRefresh = isFirstRender || isWith || (shouldDisplay !== bindingContext.internal[bindingKey].didDisplayOnLastUpdate);

**Comment by brianmhunt** [comment]
Yeah, I see that too... trying to wrap my head around it :wink:

**Comment by brianmhunt** [comment]
Just curious @Wayofthesin – might [knockout-fast-foreach](https://github.com/brianmhunt/knockout-fast-foreach) be a potential stop-gap for you?  If it doesn't work out of the box you can make a derivative/subclass of the `FastForEach` constructor that should.  Just a thought.

**Comment by Wayofthesin** [comment]
I have it implemented already. The point is that I want to throw away append because it's too expensive and causes list slower than native scrolling.

What you linked is just another implementation of foreach binding. I need list that removes invisible elements from DOM so I can operate on thousands of elements.

**Comment by Wayofthesin** [comment]
Now I just wonder if it wouldn't be better to place static handler variables inside reserved variable in viewmodel. It would allow to change bindingContext without changing existing properties.

**Comment by mbest** [comment]
Knockout supports observable view models. Haven you tried that?
