### ISSUE TITLE
Looks like an unused variable leadingCommentRegex

### ISSUE THREAD

**Issue by rboydev** [knockout/knockout#1882]
I noticed that there is a variable called leadingCommentRegex that seems to be unused. I also noticed that it was used only in version 1.3.0beta.

**Comment by brianmhunt** [comment]
Thanks for the report @rboydev – `leadingCommentRegex` has disappeared since 3.3.0, so I'll close this issue (but please comment if you think I've missed something!).

**Comment by rboydev** [comment]
Actually I still see it in "knockout-3.3.0/src/utils.domManipulation.js" on line 2

**Comment by brianmhunt** [comment]
Yes, it will likely remain in 3.3.0 as an innocuous variable (i.e. it isn't practical to have a 3.3.1 release to just get rid of it).  In `master` and by 3.4 it will be gone.
