### ISSUE TITLE
Change to ko.utils.compareArrays reverses order of edit script, which is breaking change from 3.3.0

### ISSUE THREAD

**Issue by ThomasMichon** [knockout/knockout#1887]
I noticed in commit knockout@b379c2aa7ec160aa6d0e38a9e2fbe4472a918f4c that the order of the output from array comparisons has been flipped.

This means that if you attempt to use the output of the edit script to 'replay' edits onto a target array, you get odd behaviors.

I define a simple script to replicate the changes from one array to another back onto a copy of the original array:
``` javascript
function updateArray(target, changes) {
    for (var i = 0; i < changes.length; i++) {
        var change = changes[i];
        
        switch (change.status) {
            case 'added':
                target.splice(change.index, 0, change.value);
                break;
            case 'deleted':
                target.splice(change.index, 1);
                break;
            default:
                break;
        }
    }
}
```

Now some tests:
``` javascript
var array1 = [1, 2, 3];
var array2 = [5, 6, 7, 2, 4, 3];

var changes = ko.utils.compareArrays(array1, array2, { sparse: true });

var forward = [].concat(array1);
updateArray(forward, changes);

// 'forward' is [5, 6, 7, 2, 4, 3];

var reverse = [].concat(array1);
updateArray(reverse, [].concat(changes).reverse());

// 'reverse' is [1, 6, 2, 7, 3, 4]
```

In Knockout version 3.3.0, the forward iteration produces the correct output and the reverse iteration produces the wrong output. In Knockout 3.4.0, the results will be swapped.

Perhaps I am doing the iteration incorrectly and there is a way to do the minimal-edit replication in a way which is agnostic to the change order, but this is still potentially a breaking change for anyone creating ```arrayChange```-based mappings on their own. I'm interested in some advice from @mbest here.

*Edits:* added a missing line. Also, here is a JSFiddle for the issue, in case the code is unclear: http://jsfiddle.net/ThomasMichon/nu0epoko/

**Comment by mbest** [comment]
Knockout has always "reversed" the changes if the old array is longer than the new one. Now it also does so if they are equal. Thus any code needs to be able to handle it both ways. The whole change list isn't actually reversed (like with calling `reverse`); it's just that each added/removed pair for an index is reversed.

If your code can only handle the changes in one order, you can sort the change list first:

```
function compareChangeListItems(a, b) {
    return (a.index - b.index) || -a.status.localeCompare(b.status);
}
```

http://jsfiddle.net/mbest/nu0epoko/1/

**Comment by ThomasMichon** [comment]
That is what I was looking for. Thanks!
