### ISSUE TITLE
Confusing params order 1st param is 2nd param

### ISSUE THREAD

**Issue by alvarotrigo** [knockout/knockout#1889]
When calling a function in a `data-bind` event with one parameter the order of the parameters on the viewmodel is confusing:

Basicallyl calling this following function:

```javascript
setTextColor.bind($data, 'a')
```

Will contain the 2nd parameter (`a`) as the 1st param in the view model:
And the 1st param (`$data`) as the 2nd param in the view model:

```javascript
this.setTextColor = function(data, item, event) {
        console.log(data); // Item {color: "blue"}
        console.log(item); // a
        console.log(event); // event object
}
```

[Reproduction online](http://jsfiddle.net/KLK9Z/215/)

**Comment by mbest** [comment]
The first parameter to [`bind`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind) is the `this` value.

**Comment by alvarotrigo** [comment]
Could you be more specific? 
I still finding a bit confusing the fact that the order of the parameters changes.

**Comment by stalniy** [comment]
Just read how "bind" works. 
1 arg is "this" context 
Everything else is arguments.

So what you actually did is:
data-bind="click: function(vm, event) { return yourFn.call($data, "a", vm, event) }"

And as @mbest said the result is expected

**Comment by simonmurdock** [comment]
When you are calling bind and passing in $data, thats not the first parameter that gets passed to setTextColor, Thats just what "this" means within the bound method, and the 2nd parameter passed to bind is what becomes the 1st for this.setTextColor.

https://jsfiddle.net/uoz9r5dh/ this example might help understand it, I found it confusing initially too.

**Comment by mbest** [comment]
Knockout passes the viewmodel (`$data`) and the event to the function, like this:

```
handlerFunction.apply(viewModel, [viewModel, event]);
```

When you use `bind`, you replace the `this` value (but you've provided the same value of course) and prepend a parameter. It becomes the equivalent of this:

```
handlerFunction.apply(viewModel, ['a', viewModel, event]);
```

You cannot change the parameters that are passed by the binding, but you do have the option to pass the `$data` value first also:

```
click: setTextColor.bind($data, $data, 'a')
```

You might also be interested in my [Punches](http://mbest.github.io/knockout.punches/) plugin that would allow you to bind in a maybe more intuitive way:

```
on.click: setTextColor($data, 'a', $event)
```

**Comment by alvarotrigo** [comment]
Thanks, got it! :)
I was not familiarized with the `bind` function.
