### ISSUE TITLE
Radio Buttons Not Updating Correctly?

### ISSUE THREAD

**Issue by bucktaylor** [knockout/knockout#1890]
I seem to be getting odd behavior for radio buttons. When I update viewModel values, the radio button does not seem to update correctly.

See this example https://jsfiddle.net/buck_taylor/jfkfmLb8/3/

I am setting an initial value in the viewModel, then updating it, but the radio button don't reflect the change. Furthermore, if you start selecting the second option it causes the buttons in the first group to de-select when they are not related.

Any thoughts on what I am missing?

Buck

**Comment by simonmurdock** [comment]
This might not be of any use, but knockout doesn't appear to be running at all in that example. 
I messed around and reduced your example to its simplest and the radio in the 2nd fieldset still affects the first, if they share the same name like you have.

See https://jsfiddle.net/ofk3x7zk/1/

**Comment by bucktaylor** [comment]
Thanks Simon, that actually makes sense. 

Apparently my example doesn't actually represent the issue I'm having in my application, but it gives me something else to consider. In my app, after I update the modelView value the radio button doesn't indicate or show as checked, yet if I use jquery to get its value it is the same as the modelView value.

The example after I cleaned it up seems to work as expected: https://jsfiddle.net/buck_taylor/jfkfmLb8/5/

Thanks again.
