### ISSUE TITLE
Custom Binding Loaders

### ISSUE THREAD

**Issue by IPWright83** [knockout/knockout#1891]
Knockout has some great support for custom components, but I feel it's a little lacking on the custom binding side of things. We've got great flexability to create custom component loaders, use AMD style loading of them etc.

Custom bindings however lack the same sort of support. I've got a large number of custom bindings that I want to control the loading of (just like the custom component loaders) but there doesn't seem to be a clear or obvious way of doing so. If there is then the documentation is lacking in this area. AMD support would probably be good (however in my case I'd prefer to control the loading manually myself). 

If anyone knows a way to do this in the meantime I'd be grateful to hear it.

**Comment by brianmhunt** [comment]
Thanks @IPWright83 -- interesting feature request, thanks for bringing this up.

[One of the bindings proposals](https://github.com/brianmhunt/knockout/pull/1) may make this easier / possible.

**Comment by IPWright83** [comment]
@brianmhunt No problem, it's not something I was expecting to be a problem and I'm currently trying to find a way to circumvent it at the moment. I might be forced to use more components, but from my understanding it there's heavy DOM manipulation then really a custom binding is the way to go. Unfortunately due to our architecture, I could quite easily see a few hundred binding handlers (think lots of different styles of charts like Excel and you'll get the picture) which I don't want to load en-mass on initial load.

**Comment by brianmhunt** [comment]
Incidentally, one option you have, @IPWright83, is to create a custom binding that loads the binding, then controls descendant bindings, applying after the binding is loaded. In `Promise` style, something like:

```javascript
ko.bindingHandlers.some_loadable_binding = {
   init: function (...) {
      load_binding('some_loadable_binding')
         .then(function (loadedBindingHandler) {
             loadedBindingHandler.init.apply(this, arguments)
         })
      return { controlsDescendantBindings: true }
   }
}
```

That's just a rough back-of-napkin idea, but hopefully food for thought. :)

**Comment by IPWright83** [comment]
Thanks very much @brianmhunt, I'll think that through a bit more. I've actually had a slightly different idea that may also work (which involves hijacking the way the component loader works). Essentially, instead of using a binding handler, I'd used a component - that in itself just contains a binding handler... So the following:

````
<div data-bind="lineChart: $data"/>
````

would be replaced with something akin to this, where compName is now an observable with the value *binding-lineChart*:

````
<div data-bind="component { name: compName, params: { vm: $data } }"/>
````

then using this pseduo-javascript, I'd hijack the loading of that component:

````
var bindingLoader = {
   getConfig: function(name, callback) {
      if(name.startsWith("binding-")) {
         callback({ binding: name.replace("binding-", ""), jsUrl: "/bindings/" + name });
         return;
      }
      callback(null);
   },
  loadComponent(name, componentConfig, callback) {
     var obj = { };
     obj.template = '<div data-bind="' + componentConfig.name + ': $data"/>';
     $.ajax({ url: componentConfig.jsUrl, dataType: "text" })
       .done(function(data)) {
           (new Function(data))();
           callback(obj);
     });
  }
}
````

At this point I've created some DOM, which has the custom binding in, loaded the binding JS and can now complete the component.

The content of the component should then simply be something like:

````
ko.bindingHandlers.lineChart = {
    init: function(...),
    update: function(...)
}
````

Not proven it yet, but feels like it might work. It allows the delay loading quite nicely and works generically, while also stops me having to create a component template for each binding handler.

**Comment by mbest** [comment]
You can override the `ko.getBindingHandler` method to load binding handlers dynamically. This must return the handler synchronously, but you could combine this with @brianmhunt's idea to get asynchronous loading support.

**Comment by IPWright83** [comment]
@mbest Thanks for your thoughts. I had come across `ko.getBindingHandler` but noticed that it was only synchronous. I think I need to spend a little more time reading to fully understand @brianmhunt's suggestion.Sounds like you'd advocate that over the component loading approach I put forward?

**Comment by mbest** [comment]
As I mentioned in #1892, instead of `ko.bindingHandlers[handlerName].init`, it's usually better to use `ko.applyBindingAccessorsToNode`. See http://stackoverflow.com/a/21609748/1287183

**Comment by IPWright83** [comment]
@mbest I think I might have missed something - how do I tell the `applyBindingAccessorsToNode` to use the new binding that I've delay loaded? I've managed to get half of the code that @brianmhunt showed working, but I can't quite figure out how to initialize the handler once I've loaded it? I've put together a JSFiddle http://jsfiddle.net/IPWright83/v77c9Lfo/ if you're interested.

**Comment by IPWright83** [comment]
Unfortunately it seems that JSFiddle doesn't like what I'm trying to do! I've noticed in the example that `title` is coming through to the `getBindingHandler` despite it just being the name of an observable property, is that normal?

In the mean time I can load the binding handler, get it added to the list of `ko.bindingHandlers`, it just doesn't seem to do anything when I call `ko.applyBindingAccessorsToNode(element, viewModel);`

**Comment by IPWright83** [comment]
OK, so following the original example @brianmhunt left I can get the `init` part of this working fine. I've not managed to get `ko.applyBindingAccesorsToNode` working, it seems to complain about the JavaScript that I've loaded because it has invalid tokens `<` in it. Here's my current code:

````
ko.getBindingHandler = function(bindingKey) {
	
	// If the binding handler is already known about then return it now
	if(ko.bindingHandlers[bindingKey]) {
		return ko.bindingHandlers[bindingKey];
	}

	if(bindingKey.startsWith("dl-")) {

		bindingKey = bindingKey.replace("dl-", "");
		if(ko.bindingHandlers[bindingKey]) {
			return ko.bindingHandlers[bindingKey];
		}

		// Work out the URL at which the binding handler should be
		var url = bindingKey + ".js";
		
		return {
			init: function(element, valueAccessor, allBindings, viewModel, bindingContext) {
				var self = this;
	
				$.getScript(url, function(data) { 
					ko.bindingHandlers[bindingKey].init.apply(self, [element, valueAccessor, allBindings, viewModel, bindingContext]);
				});

				return { controlsDescendantBindings: true };
			},
			update: function(element, valueAccessor, allBindings, viewModel, bindingContext) {
				//console.log("Update called " + valueAccessor().title());
				var self = this;
				if(ko.bindingHandlers[bindingKey]) {
					ko.bindingHandlers[bindingKey].update.apply(self, [element, valueAccessor, allBindings, viewModel, bindingContext]);
				}
			}
		}
	}
};
````

This is all bound up using the following object:

````
var vm = {};
vm.items = ko.observableArray();
ko.applyBindings(vm);

setTimeout(function() {
	vm.items.push({ title: ko.observable("A") });
	vm.items.push({ title: ko.observable("B") });
	vm.items.push({ title: ko.observable("C") });
}, 1500);

setTimeout(function() {
	vm.items()[2].title("D");
	vm.items.push({ title: ko.observable("E") });
}, 3000);
````

What I've found with this is that the initial binding works, and additional items work, but when I modify the title from "C" to "D" in that 2nd `setTimeout`, the binding underneath doesn't work. That binding by the way looks like: 

````
ko.bindingHandlers.myCustomBinding = {
	init: function(element, valueAccessor, allBindings, viewModel, bindingContext) {
		var value = valueAccessor();
		var title = value.title();
		console.log("Init " + title);
		$(element).html("<p>" + title + "</p>");
	},
	update: function(element, valueAccessor, allBindings, viewModel, bindingContext) {	
		
		var value = valueAccessor();
		var title = value.title();
		console.log("update " + title);
		$(element).html("<p>" + title + "</p>");
	}
};
````

It seems that the binding I've created in `getBindingHandler` never gets an `update` call. If I add the 
`//console.log("Update called " + valueAccessor().title());` in for debugging purposes I've noticed that it all starts working. Unfortunately I don't know which properties need to be observable (as I hope to use this for many children). Is there anyway in which I can force an update from the child, if the item changes?

**Comment by mbest** [comment]
The key part you need to change is within the `getScript` callback. It should be like this:

```
var binding = {};
binding[bindingKey] = valueAccessor;
ko.applyBindingAccessorsToNode(element, binding);
```

Another problem with your code is that it will make multiple network requests for the same binding. So you need to only load the file once and then have all the temporary bindings wait until it's done.

http://jsfiddle.net/mbest/v77c9Lfo/5/

**Comment by mbest** [comment]
I'd like to post this answer on your [SO question](http://stackoverflow.com/questions/32868566/delay-loading-custom-bindings), but you deleted it. If you reopen it, I'll post an answer there.

**Comment by IanYates** [comment]
Nice solution.

Just a quick note to any trying this out, if you're in IE 11 (or earlier) then you need to add a polyfill for string.startsWith or it won't work.  Once I put one in place it worked as expected :)

**Comment by IPWright83** [comment]
@mbest re-opened the SO question, originally closed as someone commented they felt it was too broad and I didn't have much more I could add to it at the time, but I've extended it with some of the thought process I went through within this thread so hopefully should survive. If I have any further comments I'll probably follow up in SO so they're easily community visible, but appreciate the help :)
