### ISSUE TITLE
Loading custom binding handlers by name

### ISSUE THREAD

**Issue by IPWright83** [knockout/knockout#1892]
I've got 10 slight variations of a component, these variations all come down to the visualizations etc that are built on them, all taking the same binding object and knowing how to interpret it. 

I'd really like to be able to load a component dynamically, and control the name of it from say a computed field, such that I can swap out the content I'm displaying. I believe I need a binding handler anyway (because these charts will be heavily JavaScript based) but it seems a waste having to build a component for each as-well.

So currently you can load a binding like so (where lineChart is the custom binding):
````
<div class='visualization' data-bind='lineChart: $data'/>\
````

I'd really like to be able to do something like, very similar to the component approach:
````
<div class='visualization' data-bind='binding: { name: computedFunc }'/>
````

**Comment by IPWright83** [comment]
I should note that this issue is related to https://github.com/knockout/knockout/issues/1891 for my particular use case. By dynamically loading the binding handlers, I'd also like to dynamically request the JavaScript required to render them on a page.

**Comment by brianmhunt** [comment]
Thanks @IPWright83 ... you can just create a custom binding handler something like this:

```javascript
ko.bindingHandlers.reflect = {
   init: (element, va) {
     Object.keys(va()).forEach(function (handlerArguments, handlerName) {
        ko.bindingHandlers[handlerName].init(element, handlerArguments, ...)
     })
   },
   update: () {
      /// much like above
   }
}
```

That's quite back-of-napkin but I hope it gives you some ideas.

**Comment by mbest** [comment]
Instead of `ko.bindingHandlers[handlerName].init`, it's usually better to use `ko.applyBindingAccessorsToNode`. http://stackoverflow.com/a/21609748/1287183

**Comment by brianmhunt** [comment]
Thanks @mbest - I'll try to remember that 😀
