### ISSUE TITLE
Differences between debug and pre-minified build?

### ISSUE THREAD

**Issue by waynebloss** [knockout/knockout#1894]
I have a build script that doesn't handle pre-minified scripts yet. It takes the unminified source, uglifies it and concats it with source maps.

If I feed `knockout.debug.js` into it and basically use that version of the script in production, am I going to have problems? I know that debug contains unminified source, but besides that - are there any differences?

**Comment by waynebloss** [comment]
I see one issue that affected the debug build in the past (#1515) and another issue that is asking for basically the same thing I'm asking for - unminified release source - #835.

I got most of my answers I guess from #835 but I wish you would consider releasing Knockout into bower the same way that most other packages do - `knockout.js` as the unminified *release* build and `knockout.min.js` as the minified release build.

**Comment by waynebloss** [comment]
Uggh, what a mess. An `sh` file for building instead of using the more common `grunt` or `gulp`? Using the `Closure` compiler instead of `UglifyJS` - now I have to spend all day figuring out how to get Knockout into my build. What a pain in the ass.

**Comment by waynebloss** [comment]
According to #835 you can change `var DEBUG=true` to `false`. But **now I have to either break away from using `bower_components` for Knockout or create a special, unicorn of a build-step just for Knockout**, that changes `DEBUG` to `false`.

However, #835 also says *...the debug and production files will also have different property names for some properties. There's special code to "export" the properties that are actually public.* So now, I probably have to do a bunch of work to make my build pipeline use pre-minified files. Either that or choose between the two really shitty options I outlined in the first paragraph.

Why even have a bower package if it's basically going to be useless?

**Comment by brianmhunt** [comment]
@waynebloss - Thanks. The problem is that knockout uses a javascript-like language that is properly compiled by Closure Compiler.  In other words, `knockout.min.js` is not the same software as `knockout.debug.js`.  I agree, it's a pain, and a workaround will be great, but we're not there yet.

One outstanding problem is how to separate private from public methods on objects.  That's really the big semantic difference between the debug and the compiled version.  It is, for the moment, unsolved.

Of course this goes back to the byte-counting days when Knockout was first created and the Closure Compiler made more sense.  The problem is that there's a fairly huge amount of baggage to updating Knockout to not use the closure compiler.

Which is all to say: your pain is felt and shared by many, and the problem is not-trivial to resolve, but hopefully there's a solution in the pipeline.

**Comment by waynebloss** [comment]
@brianmhunt OK, I can deal with this - Can you just confirm that one definitely does *NOT* want to use the debug build in production, even after you set `DEBUG=false`? (Due to the differences produced by the Closure compiler...)

**Comment by waynebloss** [comment]
I just want to get a definite response on this because in #835 @bikeshedder basically said "you can just set DEBUG to false" and then @brianmhunt said "we use the closure compiler...different property names for some properties" - but nobody said "don't do that".

I don't understand why you would want different property names for things in the debug version anyway. If you care to explain the reasoning behind that, I'd be interested to know.

**Comment by waynebloss** [comment]
@brianmhunt  I guess the other question I have is - would I ever want to use `knockout.debug.js` at all, for any reason? I don't like testing and debugging with a script that is not logically equivalent to the production version.

Typically, I use un-minified sources during development so that I can see the source code and so that my tools can give me Intellisense/autocomplete/etc.

**Comment by brianmhunt** [comment]
@waynebloss I do things the same way as you; `knockout.debug.js` can be a real problem, especially if you (perhaps inadvertently) rely on undocumented functions that are not present in the minified version (esp. if you are a plugin developer).

The safer route is to use the minified version; the problem is that you cannot sensibly trace things through Knockout. (KO also does not yet produce a sourceMap, though the #1868 patch that is on-deck should solve that).

**Comment by waynebloss** [comment]
OK, thank you. What I'm hearing is to just use the minified file at all times, even during development. So, that's what I'll do. Thanks again!

**Comment by brianmhunt** [comment]
You're welcome, thanks for the report! Once source maps are out you should at least be able to follow the problem in the original source.

**Comment by waynebloss** [comment]
*Just an update here for anyone else looking* - So, excluding Knockout wasn't terribly difficult and it actually gave me the idea I needed to finish the feature of "how to use pre-minified files" in my [build tool](https://github.com/devoptix/staticbuild). Here's what I did in my gulp file:

```js
lodash.forEach(build.bundle, function (bundle, name) {
  gulp.task(mts('js-bundle-' + name), function () {
    var bi = build.getBundleInfo(name, 'js');
    return gulp.src(bi.sources)
    //.pipe(uglify())) // Using gulpif to not minify pre-minified files.
    .pipe(gulpif(['!./bower_components/knockout/dist/knockout.js'], uglify()))
    .pipe(order(bi.sources, { base: process.cwd() }))
    .pipe(concat({ path: bi.fileName, cwd: '' }))
    .pipe(rev())
    .pipe(rename(build.gulp.bundledJs(name, gutil)))
    .pipe(gulpif(gzipOn, gzip(gzipOpt)))
    .pipe(gulp.dest(build.destLocale(bi.relDir)));
  });
});
```

When I update my staticbuild tool (which is basically just a config file + dev server that I use in combination with gulp) - something like `build.getPreMinifiedIgnoreGlobs()` will supply the array to the `gulpif` step above. In my `staticbuild.json` file, I'll have something like the following which specifies the pre-minified src to use (as compared to using autoMinSrc, which will look for something like `knockout.min.js` if it exists...

```json
"bundle": {
    "ko": {
      "scripts": [
        {
          "src": "/bower_components/knockout/dist/knockout.js",
          "min": "/bower_components/knockout/dist/knockout.js"
        }
      ]
    },
    "main": {
      "scripts": [
        "/lib/main/main.js"
      ]
    },
    "nguibs": {
      "autoMinSrc": true,
      "scripts": [
        "/bower_components/angular/angular.js",
        "/bower_components/angular-animate/angular-animate.js",
        "/bower_components/angular-touch/angular-touch.js",
        "/bower_components/angular-sanitize/angular-sanitize.js",
        "/bower_components/angular-bootstrap/ui-bootstrap-tpls.js"
      ]
    },
    "site": {
      "styles": [
        "/lib/site/site.css"
      ]
    }
  }
```
