### ISSUE TITLE
Questions about Knockout Mapping

### ISSUE THREAD

**Issue by lzl124631x** [knockout/knockout#1895]
```
var data = { a: { b: 1} };
var vm = ko.mapping.fromJS(data);
console.log(vm.a.b());
```
Why `vm.a` is not an observable? http://knockoutjs.com/documentation/plugins-mapping.html#how-things-are-mapped

**Comment by lzl124631x** [comment]
https://jsfiddle.net/Richard_Liu/pauzy5wL/

Why error occurs if I specify 'observe' setting which doesn't include the nested inner object `b`?

**Comment by lzl124631x** [comment]
Copying certain properties using “copy”

**When converting your view model back to a JS object**, by default the mapping plugin will create observables based on the rules explained above. 

The bold part is wrong! Shouldn't it be 'When converting your JS object to view model'?

**Comment by lzl124631x** [comment]
The array copy can be used for efficiency to copy array or object properties including children. If an array or object property is not specified in copy or observe then it is recursively mapped:
```
var data = {
    a: "a",
    b: [{ b1: "v1" }, { b2: "v2" }] 
};
 
var result = ko.mapping.fromJS(data, { observe: "a" });
var result2 = ko.mapping.fromJS(data, { observe: "a", copy: "b" }); //will be faster to map.
```
Why doesn't knockout work in this way: if `observe` is specified and doesn't include the array `b`, `b` is always copied directly?

**Comment by lzl124631x** [comment]
```
console.clear();
var data = [
    { a: "a1", b: "b1" },
    { a: "a2", b: "b2" }
];

var m1 = ko.mapping.fromJS(data, { 'observe' : '[0].a' });
console.log(m1());
```
How to only observe property `a` of elements in array?

**Comment by lzl124631x** [comment]
http://jsfiddle.net/Richard_Liu/vfptk976/

`ko.mapping.fromJS(data, { observe: 'b' }, data);` doesn't work as expected, is this a bug or designed intentionally?

**Comment by mbest** [comment]
Please move this to https://github.com/SteveSanderson/knockout.mapping
