### ISSUE TITLE
Encoded characters not showing correctly when coming from javascript variables

### ISSUE THREAD

**Issue by Michaelkire** [knockout/knockout#1896]
JSfiddle: http://jsfiddle.net/ovof3or1/2/

When having characters like 'å' are encoded like `"&#229;"` in a variable and then shown through a binding, it does not show the correct character. It shows the `"&#229;"` instead. 

If put directly in the binding in the html, it shows correctly.

**Comment by simonmurdock** [comment]
try using the html binding instead of the text binding. It will render encoded things as you expect.

**Comment by Michaelkire** [comment]
But you can't use html binding in the attr:{title:''} part.

**Comment by simonmurdock** [comment]
http://jsfiddle.net/sx85mqgL/3/

This seems to do what you want with a custom binding, but please do read up and make sure it's implemented properly before using it in your codebase :)

**Comment by mbest** [comment]
You shouldn't be using HTML entities in your JavaScript code. Use JavaScript escaping: `\u00e5`.

http://jsfiddle.net/mbest/ovof3or1/3/

**Comment by mbest** [comment]
You can also just put the characters themselves into the JavaScript (as long as you make sure it's saved at UTF-8).

http://jsfiddle.net/mbest/ovof3or1/4/
