### ISSUE TITLE
Inconsistent event binding behavior

### ISSUE THREAD

**Issue by Elindalyne** [knockout/knockout#1898]
So I've been working on a large project at work and noticed some inconsistencies in the experience in Chrome/FF vs IE. Basically certain bindings just don't fire, or only fire if they're bound on the initial pageload. This is an issue with components and virtual elements obviously.

Check out this fiddle to see what I'm talking about.

http://jsfiddle.net/p0rpkk4q/14/

**Comment by stalniy** [comment]
I believe keypress works only for focusable elements. In order to make div focusable add tabindex attribute

**Comment by Elindalyne** [comment]
That appears to have done it... Strange that it works in IE out of the box though.

Thanks!
