### ISSUE TITLE
Validation doesn't work when submit again

### ISSUE THREAD

**Issue by 1983cc** [knockout/knockout#1908]
When I try to run an example in the book  named *Knockout js* published by O'Relilly (the example 9-4 of the book) , the code was wrritten as follow:
	
    <!DOCTYPE html>
    <html lang="en">
    <head>
	    <meta charset="UTF-8">
	    <title>Knockout Mapping plugin with options</title>	
    </head>
    <body>
	    <form data-bind="submit: validateAndSave, with: currUser">
		    <input type="text" data-bind="value: firstName" placeholder="Enter your first name" required /><br/>
		    <input type="text" data-bind="value: lastName" placeholder="Enter your last name" required /><br/>
		    <input id="email" type="email" data-bind="value: email" placeholder="Enter your email" required /><br/>
		    <input type="submit" data-bind="value: (id==0) ? 'Create' : 'Update'" />
	    </form>
	
	    <script src="js/jquery.js" type="text/javascript"></script>
	    <script src="js/jquery.validate.js" type="text/javascript"></script>
	    <script src="js/knockout-3.3.0.js" type="text/javascript"></script>
	    <script src="js/knockout.mapping.js" type="text/javascript"></script>
	    <script>
		    function ViewModel(user) {
			    var self = this;
			
			    var mapping = {
				    'observe': ["firstName", "lastName", "email"],
				    'ignore': ["created"]
			    };				
			
			    self.currUser = ko.mapping.fromJS(user, mapping);
									
			    self.validateAndSave = function(form) {	
				    if(!$(form).validate()) return;
				
				    if (self.currUser.id == 0) {										
					alert("Creating a user");
				    }
				    else {								
					    alert("Updating a user");	
				   }				
			    };		
			
		    };
		
		    var user = {
			    id: 1,
			    firstName: 'Mike',
			    lastName: 'Wilson',
			    email: 'mike@notar.com',
			    created: '2014-10-12'
		    };
		
		    var viewModel = new ViewModel(user);
		    ko.applyBindings(viewModel);		
		
	    </script>	    
    </body>
    </html>
	

When I clicked submit button, post it successfully and the jQuery.validation works well, then I change the content of form to make it invalid and submit again, the jQuery.Validate does not work and it always submit successfully. 
	
I know it is reasonable generally, but if I saves the form and do not want to close window, this looks like abnormal.
	
I tried to debug it, and it seem to do thing with Knockout. I think I shouldn't ask here, but I cannot log in the StackOverflow.com, and I can not find jQuery.validate project 。
	
Thank you.

**Comment by mbest** [comment]
This doesn't seems like a Knockout issue. Try here: https://github.com/jzaefferer/jquery-validation

**Comment by mbest** [comment]
Actually your code is incorrect. According the [jQuery Validation documentation](http://jqueryvalidation.org/documentation/), the `validate` function returns an object and so will never be "falsy". What you really need to use is [`valid()`](http://jqueryvalidation.org/valid/).
