### ISSUE TITLE
arrayChange notification should diff on splice when adding and deleting simutaneously

### ISSUE THREAD

**Issue by timmcb** [knockout/knockout#1911]
When adding or deleting with splice the array changes can be calculated with out making a compare.  However, when splice both adds and deletes at the same time this can result in a retained item being sent added and removed edits.  I ran into this with some code where we were using splice.apply to rewrite an entire array.  The work-around is to just re-write the array without splice.

This could be fixed in ko array splice.  If there are items being both added and removed via the splice, then compare the added and removed items to generate the changes to be sent.  This removes the optimization when completely re-writing the array with splice.  However, it still would be faster when using splice to replace a section of a large array.

REPRO:
```
var a = [{ value: "v" }];
var oa = ko.observableArray(a);

oa.subscribe(function (edits) {
    if (edits && edits.length && edits[0].value === edits[1].value) {
        $("#out").text("Incorrect change. Same value " + edits[0].status + " and " + edits[1].status + ".");
    }
}, null, "arrayChange");

$("#out").text("no change");
oa.splice.apply(oa, [0, a.length].concat(a));
```

**Comment by mbest** [comment]
The "retained" items will have a `moved" property, which you can check for.

**Comment by timmcb** [comment]
Thanks.  In this case the added and deleted items do both have moved === 0.  That seems a little odd in that they are both the same value and did not actually move. I can use the moved value to ignore them though.
