### ISSUE TITLE
Adding Polymer library to KnockoutJS app causes "DOM Exception 8" on all browsers but Chrome

### ISSUE THREAD

**Issue by andreinitescu** [knockout/knockout#1913]
Please see
https://github.com/Polymer/polymer/issues/1476

**Comment by SteveSanderson** [comment]
Thanks for the report. If you can track this down to a problem in KO, please let us know. Otherwise I'm afraid this is not likely to get investigated as it's too much of a niche case and doesn't sound like KO is doing something wrong.
