### ISSUE TITLE
Something for the release notes of 3.4.0

### ISSUE THREAD

**Issue by dancras** [knockout/knockout#1915]
Just tested the v3.4.0rc on a large project and an error occurred due to passing `obs.dispose` directly to a callback. The fix was simple enough (`obs.dispose.bind(obs)`) but if the scoping of private members has moved from closure to the object itself it's probably worth mentioning in the release notes so that people can check their code.

**Comment by brianmhunt** [comment]
Thanks @dancras; that's a very good point, and arguably we ought to use a closure or bound function for `dispose` for this reason -- but at the very least note it in the release notes/docs.

**Comment by mbest** [comment]
This would be an issue for other exposed observable and computed methods, such as `peek` or `valueHasMutated`.
