### ISSUE TITLE
Accessing observable property by brackets in binding fails

### ISSUE THREAD

**Issue by pmaselkowski** [knockout/knockout#1916]
Hello!

When accessing object field by brackets syntax, knockout fails with message:

```
Uncaught SyntaxError: Unable to parse bindings.
Bindings value: event{mousedown: app.widget['ms_b'].selectGroup}
Message: Unexpected identifier
```

Example binding which fails:
```html
<a data-bind="event{mousedown: app.widget['ms_b'].selectGroup}"> </a>
```

This works fine:
```html
<a data-bind="event{mousedown: app.widget.ms_b.selectGroup}"> </a>
```

**Comment by mbest** [comment]
You have a typo in your binding. You need to have a colon after `event`.

http://jsfiddle.net/88vjnxrc/

**Comment by pmaselkowski** [comment]
Thank you, you are right. It works as it should.
