### ISSUE TITLE
submit binding doesn't prevent default form submit behavior

### ISSUE THREAD

**Issue by NZhuravlev** [knockout/knockout#1919]
Very annoying bug, form actually tries to do default 'get' action - when you use ko with sammy you get error.

**Comment by mbest** [comment]
It only does the default action if the function you call returns `true`.

**Comment by mbest** [comment]
It's described in the second paragraph of the docs: http://knockoutjs.com/documentation/submit-binding.html

**Comment by NZhuravlev** [comment]
Well, maybe I've mistaken, but: https://jsbin.com/gawuyu/edit?html,js,output

**Comment by NZhuravlev** [comment]
You should also see this: https://github.com/fredkingham/Sammy-knockout-conflict

**Comment by NZhuravlev** [comment]
This is definitely just sammy and knockout conflict, because without sammy everything works fine: https://jsbin.com/cixexe/edit?html,js,output
Sorry for bother I'll try find solution.

**Comment by mbest** [comment]
Knockout doesn't prevent another event handler from running. So that's probably what you're seeing.
