### ISSUE TITLE
Internet Explorer try/finally issue

### ISSUE THREAD

**Issue by HandsomeDan** [knockout/knockout#1920]
There is a try/finally statement in the 'event' binding handler definition that isn't supported by IE6 or IE7 (starting at line 4177 in release 3.4.0).

IE6 and IE7 require a catch statement before a finally statement can be used, as defined by Microsoft here: https://msdn.microsoft.com/library/4yahc5d8(v=vs.94).aspx

**Comment by mbest** [comment]
This isn't correct. Knockout has always supported IE 6 and 7, and the try/finally blocks have always been there.
