### ISSUE TITLE
Anything Equivalent to `Array.prototype.reduce`?

### ISSUE THREAD

**Issue by alayek** [knockout/knockout#1923]
Hi Madam/sir,

I am new to Knockout JS, and I was just playing around with it. 

I faced a situation where I thought I could easily use `Array.prototype.reduce()` on a `ko.observableArray()` object to compute something and pass that as a function argument in `ko.computed()`.

I took a peek at the `ko.util` utility library, but could not seem to find anything there (Ref. https://gist.github.com/hyle/1180607)

I would like to know if this is a conscious choice, or is it going to be available in some future version?

P.S: My English might be a bit weird, please don't mind.

**Comment by mbest** [comment]
You should be able to use `reduce` like this:

```
var arr = ko.observableArray();
arr.push(value1);
arr.push(value2);
var reducedValue = arr().reduce(callback);
```
