### ISSUE TITLE
Documentation about component inheritance

### ISSUE THREAD

**Issue by herbertpimentel** [knockout/knockout#1925]
We look everywhere but most of us can't find any sample about how to implement component inheritance. If docs can provide it as it says in "Components and Custom Elements - Overview"

…can be composed together (nested) or inherited from other components

will be awesome and for sure will help alot of us.

**Comment by jonbnewman** [comment]
I think the 'inheritance' that is being referred to here is the nesting
capabilities to 'pull in' or inherit and render nested components found
within a parent components template. I do not think there is a programmatic
'inheritance' like you are used to with class-based inheritance/etc.

To do that would involve inheritance for the viewModel as well, and in
knockout there is no standard 'viewModel' to do inheritance on, its all
objects at the end of the day so you can do inheritance on those as you
would with any other javascript.

**Comment by SteveSanderson** [comment]
I largely agree with @jonbnewman, and would add that for KO components, there *is* a standard notion of a viewmodel class - most of the [examples show the component viewmodel implemented as a JavaScript prototypical class](http://knockoutjs.com/documentation/component-registration.html#a-constructor-function). In ES2015 you can literally use a standard `class`; in older versions of JavaScript you use a traditional constructor function.

So, your viewmodel classes can inherit from one another following standard JavaScript inheritance techniques.
