### ISSUE TITLE
Why this does not work properly?

### ISSUE THREAD

**Issue by hiredgunhouse** [knockout/knockout#1926]
http://jsbin.com/wovuzifiqa/1/edit?html,js,console,output

If you click on ADD both add and remove functions are called! Why?

**Comment by Mariatta** [comment]
Hi, when you need to pass parameter to the click binding, the syntax is something like this:

data-bind="click: $root.someFunction.bind($parameter)"

as opposed to (what you had)
data-bind="click: $root.someFunction($parameter)"
The latter causes the function to get executed when the element is rendered.


I modified your fiddle like so
http://jsbin.com/bicuxayugo/1/edit?html,js,console,output

Notice the changes in removeExtraPause function .

**Comment by brianmhunt** [comment]
An alternative is to use Michael Best's excellent ko.punches library, in which case you can do:

```html
data-bind='on.click: $root.someFunction($parameter)'
```

... which will work as expected.

Closing this as it does not appear to be an issue in KO itself, but please let me know if I'm mistaken and we can reopen!

Cheers

**Comment by hiredgunhouse** [comment]
@Mariatta thank you :)

**Comment by hiredgunhouse** [comment]
@brianmhunt thanks for suggestion, yep, that's been PEBKAC :)

**Comment by stormpat** [comment]
As an alternative, when passing arbitrary params to a function you can also return a function, then its not evaluated before the user actually clicks the button/element bound.

e.g.

```html
<button data-bind="click: myClickHandler('first', 'second', 'third')">
  click
</button>
```

```javascript
// inside the viewModel
this.myClickHandler = function(a, b, c) {
  return function() {
    console.log(a, b, c);
    // logs when clicked => first second third
  }
}
```

**Comment by IanYates** [comment]
I've taken to using Underscore's partial function a bit in my views

`data-bind="click: _.partial(vmFunc, paramA, paramB, ...)"`

Useful when you've got a couple of nested for loops and some other view model levels aliased so it ends up being like

`data-bind="click:_.partial($vmMain.openPatient, $row, $col)"`
