### ISSUE TITLE
Get calling function name from called function

### ISSUE THREAD

**Issue by jakubklekota** [knockout/knockout#1929]
Hello,
Is it possible get calling function name from called function ?

Example:

In html:
```
data-bind="click: function() { postViewModel.addComment($data, $('input.add-comment').val()); }"
```

In knockoutJs view model:

```
    self.addLike = function (post) {
        console.log('Inside function', ....); //How get function name ?
    };
```

Thanks for help :)!

**Comment by vamp** [comment]
I think that your question is not correct, but I will try to help:

```click: function(data, e){ postViewModel.addComment(data, e); }```
and
```function addComment(data, e){
      console.log(e.type); /* click */
}```

**Comment by mbest** [comment]
Thanks, @vamp.
