### ISSUE TITLE
What is the behavioural difference between ko.toJSON and JSON.stringify with appropriate resolver?

### ISSUE THREAD

**Issue by cervengoc** [knockout/knockout#1930]
I've met with an earlier issue #867 where someone pointed out that it's a viable alternative to use JSON.stringify with an appropriate resolver function instead of the knockout toJSON function. The appropriate resolver function would unwrap the unwrappable members during serialization, very similarly to ko.toJSON.

As far as I've checked, every browser fully supports JSON.stringify and JSON.parse from IE8, which is I think quite wide range.

According to my tests, the performance difference is more than noticable, and I actually couldn't mimic a scenario where the two would have given different results.

In that issue, noone actually wrote what the behavioural difference is between the two implementation, and why it's preferrable to use one or the other. Could someone please write a few thoughts about it? I'm considering to switch to JSON.stringify, but would like to be careful.

**Comment by vamp** [comment]
Yep, "someone" pointed. You can use next piece at your own risk (but I will suggest to use it):
```
    // check compatibility.
    if (typeof (JSON) !== "undefined" && JSON.stringify({ toJSON: function () { return 1; } }) === "1") {
        ko.toJSON = function (value, replacer, space, usePeek) {
            var previousValue = ko.options.jsonUsePeek;
            ko.options.jsonUsePeek = usePeek;
            try {
                return JSON.stringify(value, replacer, space);
            } finally {
                ko.options.jsonUsePeek = previousValue;
            }
        };

        ko.subscribable.fn.toJSON = function () {
            return (ko.options.jsonUsePeek ? this.peek : this)();
        };
    }
```

**Comment by cervengoc** [comment]
Thanks for the feedback @vamp, and really sorry for being rude and not quoting your name, I was just lazy to check back.

I would prefer using a local resolver function because I have more complex logic for filtering out several fields, etc.

But still I would like to know what the exact difference is between this, and the native implementation. What are the advantages/drawbacks of each, and what could be a scenario where the two would give different result?

**Comment by vamp** [comment]
The main difference - only performance (native JSON works faster) + if you don't need to create dependencies when converting to JSON - you can set ```ko.options.jsonUsePeek = false```

**Comment by SteveSanderson** [comment]
@vamp Thanks for addressing this.
