### ISSUE TITLE
Bindings to add/enhance

### ISSUE THREAD

**Issue by mbest** [knockout/knockout#1932]
For the next Knockout version, I've been thinking that it would be good to include some new, small bindings, and improve some of the existing bindings. Here's what I have so far:
1. ~~Add [`let`](https://github.com/knockout/knockout/issues/1792#issuecomment-102147201) for simple aliasing.~~
2. ~~Add [`class`](https://github.com/knockout/knockout/issues/1710#issuecomment-76276624) as an alias of `css` to support combined dynamic/static classes. (#1710 and #1953)~~
3. ~~Fix $rawData within `with` bindings and rendered templates (the code in #1415 isn't optimal, but we can come up with a new implementation)~~
4. ~~Add [`withlight`](https://github.com/knockout/knockout/pull/1206#issuecomment-28525020) as a lightweight alternative to `with`. Possibly we could name it `with2`. (#1811)~~
5. (on hold) Add `afterRenderAll` and `beforeRenderAll` callbacks to `foreach` binding. (see #690 and #1856.)
6. Add [`date`](https://github.com/knockout/knockout/issues/369) (maybe; this could be more complex).
7. Support [warnings for unused bindings](https://github.com/knockout/knockout/issues/1786#issuecomment-157892917) as an option.
8. Support [html5 tristate checkboxes](https://github.com/knockout/knockout/issues/1649).
9. Make `textInput` work on any `contenteditable="true"`. (#1598)
10. ~~`checked` binding should use `checkedValue` if present when not bound to an array (#1899)~~

**Comment by brianmhunt** [comment]
I think all these would be great, @mbest.  Thanks for putting the list together.

Another binding we might consider would be something like a `transitionEnd` event binding that triggers when a child element completes a CSS animation, as [it's done in Bootstrap](https://github.com/twbs/bootstrap/blob/master/js/transition.js#L16).

I think it would be nice to see better error handling ala #1628.

What do you think about merging [fast-for-each](https://github.com/brianmhunt/knockout-fast-foreach)? (re. #1730 et al)

Are we still on for merging the gulp toolset?

**Comment by vamp** [comment]
with2 - maybe 'using'?

**Comment by mbest** [comment]
I like `using`. Thanks for the suggestion.

**Comment by mbest** [comment]
> I think it would be nice to see better error handling ala #1628.

It seems promising. It looks like there's a little more to do to get it ready--resolving the possible conflict with `ko.onError` and making it pass the build test. Also we just got a request for taking a kind of opposite approach: #1955.

> What do you think about merging fast-for-each? (re. #1730 et al)

I haven't had much time to look at it, but `foreach` is always a good candidate for improvement.

> Are we still on for merging the gulp toolset?

I'm willing to help get it done if we can do it in a step-by-step process. For reference, look at what I did for the deferred updates feature, where I broke it down into three parts, each of which was a complete feature.

**Comment by brianmhunt** [comment]
> I'm willing to help get it done if we can do it in a step-by-step process. For reference, look at what I did for the deferred updates feature, where I broke it down into three parts, each of which was a complete feature.

Did you see #1868?  I'm not sure how else we could break it down.

**Comment by mbest** [comment]
> I'm not sure how else we could break it down.

I mean to have separate PRs for each feature. The first one would probably be "Replace Grunt with Gulp".

**Comment by MrFrankel** [comment]
Hey, Id really like to be able to contribute one of these enhancements, maybe beforeRenderAll&afterRenderAll? what is the status of this, on hold? I saw several threads regarding this though non that had any final conclusion.

**Comment by mbest** [comment]
@MrFrankel Thanks for the offer. If you have something to add to the discussion on that feature, it would be best to do so in #1856.
