### ISSUE TITLE
'deferUpdates', 'with' binding, new VM, and a validation extender - recursion

### ISSUE THREAD

**Issue by petemill** [knockout/knockout#1934]
When using the latest version of knockout, v3.4 with knockout-validation v2.0.3, I get some crashes due to infinite recursion. I have narrowed it down to the following case, where a with: binding instantiates a new VM object containing an observable with a validation extender. The problem does not happen when the validation extender is removed. Apologies for cross-posting the issue to both knockout-validation and knockout, but I thought it's worth posting here too in case it's an issue requiring exploration in the core.

HTML:
```html
<div data-bind="with: EditableRepVM($data)">
  <p data-bind="text: Name"></p>
</div>
```

JS:
```javascript
ko.options.deferUpdates = true;
class ViewModel {
  constructor(){
    
  }
  
  
  EditableRepVM(nonEditableData) {
    
    console.debug('EditableRepVM called');
    var newItem = {
    };
    newItem.Name = ko.observable('default name').extend({required: true});
    return newItem;
  }
}
ko.applyBindings(new ViewModel());
```

With the above, console output is:
```
EditableRepVM called
EditableRepVM called
EditableRepVM called
...
Uncaught Error: 'Too much recursion' after processing 5000 task groups.
@ processTasks	@	knockout-debug.js:1081
```

When removing the validation extender, 'EditableRepVM called' is only logged once, as expected and the page does not crash.

Here is a codepen demonstrating this case. Remove the commented code to experience the issue:
http://codepen.io/petemill/pen/GpaPOO?editors=101

**Comment by petemill** [comment]
After some digging, I'm guessing that the `with` binding's function value is being re-evaluated perpetually for some reason, due to the extender's subscription on a value inside the result of that function. When using the [`withlight`](https://github.com/knockout/knockout/pull/1206) binding (which I noticed looking at #1811, this doesn't occur. Is this expected or something that should be looked in to and fixed?

Example using `withlight` binding:
http://codepen.io/petemill/pen/pjmqxX?editors=101

**Comment by mbest** [comment]
The problem comes from the `addRule` method in knockout-validation that reads the `rules` observable and then modifies it. It can be fixed by using `peek` when reading the observable.

**Comment by mbest** [comment]
Your `withlight` binding isn't capturing all the dependencies and so doesn't update. A more correct `withligth` will show the same problem as `with`.

```javascript
ko.bindingHandlers.withlight = {
    init: function(element, valueAccessor, allBindings, viewModel, bindingContext) {
        var innerContext = bindingContext.createChildContext(valueAccessor);
        ko.applyBindingsToDescendants(innerContext, element);
        return { controlsDescendantBindings: true };
    }
};
```

**Comment by petemill** [comment]
Thanks for the response @mbest , I think I get it with regards to the dependency tracking, and can confirm what you're saying [with a lighter test case](http://codepen.io/petemill/pen/epwZKg?editors=101). The with binding is creating a subscription on any observables it reads within the function it calls, which is only showing a recursion problem with `deferUpdates` on but is probably a problem with it off too, just not initially apparent (if, for example in this case, the validation rules changed, the entire `with` binding would be re-evaluated, losing data. I can _fix_ it, using the normal `with` binding by [wrapping the binding value with `ko.ignoreDependencies`](http://codepen.io/petemill/pen/GpaPOO?editors=101). The subscriptions and observables created within that function still fire as intended and the `with` binding is not re-evaluated when that happens.

I'm just wondering whether a) my assumptions about how this is working is correct and b) that the `with` bindingHandler should be doing something different to prevent this, or if it's up to the user to work out whether they need to use `ko.ignoreDependencies` or `peek` inside constructor functions and the like (or even a lighter `with` binding that does not perform dependency tracking.

**Comment by mbest** [comment]
I think it's not a normal use-case to create a viewmodel in the `with` binding. For your use, it seems fine to use something like your version of `withlight` that doesn't track the dependencies since you want a one-time binding only.

**Comment by petemill** [comment]
thanks @mbest . FYI, I've done this in the past mostly when creating a set of new observables to allow the user to edit some values without affecting the originals until the user saves (or cancels) the edit operation.

**Comment by mbest** [comment]
I'm glad I could help. I'll close this since it's not specifically a problem with Knockout and there are various ways to work around the problem.
