### ISSUE TITLE
Infinite loop in circular computeds

### ISSUE THREAD

**Issue by juuxstar** [knockout/knockout#1943]
It looks like computeds are prone to a circular dirtying loop as demonstrated by:

```
ko.options.deferUpdates = true;
a = ko.observable();
b = ko.computed({ read : function() { a(); return d(); }, deferEvaluation : true });
d = ko.computed({ read : function() { a(); return b(); }, deferEvaluation : true });
d();
a('something');
```

This will crap out with a "Maximum call stack size exceeded".  Looks like it's not the evaluation of them but the scheduling for re-evaluation,

Tested with KO 3.4.

https://jsfiddle.net/ye0b2p0w/10/

**Comment by juuxstar** [comment]
I believe the old stand-alone deferred library had a `clearDuplicate` method that dropped duplicate computeds from the refresh task queue.

**Comment by vamp** [comment]
@juuxstar, good catch!
PS: as quick fix - disable deferUpdates

**Comment by mbest** [comment]
So until this can be fixed, you can't use deferred updates with computed observables that depend on each other in a circular loop.

**Comment by juuxstar** [comment]
Thanks for the quick response and suggestions guys.

Disabling deferred updates is a large performance hit in a non-trivial app though and it's not always possible to figure out how computed observable depend on each other.  Again, in a non-trivial app with many computed observables, large non-obvious loops can form and it's hard to figure out how to break the loop.

I'm going to create a fork and attempt a quick fix to the scheduler by checking first if the given callback has already been scheduled on the tasks queue to prevent duplicates (essentially the same solution from the original knockout deferred library).

**Comment by mbest** [comment]
Sounds good, @juuxstar. Here's the code you'll likely want to play with: https://github.com/knockout/knockout/blob/master/src/subscribables/extenders.js#L52

**Comment by juuxstar** [comment]
Hmm, so the above PR helps but it doesn't quite pass all the tests.  I'm not familiar enough with how the task queue is suppose to work to see what the problem is.  Any ideas why the tests are failing?

**Comment by krnlde** [comment]
My 2 cents: require.js solves its circular dependencies by saving all the values in a map to decouple the values from the actual variables/implementation. Could this approach be applied here?

**Comment by maskmaster** [comment]
Any large project is probably going to have circular dependencies between computeds.

This issue is currently stopping us from using deferred updates and is probably a reason other larger projects have problems with enabling it globally. #1758 tries to address migration problems, but this is something that really could enable migrations. This issue should imho have higher priority.

**Comment by mbest** [comment]
Thanks for reminding us of this problem, @maskmaster. I'll add it to the 3.5 milestone and take a look at it soon.
