### ISSUE TITLE
Maximum call stack size exceeded  with nested components and inner $componentTemplateNodes

### ISSUE THREAD

**Issue by straeger** [knockout/knockout#1952]
Hello we currently facing a problem with a constellations of custom components.
Example: we have 2 components a and b registered as ko.components. 

Component a is a standard component which is rendering some markup and is using virtual template handler to render the outer nodes.

component a:
```
<div>
   <span>inner of a before templ</span>
    <!-- ko template: { nodes: $componentTemplateNodes, data: $data } --><!-- /ko -->
    <span>inner of a after templ</span>
</div> 
```

component b is using component a and inside of a using the  $componentTemplateNodes  to render the outer nodes
component b:
```
<div>
    <span>inner of b before templ</span>
    <a> 
        <!-- ko template: { nodes: $componentTemplateNodes, data: $data } --><!-- /ko -->
    </a>
   <span>inner of b after templ</span>
</div>
```

The Problem here is that component a is rendering the outer nodes. That is fine and works but if a is nested in b and has also component nodes whicht should be rendered. Component a is rendering the inner nodes of a in component b with the componentTemplateNodes of b. 

That just hurts my brain. I would really appreciate some recommendations on how to nest components and arrange the rendering of outer nodes in a more complex example.

I have create a small jsfiddle example which results an the  "Maximum call stack size exceeded " case to illustrate this problem.
http://jsfiddle.net/straeger/gk3y4gLb/2/

**Comment by mbest** [comment]
You don't need multiple components to duplicate this.

html:
```
<x-a>
    <!-- ko template: { nodes: $componentTemplateNodes, data: $data } --><!-- /ko -->
</x-a>
```

component `x-a`: 
```
<div>
    <span>inner of a before templ</span>
    <!-- ko template: { nodes: $componentTemplateNodes, data: $data } --><!-- /ko -->
    <span>inner of a after templ</span>
</div>
```

http://jsfiddle.net/mbest/gk3y4gLb/3/

**Comment by straeger** [comment]
Ah, ok... yes your example is working. But doesn't fit to my use case.
Please let me explain my use case a little better:

this is a working example which matches the use case.
http://jsfiddle.net/straeger/gk3y4gLb/11/

This is the same example but the x-button-list component extend the bootstrap btn-group markup to inlcude a extra row with the x-row component. And we get the error. 
http://jsfiddle.net/straeger/gk3y4gLb/13/

It would be really great to have the option to include other components in component to reuse them this way.Or am I wrong this way is an antipattern? If this is an antipattern this should be added to the documentation.?!

**Comment by mbest** [comment]
I haven't looked at your latest example yet, but I thought of another similar issue that may include some help: #1824.

**Comment by straeger** [comment]
ok, I think we have solved this issue. We saved the componentTemplate nodes another way.
The advice to use parentcontext is only usable if you know the position of your compoment. 

Thanks for the fast answer! Btw great work !
