### ISSUE TITLE
Feature Request: Asynchronous foreach loop

### ISSUE THREAD

**Issue by krnlde** [knockout/knockout#1954]
My usecase is drawing a very large amount of dots in an SVG scene, which works perfectly together with ko. Understandably ko has troubles looping >1k elements in one event-loop. My suggestion would be to have an extension to the original (synchronous) foreach loop, like `async: true`, or to create an `asyncforeach` bindingHandler. You can also have a parameter `bulksize` which provides the number of iterations per event-loop. the rest of the list would then be deferred to the next event loop via `setTimeout`, `setImmediate` or `requestAnimationFrame`.

Any comments on this? I could provide the basic async foreach, but I am not able to couple it with ko's truly complex template-foreach loop in https://github.com/knockout/knockout/blob/master/src/templating/templating.js#L9

Here's an example implementation of an eventloop-friendly foreach.

```javascript
var asyncforeach = function (array, cb) {
  bulkSize = 10;
  var firstIndex = parseInt(Object.keys(array).shift(), 10);
  var lastIndex  = parseInt(Object.keys(array).pop(), 10);
  var start = firstIndex;

  (function nextBulk() {
    var i;
    for (i = start; i <= Math.min(lastIndex, start + bulkSize - 1); i += 1) {
      cb(array[i]);
    }
    start = i;
    if (start < array.length) setTimeout(nextBulk, 0);
  })();
}
```

**Comment by brianmhunt** [comment]
@krnlde You might be interested in [knockout-fast-foreach](/brianmhunt/knockout-fast-foreach)

If that works, feel free (but not obliged) to close this issue.

See also #1730

**Comment by krnlde** [comment]
Thanks for your quick response @brianmhunt ! Your lib looks promising. The code is well written and implemented asynchronously via `setTimeout`, But: I implemented it but still can feel a jank on large objects. You can see it in the [example page](http://output.jsbin.com/dakihezega/2) when activating the fastForEach with 5k elements. There is a 1-2 sec jank where the browser doesn't respond. Any ideas?
