### ISSUE TITLE
Feature request: Optionally remove try / catch for binding parsing 

### ISSUE THREAD

**Issue by hlascelles** [knockout/knockout#1955]
There is a try/cach around [this section of code](https://github.com/knockout/knockout/blob/281e195eeae633d5f62f2fe08a8790506682bbb1/src/binding/bindingAttributeSyntax.js#L368)

I can see why it's there, but we prefer to debug in a chrome debugger. The "break on caught exceptions" feature is not possible as other plugins (for better or worse) use exceptions as usual control flow.

Can we make the try / catch optional? If you agree, I can make it a PR.

**Comment by IPWright83** [comment]
I'm assuming this bit of code is why a bad binding handler can silently cause Knockout templates to not look how you expected them to. I've come across that multiple times and it's actually really annoying to try and diagnose, so I'd definitely +1 this.

**Comment by brianmhunt** [comment]
Would I be correct in thinking this would be solved by way of #1628?

**Comment by IPWright83** [comment]
Would certainly solve the problems I've had - yeah

**Comment by mbest** [comment]
Notice that the `catch` section re-throws the exception. So it shouldn't make anything fail silently.

**Comment by hlascelles** [comment]
Good point... That's true, and certainly useful for prod error reporting tools. My use case (here) is being able to use the chrome debugger to allow it to automatically pause on uncaught exceptions *in the binding* so you can hover over the $data and $binding values etc to do more analysis.

In that respect, I think https://github.com/knockout/knockout/pull/1628 may cover us, thanks! It looks like it contains all the variables I'd look for normally.

**Comment by hlascelles** [comment]
I suppose this can be closed... if https://github.com/knockout/knockout/pull/1628 is being taken under serious consideration?

**Comment by brianmhunt** [comment]
Hi @hlascelles I'll close this up on the basis that #1628 will make it in, or in any case is the proper place for discussion!  I trust that's alright, but let me know if you think I've missed the mark, so to speak.

Cheers :)
