### ISSUE TITLE
Fieldsets causes ReferenceError in Chrome iOS

### ISSUE THREAD

**Issue by esbenp** [knockout/knockout#1959]
The following code causes error `ReferenceError: Can't find variable: fieldset` in Chrome iOS (47.2526.70). I have only tested this on an iPad mini. The reason why I am outputting the error in the DOM is that Chrome iOS have no debug tools.

```javascript
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
  </head>
  <body>

    <div id="app">
      <fieldset></fieldset>

      <div data-bind="foreach: errors">
        <div data-bind="text: $data"></div>
      </div>
    </div>

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/knockout/3.4.0/knockout-min.js"></script>
    <script type="text/javascript">
    var viewmodel = function() {
      this.errors = ko.observableArray();

      var self = this;
      window.onerror = function(message, url, line, column, error) {
        self.errors.push(message);
      }
    }

    ko.applyBindings(new viewmodel(), document.getElementById('app'));
    </script>

  </body>
</html>
```

**Comment by mbest** [comment]
Can you try this with older versions of Knockout, so we can possibly narrow down the issue?

**Comment by esbenp** [comment]
I have tested and the issue does not exist in Safari. 

It exists in (taken from https://cdnjs.com/libraries/knockout/)
* 3.4.0
* 3.3.0
* 3.2.0
* 3.1.0
* 3.0.0
* 2.3.0-rc
* 2.3.0-pre
* 2.3.0
* 2.2.1
* 2.2.0
* 2.1.0
* 2.0.0
* 1.2.1 (don't know about this one, the script did not seem to work at all)

**Comment by oising** [comment]
I have the exact same issue. It seemed like a bug in Chrome, so I went looking:

https://code.google.com/p/chromium/issues/detail?id=570095&q=fieldset&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified

It was just logged three hours ago...

**Comment by brianmhunt** [comment]
Thanks @oising!  Anyone have any ideas on workarounds?

**Comment by oising** [comment]
@brianmhunt No idea -- it seems so fundamentally broken that the mere existence of a fieldset element on the page causes DOM actions to fail. Look at the repro on the Chromium issue... it's as simple as you can get... :(

**Comment by weigruf** [comment]
This error usually happens when a (anonymous) function/method expects a string parameter but you pass a variable. Might be the case here as well.

**Comment by oising** [comment]
@weigruf See my previous post - it's a bug in chrome 47 for iOS. It's iOS only because that platform doesn't use the new Blink engine.

**Comment by weigruf** [comment]
@oising Yes, thanks for the link. I am saying that maybe this is happening on the actual browser not in our codebases :)

**Comment by oising** [comment]
Apparently there's a workaround: The bug only manifests when the fieldset elements are not within an enclosing <form>. 

https://code.google.com/p/chromium/issues/detail?id=570095#c9
