### ISSUE TITLE
HTML binding behaves quite differently than innerHTML.

### ISSUE THREAD

**Issue by ladjzero** [knockout/knockout#1964]
```
<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8">
    <script src="knockout.js"></script>
</head>

<body>
<p data-bind="html: body"></p>
<p id="purejs"></p>
</body>

<script>
var content = "<td>hello</td><span>world</span>";

var model = {
    body: content
};

ko.applyBindings(model, document.body);

document.querySelector('#purejs').innerHTML = content;
</script>

</html>
```

![2015-12-19 10 28 18](https://cloud.githubusercontent.com/assets/4110311/11913479/dfd65a80-a69f-11e5-8509-648b99b6325e.png)

Quite strange. Does ko validate the input string and reject the second span?

**Comment by ladjzero** [comment]
The version is 3.3.0

**Comment by ladjzero** [comment]
The version is 3.3.0

**Comment by simonmurdock** [comment]
You've not shown the contents of the tags in your screenshot. You seem to have no table element either

**Comment by ladjzero** [comment]
Screenshot updated.


![2015-12-19 10 52 05](https://cloud.githubusercontent.com/assets/4110311/11913599/fab12a8e-a6a3-11e5-8549-7769cc60a161.png)

**Comment by mbest** [comment]
Knockout parses the HTML first and then inserts the nodes. If the first node is a `<td>`, the HTML is treated as a set of table cells.

**Comment by ladjzero** [comment]
Knockout parses and validates HTML. Closed.
