### ISSUE TITLE
question about syntax {{}}

### ISSUE THREAD

**Issue by jlaustill** [knockout/knockout#1967]
This is more of a feature discussion request than an issue, if this isn't the place for it, I'll be more than happy to move it to another venue, I'm just not sure where else that would be.

I'm trying to explore different MVC frameworks for a new project at work.  I've got it down to either angular or knockout.  My only real hangup with ko is having to wrap everything in one binding.  Is there a way, or is it possible anyway to use handlebar like syntax in ko?  Here's what I'm referring to.

In angular you can just do something like
```
    <div>This is some {{style}} text</div>
```
And it preparses that out for you.  It seems like in ko I have to wrap everything I bind in an element and use a data-bind, something like
```
    <div>This is some <span data-bind="text: style"></span> text</div>
```
It would also be great to be able to use this style binding for attributes, I find using the data-bind attr thing just messy and I can't even imagine having to teach that to my other devs.  
```
<a href="{{link}}">Go away</a>
```
vs something like
```
<a data-bind="attr : { href : link }">Go away</a>
```

Am I missing something in ko that would allow me to use the same kind of syntax?  I looked at handlebars.js, it uses the same syntax, but requires templating, which seems like to much.  I just want to sprinkle my data elements from my model decoratively in my views.  I'm super new to knockout, so if I'm missing something obvious from the docs or past conversations on this topic, I would love to just be pointed to them.

I am not opposed to using a 3rd party library along side ko either, I'm just not sure what exists and I'm hoping other people have thoughts on this.

Thanks y'all!

**Comment by jonbnewman** [comment]
What you are looking for is Knockout Punches: https://mbest.github.io/knockout.punches/

**Comment by jlaustill** [comment]
Oh this looks like EXACTLY what I had in mind!  Thank you a ton!  I'll be going over this in depth tonight for sure.

**Comment by brianmhunt** [comment]
Thanks everyone for the post.  Unless I am mistaken, I believe this is answered – please let me know if otherwise, though, and we can reopen!

**Comment by jlaustill** [comment]
Yes Brian, this is closed indeed.  Thanks again Jon, I have gone over this pretty in depth at this point and find it to be a great solution and strike a pretty awesome balance.  I'm excited to see where these two projects head in the future, good stuff.
