### ISSUE TITLE
Update Custom Component When Model Observable Updates

### ISSUE THREAD

**Issue by someyoungideas** [knockout/knockout#1968]
I am wondering if it is possible for a custom component's observable param to update itself if the observable is updated in the view model? For example, if i update the text from the plain observable binding could it update the custom component value.

[JSFiddle](http://jsfiddle.net/someyoungideas/8pL4b880/1/)

**Comment by IanYates** [comment]
Sure.  Keep it as an observable rather than unwrapping the observable.

See http://jsfiddle.net/r7mqsy3z/

The key change is line 3 now being `this.text = params.initialText || ko.observable('');`

**Comment by someyoungideas** [comment]
:+1:
