### ISSUE TITLE
foreach-binding calls functions in array

### ISSUE THREAD

**Issue by Epaminaidos** [knockout/knockout#1969]
Hi,

I just stumbled upon an issue with the foreach-binding:
If the array contains a function, the function will be executed by the binding.

html:

    <ul data-bind="foreach: values">
      <li data-bind="text: toString()"></li>
    </ul>

javascript:

    var model = {
    	values: [function(){ 
            alert("Why is this called?");
        }]
    };
    ko.applyBindings(model);

The alert-box should not pop up, since I do never call the function. But as you already guessed, it does pop up.

Please find the jsFiddle here: https://jsfiddle.net/g4herjoe/3/

**Comment by mbest** [comment]
When using the `foreach` binding, each entry becomes a child viewmodel. Knockout considered a function given for a viewmodel to be an accessor for it (a function that returns the viewmodel).

**Comment by Epaminaidos** [comment]
Are you saying that this is expected behaviour? Or are you confirming that this is an issue?

**Comment by mbest** [comment]
Yes, it's expected. Perhaps if you need to iterate over functions, you could use the Repeat binding (https://github.com/mbest/knockout-repeat).

**Comment by Epaminaidos** [comment]
IMO, this is rather strange behaviour, since most other bindings do not behave like that.
e.g.: I cannot use the text-binding to bind against a function's value.
https://jsfiddle.net/qzpw80hj/

Is there any real-world use-case for that that does not apply to other bindings?

**Comment by mbest** [comment]
Any other binding that sets up a new context (`with`, `template`) will behave the same.
