### ISSUE TITLE
Knockout JS Click binding not working as expected? Unable to pass string

### ISSUE THREAD

**Issue by vans163** [knockout/knockout#1971]
click: alert
Empty Alert. OK

    click: function() {alert()}
Empty Alert. OK

    data-bind="click: function() {alert('test')}"
Nothing. FAIL

    click: function() {$data.custom(0,0)}
Called. OK

    data-bind="click: function() {$data.custom(0, \"whyfail\")}"
Nothing. FAIL

Can someone explain why it works like this

**Comment by mbest** [comment]
Remember that the data binding is part of HTML. So it should be

    data-bind="click: function() {$data.custom(0, &quot;whyfail&quot;)}"

**Comment by vans163** [comment]
Thank you that was the problem. I am sure someone else will ask this in the future.
