### ISSUE TITLE
Deferred dependency tracking issue

### ISSUE THREAD

**Issue by jeremyVignelles** [knockout/knockout#1975]
Hi,
I have an issue with  the dependency tracking system.

I stripped down the issue and here is the fiddle : https://jsfiddle.net/ntvco4h5/

Expected result : a green square
Got result: a red square
`vm.style()` returns 'error' whereas `vm.is1()` is true.

If I use `if:show2` instead of `if:show` (the same, but with swapped conditions, which I can't do in my real application), the green square is displayed as expected.
Removing `ko.options.deferUpdates = true;` also works as expected.

How can I solve this?

**Comment by brianmhunt** [comment]
Thanks @jeremyVignelles – It definitely looks like something has gone awry here.  The relevant bit of code is:

```javascript
    ko.options.deferUpdates = true;

    var vm = {
        value: ko.observable(0),
        is1: ko.pureComputed(function() {
            return vm.value() == 1;
        }),
        style: ko.pureComputed(function () {
            return vm.is1() ? 'ok' : 'error';
        }),
        show: ko.pureComputed(function() {
            return vm.value() > 0 && vm.is1();
        })
    }

    ko.applyBindings(vm);

    vm.value(1);
    ko.tasks.runEarly();
    vm.value(0);
    ko.tasks.runEarly();
    vm.value(1);
```

I noticed that when `deferredUpdates = false` the problem does not occur.  It also does not occur when `show` has `return true` (i.e. is not dependent on `vm.value` or `vm.is1`).

@mbest Does this look like an issue with deferred updates?

**Comment by jeremyVignelles** [comment]
Thanks for your consideration, I've been struggling with this for a day.
From my experiments, I can add some details:
- Subscribing to vm.style makes the problem go away : https://jsfiddle.net/ntvco4h5/1/
- I was unable to reproduce the issue with only `subscribe()` methods. Maybe I'm not doing it the way it's implemented in bindings. I suspect something wrong with bindings inside `if`
- The original issue was with asynchronous updates (user actions and AJAX), for simplicity, I used `runEarly` instead, which has the same behavior

As you have done, I paste the HTML code here for convenience:
```<div data-bind="if:show">
    <div data-bind="attr:{class:style}"></div>
</div>```

**Comment by mbest** [comment]
@jeremyVignelles Thanks for reporting this and providing a concise and informative example. I've uploaded a fix, eb880656a8da.

**Comment by mbest** [comment]
I've now added a lower-level test for this and updated the fix to minimized re-evaluations (only update the computed version if its value has changed).

**Comment by IanYates** [comment]
It's a small change to the code but welcome :)

Do you think there might be a new KO release in the coming days, such as 3.4.1 perhaps?  I still haven't turned on deferred updates since a lot of things broke for me when I first tried the back in the early 3.x days and then again with 3.4.  However I could also have been hitting issues like this I supose.  I'll try again later in the week using the .debug version of KO and patching it myself but if you're looking to do a patch release I'll just wait until then instead.
