### ISSUE TITLE
Pass html string to ko.renderTemplate instead of template id

### ISSUE THREAD

**Issue by helcoder** [knockout/knockout#1976]
Hi there, simple question. Is it possible to pass html string or nodes array to ko.renderTemplate instead of template id? Couldn't find any info on that. My attempts of doing that didn't give desirable effect.

**Comment by mbest** [comment]
No, you can't. But you could extend Knockout by creating a new template source object and overriding `ko.nativeTemplateEngine.makeTemplateSource`.

**Comment by helcoder** [comment]
Sorry, I couldn't find any info on what you've said. Could you please provide an example of doing this?
