### ISSUE TITLE
When no "()" in binding function/callback [3.2.0], then knockout binding doesn't work at all

### ISSUE THREAD

**Issue by alundiak** [knockout/knockout#1978]
I have knockout `3.2.0`
And I'm using https://github.com/brianmhunt/knockout-secure-binding (`v0.5.1` - 2014-10-07)
I follow docs [The "click" binding](http://knockoutjs.com/documentation/click-binding.html) to setup click binding.
My code:
```html
<a target="_blank" href="#" 
 data-bind="
  attr: {href: downloadReportURL()}, 
  click: setInProgress, 
  enable: enableDownloadButton()">Download</a>
```

```js
this.inProgress(false); // simple observable

this.downloadReportURL = ko.observable(''); // simple observable

this.setInProgress = function(){ // simple function
    this.inProgress(true);
}.bind(this);

this.enableDownloadButton = ko.computed(function(){  // computed function
   return !this.inProgress() && !!this.downloadReportURL();
}, this);
```

Then as result, **Knockout kind stuck on click binding**:
- `href` is set,
- `setInPogres()` function is executed, but `click` simply doesn't work (clicking on hyperlink causes NOTHING), feels like preventedDefault executed
- `setInPogres()` function is executed, but computed function `enableDownloadButton ` doesn't see change of observable `inProgress`.
- `enable` binding doesn't work, because after changing `inProgress()` computed function should have been executed, but not
- [reproduced not always] If I change `click: setInPogress` and put it as first in binding seqeunce, then all functions after (right) it will not work. All left binding functions will work.

So when I change code to this: `click: setInProgress()` - adding `()` everything works fine - NATIVE A HREF work as expected, **but click binding doesn't work as expected**, as I understand from docs.

*UPD*:
When I change my HTML code from `A` to `BUTTON`:
```html
<button data-bind="
 click: setInProgress, 
 attr: {href: downloadReportURL}, 
 enable: enableDownloadButton()">Download</button>
```
`click` binding works, `href` binding can not be applied and `enable` binding works.
But it's not what i needed. :)
**So looks like, Knockout Binding behaves differently, when control element is `A`**

**Is this kind of bug?** Can someone reproduce/verify with latest Knockout release? (I can't for now)/
Are docs up to date?

My Secure binding settings:
```
ko = require('knockout');
require('knockout-secure-binding');
ko.bindingProvider.instance = new ko.secureBindingsProvider({
  attribute: 'data-bind'//,        // default "data-sbind"
  //globals: window,               // default {}
  //bindings: ko.bindingHandlers,  // default ko.bindingHandlers
  //noVirtualElements: false       // default true
});
```

PS1. Interesting, that this approach - with NO `()` in function WORKS fine with Knockout v `2.3.0` (I have codebase of my old application, and it still works)

PS. This behavior was reproduced by me time ago also with another code, and it was 3.2.0 version also. No ability to provide steps and code, but behavior was the same - using `()` or not using, but binding WAS not click and was not `A/BUTTON` question.

FYI @mbest @brianmhunt

**Comment by mbest** [comment]
Seems like this issue should be reported with https://github.com/brianmhunt/knockout-secure-binding

**Comment by brianmhunt** [comment]
Thanks @alundiak  –  could you be so kind as to copy this over to the knockout-secure-binding repo, and I'll have a look at it and comment there.

I'll close the issue here on the basis that it's a KSB issue (and not something wrong with the Knockout-proper library) –– unless I'm mistaken, in which case we can reopen. :)

Cheers

**Comment by alundiak** [comment]
@mbest I am not so sure. But I can't test simple native knockout app to reproduce such behavior. My current business app is over-security-oriented, so maybe I will try to create some test app at home. 
And yes, @brianmhunt I will do copy of this issue in 2nd repo.

**Comment by alundiak** [comment]
## Initial ideas was
- To have `A` element, and 
- depends on other UI elements compose/combine URL and set to `A` via `data-bind="attr: {href = downloadReportURL}"`
- When href is set I planned to click on `A`, and meanwhile it downloads file (planned to have huge file, so some delay time expected) I wanted to kinda disabled (grayish, etc.)
- In fact that "disabling" planned to be reset by another UI logic (not related to original issue).

So, @mbest  as I mentioned in initial description, **my guess is, that when I provide click data-binding for `A` element, in fact Knockout kinda suppresses default  `A` element click behaviour, and as result such `A` element attribute href is not useful anymore.**

*Maybe it's default Knockout behavior and it was designed so, but I was surprised.*

## JSFiddle example
So, here is my jsfiddle: code is a bit different, and uses ONLY Knockout 3.2.0 (debug) and no KSB.
http://jsfiddle.net/landike/9emtsnaa/37/

![image](https://cloud.githubusercontent.com/assets/2131633/12464885/a88f367e-bfcb-11e5-96e1-d89c58337427.png)

## Use cases: (based on jsfiddle example)
**Case 1**:
1) Initially no url set to `A` element and no data-binding for `BUTTON` element.
2) Then I "setUrl", so `A` element has `attr.href` now, and in theory I expect, that A should be clickable.
3) I click on `A` element, and click handler executed (u will see alert), but clicking on `A`  href is not used and download doesn't work.
4) When I remove `click: hyprlinkClick,` from this code:
```
<a target="_blank" href="#" data-bind="click: hyprlinkClick, attr: {href: bindAttrHref}"></a>
```
then click event data-binding, and href/download works as expected.
5) U can see, that there is free `A` element, with no binding, where `href` is used as usual (u can download file).
**Case 2**:
6) On the other hand, `BUTTON` element is a bit different element, but because it doesn't have `href` :) I can't use for my feature. But if the button of `submit` type, the parent form is not submitting after button click.
**Case 3**:
7) With added `CHECKBOX` element, behavior the same - when click data-bind applied by Knockout, event with empty function, u simply can't check/un-check checkbox :) which is funny :) 
So again, I understand, that applying click data-binding, Knockout call something kinda `event.preventDefault()` and apply new handler on top of default element behavior.

I realize, it might look like it's OK, because by using click handler we replace A element default behavior. *But again, I was surprised with such data-binding case.*

@brianmhunt I have not even tired usage of KSB, so hold on on KSB :)

**Comment by mbest** [comment]
@alundiak Thanks for the additional details. You are right that this isn't a KSB issue as I had thought originally. It's merely a design of Knockout that is described in the [documentation](http://knockoutjs.com/documentation/click-binding.html#note-3-allowing-the-default-click-action). Change your `click` handler as follows and it will work as you want:

    this.setInProgress = function(){ // simple function
        this.inProgress(true);
        return true;
    }.bind(this);

**Comment by alundiak** [comment]
@mbest omg, simply "read docs more attentively" (I say to me :().
Yes it works. Thanks. Issue fixed (for me). Topic can be finally "closed".
Just in case: updated JSFiddle - http://jsfiddle.net/landike/9emtsnaa/38/
