### ISSUE TITLE
Data Bind on Span in H1 doesn't update

### ISSUE THREAD

**Issue by davidsivocha** [knockout/knockout#1979]
Found an interesting bug that has been driving me wild. When you have a span inside a h1, where the span has a databind, on the initial view model binding it takes the value, but after doesn't update.

My View model contains the following
```
status = ko.observable('Active')
```

And the page code looks like this
```html
<h1>Edit Campaign <span class="small">Campaign Status: <span data-bind="text: status"></span></span></h1>
```

On initial load of the page the text displays as you would expect, showing Edit Campaign Campaign Status: Active. but any subsequent changes to the status observable do not replicate in the page.

**Comment by brianmhunt** [comment]
Your html has an extra `</span>`. ... Is that the problem?

**Comment by davidsivocha** [comment]
@brianmhunt No, if you look at the html it's a span in a span. We tested it both with and without the extra wrapping spans and to no avail. But the second we took it outside of the H1 tag it worked perfectly.

**Comment by brianmhunt** [comment]
Thanks @davidsivocha, I see that now .  There's nothing wrong with the above then that I can see. Perhaps you can reproduce the problem with a jsFiddle?

**Comment by davidsivocha** [comment]
Here you go! https://jsfiddle.net/d6f0unx1/

**Comment by davidsivocha** [comment]
As you can see in the provided fiddle. When clicking on the button to change status the text in the `p` tag changes, but the text in the `h1` does not

**Comment by brianmhunt** [comment]
@davidsivocha Thanks for putting the jsFiddle together.  It works fine for me on Chrome 48.  What browser are you using?

**Comment by davidsivocha** [comment]
Managed to get it to fail on the following:

- Chrome Version 47.0.2526.111 on Windows 10
- Chrome Version 47.0.2526.111 on Mac OSX El Capitan V10.11.2

**Comment by davidsivocha** [comment]
I wonder if it's a chrome browser specific issue then

**Comment by brianmhunt** [comment]
How bizarre.  Based on the simplicity of the demonstration (and irreproducibility of the issue), this is almost certainly not an issue with the Knockout library.

Are there any browser plugins manipulating the DOM?  Javascript?

**Comment by davidsivocha** [comment]
It is rather bizarre. Experimented with turning off all browser extensions, and then turning them all back on one by one, resulted in the Fiddle working entirely. Which is even more bizarre.

**Comment by IanYates** [comment]
I've had the Lastpass plugin muck up one page for me in the past :(
