### ISSUE TITLE
After Drag Drop, Duplicate entries in ordered list binded with an ObservableArrary

### ISSUE THREAD

**Issue by irshad-gehlot** [knockout/knockout#1983]
I am currently working on ASP.NET MVC with Knockout 2.3.0. I feel I have hit a wall where the Knockout framework is adding duplicate <li>. The problem I am facing is as follow:

I have 2 <ol> in my .cshtml

<ol id="primary" class="listView" data-bind="sortable:{template:'primaryFilterItem', data:selectedGuiFilters, options: { axis: 'y'}, afterMove:InvalidateMove, beforeMove: dragDrop, allowDrop: true }, sortableList: selectedGuiFilters "></ol>

<ol id="extended" class="listView" data-bind="sortable:{template:'extendedFilterItem', data:selectedGuiFilters, options: { axis: 'y'}, afterMove:InvalidateMove, beforeMove: dragDrop, allowDrop: true }, sortableList: selectedGuiFilters "></ol>

using the following template for populating the <li>s with the same ObservableArray (selectedGuiFilters).

<script type="text/x-jquery-tmpl" id="primaryFilterItem">
    <li class="filterItem not-draggable" data-bind="attr: {id: name}, visible: isPrimary, css:{selected:hasFocus, draggable:!isStatic}, click:$root.selectFilter">
        <span data-bind="text:name" />
        <div class="removeButton button" data-bind="click:$root.removeFilter" title='@Html.T("Common.Remove.Tooltip","remove")'></div>
        <span class="priority" data-bind="text:linkboxPriority, css:{hidden:linkboxPriority()==0}"></span>
    </li>
</script>

<script type="text/x-jquery-tmpl" id="extendedFilterItem">
    <li class="filterItem not-draggable" data-bind="attr: {id: name}, visible:$root.isItemSelected($data), css:{selected:hasFocus, draggable:!isStatic}, click:$root.selectFilter">
        <span data-bind="text:name" />
        <div class="removeButton button" data-bind="click:$root.removeFilter" title='@Html.T("Common.Remove.Tooltip","remove")'></div>
        <span class="priority" data-bind="text:linkboxPriority, css:{hidden:linkboxPriority()==0}"></span>
    </li>
</script>

PROBLEM: When I drag one <li> from Primary to Extended list, it works fine. After that when I drag one <li> from Extended to Primary then duplicate copy of  the earlier <li> dragged from Primary to Extended appears in the Primary filters. Though it is already present in the Extended list.

The source code in my ViewModel is as follows:

    public InvalidateMove(arg, event, ui) {
        viewsViewModel.self.isModified(true);
        var self = viewsViewModel.self;

        //self.selectedGuiFilters.remove(arg.item);
        if (arg.targetIndex >= 0) {
            self.selectedGuiFilters.remove(arg.item);
            self.selectedGuiFilters.splice(arg.targetIndex, 0, arg.item);
        }
        var tempArray = self.selectedGuiFilters.splice(arg.targetIndex, self.selectedGuiFilters().length - 1);//, arg.item);
        for (var i = 0; i < tempArray.length; i++) {
            self.selectedGuiFilters.push(tempArray[i]);
        }
        event.cancelable = false;
    }

    public dragDrop(arg, event, ui) { 

        //var self = viewsViewModel.self;
        arg.item.isPrimary = ko.observable((this.id.toString() == 'primary'));        

        if (this.id.toString() == "primary")
        {            
            arg.cancelDrop = false;
            arg.sourceParent = null;
            //arg.sourceParent.remove(arg.item);
        }
    }

My understanding is that the Knockout Framework is adding this duplicate copy. The line at which this duplicate copy is added is as follows:
In Knockout-sortable.js
            //initialize sortable binding after template binding has rendered in update function
            var createTimeout = setTimeout(function() {
                update: function(event, ui) {
                            if (sourceParent) {
                                $(sourceParent === targetParent ? this : ui.sender || this).sortable("cancel");
                            }

**Comment by rniemeyer** [comment]
Hi @irshad-gehlot! Can you add your issue here: https://github.com/rniemeyer/knockout-sortable ?

If there is a way for you to create a reproduction of the issue on something like jsFiddle that would be helpful. Thanks!
