### ISSUE TITLE
Knockout breaks when "use strict" is enabled

### ISSUE THREAD

**Issue by kirtangajjar** [knockout/knockout#1985]
Same as [#211](https://github.com/knockout/knockout/issues/211)

Because ko uses the 'with' statement, it cannot be used in conjunction with the 'use strict' statement

**Comment by brianmhunt** [comment]
You can potentially work around this by using [knockout-secure-binding](/brianmhunt/knockout-secure-binding).

**Comment by brianmhunt** [comment]
@kirtangajjar  I trust this is resolved now and I can close this, but if I am mistaken please advise and we can re-open.  Cheers

**Comment by kirtangajjar** [comment]
Yup, it is :)
