### ISSUE TITLE
Disposal of Custom Element Value Subscription

### ISSUE THREAD

**Issue by someyoungideas** [knockout/knockout#1989]
I have built a custom element and I am currently subscribing to the value observable passed into the element to run logic if any changes are made to the observable from the outside. My question is if there is any way to dispose of this subscription from inside the custom element, because there is currently no way of knowing when this element is destroyed. I would also be up for suggestions for different ways of handling how to run my custom element logic if the observable is changed from the outside.

**Comment by mbest** [comment]
I know this is quite old now, but have to tried creating a `dispose` method on your viewmodel?

**Comment by someyoungideas** [comment]
Apologies for not closing this earlier. I am no longer working with the team working on this project. At this moment, the purpose for this issue isn't coming to mind so I will go ahead and close this out.
