### ISSUE TITLE
Issue with option binding inside of template, options defined in $root

### ISSUE THREAD

**Issue by shameleo** [knockout/knockout#1994]
I try to create table with select filters into column titles. I have several tabs with similar tables but different records. To create select filter I use option binding. Selected value is used in filtering function as is, so if I need to show items with unset field I need to get null. But I can't select corresponding options if select is defined inside of template, which uses $root to access options shared between tabs. Here is demo (try to select empty option): [jsfiddle](https://jsfiddle.net/bh2whpg3/)
Note: if select is defined outside of template, everything works fine.
As I'm not experienced knockout developer, I assumed that accessing to shared options is the $root of all evil. I tried to avoid it, so now it works: [jsfiddle](https://jsfiddle.net/bh2whpg3/1/). But only with one tab. If I have more tabs, the issue comes back: [jsfiddle](https://jsfiddle.net/bh2whpg3/2/)
Maybe it is simply unacceptable code, but it looks like bug for me.

UPDATE: I noticed that everything works if I use selectedOptions binding instead of value binding.

**Comment by mbest** [comment]
Although the `optionsCaption` has a value of `undefined`, Knockout matches other values to it including `null` and `""`. So when your value is `null`, Knockout will match it to the caption first.

**Comment by shameleo** [comment]
I believe it is reasonable feature. Inconvenient in my case thought, as I can't directly use selected option value in my filtering function. Would be appreciate if you will add this couple of lines in documentation. Thank you for response.
