### ISSUE TITLE
observableArray update when another observableArray change

### ISSUE THREAD

**Issue by zhengnz** [knockout/knockout#1998]
Hello, Here is the example
[http://jsbin.com/wefoduside/edit?html,js,output](http://jsbin.com/wefoduside/edit?html,js,output)

Before trigger ok button, cancel button can work, but after trigger ok button, old_checked will change when checked change, I don't know how should I solve this problem.

**Comment by mbest** [comment]
You need to make a copy of the array when copying from one observable to another. Otherwise they are actually storing the same array.

    this.old_checked(this.checked.slice(0));
