### ISSUE TITLE
Using with binding inside virtual element

### ISSUE THREAD

**Issue by JD-Robbs** [knockout/knockout#2000]
Hi there,

Slight problem with the following.

I'm looping over some viewmodels (fastForEach) and want to render code based on the type of a particular viewmodel. Works fine in `data-bind`, but when cleaning-up I moved bindings to custom bindings and ran into an issue when using `with`:

                
                <table data-bind="with: table, style: [...]"></table>
                

Now, that works perfectly.

However, I've moved the binding to a custom binding:

                
                <table data-bind="custom: type"></table>
                

The binding:

    ko.bindingHandlers.custom = {
     update: function (element, valueAccessor, allBindings, viewModel, bindingContext) {
        var layerType = ko.unwrap(valueAccessor());

        var types= {
            table: {
                with: bindingContext.$data.table,
                style: [...]
            } 
        };

        ko.applyBindingsToNode(element, types[layerType], bindingContext.$data);
     }
    };

As far as the logic goes, both ways should work exactly the same.  However, the custom binding method emits an error:

    Uncaught Error: Unable to process binding "if: function (){return type() =='table' }"
    Message: Unable to process binding "custom: function (){return type() }"
    Message: You cannot apply bindings multiple times to the same element.

This works perfectly with bindings that don't use `with`. Still, I'd have expected it to work as the `with` binding works when configuring it in `data-bind` rather than the custom binding.

By the way `table` and `'table'` are different things - one's an object, one a string. Essentially looks like this:

    var Table = function() {
       type: 'table',
       table: { name: 'Foo', rows: ['Bar'] }
    }

Just thought I'd put it out there in case this is not just me, but a bug of sorts.

**Comment by IanYates** [comment]
I think you need to tell KO not to attempt to bind to descendant bindings since you're doing that yourself in your custom binding handler.
See http://knockoutjs.com/documentation/custom-bindings-controlling-descendant-bindings.html
