### ISSUE TITLE
3.4.1 release

### ISSUE THREAD

**Issue by mbest** [knockout/knockout#2001]
So far:
- `pureComputed` sometimes doesn't pick up a change in a dependency (#1975 and #1992)
- Knockout observable arrays leak memory when resubscribing to `arrayChange` events (#1973 and #1974)
- `$rawData` within `with` bindings and rendered templates (#1415)
- Export `computed._latestValue` in debug mode (b3f24b1e247c1b)

https://github.com/knockout/knockout/tree/3.4.1

**Comment by IanYates** [comment]
:100: from me
I hadn't brought over that $rawData one into my own copy but it looks like it'd be nice to have just in case.

**Comment by dealproc** [comment]
is this possibly what I'm seeing when i have a computed observable that is bound to the checked binding, and i'm only getting writes on the uncheck (false) and not on the check (true)?

**Comment by mbest** [comment]
@dealproc If you think it might be related, try building the 3.4.1-pre code and see if it helps.

**Comment by codymullins** [comment]
Hi guys - this might not be the best place to ask, but something I've been trying to figure out. Is there some kind of long term road map for knockout or is it currently just being maintained? I use Angular at work, but have a side project (startup app) that uses knockout - it's one of the few that support back to IE8, which I currently require. Just wanted to know if there was a plan in terms of features or product evolution that I could expect or potentially contribute to making happen?

**Comment by IanYates** [comment]
@codymullins - not sure.  In terms of what KO does, it's fairly complete.  Components, etc are well-defined.  There are some bits and pieces being discussed around refining component loading some people can do transitions and "know" when every component is ready (a tricky term to define since a new component could be loaded at any time really)

The 3.x series of releases has been pretty huge in terms of new functionality.  The deferred update capabilities that @mbest introduced look awesome but I haven't had a chance to introduce them into our codebase yet as it would require a good deal of testing of some UI/Promise/Computed/etc interactions.

A lot of new functionality comes via way of the many third party bindings.  Having @mbest's punches library integrated into KO would be neat but adding it on as a second script isn't really a big deal.  I do wish it was more discoverable to newcomers though - maybe having it exposed on the home page as a featured plugin.  Same goes for other bindings I use like switch/case (love that one!)

What sort of things are you coming across that you wish were in core KO?

**Comment by JD-Robbs** [comment]
Just wondered if it'd make sense to have a release with just the pureComputed fix for now, seeing it's already been fixed. 

@IanYates having knockout.mapping supported in the core would be nice as well.

**Comment by codymullins** [comment]
@IanYates thanks for the reply! I'll have to take a look at the punches library, I haven't seen that before. I guess I don't really know specifically, just every now and again I come across something that I feel is missing. The only thing I can think of right now is dirty tracking for a model/form. Many other libraries such as Angular provide that out of the box. 

If I think of anything else (I know there are other things, just can't remember), I'll be sure to make a note of it.

**Comment by jeremyVignelles** [comment]
I just came across an issue where a subscription is not getting called, which sounds strangely familiar. I'm looking forward the 3.4.1 release, or a RC version I can use in the meantime with bower. Do you have this kind of prerelease ready?

Thanks

**Comment by carlosagsmendes** [comment]
Hi there, is release 3.4.1 planned? Thanks in advance

**Comment by jeremyVignelles** [comment]
Just published my own unofficial release in the meantime:
https://github.com/jeremyVignelles/knockout/tree/v3.4.1-pre-unoff

usage in bower:
```
    "knockout": "https://github.com/jeremyVignelles/knockout.git#v3.4.1-pre-unoff",
```

I can also confirm that issue #1975 is fixed, see this fiddle:
https://jsfiddle.net/ntvco4h5/7/

**Comment by cervengoc** [comment]
@mbest @brianmhunt I just wanted to bump this because I need the `$rawData` fix just about now, and don't like having local versions. 

When are you planning to release this? Seems to me that this few issue is worth a release.

**Comment by mKlus** [comment]
In the meantime, until 3.4.1 becomes available, would it be possible to publish 3.4.1-pre1 to npm?

**Comment by mbest** [comment]
Sorry for taking so long, but I've finally released 3.4.1.

**Comment by mbest** [comment]
Publish to:
- [ ] NPM
- [ ] CDNJS (should be automatic; check up on it)
- [ ] Microsoft Ajax CDN
- [ ] NuGet
- [ ] jsfiddle

**Comment by bludev** [comment]
Hi guys! What's new about NuGet release?

**Comment by mbest** [comment]
@SteveSanderson can you update NuGet?

**Comment by PaluMacil** [comment]
Is @SteveSanderson the only person able to update NuGet? Steve hasn't had Github activity since half a year ago. Perhaps someone could Tweet him. I asked a Microsoft engineer I know to ping him if he's comfortable reaching out on behalf of this. :)

**Comment by mbest** [comment]
Also @osbornm is listed as an owner. @osbornm, can you add me as an owner on NuGet?

**Comment by osbornm** [comment]
I'm happy to add folks but I want to get @SteveSanderson to okay it, it's his project. I've upload 3.4.1

**Comment by brianmhunt** [comment]
Thanks for the note, @osbornm .

For my part as a core developer, it is fine with @mbest owning the NuGet repo.  @rniemeyer ?

Of course we appreciate and it's completely fair to wait to hear from Steve directly, but just in case that takes a while I thought I'd note my endorsement.

**Comment by rniemeyer** [comment]
I concur. Thank you for updating 3.4.1 @osbornm!

**Comment by SteveSanderson** [comment]
Hey, sorry I was totally unresponsive to this! I wasn't paying close enough attention to the notification emails.

Totally agree that any or all of the KO core team should be co-owners of the NuGet package. I've just added @mbest (it should have sent him an email requesting his approval). If any of the rest of the core team wants to be added, please send me your nuget.org usernames.

**Comment by mbest** [comment]
Thanks, @SteveSanderson
