### ISSUE TITLE
Please update documentation for foreach to include how to use $rawData

### ISSUE THREAD

**Issue by brianlmerritt** [knockout/knockout#2002]
$rawData was created so that observables could be passed rather than just the actual data.

I am embarrassed to say how long I spent trying to get foreach  with $data in the binding to update automatically until I stumbled upon https://github.com/knockout/knockout/issues/708. 

Can you please update the webpage http://knockoutjs.com/documentation/foreach-binding.html and add an example of $rawData as developers trying to pass on observables using foreach are not so likely to stumble upon $rawData in the correct context until possibly a lot of time and energy have been expended.

**Comment by brianmhunt** [comment]
It's a good point, thanks for raising this @brianlmerritt
