### ISSUE TITLE
It's losing data on empty select?

### ISSUE THREAD

**Issue by inventti-leonardo** [knockout/knockout#2006]
Using knockout 3.4.0 :(
http://codepen.io/anon/pen/QyeXRV

It´s working on knockout 2.3.0 :)
http://codepen.io/anon/pen/qbezzb

**Comment by davidparker** [comment]
You need valueAllowUnset   <select data-bind="value: item, valueAllowUnset: true"></select>

see 

http://knockoutjs.com/documentation/value-binding.html#using-valueallowunset-with-select-elements

for documentation

**Comment by inventti-leonardo** [comment]
Nice, thank you. I was confused with this different behaviors. Now I can continue the migration from version 2.x to 3.x :)
