### ISSUE TITLE
select binding choosing first option upon ajax refresh

### ISSUE THREAD

**Issue by rgeerts** [knockout/knockout#2012]
I have a fairly complex situation which I have boiled down to the following fiddle.  It may best show the problem.  You will notice that the select box changes to "fish scale ale" after 2 seconds even though I would have expected it to only have said "schmidt".

https://jsfiddle.net/26nf0t7f/2/

I understand this is kind of pulling the rug out from underneath of select and perhaps not an intended use of the select binding as it is more complex than the documented use cases.   Although I was surprised it didn't work.  Not sure if this would happen for any of the other html bindings?  

The following is a stop gap solution I have. Does this seem reasonable or should I have some wait time after the "switcharoo", or is there a better solution all together?

https://jsfiddle.net/01t6hwpx/

Thanks for your time and consideration.

**Comment by rgeerts** [comment]
coworker found that using the valueAllowUnset: true works as well.
https://jsfiddle.net/jose_jimenez/8x3eqmd5/1/

this is probably a better solution than I came up with.  Seems that the purpose of that is slightly different that what I am using it for?

**Comment by mbest** [comment]
I'm glad you found a solution.
