### ISSUE TITLE
pureComputed not updating 

### ISSUE THREAD

**Issue by mokkabonna** [knockout/knockout#2014]
I am writing this issue as this is causing very unpredictable behaviour in various cases. However I haven't been able to isolate or recreate in a simple scenario the exact problem. But here is a general description:

Sometimes in more complex use cases I end up with pure computeds that don't evaluate when they depend on other pureComputeds. And just to be clear: this are PURE computeds, I have no other input except other observables/computeds. 

I have isolated the issue to being introduced in 3.3 (also tried with 3.4, same problem.) And I suspect https://github.com/knockout/knockout/pull/1543 introduced it. And also might be related to what is being discussed here: https://github.com/knockout/knockout/issues/1775

This behaviour have completely stopping us from using pure computeds (that or not use 3.3+) as we really can't trust it anymore. In at least two scenarios have we encountered this, but again, hard to isolate the exact issue. 

In both of the cases the pure computed is returning an array, not sure if that matters though. Also let's say I have purecomputed A and B, A depends on B. I change something (C) that updates B as expected, but A, even though depending on B does not get updated.

If I however change C back , then set it to the desired value again, everything works as expected from there.

Also if I explicitly register a subscription to A before setting C, then it works as expected.

I find this a serious bug, and wanted to register it, even though I can't really track down a simplified scenario. And can't share (or is even practical I think) the whole code that triggers this.

Hope this could be tracked down.

**Comment by brianmhunt** [comment]
Thanks for the report @mokkabonna – I believe this is related to issues that'll be solved in 3.4.1, per #2001 (and #1975 / #1992)

I'll close this on the basis that it's a duplicate, but please advise if I might be mistaken or there's something further that warrants this issue remaining open.

Cheers

**Comment by mokkabonna** [comment]
Thanks @brianmhunt ! I acutally just stumbled on that myself.

Applied the same fix in the appropriate place in the 3.3 version and it was worked as expected:

```js
    if (options['pure']) {
        pure = true;
        isSleeping = true;     // Starts off sleeping; will awake on the first subscription
        dependentObservable.beforeSubscriptionAdd = function (event) {
            // If asleep, wake up the computed by subscribing to any dependencies.
            if (!_isDisposed && isSleeping && event == 'change') {
                isSleeping = false;
                if (_needsEvaluation || haveDependenciesChanged()) {
                    dependencyTracking = null;
                    _dependenciesCount = 0;
                    _needsEvaluation = true;
                    evaluateImmediate();
                    dependentObservable.updateVersion(); ///<----------   Added this
                } else {
                    // First put the dependencies in order
```

Nasty bug.

**Comment by mokkabonna** [comment]
Sorry for the noise, I did search through existing issues, but failed to find it the first time.

**Comment by brianmhunt** [comment]
Lol.  No worries, thanks for the update, @mokkabonna !  :beers:
