### ISSUE TITLE
Feature Request: A clean approach for CSP

### ISSUE THREAD

**Issue by aersamkull** [knockout/knockout#2019]
## The Problem

CSP is an awesome Security Feature and is required in certain situations (eg, Chrome Weg Apps). Knockout should support someway to deal with CSP to stay competitive (http://stackoverflow.com/questions/18238812/how-to-do-mvvm-using-knockoutjs-in-chrome-packaged-app-it-doesntt-allow-inline) 

The default Knockout Binding Provider does execute a call on new Function(string) to parse its Bindings, which is not allowed with CSP.
## Current Solution

One can currently use Knockout Secure Bindings, but this is not so very official and as it parses Strings at runtime it feels a bit like introducing a new security risk to me.
## A Proposed approach

The default Knockout Binding Provider already has a cache, in way that the same Binding is not parsed twice. That cache could be made public. We can then make a compile step to calculate that cache and there will never ever be a call to that new Function. 
So, one would need a tool to extract bindings from one or more html files which would generate something like this:

``` JavaScript
(function(){
    var bindings = {
"enable: chosenTicket, ↵ click: resetTickettrue": function($context,$element ) { ... }
"options: tickets, ↵ optionsCaption: 'Choose...',↵ optionsText: 'name',↵ value: chosenTickettrue": function($context,$element /**/) {...}
}
ko.utils.extend(ko.bindingHandler.instance.bindingCache, bindings);
})();
```

This script had to be loaded before any ko.applyBindings call.

So, what do you think about that? Any better ideas to support CSP? Or am I the only one requireing CSP?

**Comment by brianmhunt** [comment]
Thanks @aersamkull – There's definitely a demand for CSP.

One option is separating out the binding from an identifier, as you suggest, and copying the cache into a separate JS file before production.

Another option I thought about is to have Knockout generate separate code and then provide a SHA256 that one can use in the CSP headers.  This can be problematic if there are HTML code-paths not created by Knockout, and it requires updating the CSP header every time there's a substantive change.

All to say, this is a good issue, and warrants some thought & discussion. :)

**Comment by aersamkull** [comment]
I've created a very basic prototype: https://github.com/aersamkull/KnockoutCSP

**Comment by aersamkull** [comment]
Hello everyone
I'd like to come back on this as I have tried using my implementation in production and it seems it was close to working. It does however not working with custom elements and the params attribute. The reason is that the components implementation uses an own instance of the binding provider:
```JavaScript

  var nativeBindingProviderInstance = new ko.bindingProvider();

    function getComponentParamsFromCustomElement(elem, bindingContext) {
        var paramsAttribute = elem.getAttribute('params');

        if (paramsAttribute) {
            var params = nativeBindingProviderInstance['parseBindingsString'](paramsAttribute, bindingContext, elem, { 'valueAccessors': true, 'bindingParams': true }),
     [...]
```
I can therefore not overwrite the binding cache for that provider. I think it was reasonable anyway to expose that components binding provider, to be able to overwrite it with a custom implementation. Isn't this an issue for https://github.com/knockout/tko.provider as well? @brianmhunt

**Comment by aersamkull** [comment]
Could be easily fixed: https://github.com/knockout/knockout/compare/master...aersamkull:master 
I'd do a PR if desired

**Comment by bswift** [comment]
I feel like this issue is only going to get bigger the more time goes on. If knockout doesn't include a way to be CSP compliant and other libraries do, it could have a big negative impact on the amount of new projects that choose to use knockout.

**Comment by yippibrian** [comment]
Surely CSP should be a concern warranting more discussion.  This ticket has not been updated in over 2 years.

**Comment by aersamkull** [comment]
Personally I don't use Knockout anymore for larger project - I've become lazy and just use Angular as everything works out of the box (CSP, Bundling, Tooling, for example). I still use Knockout from time to time for smaller things where I have to enrich some pages and there I don't need CSP. So I'll close this issue.

**Comment by brianmhunt** [comment]
@yippibrian Using knockout-secure-binding and TKO both provide CSP safety, and have been around for years, so this issue has arguably been solved for years, which is probably why it hasn't been updated. 😀

**Comment by Nik-kolte** [comment]
Hi @brianmhunt , i have tried using your knockout-secure-binding plugin , i was facing issues when using javascript functions in attr .

 eg- <div data-bind="attr: { class: $root.currentClass(carouselBanner.BannerClass) }">

Can we discuss about this somewhere , i've seen all threads trying to solve these problems

**Comment by Serhansolo** [comment]
@brianmhunt, our team is facing a similar problem like @Nik-kolte, simply enabling the KSB plugin does not seem to work. Could you help us out here?

@Nik-kolte, have you been able to fix your CSP issues using this plugin?

**Comment by swpnl99** [comment]
Facing issues similar problem to @Nik-kolte, @brianmhunt pls provide your inputs if you have any.

@Serhansolo are you still facing issues with your CSP? How were you able to solve it ?

**Comment by swpnl99** [comment]
Is there a way for knockout-secure-binding to support attribute like bindings. 
Example :-
event: { change: eventHandler}
