### ISSUE TITLE
Tracking array changes: ko.observableArray.splice() does not account for shifts when inserting elements

### ISSUE THREAD

**Issue by elfin-sbreuers** [knockout/knockout#2026]
Hello,

using track changes in knockout's observableArray does not account for the shifts in trailing elements introduced by inserting new elements. Observed with knockout version: v3.4.0.

```
var arr = ko.observableArray(["Alpha", "Beta", "Gamma"]);
 
arr.subscribe(function(changes) {
    console.log(JSON.stringify(changes));
}, null, "arrayChange");

arr.splice(2, 0, 'Delta');
```

The output of the posted code does only show the added element as a change.

```
[{"status":"added","value":"Delta","index":2}]
```

My expectation would be that there are also additional changes that depict the shifted elements.

```
[{"status":"deleted","value":"Gamma","index":2,"moved": 3}]
[{"status":"added","value":"Gamma","index":3,"moved": 2}]
[{"status":"added","value":"Delta","index":2}]
```

Is there a reason for this behaviour? Or are there changes planned to take those shifts into account?

Kind regards,

Sebastian

**Comment by brianmhunt** [comment]
Hi @elfin-sbreuers –

I'm guessing, not having looked at it lately, that the rationale is that depicting the shifted elements is

1. O(n) - i.e. slow;
2. Not in huge demand for the ordinary course; and 
3. Easily calculable on demand i.e. if the `index` is less than the length of the list all subsequent elements must have been moved.

I'd be inclined to say that the correct solution is not to add a feature to KO proper, but rather to add another extender that intercepts `arrayChange` events and adds "moves" as needed.

**Comment by mbest** [comment]
It doesn't report items whose position has shifted because of other insertions or deletions. Adding shifts as an add/delete would be a breaking change.

**Comment by elfin-sbreuers** [comment]
@brianmhunt thanks for your support. I followed your advice. It is working for me. I'm using the extender instead of the subscription in my.

Maybe the following code can be a starting point for someone else if they stumble accross the same requirement.

```
ko.extenders.addShifts = function(target, callback) {
    var before = target().slice(),
    after = before;

    var addShifts = function(changes, by) {
        var startIndex = changes[changes.length - 1].index - by; 
        before.forEach(function(value, index) {

            if (index > startIndex || (by < 0 && startIndex === index)) {
                changes.push({
                    value: value,
                    status: 'shifted',
                    from: index,
                    to: index + by
                }); 
            }   

        }); 
    };  

    var handleShifts = function(changes) {
        var by = after.length - before.length;

        if (by !== 0) {
            addShifts(changes, by);
        }   
    };  

    target.subscribe(function(newValue) {
        after = newValue.slice();
    }); 

    target.subscribe(function(changes) {
        handleShifts(changes);
        before = after;
        callback(changes);
    }, null, 'arrayChange');

    return target;
};
```
