### ISSUE TITLE
ko.applyBindings not working synchronously

### ISSUE THREAD

**Issue by jlaustill** [knockout/knockout#2038]
For starters, here's a fiddle
[https://jsfiddle.net/LkqTU/29770/](https://jsfiddle.net/LkqTU/29770/)

When it runs, it will bind to the initial value set in the model, and the update will happen BEFORE that and will not be reflected in the final state.  If you comment out the last line, and uncomment the one below it, it will work correctly with a timeout that gives the bindings time to finish.  

This is causing me issues on forms where I load the data from an api.  When the api returns quickly, I have this issue and the users posts don't bind properly.  If I do the api loading before binding, sometimes the api is slow and it makes the screen stay unbinded for a number of seconds.  

I can't find anywhere in the docs where there is a callback or success call for applyBindings.  So how am I supposed to do this properly?  Having to set a timeout before invoking the api seems super duper hacky...

**Comment by mbest** [comment]
The problem is caused by your `wysiwyg` binding that uses `setTimeout` but doesn't properly handle updates before the timeout completes. The solution is have your binding handle those updates.

Here is the changed code that makes your example work:

        update: function (element, valueAccessor) {
            var $el = $(element);
            var tinymce = $el.tinymce(),
				value = valueAccessor()();

            if (tinymce) {
                if (tinymce.getContent() !== value) {
                    tinymce.setContent(value);
                }
            } else {
                $el.val(value);
            }
        }

https://jsfiddle.net/mbest/LkqTU/29772/

**Comment by jlaustill** [comment]
Oh wow!  This makes total sense.  I'll step through this in detail tomorrow and make sure I really understand this, thanks a ton!
