### ISSUE TITLE
How to comment code inside binding?

### ISSUE THREAD

**Issue by benbor** [knockout/knockout#2046]
Is  it possible: 
```html
<select data-bind="
    attr: {
        name: inputName,
        id: uid, //this is comment. 
        //disabled: disabled,
    }" />
```
?

**Comment by brianmhunt** [comment]
Hi @benbor – The comments will break the parsing, if that is what you are asking. :)

**Comment by benbor** [comment]
Hi  @brianmhunt. Yes, i've got it. But i dont undestand why knockout parser can't do it. Is binding comment  usefull feature?

**Comment by brianmhunt** [comment]
Hi @benbor – there are a couple issues, including inconsistency handling line-breaks across browsers, and future content-security-policy compliance (which requires a parser that is not javascript).

Unless I misunderstand, I do not think in the future comments in binding attributes is something that will be supported.

**Comment by chrisknoll** [comment]
Why not just write your own custom knockout binding that doesn't do any actual work but lets you do something like:

~~~~ html
<div data-bind="text: someModelValue, comment: "This is a comment on this binding"></div>
~~~~

Heck, I think if you just put a binding in there that isn't handled by knockout it'll just ignore it....

-Chris

**Comment by benbor** [comment]
@chrisknoll thank you! That workaround works for me.
