### ISSUE TITLE
IE9: ko foreach inside <select> is removed

### ISSUE THREAD

**Issue by sumitkm** [knockout/knockout#2047]
Hi Team,
I have this Fiddle https://jsfiddle.net/fy9qm59e/6/ which works fine on all modern browsers but breaks in IE9. 

```html
<select>
 <option value="1">One</option>
 <option value="2">Two</option>
 <!-- ko foreach: additionalValues -->
 <option data-bind="text: text, value: value"></option>
 <!-- /ko -->
</select>
```

```Javascript
var viewModel = {
	additionalValues : ko.observableArray([{  text: "three",  value: "3"  }])
};

ko.applyBindings(viewModel);
```

That's because IE9 removes the KO foreach inside the select

Not sure if this can be put on KO, possibly that's how IE9 works. Anyone has a workaround?

It is not a blocker, I am going to change my implementation so that the defaults are populated in an array and bind the ```<select>``` using the appropriate ko bindings. 

Just thought would report it in-case someone spends a morning scratching their head with this :-)

**Comment by stalniy** [comment]
Try to use https://github.com/mbest/knockout-repeat instead of foreach binding

**Comment by sumitkm** [comment]
@stalniy Thanks. I ended up using the regular [options binding](http://knockoutjs.com/documentation/options-binding.html) with a default observable collection of objects and added new values to the collection as required. 

Closing this issue. Cheers!
