### ISSUE TITLE
Can't use variable `default` ? 

### ISSUE THREAD

**Issue by alvarotrigo** [knockout/knockout#2053]
[Reproduction online](https://jsfiddle.net/4kua2v2p/4/)

```javascript
var viewModel = {
    default: ko.observable(true)
};
ko.applyBindings(viewModel);
```

```html
<input type="checkbox" data-bind="checked: default" /> Gift wrap
```

Error: 

> Uncaught SyntaxError: Unable to parse bindings.
Bindings value: checked: default
Message: Unexpected token default

**Comment by alvarotrigo** [comment]
I guess because its a [reserved word in javascript](http://www.w3schools.com/js/js_reserved.asp)... sorry for that.

**Comment by PaulHuizer** [comment]
you're fast ;-)

**Comment by alvarotrigo** [comment]
Coming from a JSON file I didn't see it that clear, but GIthub highlighter makes a good job here :D
