### ISSUE TITLE
Trigger the change event when manipulating checkboxes and radio buttons within the checked binding

### ISSUE THREAD

**Issue by cervengoc** [knockout/knockout#2054]
It seems to be inconsistent that within the `checked` binding, when ever KO updates the editor, it doesn't trigger the `change` event. It does so for other controls like textboxes, textareas, selects (via the `value` binding). 

I'm currently in a situation where I would like to make use of it, if it were possible.

I'd like to know if this by intention for some reasons, or is it really an inconsistency? If it is by design, could someone please describe the reasons?

**Comment by mbest** [comment]
The `value` binding only generates a `change` event for `<select>` elements, and that is only to allow the `options` binding to override the written value. In general, the bindings do not fire any event when they are updated from the viewmodel.

**Comment by cervengoc** [comment]
Ah, okay I misread that, just had a quick look and saw some calls of `triggerEvent`. Thank you for the clarification, I'll go in another way then.
