### ISSUE TITLE
Virtual elements render incorrectly with self-closing span tag

### ISSUE THREAD

**Issue by serpenyx** [knockout/knockout#2057]
I have an example of the issue here: [https://jsfiddle.net/gocxjfc1/2/](https://jsfiddle.net/gocxjfc1/2/)

I did some digging around the span element's spec and it sounds like it really shouldn't be used as a self-closing tag because it is a container element.  

The main reason why I still am posting this as an issue is because I know that I, and others on my team, have been using self-closing spans with the data-bind attribute (text: or html:) quite a bit because we are specifying that the span will have content when the data is bound.

So, I'm not sure, then, if self-closing span tags need to be supported, if the there should be a binding error thrown when one is used, or we just need to grow up and use a closing tag with spans.  In any case, I felt like this was a "gotcha".

**Comment by rniemeyer** [comment]
@serpenyx - the main problem/challenge with these type of scenarios is that browsers often provide some type of "correction" when they encounter mark-up like this (before Knockout bindings are applied). For example, if you render:

```
<ul>
    <li>
         <span />
         <select></select>
    </li>
</ul>
```

Chrome will end up actually rendering:

```
<ul>
    <li>
         <span>
              <select></select>
         </span>
    </li>
</ul>
```

For your case, in Chrome, the first set of markup is rendered like:

```
<ul id="incorrect">
  <!-- ko foreach: items -->
  <li>
    <!-- ko if: useSingle -->
    <span data-bind="text:current">
    <!-- /ko -->
    <!-- ko ifnot: useSingle -->
    <select data-bind="options: values, value: current"></select>
    <!-- /ko -->
  </span></li>
  <!-- /ko -->
</ul>
```

Which ends up with some incorrect nesting of the if/ifnot bindings.

Perhaps this could be something that we look to highlight in our documentation.

Hope that makes sense. Thanks!

**Comment by mbest** [comment]
In HTML5, there's no such thing as a self-closing tag. So it interprets your `<span/>` as simply `<span>`.
