### ISSUE TITLE
custom observables hard to write against minified ko

### ISSUE THREAD

**Issue by far-blue** [knockout/knockout#2072]
I'm in the process of writing a custom observable function based on how ko.observable works and I've hit some blocks due to the minification of KO.

Firstly, in order to extend from ko.subscribable I really need to be able to run ko_subscribable_fn.init but this method's name is minified so I'm having to run ko.subscribable itself which needlessly also sets up a prototype chain (which I then need to replace).

Secondly, while ko.dependencyDetection is exposed as ko.computedContext, ko.dependencyDetection.registerDependency isn't exposed so I am unable to replicated the behaviour of ko.observable on line 18.

I have confirmed my function works using the non-minified version of KO but that isn't suitable for production so would it be possible to add these methods (ko.computedContext.registerDependency and ko_subscribable_fn.init) to be 'exposed' in the minified version?

Alternatively, if I'm just doing it wrong, please let me know!

Thanks!

**Comment by mbest** [comment]
> Alternatively, if I'm just doing it wrong, please let me know!

Why are you create a custom observable?

**Comment by far-blue** [comment]
We have been using Knockback to link NestedTypes models to ko observables but Knockback is not very resource efficient so I've written a custom observable that basically bridges the change events on an attribute of a NestedTypes model instance and the will/hasMutated events in KO.

Here's what I've done so far:
https://gist.github.com/far-blue/20e368e175b05429a054d011f02830ad

In very basic testing it has worked well as a drop-in replacement for Knockback's 'kb.observable' and is ~ 60% faster and 70% more memory efficient.

Notice, importantly, on line 25 where I'm referring to `ko.computedContext.oc` which is actually 'ko.dependencyDetection.registerDependency' but minified.

Notice also on line 43 and 44. Here I'm effectively trying to run ko.subscribable.init() in order to setup the instance vars for subscribable but have to do it this way which is inefficient as the ko.subscribable constructor not only init's but also sets up a prototype which I then immediately replace on line 44.

**Comment by mbest** [comment]
Thanks for providing the example. It's a good demonstration of the reasons for making this change.

**Comment by mbest** [comment]
Merged #2212
