### ISSUE TITLE
is there has pushAll now?

### ISSUE THREAD

**Issue by fendoude007** [knockout/knockout#2074]
I want to add an array to a observableArray Object, but there is no funtion I can user, what can I do to achieve this;

**Comment by fendoude007** [comment]
I use knockout version 3.4.0

**Comment by brianmhunt** [comment]
Hi @fendoude007 

You can use `observableArray.push(...items)` or see https://github.com/knockout/knockout/issues/416#issuecomment-21316306

I'm closing this as a duplicate of #845, but please say if there is something we might be missing.

Cheers.
