### ISSUE TITLE
component takes ownership of vm with params:$data

### ISSUE THREAD

**Issue by jeremyVignelles** [knockout/knockout#2075]
I am currently writing a custom component that wrap its children in a "foldable panel". I want it to be seamless, i.e. it uses the same vm as its parents.

For this I am using `params:$data` as a binding.

However, my ViewModel has a `dispose` method, which gets called when the component is removed.

I am reproducing the issue with this simple fiddle:
https://jsfiddle.net/j7p82quy/

For reference, here is the code:

```js
    ko.components.register('display', {
        template: '<div data-bind="text:message"></div>'
    });

    var vm = {
        show: ko.observable(true),
        message: ko.observable('Hello world!'),
        disposeCount: ko.observable(0),
        dispose: function() {
            vm.disposeCount(vm.disposeCount() + 1);
        }
    }

    ko.applyBindings(vm);
```

```html
    <input type="checkbox" data-bind="checked:show" />
    <!-- ko if: show -->
    <div data-bind="component:{name:'display', params:$data}"></div>
    <!-- /ko -->

    <div data-bind="text:disposeCount"></div>
```

expected: the disposeCount should be always 0 when clicking the checkbox
what happens: the disposeCount increases

I suggest that an option can be passed to the component, like so:

```html
<div data-bind="component:{name:'display', params:$data, takeOwnership: false}"></div>
```

The option takeOwnership  would default to `true` for compatibility.

What do you think about it? I can make the PR if you want.

**Comment by chrisknoll** [comment]
I disagree:  your view model exists only one time. The disposeCount observable is allocated once. You are passing the viewModel (as $data) as a param to the component.  Every time the component is disposed, you're updating the model's property.

This is working as intended and expected!

**Comment by jeremyVignelles** [comment]
Thanks for your reply.
My point is not about the disposeCount getting allocated or not, but in the fact that I don't want the component to do anything with my viewModel other than making it accessible to its children.

In other words, I want to say to knockout "I will take care about disposing this viewModel, don't do it for me" without having to create a viewModel for the component.

**Comment by chrisknoll** [comment]
But the view model isn't being disposed, the component is.  The component != the model.  You explicitly stated in the code that the dispose should modify the view model.

Perhaps what you need is to create a copy of the view model and pass it into the component:

~~~javascript
<div data-bind="component:{name:'display', params:getCopy($data)}"></div>
~~~

As an aside, passing the viewModel into the component is code smell.  You should be passing encapsulated data into the component not the entire root model. This sets up dependencies on the entire root model that you won't want in component design.  But this was discussed in a separate issue if you search for it.

**Comment by IanYates** [comment]
Try this
https://jsfiddle.net/IanYates/nj3pez5b/

Basically it's your fiddle but shows how the view model and component needn't be the same thing (as @chrisknoll was saying).  The component's data has a single property `vm`.  In this case that's a view model that you're passing in.  Generally that's a code smell but I've had to do the same where I want a view model, and its on-screen state, to be rendered in a small <div> on one page and then, when the user wants, open a popup <div> and render the same view model (with no loss of state) in a bigger component with different HTML, etc.  Not a common occurrence though.

Anyway, you'll see that the component gets disposed (it has no dispose function so KO doesn't do much) and your view model is unaffected.  The "with" binding lets you write your template as though it had the view model.  If you really want the HTML to not have that "with" you could have your component's template just be a small snippet of HTML that invokes the template binding using your desired HTML template and the vm property of the component.

Is that close enough to what you want?

**Comment by jeremyVignelles** [comment]
Thanks for your reply. Using the `with` binding seems to be a nice workaround. I will use this one, thanks a lot for the explanations.

**Comment by chrisknoll** [comment]
@IanYates , I don't actually understand the fiddle:

The VM is beign allocated once, the vm is being passed into the component ('display'), the createViewModel isn't actually allocating anything it's just returning a wrapped $data as the inner view model...but dispose still increments the disposeCount of the vm that was created at the root level.

Why isn't the disposeCount() showing a new value?

**Comment by jeremyVignelles** [comment]
The createViewModel is creating a new viewModel object, which wraps `$data`. When the `display` component is disposed, ko looks into this new viewModel to find a `dispose` method, which does not exist. That way, the dispose method of the main VM is not called, and the disposeCount() is not incremented.

**Comment by chrisknoll** [comment]
Ok, yes, I see now. thank you.

**Comment by IanYates** [comment]
It might be a bit unorthodox but can be handy when you legitimately have a view model with state that you want to move around the screen, possibly being rendered with some different views.  It comes down to whether enough state is in the model or not.  I tend to have models be pretty much exactly what comes down from the server so the view models have the "in the moment" state.

90% of the time though @chrisknoll is spot on - the component should be given what it needs to operate through a well-defined contract.  Just the remaining 10% of the time, that "what it needs" happens to be a specific view model.

I'll stop beating the dead horse now - I think we're all in furious agreement :)
