### ISSUE TITLE
enable binding: why is it removing attribute instead of just setting the property?

### ISSUE THREAD

**Issue by opcodewriter** [knockout/knockout#2076]
https://github.com/knockout/knockout/blob/master/src/binding/defaultBindings/enableDisable.js#L5

Very curious, any particular reason why `enable` binding implementation is removing attribute:

```
element.removeAttribute("disabled");
```
instead of just setting the property?
```
element.disabled = false;
```

Because it does use the property when disabling in the next line (https://github.com/knockout/knockout/blob/master/src/binding/defaultBindings/enableDisable.js#L7):
```
element.disabled = true;
```

**Comment by mbest** [comment]
Have you run across any problem with that method?

**Comment by opcodewriter** [comment]
@mbest No, I am just curious why author chose to remove attribute instead of setting property to `false`.
It might be a little trick/gem (performance?) but I don't see it.

**Comment by brianmhunt** [comment]
If I remember correctly in old IE (<8?) setting an attribute to false did not result in its removal.  Can't find a reference offhand .

**Comment by BrianMcBrayer** [comment]
You might already know this as well, but the `disabled` attribute really should be removed instead of being set to false. https://www.w3.org/TR/html5/forms.html#enabling-and-disabling-form-controls:-the-disabled-attribute

**Comment by opcodewriter** [comment]
@BrianMcBrayer hmm, isn't setting the content attribute to false supposed to remove the attribute?

> The disabled IDL attribute must reflect the disabled content attribute.

**Comment by BrianMcBrayer** [comment]
@opcodewriter yeah, you know, you are right. I was thinking back to the IE8 days, too. Those pesky boolean attributes used to cause so much trouble.

**Comment by brianmhunt** [comment]
There's further and lengthy discussion over at jQuery: https://bugs.jquery.com/ticket/14633 - whose most recent version (3.0) uses removeAttribute.

Closing this as the KO behaviour appears correct, but please let me know if I misunderstand or have overlooked something, and we'll re-open!
