### ISSUE TITLE
Use of jQuery's bind function

### ISSUE THREAD

**Issue by CyberBotX** [knockout/knockout#2078]
When Knockout is used with jQuery 3.0.0 (released a couple week ago), the jQuery Migrate script reports that Knockout is using the bind function from jQuery, which has been marked as deprecated. This is what I get in my console window:

`JQMIGRATE: jQuery.fn.bind() is deprecated`

The [recommendation](https://github.com/jquery/jquery-migrate/blob/master/warnings.md#jqmigrate-jqueryfnbind-is-deprecated) is to use .on() instead of .bind().

**Comment by djanosik** [comment]
It makes knockout incompatible with jQuery 3 Slim build :/

**Comment by mattfeury** [comment]
still hoping to see this released in a stable version! 3.5.0 is still in RC
