### ISSUE TITLE
"Not all browsers support JavaScript getters and setters" is it still a thing?

### ISSUE THREAD

**Issue by qwemaze** [knockout/knockout#2082]
![](http://i.prntscr.com/c0bff92179e645f7a2081ff25f320cd5.png)
Microsoft ended support for old versions of Internet Explorer, including IE8, IE9, and IE10.

**Comment by brianmhunt** [comment]
@qwemaze You can use the knockout-es5 project to set/get the observable as a property of an object.

The ko-es5 model is not always suitable, has a number of inherent issues that are inconsistent with how KO is often used.

Which is not to say there is no opportunity for improvement, but that it's a longer road that one might expect.

I will mark this as closed as there is no clear path to fix this (aside from updating the documentation?), but please comment if there is something that KO can do to improve and we can certainly re-open.

**Comment by qwemaze** [comment]
@brianmhunt Yep, I know about some ko-es5 projects and I've tried to use one for a time, it was not satisfying experience from what I can say. I mean, it's fine and cool and useful and until you write custom bindings or external plugins or something like that.

As a way to fix the issue is to continue the knockout to a new version completely based on es5, still supporting old one for backwards compatibility. But it'll require people to either rewrite their plugins or stay with old ko. And it's kind of the problem with ko-es5 projects -- no one cares to support them because it's not official ko versions.

P. S.: To be honest, I just accidentally saw this line in the docs and was interested in what maintainers could say about. So probably the best solution would to replace the line with something like: "Originally, back in a days, because of consistency problems with browsers ko.observable objects were designed as functions and, due to backwards compatibility reasons they still remain so.".

**Comment by brianmhunt** [comment]
> best solution would to replace the line with something like: "Originally, back in a days, because of consistency problems with browsers ko.observable objects were designed as functions and, due to backwards compatibility reasons they still remain so.".

It's a good suggestion, thanks @qwemaze !
