### ISSUE TITLE
Replacing observableArray data when there is a beforeRemove handler causes refresh problems

### ISSUE THREAD

**Issue by jfrank14** [knockout/knockout#2083]
Also posted on SO here: http://stackoverflow.com/questions/38061382/replacing-observablearray-data-when-there-is-a-beforeremove-handler-causes-refre

I've got a system of notifications that refreshes on a timer. Say there are 4 records in the queue. If you're viewing the queue when the refresh happens, the underlying notifications array is replaced by a new array that also has 4 records. This displays fine.

But if I have a `beforeRemove` notification in place on the `foreach`, what happens is that I briefly see a refresh where 8 items display, and then it goes back to 4 items. This happens no matter how I update the array (simple replacement, removeAll and then replace, set to an empty array and add one at a time, etc.) This happens even if I never try to remove an element from the array.

This is quite frustrating, because I'd really like to be able to apply a transition, but can't figure out how to make it work without this glitch.

**Comment by brianmhunt** [comment]
Have you tried [knockout-fast-foreach](https://github.com/brianmhunt/knockout-fast-foreach)?

**Comment by mbest** [comment]
What you've described is how `beforeRemove` works. It allows you to delay the actual removal of the nodes. Thus if you replace the items in your array with new ones, you'll see both the old and new items on screen until the old ones are actually removed.

**Comment by mbest** [comment]
A comment in the code for this might be helpful:

> If there's a beforeRemove callback, call it after reordering.
Note that we assume that the beforeRemove callback will usually be used to remove the nodes using some sort of animation, which is why we first reorder the nodes that will be removed. If the callback instead removes the nodes right away, it would be more efficient to skip reordering them.
Perhaps we'll make that change in the future if this scenario becomes more common.

**Comment by jfrank14** [comment]
@mbest: Thanks for the reply. But now I'm not sure of the correct way to accomplish what I want to do. I've got an array of data that refreshes from the server every so often. I want individual adds and removes to be animated, say when a user clicks one of the rows, but when the source data changes entirely on refresh, I want to be able to suspend animation and reset the whole array in bulk. Is there any way to do that?

**Comment by mbest** [comment]
The only time `foreach` skips the callbacks is on the initial render. So if you could get the `foreach` binding to completely reset using some sort of the wrapper, it could be done:

```html
<div data-bind="resetOnRefresh: notifications">
    <div data-bind="foreach: {data: notifications, beforeRemove: hideNotification}">
        ...
    </div>
</div>
```

The custom `resetOnRefresh` is responsible for clearing and adding/rebinding the contents when the source data is refreshed.

**Comment by mbest** [comment]
Here's an idea for the `resetOnRefresh` binding that uses `if` and assumes that the array has been refreshed when it's been replaced with a new array object.

```javascript
ko.bindingHandlers.resetOnRefresh = {
    init: function(element, valueAccessor, allBindings, xxx, bindingContext) {
        var savedValue, ifValue = ko.observable(false);
        ko.computed(function () {
            var newValue = ko.unwrap(valueAccessor());
            if (newValue !=== savedValue) {
                savedValue = newValue;
                ko.observable(false);
                ko.tasks.runEarly();    // necessary if using deferred updates so that the 'if' binding sees the changes
                ko.observable(true);
            }
        }, null, { displayWhenNodeIsRemove: element });
        ko.applyBindingsToNode(element, {'if': ifValue}, bindingContext);
    }
};
```
