### ISSUE TITLE
Skipping notification if a reference type observable value did not change

### ISSUE THREAD

**Issue by cervengoc** [knockout/knockout#2084]
When using `ko.option.deferUpdates`, for primitive types there is a built logic which skips notification if the value of an observable has not effectively changed.

I'm in a situation where I use `valueHasMutated` on arrays, to implement batch modification handling (for example I have a `refill` method). The problem is that it invokes notifications and introduces problems in the application.

I think it would make sense to check *reference* types (arrays, functions, objects) for reference-equality in the default equality comparer. What do you think? Seems like a minor code change.

**Comment by mbest** [comment]
Arrays are meant to produce a notification even if the array's identity remains the same. For example, if you have `myObservableArray.push(x)`, the array's reference hasn't changed, but it's value has changed.

If you want, you can override an observable's `equalityComparer` function to check for other types of equality.

**Comment by cervengoc** [comment]
Yes, at the end of the day I saw the logic myself. I misunderstood the handling of array changes, I thought the `arrayChange` event always fires and dependency tracking mechanism listens to them separately.  Thank you for the help.

**Comment by cervengoc** [comment]
Hi @mbest, I've met just the same scenario but with an `object`. Could you please add some thoughts why there is no reference equality check for `object` types excluding arrays?

I mean there could be something like this

```
function valuesAreEqual(a, b) {
  var oldValueIsPrimitiveOrObject = (a === null) || (typeof (a) in primitiveTypes) || (typeof a === "object" && !(a instanceof Array));;
  return oldValueIsPrimitive ? (a === b) : false;
}
```

I see that there's a way to add our custom equality comparer, however the case when two non-array objects are equal by reference seems to be quite reasonable to handle by knockout.
