### ISSUE TITLE
Documentation - offline 

### ISSUE THREAD

**Issue by jonycodes** [knockout/knockout#2086]
The gh-pages site has some issues. The css doesn't load and when I try to navigate through the documentation, all the urls have this unusual `documentation/documentation`, see below:

http://knockoutjs.com/documentation/documentation/observables.html

If remove one `documentation` from the url I can load the page but the css still doesn't load.

**Comment by daedalus28** [comment]
Seeing this issue here as well

**Comment by rniemeyer** [comment]
I am working on a fix. The version of jekyll changed since the last time it was built and there is an issue with how variables are passed.

**Comment by rniemeyer** [comment]
The docs are back up. There is one minor pathing issue with a download link that I am still following up on it at the moment.
