### ISSUE TITLE
Removal of primitives from an observableArray using 'this'

### ISSUE THREAD

**Issue by massimocode** [knockout/knockout#2087]
Hi guys

I was working though a piece of knockout code with one of my students and noticed something quite interesting.

We have a viewModel that looks like this:
```javascript
var vm = {
    values: ko.observableArray([1, 1, 2, 2, 3, 3]),
    remove: function() {
        vm.values.remove(this);
    }
};
ko.applyBindings(vm);
```

And some markup that looks a little like this:
```html
<!-- ko foreach: values -->
<button data-bind="click: $parent.remove">Remove <span data-bind="text: $data"></span></button>
<!-- /ko -->
```

When you click any of the remove buttons, nothing happens. If you used objects instead of primitives then it would work fine. Expected behaviour would be that 2 items would be removed from the list for each button press when using primitives.

I believe the reason is that the primitives are boxed when being set as the `this` context within the click handler. Running this inside a console and it will print out false.
``` javascript
(function(){return this === 1;}).call(1)
```

I do acknowledge that the vm.remove method is a rather unorthodox way of doing things (not to mention less easily transportable!) and you would typically define it as a function that takes a value, then in the click binding do $parent.remove.bind($parent, $data).

Regardless, one way we could get around this is by checking if the type of the input passed into these helper methods on observable arrays is an object and, if so, using input.valueOf().

However part of me also thinks that the user should really be responsible for doing that and if they want to go about doing things in an unorthodox way then hey, it's up to them!

One thing I couldn't find when looking through the KO documentation for binding context (http://knockoutjs.com/documentation/binding-context.html) and the click binding (http://knockoutjs.com/documentation/click-binding.html) is mention of how `this` is bound. If we did have some mention of that, we could have a small note that users should keep in mind that primitives will be wrapped and therefore not equal to themselves.

What do you guys think?

**Comment by mbest** [comment]
This is an interesting issue, but probably not one that would come up much in actual development. In fact, the `click` documentation recommends using the first parameter to access the "current item":

    remove: function(item) {
        vm.values.remove(item);
    }
