### ISSUE TITLE
should the `with` binding always recreate the nodes?

### ISSUE THREAD

**Issue by opcodewriter** [knockout/knockout#2092]
I see `with` binding is recreating the DOM sub-tree each time the bound value changes.

```
<div data-bind="with: myData">
     <input data-bind="text: myValue" type="input">
</div>
```

Each time `myData` changes (for example calling `myData(newValue)` ) the `input` is recreated.
Why is it necessary for KO to recreate the `input` element, why can't it just update its value based on `myData().myValue` ?

**Comment by chrisknoll** [comment]
Well, if you are assigning a newValue to myData, wouldn't that mean that the input binding text: myValue would be something different?  the input binding is effectively accessing myData().myValue() so doesn't it stand to reason that if you change myData then myValue will need to be re-evaluated?

**Comment by chrisknoll** [comment]
I think I understand what you're saying tho:  why is the DOM being torn down and re-created? Maybe just easier to implement but I agree, since the content below the with: binding is static, it should just be a matter of a dependency tracking on the child-bindings up to the binding to the observable in the with:binding and any change in with should signal the change in the children.

**Comment by opcodewriter** [comment]
I can only guess that the reason why it's DOM is being recreated is because it covers the case when bound value is `null`.
In this case, the DOM has to be removed.

Is there other way to create a child context in the way `with` is doing, but without recreating the DOM sub-tree when bound value changes?
This is helpful to "shorten against nested objects/models and helps to keep your data-bind attributes from becoming too verbose" (as mentioned here http://www.knockmeout.net/2012/03/knockoutjs-performance-gotcha-ifwith.html).

**Comment by IanYates** [comment]
The trick is that if you have some variable
```
var myObservable = ko.observable({
   innerOb: ko.observable(1)
});
```

and HTML like
```
<div data-bind="with:myObservable">
    <input data-bind="value: innerOb"/>
</div>
```

If I swap out myObservable like this
```
myObservable( {
    innerOb: ko.observable(6);
} );
```

You need to then think what actual observable is that `<input>` tag using.  Currently with the DOM tear down, the div's inner html is rendered again and the input's value is bound to the new `innerOb`.

To do this without tearing down the DOM would require KO to wrap the `innerOb` that's provided to the value binding as a read/write computed of the form
```
valueBinding = ko.computed({
    read: function() {
        return myObservable().innerOb();
    },
    write: function(value) {
        myObservable().innerOb(value);
    }
});
```

Maybe that could be done.  You could do it manually on your view model by flattening out your object model, making such computeds manually yourself.  Where it gets tricky is if you wanted to pass that observable around and have it retain some sort of identity, attached properties, etc (many KO extensions tack stuff onto observables).  Having it silently wrapped in a computed would make such things tricky.

I could see you could write a bindings preprocessor to do this conversion by hand.  It wouldn't be trivial, and you'd probably want to use pureComputed to avoid a pile-up of computeds not being evaluated or required.

Are you running in to perf issues?

Also, the above code took out the null handling :)  You'd need that in there too!

**Comment by chrisknoll** [comment]
The process of wrapping up the data into a computed observable sounds like the operation that happens in the component bindings. If the with: above was replaced with a component (where the observables are passed in as a parameter) wouldn't that mean that the component DOM will not be torn down even if one of the parameter observables change?

**Comment by mbest** [comment]
There are historical reasons for this, and changing the `with` binding to not recreate the nodes would be a breaking change. See #1811 for an alternate binding that should be in the next version.
