### ISSUE TITLE
Add a default value to allBindings.get() as a second parameter

### ISSUE THREAD

**Issue by mochar** [knockout/knockout#2094]
Currently, when the binding you're trying to get() does not exist, you can use the || operator to use a default value ([as is shown in the docs](http://knockoutjs.com/documentation/custom-bindings.html)):

`var val = allBindings.get('doesNotExist') || 1 // val = 1`

The problem arises when the binding does exist, but is falsey:

`var val = allBindings.get('isFalse') || true // val = true`

Inspired by Python's dict.get, adding a second "default" parameter would be appreciated:

`var val = allBindings.get('isFalse', true) // val = false`

I think a simple null check [here](https://github.com/knockout/knockout/blob/master/src/binding/bindingAttributeSyntax.js#L347) would suffice, but I'm not good enough with Javascript to be sure!

**Comment by mbest** [comment]
You're correct that the `||` method only works if a falsy value isn't valid. Another method is to make use of `has()`:

```
var val = allBindings.has('isFalse') ? allBindings.get('isFalse') : true // val = false
```

**Comment by mochar** [comment]
Thanks for the quick response. Definitely what I'm going to do from now on. It's just a small think that would be nice to have, but definitely not necessary.

**Comment by mbest** [comment]
Great. I'm closing this since I think the existing features are sufficient.
