### ISSUE TITLE
$parents[2] breaks attribute parsing

### ISSUE THREAD

**Issue by mb1069** [knockout/knockout#2097]
https://jsfiddle.net/b76fp0zz/1/

When referencing $parents[2] to create multiple radio buttons (each should have different names, example is minified, the aim is a sequence of different fields each with multiple radio buttons), the following error is thrown:

    Message: Unable to process binding "template: function (){return {name:'input-state',data:{val:val,mask:$parent.mask,filter:$parent.mask}} }"
    Message: Unable to process binding "if: function (){return $data!=undefined }"
    Message: Unable to parse bindings.
    Bindings value: attr: {name: 'filter_rad'+(parseInt($parents[2].bitNum)+$index()),
                                            bitNum: $parents[2].bitNum+$index()},
                                            checked: $root.ui.filter_bit_value()[parseInt($parents[1].connectordata.bitNum)],
                                      
    Message: Unexpected token )
    Stacktrace: 
    createBindingsStringEvaluator	@	knockout-3.4.0.debug.js:2936
    createBindingsStringEvaluatorViaCache	@	knockout-3.4.0.debug.js:2927
    parseBindingsString	@	knockout-3.4.0.debug.js:2913
    getBindingAccessors	@	knockout-3.4.0.debug.js:2895
    ko.dependentObservable.disposeWhenNodeIsRemoved	@	knockout-3.4.0.debug.js:3245
    evaluateImmediate_CallReadThenEndDependencyDetection	@	knockout-3.4.0.debug.js:2142
    evaluateImmediate_CallReadWithDependencyDetection	@	knockout-3.4.0.debug.js:2114

Printing $parents[1].connectordata.bitNum returns a number

**Comment by IanYates** [comment]
You have a stray "}"

`bitNum: $parents[2].bitNum+$index()}`
should be
`bitNum: $parents[2].bitNum+$index()`

Running your fiddle with the F12 tools in Chrome made the problem apparent.

**Comment by mb1069** [comment]
Thanks for the response, that does seem to fix it! I've also re-written the code to pass the variables down as the data of each template, but I have a question for your solution (updated fiddle: https://jsfiddle.net/puxLskrn/1/): the attr {} binding is not closed, it has an opening { but no closing }

    data-bind="attr: {name: 'filter_rad'+(parseInt($parents[2].bitNum)+$index()),
                                            bitNum: $parents[2].bitNum+$index(),
                                            checked: $root.ui.filter_bit_value()[parseInt($parents[1].connectordata.bitNum)]

**Comment by mb1069** [comment]
Having said that, removing the checked attribute from the data-bind seems to also fix the issue, with or without the }

**Comment by IanYates** [comment]
Ahh yes.  So you want to set the name attribute and bitNum attributes?

```
data-bind="attr: {
    name: 'filter_rad'+(parseInt($parents[2].bitNum)+$index()),
    bitNum: $parents[2].bitNum+$index()
    },
    checked: $root.ui.filter_bit_value()[parseInt($parents[1].connectordata.bitNum)]"
```

I must admit, it's hard to reason about using $parents[1], $parents[2], etc and makes things brittle when you move them around.  Search this issues forum for things like 'alias' and 'as' bindings - there have been a few discussions recently.  You can name your scopes so you don't have to refer to them by parent index.  That should help a LOT with readability.

**Comment by mb1069** [comment]
Absolutely, I've converted everything to use $data and $parent. Does the version of the data-bind you last posted work for you? I only get a single radio button in jsfiddle

**Comment by IanYates** [comment]
I've just tried it (I didn't bother before).

$root.ui is undefined, so filter_bit_value() call fails, etc.  That doesn't quite fit with the error message though.

**Comment by IanYates** [comment]
Debugging tip.  Use Chrome F12 tools.  Inspect the node in question (your radio button).  Use the console to execute `ko.dataFor($0)` and `ko.dataFor($0)`.  That will give you access to what $data and $context will give you.  Then you can manually type some of your binding expressions in the console to see what you get.  That's how I found `ko.contextFor($0).$root.ui` was undefined.

**Comment by mb1069** [comment]
Replacing $root.ui.... with true does seem to make it work :D But yeah I think error message could do with some modification. Thanks for the tip!

**Comment by mbest** [comment]
The problem is from nested brackets in the checked binding. See #911.

**Comment by mb1069** [comment]
Thanks for the review, I'll close this one as a duplicate of the other

**Comment by mbest** [comment]
No problem. #911 also includes a workaround, which is to enclose the value in parentheses:

    checked: ($root.ui.filter_bit_value()[parseInt($parents[1].connectordata.bitNum)])
