### ISSUE TITLE
Using nodes within template binding does not take returned value into account

### ISSUE THREAD

**Issue by cervengoc** [knockout/knockout#2104]
Consider a situation where the viewmodel itself has control over the template contents.:

```
var model = {
  dataTemplate: ko.observable(), // can be an ID string, HTML string or Node array, or empty to use the child nodes as contents
  data: ko.observable()
}

function isTemplateName(template) {
  return typeof template === "string" && template.length && template.charAt(0) == "#";
}

function getTemplateNodes(template) {
  if (template && template.length) return template;
  if ("template is HTML string")
    return ko.utils.parseHtml(template);
  return null;
}

<div data-bind="template: { name: isTemplateName(dataTemplate()) ? dataTemplate() : null, nodes: getTemplateNodes(dataTemplate()) }"></div>
```

With the current implementation, if `dataTemplate` is empty, it will still use the `nodes` value because the value is actually not checked, only the existence of the `nodes` proeprty is checked. The correct behavior would be to fall back to child nodes, like there were no `nodes`, nor `name`.

**Comment by cervengoc** [comment]
At my PR I've just noticed the failed tests (which I don't know yet why it didn't fail at me locally).
So it seems like this logic was un purpose. Could anyone explain why?

**Comment by mbest** [comment]
From the comment associated with the test *Should interpret "nodes: anyFalseyValue" as being equivalent to supplying an empty node array*:

> This behavior helps to avoid inconsistency if you're programmatically supplying a node array but sometimes you might not have any nodes - you don't want the template binding to dynamically switch over to "inline template" mode just because your 'nodes' value is null, for example.

**Comment by cervengoc** [comment]
Sorry I wasn't even checking the code for comments. I see now, however I personally don't like this. 

1. If someone uses nodes, and have no nodes at some moment, then it should pass an empty array. I think a `null` value should mean that *I'm not using `nodes` now*.
2. If someone wants to prevent KO from using the inline template, then he shouldn't put anything there. I mean what can be the point for defining inline contents when it can never be used?

But for now I can work this around at my project anyway.
