### ISSUE TITLE
valueAllowUnset is true, adding options should check value and select that option

### ISSUE THREAD

**Issue by mgildea** [knockout/knockout#2109]
when a select element has zero options, the value is bound to an observable, and valueAllowUnset is true, this allows for the observable to maintain the original value regardless of the available options in the select element.  If we later add options (via ajax or some other method), and one of those options equals the observable value, shouldn't that option then be auto selected?

**Comment by cervengoc** [comment]
As far as I can remember it should update the selected option. Could you put together a test case reproducing this?

**Comment by mgildea** [comment]
I was able to find the problem within my own code.  Closing this issue.
