### ISSUE TITLE
attr-binding does not update checkbox after user interaction

### ISSUE THREAD

**Issue by kimgronqvist** [knockout/knockout#2114]
Currently, the attr-binding only adds and removes the attribute on the element. But most browsers ignore this attribute if a user has already clicked on a checkbox. The only way to update a checkbox after that is to set the property checked on the element.

```html
<input type="checkbox" 
           data-bind="attr: { checked: data.visible }, click: data.toggleVisibility" />
```

I realize the checked-binding fixes this, but I prefer not using twoway-data binding if I can avoid it.

To fix this, attr.js would need to be updated with something like this:

```js
if (attrName === "name") {
  ko.utils.setElementName(element, toRemove ? "" : attrValue.toString());
}
if (attrName === "checked") {
   element.checked = attrValue;
}
```

**Comment by ourfeel** [comment]
<input type="checkbox" 
           data-bind="checked: data.visible" />

**Comment by kimgronqvist** [comment]
Thanks, but that doesn't really help me as I want to avoid the checked-binding from writing directly to `data.visible`.

**Comment by mbest** [comment]
You can wrap `data.visible` in a computed, thus making it read-only:

```
data.visibleReadOnly = ko.pureComputed(data.visible);
```

**Comment by mbest** [comment]
Another option is to unwrap the observable in the binding. This passes the value to the binding rather than the observable and thus makes it read-only:

```
<input type="checkbox" data-bind="checked: data.visible()" />
```

**Comment by kimgronqvist** [comment]
@mbest: Thanks! Using a computed worked nicely for my use case. I also needed to return true from the click handler for things to work as expected.

I'm still a bit surprised that the attr-binding isn't reactive though.

**Comment by mbest** [comment]
The `checked` attribute and `checked` property are not equivalent. In fact, the `checked` attribute maps to a `defaultChecked` property. This is similarly true for `value`. Both `checked` and `value` have their own bindings in Knockout.
