### ISSUE TITLE
knockout new template engine

### ISSUE THREAD

**Issue by jmvtrinidad** [knockout/knockout#2115]
Is there a way to change how knockout binds in html? Or is there any library that does it?

**Comment by brianmhunt** [comment]
Yep - look at the [template binding](http://knockoutjs.com/documentation/template-binding.html) or consider looking into creating custom binding.  There are some examples at the bottom of the template binding page linked.

Will close this on the basis that it's not an issue with KO per se, but please share if there's some room for improvement and we can re-open. :)

**Comment by jmvtrinidad** [comment]
Sorry, I didn't eloborate my question.
Is there away to change html bindings like instead using `data-bind="value:observable"`, knockout will look for `[value]="observable"`.

**Comment by brianmhunt** [comment]
Got it.  There are a few options.

First, have a look at KO Punches https://mbest.github.io/knockout.punches/  See if that does what you want.

Alternatively, consider a [custom preprocessor](http://knockoutjs.com/documentation/binding-preprocessing.html).

**Comment by jmvtrinidad** [comment]
This is awesome, I will explore it. Although there are other frameworks out there, ko is just right for our needs. Thanks!
