### ISSUE TITLE
IE 11 - KO performance with our application is 5~10 times slower than Chroeme.

### ISSUE THREAD

**Issue by erg-hzhou** [knockout/knockout#2117]
Knockout for our application has a very good performance result with Chrome however it's 5~10 times slower in IE 11 even crashed. Does anyone have encountered it or any solution or workaround? Thanks in advance.

**Comment by brianmhunt** [comment]
You might have better luck getting an answer to this by giving a demonstration of what you do and perhaps posting to a Q&A site like StackOverflow.
