### ISSUE TITLE
How can I unwrap the custom element when the component after render

### ISSUE THREAD

**Issue by zhengnz** [knockout/knockout#2119]
eg:
```
<tab></tab>
```

afterRender:
```
<tab>
    <div class='tab'></div>
<tab>
```

How can I get the code like this:
```
<div class='tab'></div>
```

**Comment by mbest** [comment]
That's not supported. The outer element must remain to enable updates.

**Comment by IanYates** [comment]
You could use the comment based syntax, rather than a custom element
