### ISSUE TITLE
can selectedOptions.optionsText support multiple columns?

### ISSUE THREAD

**Issue by KantJoe** [knockout/knockout#2120]
for example:
this is array being used
ViewModel.x=[{"n1":"1","n2":"2","v":1},{"n1":"1","n2":"2","v":2}]

<select class="m-wrap span12" data-bind='options: $root.x,optionsText:"n1&_&n2",optionsValue:"v",optionsCaption:"全部", value: $root.y'></select>

if it can be,how do i do?thx

**Comment by KantJoe** [comment]
i found the answer:
optionsText: function(item) {
                       return item.n1+ ' (pop: ' + item.n2+ ')'
                   }
---------------------------
but it doesn't support '       '(this is a long whit space) ...

**Comment by mbest** [comment]
Since it's Javascript, you can include Unicode characters in the string: `'\u2003'` is an em space.

https://en.wikipedia.org/wiki/Whitespace_character
