### ISSUE TITLE
Using an existing viewmodel object structure with component bindings

### ISSUE THREAD

**Issue by cervengoc** [knockout/knockout#2122]
We have a whole lot of prepared Knockout viewmodel classes, similar to these. Some of them are really complex, holding 20-30 properties including nested viewmodels, and viewmodels collections too.

```
function Customer() {
  this.name = ko.observable();
  ...
  this.orders = ko.observableArray([]);
}
Customer.prototype.addOrder = function(order) {
  this.orders.push(order);
}
...
function Order() {
  this.date = ko.observable();
  ...
}
```

We create a viewmodel instance manually before binding, and initializing it with values for example from server, or from URL parameters, etc. Then if the initial model is prepared, we call `applyBindings`. It works somehow like this.

```
var customer  = new Customer(); 
customer.name = "Test";

var order = new Order();
order.data = new Date();
customer.addOrder(order);

ko.applyBindings(customer);
```

I'm thinking about a future refactoring of this system to use components, so that we'd have one component per viewmodel class, something like this.

```
ko.components.register("Customer", {
  viewModel: Customer,
  template: "<strong data-bind='text: name'></strong><ul data-bind='foreach: orders'><li data-bind='component: "Order"'></li></ul>"
});

ko.components.register("Order", {
  viewModel: Order,
  template: "<span data-bind='text: date'></span>"
});
```

I'm not too familiar with components yet, but currently as far as I can understand, each time a component is activated via a `component` binding, a new instance of its associated viewmodel will be created *somehow* (via constructor or factory, etc.). However, in our current system we have an already prepared viewmodel instance, which might hold several other nested viewmodel instances too (see `customer.orders` in my example).

I'd like to activate component bindings with existing viewmodel instances grabbed from a previously prepared viewmodel structure. Is it possible?

**Comment by cervengoc** [comment]
FYI, I've posted this question on StackOverflow [here ](http://stackoverflow.com/questions/39488057/passing-existing-model-to-knockout-component-binding/39491314?noredirect=1#comment66302679_39491314) where user TSV gave a workaround using kind of *transient* viewmodel constructors.

**Comment by jlaustill** [comment]
I'm following this with enthusiasm.  I am having a very hard time understanding components and how they are even meant to be used.  I've gone through the tutorial examples and created some, but I just don't see how to apply them to my projects or what use they have over standard templates.  I think maybe I am missing an important piece of the picture, and this issue is right on track with my line of thinking.  I can't wait for that aha moment :)

**Comment by sumitkm** [comment]
I managed wrap my head around components after Steve's NDC talk here -> https://vimeo.com/97519516

A bit of self-plug, I did write a multi-part series on how to get started with KO Components, starts here ->  https://sumitmaitra.wordpress.com/2014/07/19/dipping-your-feet-into-knockoutjs-components/

Hope this helps :-)

**Comment by sumitkm** [comment]
@cervengoc one easy way to do it is to make the existing viewmodel a property in the component's viewmodel. This will be the top level component. 

There on, you can go on creating nested components and pass the next level of your viewModel as another property via the child component's "params".

**Comment by jmvtrinidad** [comment]
It is better to [load component](http://knockoutjs.com/documentation/component-registration.html) using AMD instead of putting directly the markup inside `template option`.

You can use this helper function to register your components
```
function registerComponent(name, path) {
    ko.components.register(name, {
        viewModel: { require: path },
        template: { require: 'text!'+ path +'.html' }
    });
}
```
You can use it like this
```
require.config({
    baseUrl: baseUrl('app'),
    paths: {
        'text': "../Scripts/text",
        'widgets': "widgets",
        'app': "."
    }
});
registerComponent('pagination', 'widgets/pagination/pagination');
registerComponent('feature1', 'app/feature1/index');
registerComponent('feature2', 'app/feature2/index');
```
And structure your app like this
```
app
|---feature1
     |---index.js (viewModel)
     |---index.html (view)
|---feature2
     |---index.js (viewModel)
     |---index.html (view)
|---widgets
     |---pagination
               |---pagination.js (viewModel)
               |---pagination.html (view)
```
In this way you can separate your concerns by feature.

You can also use this [custom component loader](https://gist.github.com/jmvtrinidad/7e59bf9be127451fe5bfd293721cfe10) to use angular2 html like binding instead of `data-bind`.

**Comment by cervengoc** [comment]
Thank you guys, I'll watch that video when I have time. Other than that I don't feel I'm closer to the point :).

**Comment by jmvtrinidad** [comment]
Hi @cervengoc ,
Just a suggestion.
Can you separate your model into your viewModel?
```
function Customer() {
  this.name = ko.observable();
  ...
  this.orders = ko.observableArray([]);
}

function CustomerViewModel(params){
this.customer = params.customer;
}
CustomerViewModel.prototype.addOrder = function(order) {
  this.customer.orders.push(order);
}

...
function Order() {
  this.date = ko.observable();
  ...
}
```
Then if you separate your app into components you only need to pass `customer` from `customerViewModel` to other components just like `order component`.

**Comment by cervengoc** [comment]
@jmvtrinidad The problems I see with this are

1. I'd introduce kind of a new layer for almost nothing.
2. I'd still create another object graph.
3. I'd loose some measure of unit testability of the system on its own. Note that in these model classes I may have computeds, other logic, etc. which should all work without even data-binding.

So I still don1t get the point at all. I don't quite understand why components force creating a new viewmodel object.

By the way, I know about the ability to define components without the `viewModel` option, so they actually bind the `params` object, which would be a viable option in pure technical sense. However, for the sake of code readability and consistency I'd prefer defining the `viewModel` constructor, but still be able to pass an existing instance at binding time. I hope you get my points.

**Comment by kimgronqvist** [comment]
(This is more of an answer to the questions about what components bring to the table).

You don't need to use components. Classical Knockout works well for small and medium-sized apps, and - as you say - just add another layer for no benefit. Where components shine is reusability, composability and encapsulation in massive applications with complex UI. 

In the application I work on (50k+ loc), a component is just not a "template with a view model". It is a self-contained unit that has it's own styles, markup, and data. 

Generally we have two types of components: "Controller" components that accept some view model, starts data fetching and deals with more application specific code. And components that are just pure view representation of their data.

A typical controller component could look something like this (store is just a view model):

```js
import todosStore from 'Stores/TodosStore';
import todosTemplate from './Todos.html';
import './Todos.less';

class Todos {
    constructor({ viewId, store = todosStore }) {
        this.store = store;

        this.sortedTodos = ko.pureComputed(() =>
             this.store.sortedByDate.filter(r => r.viewId === viewId);
        );

        this.store.fetchTodos(viewId);
    }
}

export default {
    viewModel: Todos,
    template: todosTemplate
};
```

**Comment by jmvtrinidad** [comment]
Hi @cervengoc,
See this [JSFiddle](https://jsfiddle.net/jmvtrinidad/7t03nyok/4/) for demo. Instead of passing your Customer class in your component registration, you need to create a function that will extend itself from `params.data`, something like this one.
```
function CustomerViewModel(params) {
    ko.utils.extend(this, params.data);
  }
```

**Comment by jlaustill** [comment]
So if I'm following this right, what I'm getting out of this is that components are like angular directives in a sense.  And that they aren't meant for every case, only cases where you need to reuse the code over and over?  So in my project, it might sense to create a communication popup component that takes an employee as a parameter since I use these freaking everywhere on my site.  But it might not make sense to turn my chatbox into a component since it's only used in one place and doesn't really even make sense to reuse it?  

Is this even remotely on key?

**Comment by kimgronqvist** [comment]
That's certainly one aspect of it, yes :) I do think it's fine to use components as an alternative for templates, though. You might get some redundant view models, but your templates become a lot more readable, and you don't have to worry about having templates in your DOM.

Consider a component `chat-box`:

```html
<div class="my-app-chat-box">
   <div class="messages" data-bind="foreach: messages">
       <chat-box-message params="message: $data"></chat-box>    
   </div>
   <chat-box-settings params="settings: settings"></chat-box-settings>
</div>
```

**Comment by cervengoc** [comment]
Ok, I've just realized what @sumitkm  ment by making my existing class a property of the component `viewModel`. That actually makes sense. Then one could put (I guess) additionaly, stricktly view-related stuff in there too, like view-related computeds, etc.

But to be honest I still don't see so big of an advantage over having a nice viewmodel class structure + templates. At least I now know a way of joining the two concepts.
