### ISSUE TITLE
ViewModel lost ChildNode observable()

### ISSUE THREAD

**Issue by KantJoe** [knockout/knockout#2128]
```
var ViewModel={
  model:ko.observable(new Car(null)),
  toSelect:function(data){
    var c = new Car();
    ViewModel.model(data||c);
    //here has a problem
  }
};

function Car(data){
  var self=this;
  self.ID=ko.observable("");
  self.Name=ko.observable("");
  if(data!=null && data!=undefined){
    self.ID(data.ID);
    self.Name(data.Name);
  }
}
ko.applyBindings(VIewModel);

ViewModel.toSelect(somedata);//here
```

after i fill data in model,it's lost 'ID',like:
```
{ID:c()
Cc:65
K:Object
Nb:2
arguments:null
caller:null
length:0
name:"c"
prototype:Object
Symbol(_latestValue):undefined}
```

...it looks all node which has this problem because it's name include'id' character.is it means my knockoutjs-3.4.0.min.js has been change by someone or some bug in it?
thx

**Comment by KantJoe** [comment]
newly report,if i remove puredComputer() from Viewmodel,this problem disappear too.

**Comment by mbest** [comment]
In your code, `model` is an observable. See http://knockoutjs.com/documentation/observables.html about reading and writing observables.

But usually you only want to use an observable for a model object if you need to update the model object itself (like linking to a new object).
