### ISSUE TITLE
Omitting data-bind from generated DOM nodes

### ISSUE THREAD

**Issue by nerdcave** [knockout/knockout#2131]
When knockout generates DOM elements, couldn't it just omit the data-bind from the actual HTML? For example, this:

```html
<ul data-bind="foreach: people">
  <li data-bind="text: name, visible: !hidden, css: { orange: name.length > 3 }"></li>
</ul>
```

Will generate:
```html
<ul data-bind="foreach: people">
  <li data-bind="text: name, visible: !hidden, css: { orange: name.length > 3 }">Bob</li>
  <li data-bind="text: name, visible: !hidden, css: { orange: name.length > 3 }" class="orange" style="display: none;">Jimmy</li>
  <li data-bind="text: name, visible: !hidden, css: { orange: name.length > 3 }" class="orange">Mike</li>
</ul>
```

All those data-binds create lot of excessive HTML, especially with longer lists. Any reason it can't just generate:
```html
<ul data-bind="foreach: people">
  <li>Bob</li>
  <li class="orange" style="display: none;">Jimmy</li>
  <li class="orange">Mike</li>
</ul>
```

Because aren't bindings already applied under the hood?

**Comment by cervengoc** [comment]
The "generated" nodes don't imply any kind of *HTML generation*. Those nodes exist only in memory, and you can examine them from there when using a dev tool or so. Only overhead here is that those nodes indeed have the `data-bind` attributes. But not "HTML". I agree though that it kind of pollutes the readability of the DOM.

Attributes semantically used to mean kind of an *initial state* of a node. Hence theoretically they should not be removed, because one could expect them to exist when for example manually cloning a node, etc.

But I think it's not a bad idea to make it possible at least to opt-in for removing the `data-bind` attributes after all bindings have been applied to a specific node.

**Comment by brianmhunt** [comment]
As a thought - ko could remove the binding attributes after bindings are applied.  

We should probably expose a post binding processing hook so a plugin that does this would be trivial.

**Comment by chrisknoll** [comment]
So, if you remove it you won't know what value from your model the node is bound to. Where did Jimmy and Mike come from?  Which CSS was static vs calculated?  I think this is a negative.  Secondly, @nerdcave gave his example, he left the data-bind in the for-each part. Why?

What if you had:

```` javascript
<div data-bind="foreach: classroom">
People in class: <span data-bind="roomName"></span>
<ul data-bind="foreach: people">
  <li data-bind="text: name, visible: !hidden, css: { orange: name.length > 3 }">Bob</li>
  <li data-bind="text: name, visible: !hidden, css: { orange: name.length > 3 }" class="orange" style="display: none;">Jimmy</li>
  <li data-bind="text: name, visible: !hidden, css: { orange: name.length > 3 }" class="orange">Mike</li>
</ul>
</div>
````

Would the outer foreach stay, but inner be gone?  Should this really apply to only generated nodes?  wouldn't it be confusing to see sometimes data-binds and other times not?

Leave 'em in.  It's just the way it's done.  Of course if you're really concerned, making it an opt-in post process would be something, but just something I wouldn't leverage :)


-Chris

**Comment by cervengoc** [comment]
@chrisknoll yes I ment something like that. Completely agree.

**Comment by nerdcave** [comment]
@cervengoc Good point about the semantics of initial state (although, I can also see an argument for the post-binding processed node to be its initial state). But yeah, readability of the DOM is the issue I have.

@brianmhunt A post-binding processing hook sounds like a great idea!

@chrisknoll Looking at your original template code (vs. generated) shows you how the node relates to the model, so I don't see a problem there (maybe I'm misunderstanding you). But yeah, I'm only suggesting this for nodes that knockout generates dynamically, so the data-bind would remain on any "static" nodes. To me, that seems like a pretty clear distinction that wouldn't be confusing when you view the generated DOM.

Either way, this would be nice as an opt-in or plugin. It seems perfectly reasonable to me to treat dynamically generated nodes differently, but I'm not necessarily suggesting knockout do this by default.

**Comment by mbest** [comment]
Here's a solution I put together some time ago:

```javascript
ko.bindingProvider.instance.getBindingsString = (function (originalFunc) {
    return function (node, bindingContext) {
        if (node.__savedBinding) {
            return node.__savedBinding;
        }
        var binding = originalFunc.call(this, node, bindingContext);
        if (binding && node.nodeType == 1) {
            node.__savedBinding = binding;
            node.removeAttribute('data-bind');
        }
        return binding;
    }
})(ko.bindingProvider.instance.getBindingsString);
```

http://stackoverflow.com/a/23620576/1287183

**Comment by nerdcave** [comment]
@mbest Thanks! I'll close this out since it's clear there's no built-in way to do this in knockout, and seems to be more of a personal preference thing.
