### ISSUE TITLE
Issue with text binding on nodes that get added and removed from the DOM

### ISSUE THREAD

**Issue by Retsam** [knockout/knockout#2134]
I'm trying to properly implement a bootstrap popover in a KO binding handler, and I'm running into an issue where the text binding breaks if the observable it's attached to updates while the popover element isn't in the DOM.

**Version:** 3.4

**Steps to reproduce:**

1.  Create a DOM element and apply a text binding to it
2.  Add the DOM element to the DOM and remove it from the DOM
3.  Update the observable bound to the text binding
4.  Add the element back to the DOM

**Actual behavior:**

The text binding no longer reflects the correct value of the observable, and doesn't update when the observable changes.

**Sample:** http://codepen.io/Retsam/pen/ORgAyd

---

It might just be that this sort of thing isn't supported by KO; but I didn't see that stated anywhere in the docs.

**Comment by jmvtrinidad** [comment]
`popover` was detaching the element from the DOM, and it seems `ko` will no way to know when the element is reattached to DOM, so it lost track to element.
But a quick fix for this is to re-bind your title element. See updated [demo](http://codepen.io/anon/pen/jrLxLO?editors=1010). It also includes detached demo.

```
$(buttonEl).on('show.bs.popover',() =>{
  ko.cleanNode(header)
  ko.applyBindingsToDescendants(childContext, header);
});
```

**Comment by mbest** [comment]
All bindings will stop if you remove elements from the DOM. It's how Knockout works.

**Comment by Retsam** [comment]
@jmvtrinidad Thanks; the `cleanNode` and reapply trick seems to fix my issue.

@mbest
Is that documented anywhere?  

And plus, that isn't how it currently works: all bindings don't stop when you remove an element from the DOM, they generally seem to work, except if you hit an edge case like this one.  And "looks like it works, but actually has some surprising pitfalls" is a rather unfortunate state to be in.

**Comment by mbest** [comment]
@Retsam I don't think it's documented. And you're right that it might not be all bindings. A binding will stop working only if it receives an update while it's removed from the DOM.
