### ISSUE TITLE
Load Timeout when using RequireJS and Knockout is bundled with jQuery.

### ISSUE THREAD

**Issue by pimbrouwers** [knockout/knockout#2135]
I am relatively new to Require, but feel I have a pretty firm grasp on how things work. Knockout on the other hand, is without a doubt my favorite "technology" today (and I'm not even overly passionate about client-side programming). Anywhoooooo

Recently, when taking a site into product I noticed a strange problem. I would receive intermittent Load Timeouts for Knockout. It wasn't until I played around with my bundling (relentlessly) that I discovered the culprit was the bundling of Knockout and jQuery. As soon as jQuery is moved into a different bundle, the problem magically disappears. And of course, with bundling disabled everything works perfectly as well.

I realize there isn't a ton of context to go off here. But felt this would at least get the discussion going and perhaps someone else has noticed a similar issue. I am more than happy to provide any code samples if needed.

For reference, I am using the built-in building within .NET MVC.

**Comment by cervengoc** [comment]
Pay attention when using the built-in bundling stuff, because it *might* also minify the source files, which *might* break something in knockout, as it provides its own minification implementation.

**Comment by pimbrouwers** [comment]
This doesn't make much sense to me. I'm using both of the vendor supplied minified files. Additionally, the MVC bundler simply appends them together, which I've verified is the case. No other manipulations are occurring.

**Comment by cervengoc** [comment]
Okay, it was just a tip because I had some serious headaches with the MVC bundling framework. I was actually happy to migrate to `gulp` and friends.

**Comment by pimbrouwers** [comment]
For sure. Great point.

Likewise. The new tooling in VS is great.
