### ISSUE TITLE
Awesome Knockout-Decorator library.

### ISSUE THREAD

**Issue by Eisenspalter** [knockout/knockout#2137]
Check this out.:
[knockout-decorators]https://github.com/gnaeus/knockout-decorators)

**Comment by caseyWebb** [comment]
Perhaps a PR to [awesome-knockout](https://github.com/knockout/knockout/issues/2137) is in order?

**Comment by IanYates** [comment]
I hadn't heard of `awesome-knockout`.  @caseyWebb thanks.  Fixed link too - should be https://github.com/dnbard/awesome-knockout

**Comment by jmvtrinidad** [comment]
It will be best combined with variotry [knockout-decorator](https://github.com/variotry/knockout-decorator) as it uses knockout-es5 like syntax for creating observable.
