### ISSUE TITLE
AMD Component Render - Can't Render Named Modules

### ISSUE THREAD

**Issue by pimbrouwers** [knockout/knockout#2138]
The following will load:
```
define(['knockout', 'text!../Scripts/app/components/templates/loader.html'], function (ko, html) {
    function Loader(params) {
        var self = this;

        self.visible = params.visible
    };
    
    return { viewModel: Loader, template: html };
});
```

The following returns "undefined" from "possiblyGetConfigFromAmd()":
```
define('loader', ['knockout', 'text!../Scripts/app/components/templates/loader.html'], function (ko, html) {
    function Loader(params) {
        var self = this;

        self.visible = params.visible
    };
    
    return { viewModel: Loader, template: html };
});
```

**Comment by chrisknoll** [comment]
are you require()-ing a moduleId called 'loader' that would resolve to this .js file?

**Comment by pimbrouwers** [comment]
Thanks for the response Chris.

What turned out to be the issue, was that the named component file was being called in using the direct path to the file. Given that require can throw errors if you're requesting modules using different aliases, I'm guessing this was causing the issue.

**Comment by chrisknoll** [comment]
Yeah, when you define(['module1','module2']) or requirejs(), those aren't paths to files (tho sometimes they closely resemble them) but rather those are moduleIds that you're requesting. I think in certain circumstances you can put a path to a file (maybe in the case of some plugins?) but it's always safest to request things by a module ID and use paths to help you navigate from the moduleId to the physical file.
