### ISSUE TITLE
Option to disable console.warn

### ISSUE THREAD

**Issue by jogibear9988** [knockout/knockout#2140]
We should have a setting to disable the Console.Warn

**Comment by mbest** [comment]
Knockout doesn't include any console.warn.

**Comment by brianmhunt** [comment]
Closing since there is no indication how knockout could fix this - please comment if there's more to it and we can reopen.

**Comment by jogibear9988** [comment]
Oh, I'm so silly. It was added from my Pull Req. See https://github.com/knockout/knockout/pull/2016/files

But I need the Try/Catch here
