### ISSUE TITLE
"with:" binding statement behaviour using $parent

### ISSUE THREAD

**Issue by koljagava** [knockout/knockout#2143]
Hi there, 
first of all thank you for your work.
I'm trying to creating a custom component having some inner markup that should refer to the caller bindingContext, because the inner markup refers to caller $data and $parent, 
for $data there is no problem due to the data option on template binding, but what about its $parent ?

I found a crappy solution changing ko.bindingContext.prototype['createChildContext'] function 
setting self["$parent"] in this way : 
`self['$parent'] = parentContext['$parent'] === self["$data"] ? parentContext['$parents'][1]:parentContext['$data'];`

no idea how to handle self['$parents'] :/
what do you think about it ?
is there a clean way to do it ?

thank's in advance
kolja
**jsfiddle example** : [https://jsfiddle.net/koljagava/nyh565xp/]

**Comment by brianmhunt** [comment]
@koljagava – As a support question, you will have more success on stackoverflow or gitter.im/knockout/knockout

If there is something you think would improve Knockout please note it here.  I will close this issue just to clean it up, but if there is an improvement Knockout is missing, we can of course reopen.

Cheers

**Comment by koljagava** [comment]
thank you brianmhunt, I'll do it, and i'll report here any improvement
regards
  kolja

**Comment by koljagava** [comment]
@brianmhunt 
Sorry if i bother you again, but at the end, my issue could be summarize into this conceptual question: 
in "with:$parent" binding statement what to expect on new $parent variable ? 
* the original parent's parent 
* its child 
what do you think ?
thank you
kolja

**Comment by brianmhunt** [comment]
Hi @koljagava 

The `with` binding changes the `$parent` context.  See:
http://knockoutjs.com/documentation/with-binding.html

I hope that answers your question. :)

**Comment by koljagava** [comment]
@brianmhunt 
yes, but i would like to point to you that if $parent is used as a binding context it's better to pop the $parents stack instead to push another level
Do you see inconsistency in my thought? 
could you consider it a fix for a next ko release?
kolja

**Comment by brianmhunt** [comment]
Thanks @koljagava — Got it.

This is something that would take some thinking since there implications affecting separation of concern, but I'll reopen so it can be discussed.  Thanks for suggesting. :)

**Comment by mbest** [comment]
`$parent` and `$parents` are used to refer to the view-model in an outer context. If you create an inner context that binds to the same view-model as an outer context, you still have nested contexts and the relationship needs to be maintained. Certainly Knockout should make that assumption.

You could, of course, create a custom binding that worked differently. You can navigate the parent context objects using `$parentContext` and then have you binding use a parent context directly with `ko.applyBindings...`

**Comment by koljagava** [comment]
@mbest 
with your suggestion and the ko flexibility i made a workaround using ko.customBinding
here the  examples : [https://jsfiddle.net/koljagava/nyh565xp/]
hope to see this binding behaviour in the next release (tko?)
