### ISSUE TITLE
There is no dist folder in bower package

### ISSUE THREAD

**Issue by ahilis** [knockout/knockout#2152]
"dist" folder is gone after knockout has been updated up to version 3.4.1 with bower.
There is only "build" and "src". Version 3.4.0 is ok.

**Comment by mbest** [comment]
That's strange. The 3.4.1 tag has a dist folder: https://github.com/knockout/knockout/tree/v3.4.1

**Comment by mbest** [comment]
Maybe it's actually pulling from the `3.4.1` branch instead of the `v3.4.1` tag.

**Comment by ahilis** [comment]
I tried again, no changes. But I found that the version in package.json after update is "3.5.0-pre" despite of strict setting "3.4.1" in bower.json.

**Comment by mbest** [comment]
I just ran `bower install knockout` and it correctly pulled the 3.4.1 version with the `dist` folder.

**Comment by ahilis** [comment]
You right. I just successfully installed 3.4.1 with composer bower plugin. Everything is ok. There might be some error with VS2015.
Thank you for answers!
