### ISSUE TITLE
How to avoid execution of a computed at model initialization?

### ISSUE THREAD

**Issue by cervengoc** [knockout/knockout#2153]
I have a complex viewmodel structure, which gets initialized with some data after it's creation. This data is coming right from the HTML at page loading time. It fills the model with the initial data, so it allows me to avoid an immediate server round trip after page load.

Let's say I have some kind of a grid similar to this (simplified for clarity).

```
function GridViewModel() {
  this.pageIndex = ko.observable(0);
  this.pageSize = ko.observable(10);

  this.rows = ko.observableArray([]);
 
  // issue a grid update whenever page size or page index changes, skip initial computed run
  ko.computed(function() {
    var pageSize = this.pageSize();
    var pageIndex = this.pageIndex();
    if (ko.computedContext.isInitial()) return;
    this.updateGrid();
  });
}

GridViewModel.prototype.initialize = function(data) {
  this.pageSize(data.pageSize);
  this.rows.pushAll(data.rows);
};

GridViewModel.prototype.updateGrid = function() {
  // post pageIndex and pageSize to server, process returned rows, etc.
};
```

Now in my page I have something like this.

```
<script>

var model = new GridViewModel();

// HERE an update is sent to the server because pageIndex and pageSize changes
// however, it is unnecessary because rows are initialized too
model.initialize({ pageIndex: 3, pageSize: 50, rows: [ ... ] }); // coming from for example PHP or ASP.NET MVC

ko.applyBindings(model); 

</script>
```

How could I possibly avoid the `computed` run when I call `initialize`? 

I'm using deferred updates if that matters, so a simple flag can't solve the issue I guess.

**Comment by brianmhunt** [comment]
From http://knockoutjs.com/documentation/computed-reference.html

```javascript
ko.computed({
  deferEvaluation: true,
  read: function() {
    var pageSize = this.pageSize();
    var pageIndex = this.pageIndex();
    if (ko.computedContext.isInitial()) return;
    this.updateGrid();
  }
});

```

**Comment by cervengoc** [comment]
Not directly I think. Because these kind of *side-effect* computeds actually never get accessed. What I could do however, is to access it somehow after initialization, so it would trigger a first run. That first run would be nullified by the `isInitial` condition, so that might be a solution. I just need to work around accessing it after initial data had been assigned.

**Comment by cervengoc** [comment]
I have several problems with direct subscriptions.

- A direct subscription cannot have `rateLimit` for example.
- My initialization is actually different then "initial value" of the observable. For example the "initial" value of `rows`  is an empty array, and I add the *logically initial* rows at HTML load. So what you mean is a *technical initial value*, and for that it's good to use subscriptions. I hope it makes sense, I'm starting to reach my English limitations :)

**Comment by mbest** [comment]
Another option might be to create your computed in the `initialize` function.

**Comment by cervengoc** [comment]
Thanks, generally it would solve it of course, but that's technically harder in my real case, but I'll think it over again.

**Comment by mbest** [comment]
Another option is to cache the "loaded" values of `pageSize` and `pageIndex`.

```javascript
ko.computed(function() {
	var pageSize = this.pageSize();
	var pageIndex = this.pageIndex();
	if (!ko.computedContext.isInitial() && (loadedPageSize !== pageSize || loadedPageIndex !== pageIndex)) {
		loadedPageSize = pageSize;
		loadedPageIndex = pageIndex;
		this.updateGrid();
	}
});

...

GridViewModel.prototype.initialize = function(data) {
	this.loadedPageSize = data.pageSize;
	this.loadedPageIndex = 0;
	this.pageSize(data.pageSize);
	this.rows.pushAll(data.rows);
};
```

**Comment by wmag777** [comment]
[mbest](https://github.com/mbest), thanks!!

this work for me too!
   
```
      selectedAll = ko.computed(function () {

          if( **!ko.computedContext.isInitial()** ){
          some logic
           }
})
```
