### ISSUE TITLE
inconsistent behavior when encodeURI is used on an anchor href attribute

### ISSUE THREAD

**Issue by simevo** [knockout/knockout#2155]
when the href attribute of an anchor is set to a URL encoded with JS builtin encodeURI function, different results are observed in different browsers

for example, with this code:
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>encodeURI</title>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/knockout/3.4.1/knockout-min.js"></script>
  </head>
  <body>
    <h2>Knockout encodeURI example.</h2>
    <hr/>
    <ol>
      <li>
        <label>Input URL:</label>
        <input data-bind="value: url"/>
      </li>
      <li>
        <label>As-is URL:</label>
        <code data-bind="text: url"></code>
      </li>
      <li>
        <label>Encoded URL:</label>
        <code data-bind="text: encodeURI(url())"></code>
      </li>
      <li>
        <label>Viewmodel-encoded URL:</label>
        <code data-bind="text: encodedUrl"></code>
      </li>
      <li>
        <label>As-is URL as anchor href attribute:</label> 
        <a href="#" data-bind="attr: { href: url }" target="_blank">
          <span data-bind="text: url"></span>
        </a>
      </li>
      <li>
        <label>Encoded URL as anchor href attribute:</label> 
        <a href="#" data-bind="attr: { href: encodeURI(url()) }" target="_blank">
          <span data-bind="text: url"></span>
        </a>
      </li>
      <li>
        <label>Viewmodel-encoded URL as anchor href attribute:</label> 
        <a href="#" data-bind="attr: { href: encodedUrl }" target="_blank">
          <span data-bind="text: url"></span>
        </a>
      </li>
    </ol>
    <script type="text/javascript">
      var ViewModel = function(url) {
        this.url = ko.observable(url);
        this.encodedUrl = ko.pureComputed(function() {
          return encodeURI(this.url());
        }, this);
      };
      ko.applyBindings(new ViewModel("file://C:/filename with some spaces.txt"));
    </script>
  </body>
</html>
```

on Chromium 53 and Firefox 45, the links point to:
5. `file://C:/filename with some spaces.txt`
6. `file://C:/filename%20with%20some%20spaces.txt`
7. `file://C:/filename%20with%20some%20spaces.txt`

whereas on IE11:
5. `file://C:/filename%20with%20some%20spaces.txt`
6. `file://C:/filename%2520with%2520some%2520spaces.txt`
7. `file://C:/filename%2520with%2520some%2520spaces.txt`

curiously, the inconsistencies are not present if the URL starts with `http://` as in `http://example.com/with some spaces.txt`: here 6 and 7 always point to `http://example.com/with%20some%20spaces.txt` (but 5 is still different as IE11 escapes it anyway)

and BTW thanks for the excellent library !

**Comment by mbest** [comment]
This is curious, but is there really a problem?

**Comment by simevo** [comment]
The problem is that 6 and 7 do not work on IE11, as the space is escaped twice first to `%20` and then to `%25%20`.
Clicking on the link it gets unescaped only once so it goes to the filesystem and looks for `C:\filename with%20some%20spaces.txt` which is not what we want.

**Comment by codymullins** [comment]
@simevo, this is not an issue with knockout. Please see this JsFiddle for how to make this work:

https://jsfiddle.net/uyqy39gb/2/

**Comment by simevo** [comment]
@codymullins, thanks for the suggestion but this is not a viable solution for us.
In our case the `url` field is really an URL so it can start with `file://` or with `https://`.
The behavior I describe is specific to URLs with the **file** protocol.

**Comment by codymullins** [comment]
@simevo, this still works when using the file protocol in the URL, but you need to ensure it's in the correct format - `file:///C:/`

See here - https://jsfiddle.net/uyqy39gb/3/

**Comment by simevo** [comment]
You're right, it works for absolute file URLs starting with file:///. Thanks for the tip !
