### ISSUE TITLE
Style attribute is not updated when trying to set fontFamily to a family with a number in the name

### ISSUE THREAD

**Issue by ChlorideCull** [knockout/knockout#2158]
Minimal test-case on JSFiddle: https://jsfiddle.net/sebjoh/cs2r352w/2/

Noticed this while playing around with Knockout, if a number is located in the font family name, the style attribute is not updated when the data is updated.

In IE11, the font family is set correctly, as expected, but in Chrome 54.0.2840.99 nothing happens. I have not tested Firefox.

**Comment by mbest** [comment]
My investigation is that there's a simple workaround: enclose the font name in quotes.

https://jsfiddle.net/mbest/cs2r352w/3/

**Comment by mbest** [comment]
From https://developer.mozilla.org/en-US/docs/Web/CSS/font-family

> Font family names must either be given quoted as strings, or unquoted as a sequence of one or more identifiers. This means that punctuation characters and digits at the start of each token must be escaped in unquoted font family names.

So this also works: https://jsfiddle.net/mbest/cs2r352w/4/
