### ISSUE TITLE
Containerless control syntax - Viewport aware?

### ISSUE THREAD

**Issue by Aidurber** [knockout/knockout#2160]
Hi, 

Just a quick query as to whether it's possible for a condition to be aware of the viewport?
So I only want to load a component if it's in in view, and since the containerless control syntax won't load a component if it doesn't match a condition, I think this would be the logical place to do it. My components are loaded in with RequireJS. 

So let's say I have: 

```html
<!-- ko if: inViewport -->
<datepicker params=""></datepicker>
<!-- /ko-->
```

The component hasn't been initialised if `inViewport` is false by default. 

Is it possible to have a binding that recognises if it's in the viewport?

**Comment by mbest** [comment]
How about: `<!-- ko if: $($element).is(":visible") -->`?

**Comment by Aidurber** [comment]
That will work for components that are in tabs or something. But won't work for components that aren't yet  in the view. Following your idea I could do some work with [jQuery.inview](https://github.com/protonet/jquery.inview) or something. 

I didn't even think about putting jQuery in the condition. Thanks @mbest

**Comment by mbest** [comment]
If you want to be able to react to something becoming visible later, it's more complicated. I'd suggest, then, to create a custom binding or maybe just a helper function that will handle the conditions.

**Comment by brianmhunt** [comment]
Here's a binding that might help (it requires a `debounce`, in this case from `lodash`):

```javascript
module.exports.whenInViewport = {
  init: function (node, valueAccessor, allBindings, viewModel, bindingContext) {
    var fn = valueAccessor(), scrollFn

    function onScroll(evt) {
      var rect = node.getBoundingClientRect()
      if (rect.bottom >= 0 && rect.top <= window.innerHeight) {
        fn.call(viewModel, node, bindingContext)
        removeListener()
      }
    }

    function removeListener() {
      if (!scrollFn) { return }
      window.removeEventListener('scroll', scrollFn)
      scrollFn = null
    }

    scrollFn = _.debounce(onScroll, DEBOUNCE)
    window.addEventListener('scroll', scrollFn)
    ko.utils.domNodeDisposal.addDisposeCallback(node, removeListener)
  }
}
```

Now in your HTML the argument passed will be called as a function.

```html
<div data-bind='whenInViewport: functionToBeCalled'></div>
```

Is that the sort of idea you were going for?

**Comment by IanYates** [comment]
@brianmhunt - that's a handy looking function
