### ISSUE TITLE
Use .extend with anonymous function

### ISSUE THREAD

**Issue by caseyWebb** [knockout/knockout#2161]
The ability to use an extender without registering it could come in handy for one offs, e.g.

```javascript
const obs = ko.observable.extend((x) => someTransformation(x))
```

**Comment by mbest** [comment]
Wouldn't that just be the same as `const obs = someTransformation(ko.observable())`?

**Comment by caseyWebb** [comment]
it would be more similar to 

```javascript
const obs = ko.pureComputed((x) => someTransformation(x))
```

but nicer for chainability

**Comment by caseyWebb** [comment]
Nevermind, I'm mistaken. I was doing some funky stuff in an extender and thought it was being re-evaluated w/ changes. Closing.
