### ISSUE TITLE
img src in component template from an element doesn't appear in Firefox

### ISSUE THREAD

**Issue by StoicLoofah** [knockout/knockout#2162]
In Firefox 50, the `<img src="..."` does not load properly when it is included as part of the HTML in a `<template>` tag. 

See below: I have a few different implementations of loading the image, and you can see the missing image. On the left is Chrome 54, which appears to be working correctly. On the right is Firefox 50.0.1, where the img src loaded from a HTML template doesn't not appear at the bottom.

![image](https://cloud.githubusercontent.com/assets/1123311/20732489/c409efec-b643-11e6-8204-cc06cc334b7a.png)

Code for this page is below. I also tried putting the HTML for the template as a string directly into the component, and that worked fine, so it appears to be something specific to loading via `template: {element: 'component'}`

```
<html>
  <head>
    <script src="http://knockoutjs.com/downloads/knockout-3.4.1.js"></script>
    <style>
      body {
        background: black;
        color: white;
      }
    </style>
  </head>
  <body>
    <div id="content">
      <h1>No knockout</h1>
      <img src="http://knockoutjs.com/img/ko-logo.png" />
      <h1>Knockout</h1>
      <div>
        <img data-bind="attr: {src: 'http://knockoutjs.com/img/ko-logo.png' }" />
      </div>
      <h1>Knockout Template</h1>
      <div data-bind="template: { name: 'template' }"></div>
      <h1>Knockout Component</h1>
      <my-component></my-component>
    </div>

    <script type="text/html" id="template">
      <img src="http://knockoutjs.com/img/ko-logo.png" />
    </script>

    <template id="component">
      <img src="http://knockoutjs.com/img/ko-logo.png" />
    </template>

    <script>
      ko.components.register('my-component', {
        viewModel: function(params){},
        template: {element: 'component'}
      });
      ko.applyBindings({}, document.getElementById('content'));
    </script>

  </body>
</html>
```

**Comment by brianmhunt** [comment]
Thanks for the thorough report, @StoicLoofah .

It sounds like an upstream browser issue moreso than something specific to Knockout, but it'd be good to know what's going on in any case – and maybe we can find a workaround.

Would you mind putting together a jsFiddle with the above?

**Comment by StoicLoofah** [comment]
Oh, sure. that would have been a much better way to assemble the visuals and code for this =)

https://jsfiddle.net/fdftmzjr/2/

I'm seeing the same behavior with this in Chrome/FF as I did in a separate page.

Yeah, it seems like it's a browser thing. Unfortunately, I don't have older FF builds handy to know when this came about. I think it is relatively recent, though, because we only saw this bug manifested recently in the original project where we found it

**Comment by mbest** [comment]
![image](https://cloud.githubusercontent.com/assets/1230364/20743177/9a449662-b689-11e6-9bed-e11a44f51d1e.png)

**Comment by mbest** [comment]
![image](https://cloud.githubusercontent.com/assets/1230364/20743207/e023ce14-b689-11e6-8b85-e818b0709ebb.png)

**Comment by mbest** [comment]
![image](https://cloud.githubusercontent.com/assets/1230364/20743222/fc885a16-b689-11e6-8e9d-1c07eabce24c.png)

**Comment by mbest** [comment]
So it definitely a bug in the latest version of Firefox that wasn't there in 48.

**Comment by StoicLoofah** [comment]
just wanted to note that Firefox 51.0 appears to have fixed the problem
