### ISSUE TITLE
Version 3.4.1 - Using a returned computed for a template binding. 

### ISSUE THREAD

**Issue by Wibberley** [knockout/knockout#2180]
Using a computed to a template works fine in <= 3.4.0, but in 3.4.1 to doesn't seem to unwrap the computed so cant find the properties required.  This issue is stopping the upgrade.

**Comment by mbest** [comment]
Can you provide an example?

**Comment by RaptorCZ** [comment]
Maybe it is related to my "problem"? https://github.com/knockout/knockout/issues/2219

**Comment by mbest** [comment]
@RaptorCZ Yeah sounds like the same thing. I'll close this then.
