### ISSUE TITLE
Async component registration and application loading.

### ISSUE THREAD

**Issue by hardhub** [knockout/knockout#2184]
When component registration contains "synchronous: false" option components will be registered and created asynchronously.

Is it possible to handle the event when all components are registered?   
I can continue code execution only when all components are ready.
How to wait it? Loop with timer and checks? Make it synchronous?
Any ideas...

**Comment by codymullins** [comment]
@maxim-boligatov there is an issue opened for something similar that is in the works, see #1533 and #2165

**Comment by maxim-boligatov** [comment]
I think #2156 is similar to what I am looking for.    
But of course applicability finally will depend on provided events and their implementation.
AfterRender is mostly important for appearance code (not for primary UI logic of app).   
Also it looks not much things are ready for desired functionality.    
I will have to use sync mode for now.

**Comment by mbest** [comment]
Closed as duplicate.
