### ISSUE TITLE
Anonymous templates with same nodes cause problems

### ISSUE THREAD

**Issue by cervengoc** [knockout/knockout#2187]
If I have template bindings which refer to the same `nodes` set, then when reevaluating at first time, all of the nodes are lost, except for the "last" one.

I've been digging into the source for an hour now, and I've found that this is due to a behavior that ko stores the `nodes` in a detached `div`, which is created on a per-binding basis. So when ever it meets a template binding which refers to the same node set, it will replace them into a new detached `div`. 

So when the first template binding would like to reevaluate itself, it will meet an empty `div` because it has lost it's nodes. The last `template` binding with the same `nodes` steals the nodes from every previous binding.

A relatively simple fix could be if ko could behave like *"hey, these nodes are attached to my technical `div`, so I shouldn't remove them, but clone them".*. Or if it's safe, it would be even better to do like *hey, these nodes are attached to my technical `div`, so I should just use that `div` and not create another*.

**Comment by cervengoc** [comment]
If I have template bindings which refer to the same `nodes` set, then when reevaluating at first time, all of the nodes are lost, except for the "last" one.

I've been digging into the source for an hour now, and I've found that this is due to a behavior that ko stores the `nodes` in a detached `div`, which is created on a per-binding basis. So when ever it meets a template binding which refers to the same node set, it will replace them into a new detached `div`. 

So when the first template binding would like to reevaluate itself, it will meet an empty `div` because it has lost it's nodes. The last `template` binding with the same `nodes` steals the nodes from every previous binding.

**Comment by cervengoc** [comment]
Sorry I've accidentally pressed Ctrl+Enter very early.

**Comment by cervengoc** [comment]
Here is simple a jsfiddle repro.
https://jsfiddle.net/p5gtxuza/

**Comment by cervengoc** [comment]
Reading through the source code it seems like it's safe to just use the already created `div` container if ko could detect it. For the detection, in `moveCleanedNodesToContainerElement` there could be added a dom data key like `ko-generated`, which could be checked on `nodesArray[0].parentNode`, and if it's `true`, then return that `parentNode` instead of creating a new container and moving the nodes. 

If you have a look and approve this idea, I'll put together a PR with the fix.

**Comment by mbest** [comment]
@cervengoc That sounds like a good idea. Should we check that the new nodes array is actually the same set of nodes?

**Comment by cervengoc** [comment]
As far as I can judge, the node set is always cloned when the template is actually rendered. So that's why I think it's enough to check if the node set is appended to a `div` which was created by ko, and if yes, just use that container. I'm starting to work on it now..

**Comment by mbest** [comment]
closing in favor of #2188
