### ISSUE TITLE
Writable vs writeable

### ISSUE THREAD

**Issue by HamsterCoder** [knockout/knockout#2194]
Recently stumbled into a small problem using (knockout.js 3.1.0)

although docs state that observables and computeds are `writable`:

http://knockoutjs.com/documentation/computed-writable.html

the method for checking this is called `isWriteableObservable`

So the docs appear a little misleading, and it took me some time to grep the above method, when I didn't remember what exactly it was called.

**Comment by mbest** [comment]
Knockout 3.4.0 is the latest and the documentation reflects that. `isWritableObservable` was added in 3.2.0. The page that mentions that method refers to both spellings: http://knockoutjs.com/documentation/computed-reference.html
