### ISSUE TITLE
Nodes don't get cleaned in some cases

### ISSUE THREAD

**Issue by cervengoc** [knockout/knockout#2198]
I have a custom binding, let's say called `modal`. This binding controls descendant bindings, and in the `init` handler it binds the descendants, then moves all the descendants to a modal `div` which is dynamically created in the `body`. Then in the DOM node disposal callback it moves the contents back to the "bound" `div`. 

Next, I call `ko.removeNode` somewhere later to clean up things (or it's called by some binding like `with` for example). Then the `ko.cleanNode` won't be called on the element's descendants, which were put back by the DOM node disposal callback.

The cause of this is that `knockout` gathers all the descendants only when calling `ko.removeNode`, and then it just calls `cleanSingleNode` on each of them without taking into account possible DOM tree changes, made by for example such DOM node disposal callbacks.

A possible fix could be to gather direct children of cleaned nodes level by level instead of gathering them all at once and forever in `ko.cleanNode`.

I guess the current behavior was intentional for some reasons I'm not aware of, and if so, please suggest a correct implementation for this scenario which properly cleans up everything at every level.

Hope it's clear enough. Here is a fiddle to demonstrate the issue. https://jsfiddle.net/33exz5j8/

**Comment by brianmhunt** [comment]
It's outside the design scope for disposal callbacks to add new nodes.

Disposal callbacks that *do* add new nodes should be responsible for them.

For simplicity's sake, Knockout's life-cycle is just binding and cleaning before removal.

That said, if there's a simple fix it may be worth fleshing it out more.

**Comment by cervengoc** [comment]
I see, that makes sense.

If I call manually `ko.removeNode(elemen)` in the disposal callback, I'll fall into an infinite call loop. So it would be good to expose a method to remove the contents of a given element, so that it could be used in cases like this. Of course this is not a very difficult thing to do by hand, it just would be nice to have.
