### ISSUE TITLE
Writing to a computed field does not update checkboxes after 3.1.0

### ISSUE THREAD

**Issue by ffocsi** [knockout/knockout#2200]
If you check this jsfiddle: http://jsfiddle.net/ckrytjwh/

Check these lines:
    var instance = new vm;
    instance.bitwiseValue(6);
    ko.applyBindings(instance);

These lines correctly check the 2 and 4 checkboxes when the model loads. You can uncheck them and the value updates.

If you use a later version this will set the input value to 6, but the checkboxes will not be checked. You can check and uncheck them and it will not take the value below 6. You can check other checkboxes to add or remove, but the value will never go below 6.

I have tried 3.2.x, 3.3.x 3.4.x and they all have the bug.

**Comment by mbest** [comment]
In 3.2.0, the `value` binding can be used to set numeric values for a checkbox (equivalent to the `checkedValue` binding). So the checkboxes expect numeric values in the array because you're setting numeric values in the binding.

http://jsfiddle.net/ckrytjwh/1/

**Comment by fastfasterfastest** [comment]
I think you need to NOT use the value binding with the checked binding, and instead use a value attribute.  I.e., change
`<input type="checkbox" data-bind="checked: checkedList, value: 2" />`
to
`<input type="checkbox" value="2" data-bind="checked: checkedList" />`

Alternatively, you can use the checkedValue binding:
`<input type="checkbox" data-bind="checked: checkedList, checkedValue: 2" />`
If so, you need to push integers to your checkedList, not strings, i.e.
`vm.checkedList.push(placeValue);`

**Comment by ffocsi** [comment]
Thanks, that's a relief.
