### ISSUE TITLE
Numeric value binded to SELECT element causes dependend computed are called twice

### ISSUE THREAD

**Issue by RoboBurned** [knockout/knockout#2207]
I have a SELECT element that is binded to an obsevable array.
Notice that options values are strings '3' but initial value of selectedItem is number 3.
```
function ViewModel() {
    var self = this;
    self.items = ko.observableArray([
        { value: '1', text: "one" },
        { value: '2', text: "two" },
        { value: '3', text: "three" }
    ]);
    self.selectedItem = ko.observable(3);
}

//HTML
<select data-bind="options: items, optionsCaption: ' ', optionsText: 'text', optionsValue: 'value', value: selectedItem">
</select>
```
I have a computed observable that depends on selectedItem() and performs huge work to load data.
```
self.comp = ko.computed(function() {
     var v = self.selectedItem();
     //Do huge work here
});
```
Currently when page is opened and applyBinding is called the computed observalbe is evaluated twise: one time selectedItem has value 3 and second time it has value '3'.

Debugging shows that when updateFromModel is called to fill DOM with value, newValue (3) is compared to what is actually placed into DOM ('3') and 'change' event is triggered which causes recalculation of computed observable.

Knockout.js 3.4.1 Demo
https://jsfiddle.net/426wsbtk/3/

**Comment by mbest** [comment]
This is normal. If you make your viewmodel consistent, you won't see two updates.
