### ISSUE TITLE
Observable Array from computed observable in template returns length == 0 in 3.4.1 and later

### ISSUE THREAD

**Issue by RaptorCZ** [knockout/knockout#2219]
Please check this sample:
https://codepen.io/raptor/pen/wJQprR

When Knockout 3.4.0 is used, it works fine. Using version 3.4.1 and later is not working. Array length is always 0.

Checked source code and problem seems to be binding 'template'. In version 3.4.0 there is in 'update' used
```
dataValue = ko.utils.unwrapObservable(options['data']);
...
bindingContext['createChildContext'](dataValue, options['as'])
```
so value is observable.

But in 3.4.1 there is no unwrapObservable
```
bindingContext.createStaticChildContext(options['data'], options['as']) :  
```
Adding this unwrap back to 3.4.2 version will fix this.

**Comment by mbest** [comment]
I would say that the 3.4.0 behavior is actually a bug. When `template` is used without a `data` parameter, it should pass through the `$data` value without any modification. Your example will work in later versions if you specify the `data` parameter: `<!-- ko template: { name: 'summary-error', data: $data } --><!-- /ko -->`.

I'll also add that returning a new observable from a computed is generally bad practice. Just return the value.
