### ISSUE TITLE
Roadmap, future?

### ISSUE THREAD

**Issue by Eisenspalter** [knockout/knockout#2220]
Is there anywhere a roadmap for knockout? Or where can I see which new features will coming? Will be there new features? What about the new website about knockout. Is this project cancelled?

**Comment by miellaby** [comment]
I've found https://github.com/knockout/tko

**Comment by codymullins** [comment]
@Eisenspalter it's very much alive. @mbest has been doing a fantastic job, and @brianmhunt is doing good stuff with TKO. I hope to get more involved with commits in the future too.

**Comment by mbest** [comment]
Thanks, @codymullins.

@Eisenspalter There's not a specific roadmap. Some discussion is at #1932 and #1533. Also take a look at the [3.5.0 milestone](https://github.com/knockout/knockout/milestone/9).
