### ISSUE TITLE
Component parameter binding improvements

### ISSUE THREAD

**Issue by codymullins** [knockout/knockout#2224]
I'd like to propose a few general improvements to how the component parameter binding works. Currently, there's not much control over the bindings that get injected - it's either the observable, a computed observable, or a literal value if you've passed one. Unfortunately, passing something like `myObservable()` as a param, still passes a computed observable - this has tripped me up on a few different occasions.

I'm finding more and more need to build stateless components that would greatly benefit from more control over these bindings. Furthermore, many scenarios I find myself repeating the following pattern:

```
function UserEditComponent(params){
   this.userId = params.userId();
   this.title = params.title;
   this.name = params.name;

   // or if I get lazy....
   this.model = params;
}
```

Thus, borrowing from the bindings in Angular (more so when they introduced components in 1.5 and 2.0), I'd like to propose a way to register your component with a parameter/binding configuration. The configuration will instruct KO how to bind the parameters **directly to the viewModel** on creation of the component. This design should be backwards compatible and "opt in" so as not to break any existing code that may have identical parameters on the existing view model. 

The different bindings I had in mind:

## One way bindings
This binding would indicate that the value passed in should be a non-observable value. A literal would be passed in and remain a literal while an observable would be unwrapped. I'm assuming this would just utilize the `ko.unwrap` pattern.

## One way observable bindings
This binding would indicate that the component should create a copy of the observable passed in. In many scenarios, a child component may need to have an observable but not update the parent observable.

_Questions_
Does an update to the parent observable trickle down to the copy created?

## Two way bindings
This binding would be as it currently exists, an observable passed in to a child component would remain the same. Updates in the child component would reflect in the parent component.

## Callback bindings
This binding would be to indicate any function callbacks that are passed in to the component. This could potentially be solved with the above two way binding, but might not hurt to be more specific.

This is just the general idea, would appreciate any thoughts or feedback on this. I'm sure there's a way to accomplish some of this using custom component loaders or the createViewModel function, but it would be nice to have something like this built into the core framework.

## Required bindings
It would be nice to also be able to specify for any of the above bindings, which are explicitly required for the component.

## Example:

```
function UserEditComponent(params){
    // the bindings would automatically be set to the viewModel
    // i.e. Object.assign(this, { userId, title, firstName, onSave });
    // they would immediately be available as: this.userId or through the injected params
}

ko.components.register('user-edit', {
    viewModel: UserEditComponent,
    template: require('./user-edit.html'),
    bindings: {
        userId: '@', // one way binding, not observable - sets the observable's value directly on the view model (or literal value) perhaps by doing the unwrap pattern: this.userId = ko.unwrap(valueAccessor())
        title: '<', // one way binding but still observable - creates a new observable from the observable on the view model
        firstName: '=', // two way binding - sets the observable directly on the view model for two way binding
        onSave: '&' // callback function - sets the callback function as available on the view model
    }
});
```

If this is implemented, we'll also now know the names of the bindings ahead of time. This could let us clean up the parameter binding on the HTML side as well (note, using data-xxx for conflicts):

```<user-edit user-id='userId' data-title='title' data-name='name' on-save='onSave'></user-edit>```

In any case, if this isn't something that would be liked in the core framework, let me know and I can spin off a new project for it as an extension. I think this would be a good add and fits with the general philosophy of Knockout. (I'm up for any suggestions or ideas, this is just a rough thought I've had in the back of my head for a while.)

**Comment by codymullins** [comment]
I will create a new library for this item.

**Comment by brianmhunt** [comment]
FYI I'm working on this for TKO, with a view to replacing the whole "quasi-javascript-in-data-bind" model with something vastly simpler (likely along the lines of what you've got).

**Comment by codymullins** [comment]
Would you mind sharing what you already have for this? If it's something that will suit my needs I don't want to reinvent the wheel, and could offer help with the implementation.
