### ISSUE TITLE
jQuery 3+ Deprecates Bind

### ISSUE THREAD

**Issue by ambroselittle** [knockout/knockout#2229]
Was digging into upgrading to jQuery 3, and using their migrate tool. It warns about KO's use of `bind`. I find it still in latest 3.4.2 on line 428 of the debug file:
`jQueryInstance(element)['bind'](eventType, wrappedHandler);` 

Minor issue, to be sure, but also I suspect easy to fix by using `on`:
https://jquery.com/upgrade-guide/3.0/#deprecated-bind-and-delegate

**Comment by mbest** [comment]
This will be fixed in the next version. See #2078
