### ISSUE TITLE
The "html" binding has error if the init value has bind syntax

### ISSUE THREAD

**Issue by asuishi** [knockout/knockout#2231]
this is right [https://jsfiddle.net/asuishi/faz0adne/1/](https://jsfiddle.net/asuishi/faz0adne/1/)
but when the init value has bind syntax like this 
`('<div data-bind="text:test">there is no error</div>'`
there will be a error:Unexpected identifier [https://jsfiddle.net/asuishi/faz0adne/](https://jsfiddle.net/asuishi/faz0adne/)

**Comment by mbest** [comment]
You need to escape the quotes in the string (or use single quotes).

`"<div data-bind=\"text:test\">htmlContent</div>"`

**Comment by Cheema1** [comment]
Please remove the quotes
