### ISSUE TITLE
Suggestion: extend beforeRemove binding to optionally expect a Promise value from the callback function, whose resolve would tell Knockout it's safe to remove element

### ISSUE THREAD

**Issue by ErroneousFatality** [knockout/knockout#2233]
What do you guys think about extending the beforeRemove binding so that it's callback function can optionally return a Promise which when resolved indicates that the node can be removed by the knockout library?
In the years I've used KO, I've always liked to keep my code's responsibility away from the HTML manipulation, and let the KO bindings do that. The beforeRemove binding was always an excpetion when it came to that, since it is usually the only time I have to put HTML manipulation into my code's logic.
As for compatibility: if the returned value isn't a Promise, then do as before.

**Comment by mbest** [comment]
The purpose of beforeRemove is html manipulation. What are you using it for?

**Comment by ErroneousFatality** [comment]
I concede that my idea makes no sense after all. 
Every situation I used it for, and that I thought of, where I thought this addition would benefit the coder, can be refactored to work without it by using subscriptions, and that would always be the better solution.
Sorry for the redundant ticket, you can close it at your discretion.

**Comment by brianmhunt** [comment]
Thanks @ErroneousFatality :)
