### ISSUE TITLE
Computed observable only updates UI once

### ISSUE THREAD

**Issue by sngeth** [knockout/knockout#2235]
I have a observable array which contains observable items via ko.mapping.fromJS

I have a computed, `feedback_count_string`,  in the view model below that only seems update the UI once (however it triggers the computed correctly and calculates the correct value when debugging)

```js
Starfield.ViewModelWithFeedbackCount = function(attributes) {
  Starfield.BaseViewModel.call(this, attributes)

  if(!this.feedback_count       ) { this.feedback_count        = ko.observable(0) }
  if(!this.hidden_feedback_count) { this.hidden_feedback_count = ko.observable(0) }

  this.feedback_count_string = ko.computed(function() {
    return this.feedback_count() + (this.hidden_feedback_count() > 0 ? '*' : '')
  }, this)

  /*
  self = this

  this.feedback_count_str = ko.observable(this.feedback_count_string())

  this.feedback_count_string.subscribe(function(newVal) {
    console.log("new value: " + newVal + " feedback count is now: "+ self.feedback_count())
    self.feedback_count_str(newVal)
  })
 */
}
```

The execution model goes as follows:

1) Load page containing observable array KO viewmodels via ko.mapping.fromJS
2) I will update an item, fetch json of edits, update viewmodel via mapping.fromJS

Expected Behavior:
I am expecting that when I fetch the new json where I update the feedback_count, it will trigger the computed to fire and update the UI.

Note: I am confident that all the code is wired up correctly since the view model contains some other base observables omitted here that _do_ update correctly. Only the computed one fails to update the UI after initial update.

When I debug into the computed, the function returns the correct values, but the UI itself does not update. Am I running into an async issue here?

I created a work around in the commented code above. If I uncomment the code above and subscribe to the computed and update it to a non computed observable and bind that to my UI, everything works. But i'm not sure why I need that intermediate solution.

**Comment by mbest** [comment]
Nothing in your example seems wrong except `self = this`, which should be `var self = this`.

**Comment by sngeth** [comment]
Thanks for the quick response!

That portion of the code _does_ work and i'm not really concerned too much with it since. My question is _why_ do I even need of that code (manually subscribing to the computed and updating a proxy observable)

I forgot to state my expectation in my original post:
I am expecting that when I fetch the new json and update the viewmodel's via mapping.fromJS (code omitted)...It updates the feedback_count observable which in turns, updates the  computed to fire and update the UI. But it fires once and then it seems to "disconnect"

Not sure if this needs to be investigated or not I'm fine with closing this issue since my work around does work.

**Comment by mbest** [comment]
I believe that the missing `var` is a clue. Try fixing that and see if your "workaround" still works.

**Comment by sngeth** [comment]
Added the var and output seems fine after firing updates to my view model, console log in my subscribe function is as follows:

```
new value: 42* feedback count is now: 42
new value: 43* feedback count is now: 43
```

**Comment by mbest** [comment]
Cool. Can you show the code that's not working right?

**Comment by sngeth** [comment]
This is the rest of the pieces. The update is triggered similar to as follows:

```
var catalog = new UserAssociatedItemCatalog();
catalog.for_downline_user().upsert(updated_serialize_data)
//above will use mappedIndexOf to find existing view model in observable array
//if finds a match called update() in base view model
//and updates view model with mapping.fromJS
```

Base View Model
```js
Starfield.BaseViewModel = function(attributes) {

  var defaults = this.attribute_defaults()
  for (var attr in defaults) { 
    this[attr] = ko.observable( defaults[attr] )
  }

  ko.mapping.fromJS(attributes, {}, this);
}

Starfield.BaseViewModel.prototype = {
  update: function(attributes) {
    ko.mapping.fromJS(attributes, {}, this)
  },
  attribute_defaults: function() {
    // Overide this method in subclass to return 
    // a hash. The keys will become observable methods
    // on this object and the values will be used for 
    // initial values for those observables
    return {}
  }
}
```
Catalog abstraction
```js
Starfield.UserAssociatedItemCatalog = function(args){
  if(args === undefined) { args = {} }

  function UpdateableList(){
    var observable_array = ko.mapping.fromJS([], {
      key: function(item) {
        return ko.utils.unwrapObservable(item.id);
      },
    })

    observable_array.upsert = function(object){

      var i = this.mappedIndexOf(object)

      if(i >= 0) {
        this()[i].update(object)
      }
      else {
        this.push(object)
      }

    }
    return observable_array
  }

  var item_lists = {}

  var catalog = {
    for_user: function(user){
      return (item_lists[user] || (item_lists[user] = new UpdateableList))
    },
    for_downline_selection: function() {
      var page_downline_selection_id = StarfieldSession.downline_selection_id()
      page_downline_selection_id = page_downline_selection_id.length > 0 ? page_downline_selection_id : 'self'

      return this.for_user(page_downline_selection_id)
    },
    remove: function(object){
      for(var user in item_lists) {
        item_lists[user].mappedRemove(object)
      }
    },
    update: function(object){
      for(var user in item_lists) {
        var item_list = item_lists[user]
        var i         = item_list.mappedIndexOf(object)
        if(i >= 0) { item_list()[i].update(object) }
      }
    }
  }

  return catalog
}
```
Haml template
```ruby
.feedback_button_container(data-bind="attr: {'data-click-target': enter_feedback_path}")
  %button{"class" => "ui-btn ui-btn-b ui-shadow ui-corner-all", "data-theme" => 'b'}
    .icon-feedback-bubble-single
  .ui-li-count.ui-body-inherit(data-bind="text: feedback_count_string")
```

**Comment by mbest** [comment]
I'm not familiar with ko.mapping, but I think the problem is in your `upsert`. You're calling `update` with the viewmodel object instead of the raw JS object.

**Comment by sngeth** [comment]
That appears to be exactly it. After passing the raw js object the computed works as is.

My apologies for overlooking how to clearly use mapping.fromJS (although it was more of cargo culting an incorrect pattern in our system). Thank you for your time and effort Michael...looks like I just needed a second pair of eyes.
