### ISSUE TITLE
Radio input in knockout observableArray lose check after splice

### ISSUE THREAD

**Issue by VladaHejda** [knockout/knockout#2238]
- Have a radio input inside an element multiplied by knockout foreach.
- Give an observableArray into that foreach.
- Make a function to switch two of these elements.
- Check both radios, then switch. **One of radios loses its check.**

SO question: http://stackoverflow.com/questions/43769619/

Fiddle: https://jsfiddle.net/hejdav/6dzg9hs8/17/

Fiddle with workaround by **valueHasMutated**: https://jsfiddle.net/hejdav/6dzg9hs8/18/

**Comment by mbest** [comment]
While updating the `foreach` binding, each item's `$index` property is updated. During the process, both items will have the same index value (and thus names) very briefly, but it's enough for the browser to clear one of the checked values. You should instead use the `checked` binding (and not set a name based on the index).
