### ISSUE TITLE
Custom loader and component template?

### ISSUE THREAD

**Issue by hardhub** [knockout/knockout#2242]
I am trying to create custom template loader as the following:

```JS
var templateLoader = {
    getConfig: ko.components.defaultLoader.getConfig,
    loadComponent: ko.components.defaultLoader.loadComponent,
    loadTemplate: function (name, templateConfig, callback) {
        // some code here...
    },
    loadViewModel: ko.components.defaultLoader.loadViewModel
};

ko.components.loaders.unshift(templateLoader);
```

I want to override only load template... to get it over network only in moment when component registration will be require this template.

So what should be written for template property during component registration?
It is not id or element or string... I think it should work in the way similar to require...
template: { require: 'some path ' }

I need to ask server for template exactly in the moment when component needs it.

**Comment by mbest** [comment]
I'm not quite sure what you're looking for, but it sounds similar to what I posted here: https://github.com/knockout/knockout/issues/1458#issuecomment-154578662

**Comment by hardhub** [comment]
I mean what should be written here in case of custom loader:

ko.components.register('my-component', {
    viewModel: { require: 'some/module/name' },
    **template**: { require: 'text!some-template.html' }
});

**Comment by hardhub** [comment]
I think this the key point:

_To use this custom loader, the component must define a createTemplateForViewModel function and not define a template._

I will read info about createTemplateForViewModel and come back.

**Comment by hardhub** [comment]
There is no any documentation for that method.

But considering your example: http://jsfiddle.net/mbest/q84svmjg/
I can say it loads template synchronously:

```
createTemplateForViewModel: function(vm) {
        return 'Message: <input data-bind="textInput: text" /> '
            + '(length: <span data-bind="text: text().length"></span>)';
    }
```

How to do that on demand?
In other words how to do this:

```
createTemplateForViewModel: function(vm) {
        return someRepo.getFromServerOrCachedCopy('my_component_name');
    }
```
But I am sure I will need to call server asynchronously.
Of course I can assume this method creates only DOM.
And this loadTemplate looks more suitable. But how to use then this template during registration?

**Comment by mbest** [comment]
You don't need a custom loader to do what you want. Simply using 

```
ko.components.register('my-component', {
    viewModel: { require: 'some/module/name' },
    template: { require: 'text!some-template.html' }
});
```

... will load the template only when the component is used for the first time.

**Comment by hardhub** [comment]
@mbest 
If I understand it correctly it needs RequreJS and AMD... Right?
I do not need AMD and even cannot use it.
So I am trying to achieve the same result but without RequireJS.

**Comment by mbest** [comment]
If you create a custom component loader, it's up to you to define what should be specified in the configuration. If you only customize `loadTemplate`, the only part you need to define is what should be specified for the `template` value. So:

```
ko.components.register('my-component', {
    viewModel: MyComponentViewModel,
    template: /*whatever you want passed to loadTemplate*/
});
```

**Comment by hardhub** [comment]
I see.. Thanks!

Working loader:
```JS
"use strict";

var templateLoader = new (function () {
    var self = this;
    var cache = {};

    self.getConfig = ko.components.defaultLoader.getConfig;
    self.loadComponent = ko.components.defaultLoader.loadComponent;
    self.loadViewModel = ko.components.defaultLoader.loadViewModel;

    self.loadTemplate = function (name, templateConfig, callback) {
        if (templateConfig.load == null) {
            callback(null);
        } else {
            var existing = cache[name];
            if (existing) {
                callback(existing);
            }
            else {
                $.ajax({
                    type: 'GET',
                    url: templateConfig.load,
                    contentType: "application/x-www-form-urlencoded",
                    dataType: 'html',
                    timeout: 10000
                }).done(function (template) {
                    var nodes = ko.utils.parseHtmlFragment(template.trim());

                    cache[name] = nodes;

                    callback(nodes);
                }).fail(function () {
                    callback(null);
                });
            }
        }
    };
});

ko.components.loaders.unshift(templateLoader);
```

Template in component registration:
```
template: { load: 'relative/path/to/template/on/server' }
```
