### ISSUE TITLE
Knockout Prototype Issue

### ISSUE THREAD

**Issue by McKabue** [knockout/knockout#2243]
i would like to understand why knockout behaves differently when a property is a prototype, and especially important, how to avoid it, while still using prototypes. i want some methods to be overridden because i have a base view model that we are to inherit... the following demonstrates what i mean...

[JSFIDDLE WITH PROTOTYPE [try typing into the first input box and it will appear in the other]](https://jsfiddle.net/mckabue/f637juxm/1/)

[JSFIDDLE WITHOUT PROTOTYPE [try typing into the first input box and it will not appear in the other]](https://jsfiddle.net/mckabue/6djhugbv/)

[**Why are they behaving differently?**](http://stackoverflow.com/q/43930205/3563013)

**Comment by mbest** [comment]
See my answer on SO.
