### ISSUE TITLE
how does “click: test()” work in KO?

### ISSUE THREAD

**Issue by aleksey-bykov** [knockout/knockout#2246]
crossposted at SO: https://stackoverflow.com/questions/44153000/how-does-click-test-work-in-ko

my view model
```
    function Test() {}
    Test.prototype.test = function() { alert('hi'); }
```
my view 
```
    <button data-bind="click: test()">Click me</button>
```
code that runs it
```
    var test = new Test();
    ko.applyBindings(test);
```
fiddle:
   https://jsfiddle.net/5g4cfg7u/

question:

 - can anyone explain what is going on here, the `test()` is a call expression which is supposed to be evaluated to `undefined` at binding (which you can see when the alert is displayed the first time), so `click: test()` is as good as `click: undefined`, if so how come i see the alert when i click the button?

 - can anyone share a link to the official Knockout documentation that explains it?

**UPDATE:**

to illustrate it better, if we add another binding `text: test()` we see that the text on the button disappears at binding (as expected, because tests returns undefined), if so, what is the difference between evaluating `click` and `text`?
```
    <button data-bind="click: test(), text: test()">
    Click me
    </button>
```
fiddle:
   https://jsfiddle.net/5g4cfg7u/3/

**Comment by mbest** [comment]
https://stackoverflow.com/a/44166102/1287183
