### ISSUE TITLE
Custom component loader memory leak?

### ISSUE THREAD

**Issue by thcgit** [knockout/knockout#2250]
On knockout v3.4.2, it appears that when you apply bindings and a component is loaded via a custom loader for the first time, the view model for that first time is retained in memory forever.

In the following example:

```
<html>
<head>
	<title></title>
	<script src="knockout-3.4.2.js"></script>
</head>
<body>
	<div id="target">
	</div>
	<button onclick="bind('customwidget1')">Bind Custom 1</button>
	<button onclick="bind('customwidget2')">Bind Custom 2</button>
	<button onclick="bind('widget')">Bind Normal</button>
	<button onclick="unbind()">Unbind All</button>
	<script type="text/javascript">
		(function () {
			var customLoader = {
				getConfig: function (name, callback) {
					callback(name.indexOf('customwidget') === 0 ? {} : null);
				},
				loadComponent: function (name, componentConfig, callback) {
					if (name.indexOf('customwidget') === -1) {
						callback(null);
					} else {
						ko.components.defaultLoader.loadComponent(name, componentConfig, function (baseResult) {
							var number = name.substr(12);
							var template = document.createElement('div');
							template.textContent = 'Custom Loaded ' + number;

							var result = {
								template: [template],
								createViewModel: function () {
									return {};
								}
							};

							callback(result);
						});
					}
				}
			};

			ko.components.loaders.unshift(customLoader);
			ko.components.register('widget', {
				viewModel: function () {
					return {};
				},
				template: '<div>Normal Loaded</div>'
			});
		})();

		function bind(name) {
			var target = document.getElementById('target');
			var element = document.createElement('div');
			element.setAttribute('data-bind', "component: '" + name + "'");
			target.appendChild(element);

			var viewModel = new ViewModel();
			ko.applyBindings(viewModel, element);
		}

		function unbind() {
			var target = document.getElementById('target');
			ko.utils.emptyDomNode(target);
		}

		function ViewModel() {
		}
	</script>
</body>
</html>
```

Using Chrome version 59.0.3071.86.

1. Take a heap snapshot. There are no ViewModel instances yet.
2. Click on Bind Normal any number of times.
3. Take a heap snapshot. There are some ViewModel instances.
4. Click on Unbind.
5. Take a heap snapshot. No ViewModel instances remain, as expected.
6. Click on Bind Custom 1 any number of times, then Unbind.
7. Take a heap snapshot. There is one ViewModel instance remaining, not zero as expected.
8. Click on Bind Custom 2 any number of times, then Unbind.
9. Take a heap snapshot. There are 2 ViewModel instances remaining.

It looks like references to the view models are being held by the loadedDefinitionsCache somehow.

**Comment by thcgit** [comment]
For anyone that's interested, I eventually solved this by clearing the reference to callback after it has been invoked (e.g. by setting it to null).

**Comment by mbest** [comment]
@thcgit So was there an issue in the Knockout code?

**Comment by thcgit** [comment]
It doesn't appear to be an issue in KO.

```
var result = {
    template: [template],
    createViewModel: function () {
        return {};
    }
};
```

In the above example, createViewModel becomes a closure that holds a reference to the outer scope that contains callback, even though the function does not touch anything in the outer scope.

Since the result object is stored in the loadedDefinitionsCache, the callback never gets GC'ed and since the callback has a reference to the initial binding context, that binding context also never gets collected.

I'm not sure if this is a bug in Chrome or if nested functions always form a closure.

So either nulling out the reference to callback, or changing createViewModel to not be a nested function resolves the issue.
