### ISSUE TITLE
valueUpdate not working anymore (with latest version at least)

### ISSUE THREAD

**Issue by alphanull** [knockout/knockout#2254]
In order to work around Safari autofill issues, I use `valueUpdate: 'blur'` in conjunction with the `value` binding.

Now it seems that this is simply doing nothing anymore. I dug a bit into the knockout code and the issue may be caused by this assignment in the `value` binding handler code: `var requestedEventsToCatch = allBindings.get("valueUpdate");`

Turns out this returns `undefined` even if I specified the `valueUpdate` binding like described above , so the subsequent code `if (requestedEventsToCatch) { ... }` is not executed.

In fact, if I just manually insert this  line:
`requestedEventsToCatch = 'blur';`
after the assignment mentioned above, it seems to work again!

Of course no real solution, but it seems to support my assertion.

**Comment by mbest** [comment]
Which version of Knockout did it work with? Can you provide a sample?

**Comment by alphanull** [comment]
Allright, after digging deeper it turned out that this is NOT a problem with knockout, but rather a problem with my component template, where I had to use nested quotation marks and simply used a double quotation mark instead of using an escaped single quote. So knockout thought the `bind` attribute was being closed - ignoring the remainder of the actual intended binding, which contained the `valueUpdate`. And as knockout (apparently!) parsed and executed the template without throwing an error, everything worked fine - except the valueUpdate binding. So therefore this simply went under my radar at first. Think this can be closed.
