### ISSUE TITLE
Nested observables - How is this not a memory leak?

### ISSUE THREAD

**Issue by agquick** [knockout/knockout#2258]
Imagine I have an observable array that consists of objects that have observables as properties. For example:

```javascript
var users = ko.observableArray();
var user = {
  name: ko.observable("Alan"),
  age: ko.observable(25)
};
users.push(user);
```

Furthermore, imagine I have a computed observable which just filters this array based on age:

```javascript
var young_users = ko.computed(function() {
  users().filter(function(user) { return user.age() < 30 });
});
```

My question is: as the users array has objects removed over time, isn't the computed still bound to them, since I accessed the `age` observable property? Thus, even though a user may be removed from the array, it is never released to be garbage collected because the computed still depends on the age parameter.

What am I missing?

Thanks in advance to anyone who can help.

**Comment by mbest** [comment]
Each time a computed observable is recalculated, it also updates its list of dependencies.

**Comment by agquick** [comment]
Got it. So I'm guessing on the next update, it will automatically dispose of subscriptions that are no longer needed. Thanks!
