### ISSUE TITLE
auto-disposed subscribe feature

### ISSUE THREAD

**Issue by miellaby** [knockout/knockout#2260]
would it be possible to add a disposeWhenNodeIsRemoved feature to KO subscriptions?

It would work like this workaround:
```
function subscribeAndDisposeWhenNodeIsRemoved(someObservable, node, callback) {
        ko.computed(function() {
            var v = someObservable();
            ko.ignoreDependencies(callback.bind(someObservable, v));
        }, null, { disposeWhenNodeIsRemoved : node});
}

```
any thought?

**Comment by codymullins** [comment]
You can keep track of the subscriptions your component starts and then hook into the onDestroy method.

**Comment by codymullins** [comment]
@miellaby does this address the issue?

**Comment by Retsam** [comment]
Here's my personal convention for handling disposal.  I actually use this over `disposeWhenNodeIsRemoved`, just to keep disposal logic consistent.

```
ko.bindingHandlers.someBindingHandler = {init: function(element) {
    const onDispose = (handler) => ko.utils.domNodeDisposal.addDisposeCallback(element, handler);
    
   const myComputed = ko.computed(() => {/*...*/});
   onDispose(() => myComputed.dispose());

   const mySubscription = myComputed.subscribe(() => /*...*/);
   onDispose(() => mySubscription.dispose());
}};
```

I use the same pattern (with a slightly different definition for `onDispose`) for other contexts of disposal too.

---

That being said, it doesn't seem unreasonable that subscriptions could support the same API as computeds in this regard, either.

**Comment by mbest** [comment]
Adding as part of #2324.
