### ISSUE TITLE
Disabled attribute incorrectly set

### ISSUE THREAD

**Issue by mattLummus** [knockout/knockout#2262]
I am experiencing an issue where Knockout (3.4.2) is not consistently rendering its `disable` binding correctly.

We are using knockout on a single page "app" within a larger site - its a dynamic form that makes AJAX calls to update some info. We use a couple buttons to toggle state, such as a "readOnly" mode. Some buttons are disabled during certain conditions. 

In this case a "Cancel" button should be disabled while any active AJAX calls are processing (which we track through a pureComputed that returns a boolean). However, while reproducing this issue, we are not actually making any edits so it should never be disabled. 

### To Reproduce

The Cancel button has a `visible` binding hooked to a `readOnly` pureComputed that returns a boolean. After toggling this `visible` binding on and off a first time, the erroneous disabled attribute pops in and remains there even though the `anyProcess` binding it is tied to hasn't changed...

These are the initial (and correct) !visible and visible states of this button.

(readOnly is true, button is hidden)
![initial state](https://user-images.githubusercontent.com/6342564/27647020-de8e6abc-5bef-11e7-8067-316d9d564c9c.png)
(readOnly is false, button is shown)
![initial on state](https://user-images.githubusercontent.com/6342564/27647154-471395a8-5bf0-11e7-99f4-adbe5ba7f2ba.png)

And this is how the button is rendered after toggling its visibility on/off a first time...

(readOnly is true, button is hidden but disabled)
![incorrect attribute off](https://user-images.githubusercontent.com/6342564/27647293-a37b73ec-5bf0-11e7-93c8-81f22b22876f.png)
(readOnly is false, button is shown but disabled)
![incorrect attributes](https://user-images.githubusercontent.com/6342564/27647537-4b27c370-5bf1-11e7-9bd4-29361978e733.png)

I confirmed by way of logging that `anyProcess` does not change. I also tried letting knockout unwrap this binding in the HTML and explicitly unwrapping it myself as shown. Both had the same effect. I have tested this on Chrome, Firefox, and Safari.

**Comment by mattLummus** [comment]
There was another script that shouldn't have been included in this project that was causing a namespace conflict. Closing this issue out.

Some days you just have to talk to the duck. 
![zzcczpv](https://user-images.githubusercontent.com/6342564/27650436-97202048-5bfa-11e7-9e0c-5f8aceb29164.jpg)

**Comment by codymullins** [comment]
works on my machine! lol
