### ISSUE TITLE
Performance issues when using lots of observables...

### ISSUE THREAD

**Issue by jogibear9988** [knockout/knockout#2264]
I use knockout in a html visualization system.

On big systems, we have about 160000 tags we need in our UI. For each tag I create 1 observable and 3 computed ones, because you can bind to different values of the tag.

The creation of the observables takes abou 5seconds, is there a good way to speed this up?

**Comment by brianmhunt** [comment]
That's a long time for observable creation; are they bound to the DOM  at the time of creation?  Are the computeds O(1)?

**Comment by jogibear9988** [comment]
They are not yet bound!

This is my init Code:

    constructor (config, startValue) {
        this.Config = config;
        this.FullName = config.A; // A='Name'
        this.Name = this.FullName.substr(this.FullName.lastIndexOf('.') + 1);
        this._controlOrginalValue = null;

        this._orginalValue = ko.observable();
        this._orginalValue(this._parseValue(startValue));

        this.value = ko.computed({
            read: () => {
                return this._scaleValue(this._orginalValue());
            },
            write: (value) => {
                this.controlValue = value;
            },
            owner: this
        });

        this.value.beforeSubscriptionAdd = () => {
            this.registerTagForReading();
        };

        this.value.afterSubscriptionRemove = () => {
            this.unRegisterTagForReading();
        };

        this.originalValue = ko.computed({
            read: () => {
                return this._orginalValue();
            },
            write: (value) => {
                this.controlOrginalValue = this._scaleControlValue(value);
            },
            owner: this
        });
        this.originalValue.beforeSubscriptionAdd = () => {
            this.registerTagForReading();
        };
        this.originalValue.afterSubscriptionRemove = () => {
            this.unRegisterTagForReading();
        };

        this.valueStripped = ko.computed({
            read: () => {
                let val = this._scaleValue(this._orginalValue());
                if (val != null && typeof val === 'string') {
                    val = val.trimEnd('.');
                }
                return val;
            },
            write: (value) => {
                this.value(value);
            },
            owner: this
        });
        this.valueStripped.beforeSubscriptionAdd = () => {
            this.registerTagForReading();
        };
        this.valueStripped.afterSubscriptionRemove = () => {
            this.unRegisterTagForReading();
        };

        this.isChanged = false;
    }

**Comment by jogibear9988** [comment]
and this are the 2 used functions:

    _parseValue (value) {
        if (this.Config.C === 'Bool') { // C='TagDataType'
            if (typeof value === 'boolean') {
                return value;
            }
            if (value != null && ((typeof value === 'string' && value.toLowerCase() === 'true') || value === '1')) {
                return true;
            }
            return false;
        }
        return value;
    }

    _scaleValue (value) {
        return value;
    }

**Comment by mbest** [comment]
Suggestions: use `ko.pureComputed` instead of `ko.computed`. Don't use `beforeSubscriptionAdd`, etc., which are internal. Subscribe to [`awake` and `asleep` events](http://knockoutjs.com/documentation/computed-pure.html#state-change-notifications) instead. Because you are using `=>` syntax for your functions, you don't need to set `owner`.

Also it seems that you're creating computed observables whose value wouldn't even change. In none of the `write` functions do you write to an observable.

**Comment by jogibear9988** [comment]
How can I use the write event on the pureComputed? 
I do not write to observables, but write sends values to my backend wich then sends changes back to frontend

**Comment by mbest** [comment]
> How can I use the write event on the pureComputed?

It's the same as `ko.computer`.

**Comment by jogibear9988** [comment]
At my test project I've now switched from "Computed" to "purecomputed" it's faster, but still not very fast ;-)
I've 160190 Tags wich means I create 160190 observables and 3*160190 computed ones. This takes 6172 miliseconds with "computed" and 4774 miliseconds with "purecomputed" (this is all in using chrome)

**Comment by codymullins** [comment]
@jogibear9988 you should consider, do you really need a computed here?

**Comment by jogibear9988** [comment]
is a normal observable performanter than a computed?
the value of the computed is only calculated when it's bound, or am i wrong?

**Comment by krnlde** [comment]
The value of a pureComputed is only calculated when something is subscribed to it (e.g. bound to a DOM)

**Comment by fastfasterfastest** [comment]
> the value of a computed is always and immediately calculated

Unless the `deferEvaluation` option is specified when the `ko.computed` is created.

**Comment by jogibear9988** [comment]
then why does the creating of my 160k observables and my 480k computed takes so long? (don't know if this is long for knockout)

**Comment by jogibear9988** [comment]
ok, could deferEvaluation also be used on purecomputed?

**Comment by fastfasterfastest** [comment]
[Computed Observable Reference](http://knockoutjs.com/documentation/computed-reference.html)

**Comment by jogibear9988** [comment]
i've now tried using "deferEvaluation" with computed or pureComputed. Init takes the same time...

**Comment by krnlde** [comment]
Creating 100k+ observables is not a trivial problem. What time do you expect it to take? I think 10sec is fair, although not a great user experience.

**Comment by jogibear9988** [comment]
don't know ;-) because of that i ask
its 100k observables and 300k computed

in wpf i can create the objects in a task and hand them over to the ui thread.

can i use webworkers to create my observables?

**Comment by krnlde** [comment]
Also drawing 100k elements to the DOM will freeze your browser for a lot longer than 10sec. And an IE longer than a chrome.

**Comment by krnlde** [comment]
You could try batching the creation, say 1000 per event-loop, using setTimeout

**Comment by jogibear9988** [comment]
will requestAnimationFrame also work?

i do not draw 100k elements. The problem is, I have a visualization wich can be changed by the customer, so i don't know wich observables are used in wich view, so I need to create them all!

**Comment by krnlde** [comment]
I don't think you really need to, but of course it is easier. Yes you can also use rAF

**Comment by mbest** [comment]
How many observables are displayed at a time? Observables are used for values that can change in the application. How can these values change and how often?

**Comment by jrsearles** [comment]
It may be that you are trying to solve the wrong problem here, but I've run into similar situations with wide datasets. Based on configurations any number of properties need to be wrapped in observables. The way i dealt with this is to lazily create the observable, only when the property is read. There is no value in creating the observables during initialization or when values are set, but when they are read you need to create the observable so that all of the dependencies are registered. In this manner the cost of creating observables is only incurred when you actually need them.

In the [ko-track](https://github.com/SteveSanderson/knockout-es5) plugin i added a `lazy` option. I also have a wrapper for lazily creating observables that i can post if it's helpful.

As mentioned chunking is another option. The caveat here is that it will actually take longer to process your data, however the UI won't appear locked to the user. I can't think of a way web workers will help you here.

**Comment by jogibear9988** [comment]
I've now switched to creating the observables lazily, seems to work. Thanks for the tip.

**Comment by krnlde** [comment]
Cool. Close this issue?
