### ISSUE TITLE
Google forum blocked

### ISSUE THREAD

**Issue by mbest** [knockout/knockout#2266]
http://groups.google.com/group/knockoutjs is showing a "Banned Content Warning" and therefore doesn't work anymore. @rniemeyer can you take care of that? Maybe make me an owner also. Thanks.

**Comment by rniemeyer** [comment]
@mbest I tried on Friday and couldn't get into any management options or anything useful. I'll try again and see if I can find a way to contact google. @SteveSanderson - any chance that as the owner you see any useful options on the forum?

**Comment by rniemeyer** [comment]
My role is listed as Manager and Steve is Owner. The management options are not showing me anything helpful at this point. Hoping perhaps Steve can assist. I will try to find a way to contact google as well.

**Comment by rniemeyer** [comment]
I sent a feedback message to Google. I am unable to see or remove messages or elevate anyone else's role. Best I can find is that the owner should have an option to appeal:

```
If you're the owner of the Group with the limited content, you can appeal the decision through these steps.

1. Open Google Groups > click My Groups > name of the Group you wish to appeal.
2. Click the name of your Group > Request Review on the Group's home page.
```

cc: @SteveSanderson

**Comment by mbest** [comment]
Thanks for trying.

**Comment by SteveSanderson** [comment]
Thanks for keeping an eye on this! I've clicked the big red "Request Review" button, and it says the request was received. It doesn't saying anything about an ETA for when they will do anything.

> My role is listed as Manager and Steve is Owner

I've now added Michael and Ryan as owners too. Hopefully that takes effect immediately.

**Comment by rniemeyer** [comment]
Forum is back up. I went through and deleted some of the recent spam.
