### ISSUE TITLE
Problem with Virusscan ClamAV

### ISSUE THREAD

**Issue by wetzesa** [knockout/knockout#2271]
Hi *,

we have the problem that the virusscan ClamAV blocks the download of 2 knockout files.
../lib/knockout/template/renderer.js
../knockoutjs/knockout-repeat.js

We use Magento 2 (Version 2.1.7) as eCommerce Software.
Now I am not sure if it is a bug inside of the used knockout version or it is a bug from virusscan side. 

Knockout version: 2.1.0

Best, Sascha

**Comment by codymullins** [comment]
This is probably an issue with your AV.

**Comment by brianmhunt** [comment]
This is not something Knockout can predictably or reliably fix, and falls in the domain of support.

You may want to contact the virus scanner, or a general support site Q&A such as superuser.com

I hope that helps.

There not being anything that Knockout can do to fix this, I am closing— but if I am mistaken please comment and we can certainly consider reopening.
