### ISSUE TITLE
Assigning an Observable to Another Observable Changed from 3.4.0 to 3.4.2

### ISSUE THREAD

**Issue by mattf0st3r** [knockout/knockout#2274]
After recently updating from 3.4.0 --> 3.4.2 we started getting view binding errors in parts of our app that had not otherwise changed. The issue seems to be in areas where we were assigning an observable to another observable `targetObservable(sourceObservable);`. The binding error seems to occur because this assignment seems to create an observable observable.... meaning to access the properties you would need to call them as `targetObservable()().someProperty` instead of `tragetObservable().someProperty`. It also may be worth mentioning that the view also uses `with: targetObservable` binding.

Perhaps this approach of assigning one observable to another is incorrect?

**Comment by mbest** [comment]
If Knockout was double unwrapping the observable, then that was a mistake. Knockout bindings should only do a single unwrap.

**Comment by mbest** [comment]
You could work around the change by using `with: targetObservable()`. In this case, you do the first unwrap and let the binding handler do the second.
