### ISSUE TITLE
Failed to read the 'cookie' property from 'Document': Access is denied for this document.

### ISSUE THREAD

**Issue by hoanghiep** [knockout/knockout#2284]
Hi guy
I  use knockoutjs 3.4.2 and get an error below. Can someone help me? Thank in advance.

knockout-3.4.2.debug.js:2395 Uncaught DOMException: Failed to read the 'cookie' property from 'Document': Access is denied for this document.
    at http://localhost:8084/xxx/static/lib/knockout-3.4.2.debug.js:2395:61
    at visitPropertiesOrArrayEntries (http://localhost:8084/xxx/static/lib/knockout-3.4.2.debug.js:2427:17)
    at mapJsObjectGraph (http://localhost:8084/xxx/static/lib/knockout-3.4.2.debug.js:2394:9)
    at http://localhost:8084/xxx/static/lib/knockout-3.4.2.debug.js:2409:27
    at visitPropertiesOrArrayEntries (http://localhost:8084/xxx/static/lib/knockout-3.4.2.debug.js:2427:17)
    at mapJsObjectGraph (http://localhost:8084/xxx/static/lib/knockout-3.4.2.debug.js:2394:9)
    at http://localhost:8084/xxx/static/lib/knockout-3.4.2.debug.js:2409:27
    at visitPropertiesOrArrayEntries (http://localhost:8084/xxx/static/lib/knockout-3.4.2.debug.js:2427:17)
    at mapJsObjectGraph (http://localhost:8084/xxx/static/lib/knockout-3.4.2.debug.js:2394:9)
    at http://localhost:8084/xxx/static/lib/knockout-3.4.2.debug.js:2409:27

**Comment by brianmhunt** [comment]
It looks like you're calling `toJS` on something that has a cookie property (the root Document?).  the `toJS` method does serialize HTML nodes.

I've seen this before and I recall solutions on Google.  In any case, this is a support questions so I will close this — it would be better handled on e.g. stackoverflow.

If there is any improvement KO could do here, please advise and we can reopen.

Cheers.

**Comment by cannontechnology** [comment]
Hi hoanghiep - I just ran into this same issue with knockout on an app that has been in production for quite some time.  Could you let me know where the issue was and how you solved it?

**Comment by hoanghiep** [comment]
My code
```
var MyVm = function(){
  var self = this;
  var self.var1 = ko.observable();
  var self.var2 = ko.observable();
  var self.popup = null;
  // somewhere
 // ....
  self.popup = [A html UI control]; 
//...
}
```
After self.popup was assigned (it not null), that error has occurred when i called toJs function. 

You should clear all self.XXX variables (they are not ko.observable) before calling toJs.

**Comment by chrisknoll** [comment]
I think that storing an element like that in the view model is problematic, although I do understand the use case.  toJS() can take a function that can be used to 'ignore' certain properties, maybe the answer is to skip that property when serializing to JS.

**Comment by IanYates** [comment]
I agree with @chrisknoll .  There are a couple of cases where it's necessary.  One example is where we had a binding to a Kendo Chart control and needed the actual Kendo widget reference in the view model to do some configuration.  The binding populates that for us.

I patch our KO's .toJS and .toJSON with a version of toJS and toJSON which check the given object for its own toJS method, and if found, that method is used instead.  That way I can handle the *very* occasional view model having this sort of mess without worrying about toJS blowing up (one of the Chrome debug tools inspectors, for example, didn't cope with this).

**Comment by chrisknoll** [comment]
Right, the chrome debugger chokes on this.  Would be nice if there was some feature in knckoutJS that properties of DOM elements are skipped.  Not exactly sure how to detect it.  

On your point about widgets: we do the same thing with jquery-ui components: we pass in an observable that is assigned to the databindings' api to the jquery widget.  Thing is, I don't think that's actually a dom element that it is bound to in that case, but it's definitely somethign you don't want to serialzie...but come ot think of it, the api handles returned from jqueryUI i think are 'pure function interfaces' (only sets of functions returned) so I don't think that would get serialized out anyways...but I haven't looked closely at this.
