### ISSUE TITLE
'src/tasks.js' maybe there is a bug

### ISSUE THREAD

**Issue by xp44mm** [knockout/knockout#2289]
in function processTasks(),the code is:
```javascript
    function processTasks() {
        if (taskQueueLength) {
            // Each mark represents the end of a logical group of tasks and the number of these groups is
            // limited to prevent unchecked recursion.
            var mark = taskQueueLength, countMarks = 0;

            // nextIndexToProcess keeps track of where we are in the queue; processTasks can be called recursively without issue
            for (var task; nextIndexToProcess < taskQueueLength; ) {
                if (task = taskQueue[nextIndexToProcess++]) {

```
the last line sould be next line, right?
```javascript
if (task === taskQueue[nextIndexToProcess++]) {
```
i don't sure. but i point it out.

**Comment by chrisknoll** [comment]
I think it's correct:  it assigns task to the next task to process via tasQueue[nextIndexToProcess], then incrementing nextIndexToProcess...and if task is something 'truthy' (ie: has a value) then it will do the work that's inside the IF.  

Your proposal would never assign task to anything, and therefore never do work.

**Comment by mbest** [comment]
Some might like the code to be split up for clarity, but the logic is correct.

```
task = taskQueue[nextIndexToProcess++];
if (task) {
```
