### ISSUE TITLE
Binding only works once ...

### ISSUE THREAD

**Issue by jogibear9988** [knockout/knockout#2291]
I've the following Binding:

     data-bind="style: { 'background-color': visuClient.intToBrushConverter(RF013.value()) }"

where "RF013.value" is a computed observable!

But my background is only refreshed once.

**Comment by brianmhunt** [comment]
The value needs to be a `ko.computed`, so `intToBrushConverter` must return a computed observable or there must be another function on the view that does (i.e. `ko.computed(function ( { return visuClient.intToBrushConverter(RF013.value()) } ))`

As a support question I'll close this, since there's no issue that KO itself can improve upon.  However, @jogibear9988 if you feel there's a way to improve Knockout please advise and we can re-open.

Cheers

**Comment by jogibear9988** [comment]
I do not understand what you mean.


If you look at:  http://knockoutjs.com/documentation/binding-syntax.html

you have this example:

     
     <button data-bind="enable: parseAreaCode(cellphoneNumber()) != '555'">...</button>
 
du you return a computed there?

**Comment by brianmhunt** [comment]
Thanks @jogibear9988 — you are correct that computeds will be generated from bindings with observables.

Is `RF013.value` an observable?

Maybe you can post a jsFiddle illustrating the problem?  What version of KO are you using?

You can also cross-post this to StackOverflow for better visibility.

**Comment by jogibear9988** [comment]
RF013.value is a computedObservable

i look if i can create a fiddle!

reopen?

**Comment by brianmhunt** [comment]
Thanks @jogibear9988 

Let's look a the jsFiddle then we see where the problem lies — If there's an issue with KO, will absolutely reopen.

**Comment by jogibear9988** [comment]
I've now tried in this fiddle: http://jsfiddle.net/LkqTU/36651/
there it works.... need now to look what is different in my code

**Comment by papandreou** [comment]
@brianmhunt

> The value needs to be a `ko.computed`, so `intToBrushConverter` must return a computed observable or there must be another function on the view that does (i.e. `ko.computed(function ( { return visuClient.intToBrushConverter(RF013.value()) } ))`)

That doesn't sound entirely correct? If I'm not mistaken, Knockout's dependency tracking will notice that `RF013.value` is being dereferenced, so the `ko.computed` that's automatically wrapped around the value of the `style` binding will have a dependency on `RF013.value` and update itself automatically when it changes.

That's also consistent with how the fiddle behaves.

**Comment by jogibear9988** [comment]
It works now on my system... don't know what I did wrong yesterday... Same as in the fiddle... it works

**Comment by brianmhunt** [comment]
@papandreou You're correct - I didn't know `.value` was an observable. :o)
