### ISSUE TITLE
Binding context exports unnecessary properties which could shadow globals.

### ISSUE THREAD

**Issue by bennieswart** [knockout/knockout#2294]
In the file bindingAttributeSyntax.js a `_subscribable` property is created on a binding context under certain conditions. During build, this property is minified and in the 3.4.2 release it is exported as `Q`. See this jsfiddle for an example: https://jsfiddle.net/s0wf1hga/1/. Note the errors in console.

This becomes a problem when a global property with the same name exists and referenced from inside bindings. Granted, the chance of a name conflict is rare. I did, however, encounter a problem with a custom build I was making where `_subscribable` was minified to `$`, which shadowed jquery in all bindings and broke a lot of things.

The workarounds for this problem are many, I know, but rather than a workaround I feel it is more right and rather easy to remove the problem. I'm also not saying that all unnecessary properties everywhere should be hidden, but the binding context is a rather unique situation with more ramifications than usual.

**Comment by mbest** [comment]
Those are good points. Perhaps we shouldn't minify `_subscribable`.

**Comment by bennieswart** [comment]
Not minifying `_subscribable` is the workaround I ended up using.
Ideally I suppose one would want to 'hide' the property on the instance, for example by using Symbols. Is there a way to do this across all the currently supported browser versions?
If not I'd be happy to submit a PR which prevents `_subscribable` from being minified, as well as a test case if you think it useful.

**Comment by mbest** [comment]
We could use a `Symbol` in browsers that support it and a non-minified property on the others. We have that already for `ko.computed`: https://github.com/knockout/knockout/blob/master/src/subscribables/dependentObservable.js#L1
