### ISSUE TITLE
[Performance] Computed vs if binding

### ISSUE THREAD

**Issue by sacredMonster** [knockout/knockout#2299]
Hello,

Is it performant to use if bindings with a bunch of && statements in the view vs creating a computed value of all these statements in the viewModel. 
Eg: 
 ko if: $data.value1() && $data.value2()
or
viewModel.value3 = ko.computed(function () {
return viewModel.value1() && viewModel.value2();
});

thanks..

**Comment by chrisknoll** [comment]
That results in the same, it might look inicer to do the ko: if: value3 in the html. But when you ahve an expression in a binding, the expression is wrapped in a computed.

**Comment by brianmhunt** [comment]
As Chris says, they are effectively near-identical, in the sense that expressions are automatically translated into computeds.

Closing as this is a not really something that KO can improve on, and it can be answered by experimentation.  But please advise if there's something here that we could do.
