### ISSUE TITLE
template binding with property? 

### ISSUE THREAD

**Issue by miellaby** [knockout/knockout#2307]
I often use the "template" binding where I should use the "with" binding because I lake for an "afterRender" callback.

To replicate the "with" behavior (no sub-tree for falsy values), I had to duplicate "if" and "data" properties in my templates.

Any chance for a "with" property in the template binding?

**Comment by mbest** [comment]
`afterRender` is coming for the `with` binding. See #2100

**Comment by miellaby** [comment]
@mbest. I consider submitting another feature-request. My need consists in passing every output of knockout DOM generation mechanism through a couple of processors like i18next.com (which looks at data-i18n html attributes), or some CSS toolkits which attach behavior here and there. Custom-bindings doesn't help much here. So, I think about a global afterRender callback which would be called on all nodes generated by the overall ko templating mechanism. Have such a feature already been thought about?

**Comment by brianmhunt** [comment]
Noting https://github.com/knockout/tko/issues/8
