### ISSUE TITLE
Use jQuery when available in style binding

### ISSUE THREAD

**Issue by wallymathieu** [knockout/knockout#231]
We had a problem in our project with setting background color in IE and firefox. I've tried to make a simple example out of an existing fiddle:
http://jsfiddle.net/ozzymcduff/GSvnh/30/
The fiddle has problem rendering in firefox, but not IE9 and chrome. This is probably a cross browser thing.  

In knockout we have the following in the style bindinghandler
element.style[styleName] = styleValue || "";
We made a separate style bindinghandler and changed the above to 
$(element).css(styleName, styleValue || "");

**Comment by jrsearles** [comment]
Another useful thing jQuery does is check for a vendor prefixed version if the style property does not exist. I ran into this today using the default Knockout style binding.

I agree that the behavior should be consistent when not using jQuery though, so my preference would be for that behavior to be pulled into Knockout.

**Comment by mbest** [comment]
See #2302

**Comment by derrickb** [comment]
Would it be feasible to make this optional?

Using 3.5.0rc, I'm finding that I now have to wrap my url()'s in escaped quotes which, while not the end of the world, is cluttering up my html quite a lot and making VS Code's syntax highlighting unhappy as a side effect.

I've been using the style binding like so:
`style: { backgroundImage: 'url('+getAsset('select_arrow')+')' }`
Where 'getAsset' returns a base64 string.
With the new functionality, I have to use:
`style: { backgroundImage:'url(\"'+getAsset('select_arrow')+'\")' }`

Again, not a severe issue, but I use this binding a LOT in my UI so it's unfortunate to have to go through it all to add the quotes.

**Comment by chrisknoll** [comment]
have you tried tempalted strings (using a ` to wrap your string)?

**Comment by derrickb** [comment]
Do you mean in the binding in the html file? No, because although I see that ko will support parsing these, my app runs in very old browser versions so everything needs to be transpiled, and AFAIK, there isn't a way to preprocess templated strings within data-bind's. Would love to be wrong on that.

Using template strings in the getAsset function hasn't made a difference either. I always have to wrap the result in escaped quotes in the html.

**Comment by fastfasterfastest** [comment]
@derrickb  I think you may have something else going on, or haven't told the whole story.  Are you using jquery, and if so, which version?

Here are two fiddles that uses the `style` binding and sets the background image using a data url
`<div data-bind="style: { backgroundImage: 'url('+getDataUrl(backgroundColor())+')' }"></div>`
and they seem to "work"

- [With 3.5.0rc, no jquery](http://jsfiddle.net/fastfasterfastest/bkmfwckq/)
- [With 3.5.0rc, jquery 3.3.1](http://jsfiddle.net/fastfasterfastest/bkmfwckq/1/)

**Comment by chrisknoll** [comment]
> there isn't a way to preprocess templated strings within data-bind's.

So no transpiling of code within <script> tags?  That's an interesting limitation....

**Comment by mbest** [comment]
@derrickb I'm glad you're trying out version 3.5. How has it working for you otherwise?

@chrisknoll Templated strings work in a `data-bind`: http://jsfiddle.net/bkmfwckq/2/

    data-bind="style: { backgroundImage: `url(${getDataUrl(backgroundColor())})` }"

**Comment by mbest** [comment]
Actually I think I know what the problem is. It's probably from changes made in #2148. I'll take a look at a fix.

**Comment by derrickb** [comment]
> Actually I think I know what the problem is. It's probably from changes made in #2148. I'll take a look at a fix.
Thank you! That would be the one major blocker preventing me from switching over to 3.5.0 so I really appreciate it.

**Comment by mbest** [comment]
See #2380 for a fix.
