### ISSUE TITLE
Knockout js creating memory leak when used with signal r 

### ISSUE THREAD

**Issue by phani257** [knockout/knockout#2313]
Below is my source code for reconnection if the connection to the hub is lost. I try the reconnection every 3 sec and the memory on the browser keeps increasing.

```
 $.connection.hub.start({
            transport: ['webSockets', 'longPolling']
        }).done(function () {
            var transport = $.connection.hub.transport ? $.connection.hub.transport.name : null;
            if (transport) {
                this.state(State.Connected);

            } else {

                this.retryConnection();
            }
        }.bind(this))
```

**Comment by brianmhunt** [comment]
It's not apparent what any of this means without context, or how KO is involved.  Please provide a jsFiddle demonstrating the issue.

You may also wish to consult a support forum such as StackOverflow.

Closing this for the moment, but please advise if there is a memory leak that's reproducible in a jsFiddle.
