### ISSUE TITLE
foreach example doesn't work

### ISSUE THREAD

**Issue by ahnkle** [knockout/knockout#2318]
The jsfiddle example here; http://knockoutjs.com/examples/collections.html does not work.

![image](https://user-images.githubusercontent.com/3024647/32434948-7bdaf986-c2d7-11e7-886d-2985d7f3f289.png)

Attached image is output pane.

I have tried chrome, firefox and edge.

**Comment by mbest** [comment]
It works for me.

![image](https://user-images.githubusercontent.com/1230364/32469595-45d16a7e-c308-11e7-9766-4cb682bd0269.png)

**Comment by IanYates** [comment]
@ahnkle - do you have some browser plugins installed which could be causing grief?  A private browsing / incognito session can give you a fairly plugin-free experience to easily test.

Also, run your browser dev tools and look for any failures to load resources, or errors logged to the console.

I can confirm the page works for me
