### ISSUE TITLE
ko.cleanNode() removes jQuery.on("focusout") event in textbox.

### ISSUE THREAD

**Issue by Shanmugarajakaliappan** [knockout/knockout#2321]
I have a problem when i use **ko.cleanNode(node)**, it removes focusout client event. i.e., before calling cleanNode method focusOut works properly on text box. After that focusOut event does not triggered.

**JS Fiddle link:** https://jsfiddle.net/L8cp8Los/2/

Please check the JSfiddle link, if this is behaviour that cleanNode removes the corresponding element event listeners means, is there any alternative solution without using [cleanExternalData ](http://knockoutjs.com/documentation/custom-bindings-disposal.html#overriding-the-clean-up-of-external-data)method?

**Comment by mbest** [comment]
Thanks for the report. However, using `ko.cleanNode` to re-apply bindings isn't a supported usage. I see you asked the [same question on SO](https://stackoverflow.com/q/47388242/1287183) and received a good answer there.
