### ISSUE TITLE
Knockout 4.0 - come into being?

### ISSUE THREAD

**Issue by thomas-mindruptive** [knockout/knockout#2325]
Will KO 4.0 be released any time soon? I'm perfectly happy with KO and would like to continue working with it. But maybe it's time to say farewell and choose another MVVM-framework? What are the concrete plans?
Thanks a lot

**Comment by thomas-mindruptive** [comment]
That's all very true, Paul.  And I love KO. My point is more that JS/ES evolves over time, browsers support more features and therefore I'm looking for a framework that's actively developed. 
@mbest Do you know if there are any plans for 4.0 soon?
Thanks

**Comment by brianmhunt** [comment]
Knockout has been rewritten into ES6 and the plan is for version 4 (just about to enter beta) to be based on the modules of [tko](/knockout/tko).  Check out its CHANGELOG.md for details.

**Comment by brianmhunt** [comment]
... closing this, but please comment if there is a reason to leave it open.

**Comment by thomas-mindruptive** [comment]
OK, thanks Brian, looking forward to 4.0.
Best
