### ISSUE TITLE
Memory Leak involving ko.computed() and a rate-limited ko.observable()

### ISSUE THREAD

**Issue by kersam-bl** [knockout/knockout#2328]
[knockout_memleak.zip](https://github.com/knockout/knockout/files/1538765/knockout_memleak.zip)
![devtools](https://user-images.githubusercontent.com/1724111/33711818-9a7cf8cc-db45-11e7-8afb-c273db79cafa.png)

We are experiencing some memory leak/missing cleanups when using ko.computed() together with a rate-limited observable.

Steps to reproduce:
- Load the attached test.html in Google Chrome.
- Open the developer tools and make a Heap Snapshot.
- Search for "MyFancyObject"
Result:
The object shows up in the heap (see screenshot).
Expected result: no instance of MyFancyObject shows up, since none of it is reachable. The only reference is from inside the computed-observable callback, but the computed observable was already disposed.

Please note: Removing on of the two lines marked in the script will make the leak disappear.

**Comment by mbest** [comment]
I tested your sample with 3.5.0-pre code and there is no longer a leak. Probably this is related to #1405.
