### ISSUE TITLE
Template no longer invokes functions given to observables

### ISSUE THREAD

**Issue by JoshWhite** [knockout/knockout#2329]
Since upgrading from release 3.4.0 -> 3.4.2, the behavior of observables inside templates has changed. 

As you can see [here](https://codepen.io/JoshWhite/pen/YYXypB), with release 3.4.0, if an observable containing a function was passed to a template, the function would first be executed, then the returned value would be given to the template. 

In version 3.4.2, the function is not executed. 

Although I think the latest functionality feels more natural (and matches the behavior of observables not contained in a template), it has broken a web app I'm working on, so seems strange for a minor release. For example, if this technique has been used elsewhere, it will be pretty hard to track down, as functions given to observables could have been named. Eg:

```
function myFunc() {
    return 'some text'
} 
var obs = ko.observable(myFunc)
```

**Comment by mbest** [comment]
Unfortunately, the previous functionality was mostly accidental. But you can work around the issue by unwrapping the observable in the binding

```html
<!-- ko template: { name: 'template', data: observableWithFunction() } --><!-- /ko -->
```

https://codepen.io/anon/pen/Mraeay

**Comment by JoshWhite** [comment]
I agree it seemed like a bit of a quirk.

However, this is a (slight) change of API and causes bugs after upgrading. 

Although the fix is simple, as I mentioned, it will be very difficult to confidently track down instances where functions have been provided to observables, before being passed into a template.
