### ISSUE TITLE
Knockout memory crash issue

### ISSUE THREAD

**Issue by AtulUjjwal** [knockout/knockout#2330]
I am using KO for updating rows of an observable table. The table is generated and works for data array less than 700, but the page crashes when data is larger say > 1000. I am not sure how to prevent this issue. I am using knockout-3.3.0 Here is the code where the crash occurs.

`self.testcase = ko.observableArray([]); `
 `self.loadDetailData = function (type, entity, criteria) `
                                  ` { self.testcase.removeAll();`
                                    ` toastr.clear();`
                                     `UI.toastrPopUp("info", 'Getting information...', '', null, 'progressbar'); `
                                     `fetchResults(type, entity, criteria).done(function (data) {`
                                                        `  if (data != "") {`
                                                              ` var testInstances = data.map(function (item) {`
                                                              ` return (new test(item))});      `               
                                      `self.testcase(testInstances);//crashes here if data ~ 1000    `     
  ` });`

**Comment by brianmhunt** [comment]
There are folks (including myself) who have used KO with tens/hundreds of thousands of rows of data without issue.  There's no immediate indication from the code sample why this would be going off the rails for you.

Please consider posting a jsFiddle and asking on Stackoverflow as it's better support forum with a broader audience.

As this is a support question and there's no apparent improvement to be done to Knockout here, I'll close this — but please feel free to continue discussing, and if an issue with KO comes up we can reopen.

Sorry it's not more help here, but I hope this helps.
