### ISSUE TITLE
Question about migration to vue.js

### ISSUE THREAD

**Issue by mrshawn191** [knockout/knockout#2331]
Sorry for opening an issue, but couldn't find any material online about migration to another framework such as vue.js

While knockout has served me very well. I'm trying to understand if it is possible to migrate small chunks of the program in vue.js? And would that be done?

**Comment by mbest** [comment]
Perhaps you'll find an answer posting this on StackOverflow.

**Comment by brianmhunt** [comment]
@mrshawn191 The way to go here would probably be a custom binding that renders its internals with Vue.  I've never given it a shot, but that's the theory.
