### ISSUE TITLE
Knockout Component Template Rendered as Plain Text in Firefox

### ISSUE THREAD

**Issue by bschne** [knockout/knockout#2337]
I have a knockout component declared like this:

  ```
  ko.components.register('promocode-box', {
        viewModel: { require: 'foo/promocode-box-viewmodel' },
        template: { require: 'text!foo/promocode-box-template.html' }
    });
```

RequireJS as well as the text plugin are both loaded and configured like this:

   ```
 requirejs.config({
        baseUrl: 'https://foo.com/js/'
    });
    define('knockout', ko);
```

I then use it in the page with a custom element:

```
<promocode-box params="foo: 'bar', baz: 'foobar'"></promocode-box>
```

Now what happens is that in every browser, the component renders correctly, but firefox (tested on v. 57.0.4) shows the component template's source code as 
plain text in the page, instead of rendering the component as expected.

Does anyone have any pointers as to what could be the issue here?

**Comment by bschne** [comment]
Just a quick update, I have put together a small demo with which I was able to reproduce the issue, you can download it here: [KO Firefox Issue Repro.zip](https://github.com/knockout/knockout/files/1628187/KO.Firefox.Issue.Repro.zip)

To run it, simply start http-server (install with `npm install http-server -g` if you don't have it already) in the root directory and open localhost in the browser.

Here's how it looks like in Chrome:

![image](https://user-images.githubusercontent.com/18404509/34904555-6a36e446-f848-11e7-99ee-e10ccac341ea.png)

And here's Firefox:

![image](https://user-images.githubusercontent.com/18404509/34904561-7dd5eb78-f848-11e7-98e2-6823780c23e5.png)

**Comment by bschne** [comment]
I did some further tests and it appears to be an issue with the text.js plugin returning the template content in a form that jquery cannot parse, so I will look into it on that end and am closing this issue.

**Comment by chrisknoll** [comment]
I'd look into those 2 unprintable characters appearing at the start of the firefox output. Could be some kind of BOM that is screwing with the parsing.
