### ISSUE TITLE
ko is not defined when knockout's script tag is added after monaco-editor's.

### ISSUE THREAD

**Issue by zhuxinghan** [knockout/knockout#2340]
I use both knockout and monaco-editor in may html pages. I found that if I introduce monaco's script tag first, knockout's ko will not be defined, but If I switch the order they are introduced(knockout first), ko works well. Here is a sample html page that can reproduce the problem:

`<pre>&lt;html>
&lt;head>
    <script src="monaco-editor/loader.js"></script>
    <script src="knockout-3.4.2.js"></script>
&lt;/head>
&lt;body>
    <script>
        ko.applyBindings({});
    </script>
&lt;/body>
</html></pre>`

Knockout version: 3.4.2
monaco-editor version: 0.10.1
Browser: Edge

**Comment by mbest** [comment]
It appears the Monaco includes an AMD loader. Knockout is set up to use AMD if it is present and not set a global `ko` in that case.

**Comment by brianmhunt** [comment]
Perhaps this might be noted in the docs?
