### ISSUE TITLE
Knockout observable (two way binding) not working with Sharepoint modal dialog

### ISSUE THREAD

**Issue by sairfan1** [knockout/knockout#2348]
I was trying to test knockout observable (two way binding) on SP wiki page i was able to run code successfully, when i update last name its updated in fullname p tag, but when i tested same code on sharepoint dialog it shows values but does not update fullname, means its not working as observable (two way binding)

```    
<div id="wrap" style="display:none">
    <div id="d10" class="dialogHolder">
        <div id="kobasic">
            <h4>Editable data</h4>
            <p><input type="text" data-bind="value: firstName" /></p>
            <p><input type="text" data-bind="value: lastName" /></p>
            <p>Full Name: <span data-bind="text: fullName"></span></p>
        </div>
    </div>
</div>

        var ViewModel = function () {
        var self = this;

        self.firstName = "Irfanullah";
        self.lastName = ko.observable('M.');

        self.fullName = ko.computed(function () {
                return self.firstName + ' ' + self.lastName();
            });
        };
        ko.applyBindings(new ViewModel());

     function openDialog2() {
        var e = document.getElementById('d10');
        var options = {
            title: "Test knockout",
            width: 700,
            height: 800,
            html: e.cloneNode(true)
        };
        mydialog = SP.UI.ModalDialog.showModalDialog(options);
    }
```
What i understand, it be because of e.cloneNode(true) but i could not figureout how can i fix it.

**Comment by chrisknoll** [comment]
Sounds like cloneNode is the suspect here, but why don't you have a custom databind that you can apply tot he DIV element instead of using getElementByID (which I think is an anti-pattern in the knockout world):

```
<div id="wrap" style="display:none">
    <div data-bind="sharepointDialog: openObservable">
        <div id="kobasic">
            <h4>Editable data</h4>
            <p><input type="text" data-bind="value: firstName" /></p>
            <p><input type="text" data-bind="value: lastName" /></p>
            <p>Full Name: <span data-bind="text: fullName"></span></p>
        </div>
    </div>
</div>
```

You'd implement inside the sharepointDialog all the init steps you need to set up the dom element. I don't think you'd clone in this case, you're given the dom's element in the init() method.  I imagine it would follow the same pattern as the jquery-ui dialog pattern: https://gvas.github.io/knockout-jqueryui/dialog.html.

**Comment by sairfan1** [comment]
I have more than one elements on the page that i want to bind, that's why I'm using document.getElement

**Comment by chrisknoll** [comment]
Right, so each element you'd apply your custom databind to.  As your app gets larger and more complicated, you run the risk of 'elementId collisions'. So I'd suggest working with a custom databinding.

**Comment by mbest** [comment]
See http://knockoutjs.com/documentation/custom-bindings.html

**Comment by sairfan1** [comment]
I tried above link, but no success, found solution [https://stackoverflow.com/questions/48790825/knockout-two-way-binding-not-working-with-sharepoint-modal-dialog/48794006#48794006](here) I will appriciate if you could explain it with small example. thanks
