### ISSUE TITLE
preprocessNode is not called for the bound root node

### ISSUE THREAD

**Issue by cervengoc** [knockout/knockout#2350]
Hi, I've found an interesting scenario.

If I call `ko.applyBindings` on a node, then the `ko.bindingProvider.preprocessNode` hook won't get called on the root node itself, only on its descendants. I've double-checked the source code and found the call only inside `applyBindingsToDescendantsInternal` which kind of proves this. 

Is this behavior by design? Won't it cause issues when using for example `ko.punches` plugin?

**Comment by mbest** [comment]
This is an interesting case. I know that `ko.applyBindings` is used internally on nodes that were already preprocessed, so there would need to be some way to figure out whether it had already been done. Also `preprocessNode` can return a new set of nodes, so `ko.applyBindings` would need to be able to handle an array of nodes.

**Comment by cervengoc** [comment]
That's clear, thank you for the details. In this case I'd rather live with this limitation as this has very few real-world use-cases I guess.

Although it would probably be good to take a note in the documentation.
