### ISSUE TITLE
Nesting option element under an if binding causes wrong behavior

### ISSUE THREAD

**Issue by HeyJude1** [knockout/knockout#2352]
I have a `<select>` element bounded to some value, and an `<option>` element (bounded also to some value) nested under two bindings levels: a `foreach-binding` and an `if-binding`.
The behavior I get is that when selecting an option, it doesn't get rendered, but the underlying observable is correctly updated.
Code ([fiddle](https://jsfiddle.net/HeyJude/wbb5258q/44/)):
JS:
```
var DogHouseViewModel = function() {
    var self = this;
    self.allowedNames = ["A", "B", "C"];
    self.puppies = ko.observableArray([]);
    self.createPuppy = function () {
  	   self.puppies.push(new DogViewModel());
    }
    self.isNameAlreadyTaken = function (puppyName) {
      self.puppies().forEach(function (puppy) {
        if (puppy.dogName() == puppyName) {
          return true;
        }
        return false;
      })
    }
    self.printPuppiesName = function () {
  	  self.puppies().forEach(function (puppy) {
    	  alert(puppy.dogName())
    })
  }
} 
var DogViewModel = function (dogName) {
   var self = this;
   self.dogName = ko.observable();
}

vm = new DogHouseViewModel()
ko.applyBindings(vm);
```
HTML:
```
<div>  
   <button data-bind="text: 'create a puppy', click: createPuppy"></button>
   <button data-bind="text: 'print puppies names', click: printPuppiesName"></button>
   <div data-bind="foreach: puppies">
      <select data-bind="value: dogName">
         <!-- ko foreach: $parent.allowedNames -->
            <!-- ko if: !($root.isNameAlreadyTaken($data)) -->
               <option data-bind="value: $data, text: $data"></option> 
            <!-- /ko -->
         <!-- /ko -->
      </select>
   </div>
</div>
```

**Comment by chrisknoll** [comment]
I get the foreach to get you multiple dropdowns, but you should use the select binding when dealing with select lists:
```
<select data-bind="options: $parent.allowedNames, 
	optionsText: function(item) { return item.name }, 
	optionsValue: 'id',
	value: $data.dogName>
</select>
```

Something like that, i'm not sure how your names are keyed.  Also, your allowedNames, if it's dynamic based on what is selected, you might need to make that a function that returns an array of allowed names...I'd suggest a computed observable, however the computed observable needs to take a parameter indicating which name has already been accepted (or you can just simplify it so that your allowedNames always shows all the sets of names.  But it looks like you want all puppy names to be unique, so i'd decare a function at the same scope as isNameAlreadyTaken called getAllowedNames() that returns the list of available names (after taking account all the chosen names).

Actually, if you do it this way, getAllowedNames can be a pure computed since you're scanning the all the puppies, not just the one in the current context...so it's more of a global thing.

**Comment by fastfasterfastest** [comment]
And... your `isNameAlreadyTaken ` is likely incorrect, since it doesn't return a value.

**Comment by mbest** [comment]
This is simple not a supported usage. As @fastfasterfastest mentioned, the recommended approach is to use the `options` binding. If you want to use `foreach`, you need to figure out some way to let the `value` binding know to update (something the `options` binding does for you).

Unfortunately, you'd run into another problem. Your design is to immediately remove the currently selected item. This will cause the value binding to update to the newly selected item. Then that item will get removed, etc., resulting in an infinite loop. You could mitigate this by using the `valueAllowUnset` binding option, although it would be better to improve your design.

**Comment by fastfasterfastest** [comment]
> for the sake of understanding what's technically wrong here, I can't make it work

What happens is that as soon as you select an item in the/a `select` element, your if-binding removes the very `option` element that was selected.  Thus, it (that item) is no longer available in the `select` element and can not be rendered as the selected item of the `select` element;  instead, the first `option` is rendered.

**Comment by chrisknoll** [comment]
Perhaps if the computed options left the option that was currently selected for the given item...it's more complicated, but @fastfasterfastest  and @mbest are correct that you need to leave the option in the select list in order for the item to remain selected.

**Comment by fastfasterfastest** [comment]
The correct approach is to do what @chrisknoll mentioned - to use the `options` binding - I was just trying to explain what actually happens in @HeyJude1's example.

In @HeyJude1's example if you add `<option data-bind="value: dogName, text: dogName"></option>` (see https://jsfiddle.net/z4vdfyde/10/) then it's probably closer to the desired behavior (although I don't think the desired behavior has been clearly defined).  Again, though, using the `options` binding is very most likely the correct approach.

**Comment by HeyJude1** [comment]
ok all, thanks. I'm closing the issue.
