### ISSUE TITLE
Evalutating of a computed observable doesn't update back the DOM element

### ISSUE THREAD

**Issue by IkstraX** [knockout/knockout#2361]
In my case I have a computed observable to allow user insert separately hours and minutes, storing them as decimal.

This is the code for the 2 computed observables

		self.Functionality_EstimatedExecutionHours = ko.computed({
			read: function () {
				if (self.data.selected.EstimatedExecutionTime() === null) return null;
				else return Math.floor(self.data.selected.EstimatedExecutionTime());
			}, write: function (newValue) {
				if (newValue === null) self.data.selected.EstimatedExecutionTime(null);
				else {
					var minutes = self.data.selected.EstimatedExecutionTime() - Math.floor(self.data.selected.EstimatedExecutionTime());
					self.data.selected.EstimatedExecutionTime(newValue + minutes);
				}
			}
		});

		self.Functionality_EstimatedExecutionMinutes = ko.computed({
			read: function () {
				if (self.data.selected.EstimatedExecutionTime() === null) return null;
				else {
					var minutes = self.data.selected.EstimatedExecutionTime() - Math.floor(self.data.selected.EstimatedExecutionTime());
					return minutes * 60;
				}
			},
			write: function (newValue) {
				if (newValue === null) self.data.selected.EstimatedExecutionTime(null);
				else {
					var hours = Math.floor(self.data.selected.EstimatedExecutionTime());
					self.data.selected.EstimatedExecutionTime(hours + (newValue / 60));
				}
			}
		});

they are bound to two inputs. but if I set for example 90 minutes, the observable "EstimatedExecutionTime" has the correct value "1.5", the input bound to the computed "Functionality_EstimatedExecutionHours" is updated with value "1", but the input bound to "Functionality_EstimatedExecutionMinutes" keeps value "90", also if debugging in the read function it returns "30"

**Comment by IkstraX** [comment]
I forgot to tell that i am using a custom binding handler, to handle numeric values with min, max, format, which is this one

		ko.bindingHandlers.nullablenumeric = {
			init: function (element, valueAccessor, allBindingsAccessor) {
				var options = allBindingsAccessor().nullablenumericOptions || {};

				$(element).val($.format.number(valueAccessor()(), options.format, options.local));

				//handle the field changing
				ko.utils.registerEventHandler(element, "change", function () {
					var observable = valueAccessor();
					var value;
					if ($(element).val() == '') {
						value = null;
					}
					else {
						value = $.format.number($(element).val(), options.format, options.local);
						if (isNaN(value)) {
							value = null;
						} else {
							if (!isNaN(options.min) && value < options.min) value = $.format.number(options.min, options.format, options.local);
							if (!isNaN(options.max) && value > options.max) value = $.format.number(options.max, options.format, options.local);
						}
					}
					observable(value);
					if (value == null) {
						$(element).val('');
					} else {
						$(element).val($.format.number(value, options.format, options.local));
					}
				});
			},
			update: function (element, valueAccessor, allBindingsAccessor) {
				var options = allBindingsAccessor().nullablenumericOptions || {};
				var value = ko.unwrap(valueAccessor());
				var current = $.format.number($(element).val(), options.format, options.local);

				if (value == null) {
					$(element).val('');
				} else /*if (value - current !== 0)*/ {
					$(element).val($.format.number(value, options.format, options.local));
				}
			}
		};

I tried replacing in data-bind attribute of the element "nullablenumeric" with "value" and it works. I debugged and it calls the update callback only for the input I don't have changed (so if I update minutes it calls the update only for hours, not for minutes also if the result of the computed has changed)

**Comment by mbest** [comment]
> var options = allBindingsAccessor().nullablenumericOptions || {};

This should be `var options = allBindingsAccessor.get('nullablenumericOptions') || {};

But the problem is the code in your event handler that sets the value:

> ```
>if (value == null) {
>    $(element).val('');
>} else {
>    $(element).val($.format.number(value, options.format, options.local));
>}
>```

You need to remove that.
