### ISSUE TITLE
Is there any better way so I can call a function inside component from my viewmodel?

### ISSUE THREAD

**Issue by ervinfetic** [knockout/knockout#2363]
For example I have following component:

    `ko.components.register("search-component", {
        viewModel: function(params) {
            var self = this;
            self.Show = params.show;
            self.Callback = params.callback;

            self.specificFunction = function() {
                // do something
            };

            self.Submit = function() {
                // hide dialog
                self.Show(false);
                // return result
                self.Callback("result");
            };
        },
        template: "<div data-bind='visible: Show'><p>search dialog goes here</p><button data-bind='click: Submit'>Submit</button></div>"
    });`

My viewmodel looks like this:

     `var vm = function() {
        var self = this;
        self.Result = ko.observable("");
        self.myVariable = ko.observable();
        self.DialogVisible = ko.observable(false);
        // user has clicked Find button
        self.Find = function() {
            // show the dialog
            self.DialogVisible(true);
        };

        self.otherFunction = function() {
                // here I want to call function called 'specificFunction()' from component 
        };

        // callback
        self.Update = function(data) {
            self.Result(data);
        };
    };

    ko.applyBindings(new vm());`

I solved this on the following way. I've made observable variable inside my viewmodel and forwarded it to my component like a parameter.  Afterwards I made subscription on this variable so whenever it  is changed I have an event in my component then I can call the 'specificFunction()'.

`    <search-component params="myVariable: myVariable"></search-component>
`

    `params.myVariable.subscribe(function(newValue) {
            // here I am able to call 'specificFunction()' from component
    });`

Do you know any other/better solution so I can solve this?

**Comment by chrisknoll** [comment]
What I have done:

```
<search-component params="myVariable: myVariable, ref: componentObs"></search-component>
```

Component model:
```
function searchCompoent(params)
{
  var self = this;
  params.compoentObs(self); // this could also return an 'api' back to access this component instead of the entire model.
}
// on dispose, we could reset the passed in observable to null so the container knows it's gone
```


Main app model:
```
    var vm = function() {
    var self = this;
    self.Result = ko.observable("");
    self.myVariable = ko.observable();
    self.DialogVisible = ko.observable(false);
    self.componentObs = ko.observable();
    // user has clicked Find button
    self.Find = function() {
        // show the dialog
        self.DialogVisible(true);
    };

    self.otherFunction = function() {
            if (self.componentObs()) {
                // do work
            }
    };

    // callback
    self.Update = function(data) {
        self.Result(data);
    };
};

ko.applyBindings(new vm());

```

Personally, I wish there was a standardized way to associate a child component ref back to a parent context, but I understand that is complicated in a dynamic lifecycle where child compoents could come and go, or if there's an array of components you wan to track.

I've also had success using event binding where an outer event binding can 'catch' events raised by the inner component (using jQuery on() semantics) and the event raised can be used to get a reference to the component model that was clicked on (via ko.contextFor), and then once you have the reference you can call the method.

-Chris

**Comment by ervinfetic** [comment]
Hi @chrisknoll 

Thanks for the response. I tried your proposal and it works. Thank you. 
I think your approach is much more better than what I've done so I will use it. It is not the best option but I could not find any other solution.

Best, Ervin.

**Comment by miellaby** [comment]
Another classical design pattern may be to emit a custom event from the containing application DOM down to your component. You need to get a reference of the DOM element when initializing your viewmodel, so to start listening to events.

For example, use the `ko.components.register('my-component', {  viewModel: {  createViewModel: function(params, componentInfo) {}}})` approach. It allows you to get a componentInfo.element attribute and initialize your component with something like `$element.on('reset', doReset)`

Events allow to integrate behaviors together with no strong coupling. For exemple, they allow to instantiate several times the same component in the same document.

**Comment by fastfasterfastest** [comment]
I don't think I have had the need for a view model calling functionality exposed by a component's view model...
What is an example of "specificFunction" and "otherFunction", what do they do?
Perhaps it is better to have "specificFunction" in the/a view model and pass it to the component?

**Comment by chrisknoll** [comment]
Imagine a component which fetches from a service some information which you may want to refresh when the user asks.  By placing teh component and storing the 'api' back to the component, you can have it so that if a user takes action, or possibly a timer from the containing application can invoke refresh() on the component without knowing the underlying workings of how the data is being fetched. 

You could solve this by passing in the data to the component to view, but then you'd have to know how the data was being fetched.  On the other hand, if you had the 'black box' module which fetches the data and you pass that into the child component and the child component reads form the 'black box' you could call functions on the 'black box' which would trigger refreshes of data in the component (assuming the black box returns observable to be read that the component expects).

I haven't really done it this way, I don't think it's a bad idea, but just adds another layer of abstraction which sometimes makes the workings of the app too fuzzy for my tastes (but I'm sometimes guilty of begin a pragmatic)

**Comment by mbest** [comment]
@ervinfetic I hope you've gotten some useful advice, but since this isn't a problem in Knockout, I'll close this issue.
