### ISSUE TITLE
use dist-tags on npm for beta version

### ISSUE THREAD

**Issue by SheetJSDev** [knockout/knockout#2366]
Currently `npm` marked `3.5.0-beta` as the latest version:

```
$ npm info knockout dist-tags
{ latest: '3.5.0-beta' }
```

The content of http://knockoutjs.com/downloads/index.html suggests that `3.4.2` is the "latest stable production build".

`3.4.2` probably should be marked as `latest` on npm and `3.5.0-beta` probably should be marked as  `beta`.  This can be done with the [`npm dist-tag` subcommand](https://docs.npmjs.com/getting-started/using-tags)

Note: This affects npm-powered CDNs like https://unpkg.com/ , which serve the `latest` tag by default.  https://unpkg.com/knockout serves the beta version because of the incorrect tags

**Comment by mbest** [comment]
Thanks. I've made the update.

![image](https://user-images.githubusercontent.com/1230364/38208968-92604f2c-3667-11e8-9cd8-34e5a1273f89.png)

https://www.npmjs.com/package/knockout
