### ISSUE TITLE
Click Bindings DO not listen to clicks

### ISSUE THREAD

**Issue by retrocausal** [knockout/knockout#2371]
I do not understand! Is there something I am missing here? Because KO randomly seems to ignore clicks
Or, In *Some* cases, completely ignores clicks. Event not listened to at all.
### View
```html
<ul class="user-interface-places" data-bind='foreach:filteredVenues'>
        <li class="user-interface-venue">
          <div class="venue-name" data-bind='text:name'></div>
          <div class="venue-details-drawer-opener">
            <a class="far fa-plus-square venue-details-expander" data-bind='click:$parent.fetchInfo'></a>
          </div>
       </li>
```

### Model

```js
  this.fetchInfo = ( venue ) => {
    console.log( venue );
    //Set the current venue to the clicked venue
    this.currentVenue( venue.id );
   //some more code
  };
```
**Browsers used**
 - latest google chrome
 - latest mozilla firefox

**Are there console errors? **  : **No!**
**Note** 
The bindings are all fine. `$parent` actually is referring to the ViewModel. My issue is that the event doesn't fire it's listener.
Also, the arrow function is **Only** for ease of using `this`. 
The issue again, is Knockout randomly stops listening to clicks, and the `console.log` above, does not log.
At times, Knockout completely stops listening to clicks

**Comment by retrocausal** [comment]
I am beginning to think, this might just be a mishap of using **font-awesome** . the icons may not be visible / even attached when bindings happen. Even with a defer on knockout that is. 

need to investigate without font awesome . Will update this then

**Comment by retrocausal** [comment]
So **font-awesome** seems to be the culprit here. It loads the library, and _schedules_ an `DOM element` to `SVG tag` replacement. And any hitherto javascript references are loosely held and disposed. 

It would be so good to have the below in the documentation as a time saver for future knockout users?

**If using font awesome** 

 - For binding event listeners, use 
```html
<script>
  FontAwesomeConfig = { autoReplaceSvg: 'nest' }
</script>
```
So bindings are applied and references held on to.

**Comment by brianmhunt** [comment]
Thanks @retrocausal .  Cross-referencing FortAwesome/Font-Awesome/issues/12489

**Comment by miellaby** [comment]
> DOM element to SVG tag replacement

For anyone wondering why FA is going JS+SVG: it deals with "Power Transforms" https://fontawesome.com/how-to-use/svg-with-js#power-transforms ; Fortunately, there is still a pure CSS option https://fontawesome.com/how-to-use/web-fonts-with-css

**Comment by Sebazzz** [comment]
You also can workaround by placing the click on a parent element, since the event bubbles up.

**Comment by retrocausal** [comment]
Closing this, as it is not really knockout failing my data bindings / event listener triggers.

 - Regarding font awesome, I agree to everything offered as a workaround be it pure css / a parent on-click binding

However, I guess, people have been using FA a certain way, and even the new releases appreciably have not changed the way a user writes / assigns classes on DOM elements. 

So, Either FA should have this exposed on the documentation at the very first / landing page where instructions to download FA are mentioned. I literally had to search and understand and read a lot more than ideal to get to the cause and the solution. 

Also, In lieu of the documentation search time, FA could possibly have *nesting* as a default. Would root out the problem at once. 

For knockout, I wish the owners / collaborators would find it a worthy note to have in their own documentation since FA is widely used and click bindings are extremely common on FA modified DOM
