### ISSUE TITLE
Uncaught Error: Cannot find closing comment tag to match:  ko foreach: tasks

### ISSUE THREAD

**Issue by LoganDark** [knockout/knockout#2372]
I'm creating my own 'tasks' example, just as a test.

Here's my code:

```html
<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<style type="text/css">
			/* put CSS here */
		</style>
		<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
		<!--script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script-->
		<script src="https://cdn.rawgit.com/knockout/knockout/gh-pages/downloads/knockout-3.4.2.js"></script>
		<script type="text/javascript">
			$(function($) {
				function ViewModel() {
					this.tasks = ko.observableArray([
						'Task 1',
						'Task 2',
						'Task 3'
					])
					
					this.addTask = function() {
						this.tasks.push('New task')
					}
					
					this.removeTask = function(task) {
						this.tasks.remove(task)
					}
				}
				
				ko.applyBindings(new ViewModel())
			})
		</script>
	</head>
	<body>
		<table>
			<!-- ko foreach: tasks -->
			<tr>
				<td data-bind="text: $data"></td>
				<td>
					<button data-bind="click: $parent.removeTask">Remove</button>
				</td>
			</tr>
			<!-- /ko -->
			<tr>
				<td colspan="2">
					<button data-bind="click: addTask">Add task</button>
				</td>
			</tr>
		</table>
	</body>
</html>
```

Here's my error:

```
Uncaught Error: Cannot find closing comment tag to match:  ko foreach: tasks 
    at d (knockout-3.4.2.js:63)
    at e (knockout-3.4.2.js:63)
    at Object.nextSibling (knockout-3.4.2.js:65)
    at g (knockout-3.4.2.js:70)
    at h (knockout-3.4.2.js:70)
    at g (knockout-3.4.2.js:70)
    at h (knockout-3.4.2.js:70)
    at Object.a.Ub (knockout-3.4.2.js:76)
    at HTMLDocument.<anonymous> (blob:https://html.logandark.net/63a3a2c3-7b9f-457e-8427-160fedc95802:29)
    at j (jquery-3.2.1.min.js:2)
```

This makes no sense, because there is **clearly** a closing comment. You can't miss it.

**Comment by fastfasterfastest** [comment]
Try adding a `tbody` element, i.e.
```
<table>
   <tbody>
      <!-- ko foreach: tasks -->
      ...
      <!-- /ko -->
      ...
   </tbody>
</table>

**Comment by fastfasterfastest** [comment]
It "changes things" so knockout finds the closing comment tag.

**Comment by LoganDark** [comment]
How though? Can you explain _why_ it works?

**Comment by chrisknoll** [comment]
I'm not sure, but I believe it's the way some browsers inject implicit tbody elements when it's not present in the raw HTML. That could be the case here, and interfering with knockout's finding the elements.

**Comment by LoganDark** [comment]
Oh! The browser injected its own tbody, looking in developer tools:

```html
<table>
			<!-- ko foreach: tasks -->
			<tbody><tr>
				<td data-bind="text: $data"></td>
				<td>
					<button data-bind="click: $parent.removeTask">Remove</button>
				</td>
			</tr>
			<!-- /ko -->
			<tr>
				<td colspan="2">
					<button data-bind="click: addTask">Add task</button>
				</td>
			</tr>
		</tbody></table>
```

Thanks, the fix worked.

**Comment by fastfasterfastest** [comment]
1. The DOM always has a `tbody` element, regardless whether the markup has a `tbody` tag or not.
If the markup does not have a `tbody` tag, the browser "moves" child nodes of the `table` to the `tbody` element.  It appears the way that is done is by finding the first child element of the `table` and moving it and all subsequent child nodes to the `tbody` element.  Thus, text and comment nodes preceding the first child element remain child nodes of the `table` element.

2. To find the closing comment node knockout operates on the DOM and looks for a sibling node to the opening comment node.  Because of 1, the opening and closing comment nodes are no longer sibling nodes and thus knockout does not find the closing comment node.

**Comment by LoganDark** [comment]
1. Nice to know, thanks.
2. I know. It's how I expected it to work - for example, `<b>bold<em>bold italic</b>italic</em>` doesn't work (although some modern browsers convert it to `<b>bold<em>bold italic</em></b><em>italic</em>`)
