### ISSUE TITLE
Is it possible to iterate in chunks, like two or three at a time?

### ISSUE THREAD

**Issue by mw44118** [knockout/knockout#2373]
The foreach binding returns one item at a time.  Is there some way to get two, three, four elements at a time?

**Comment by fastfasterfastest** [comment]
No.  Although you do have `$index` available and could "look ahead" in the array and get the next element(s) in the array, if any available - but that gets ugly real quick.
Instead, pass _another_ array to `foreach`, e.g. a `ko.computed` or `ko.pureComputed` calculated using the original array.
