### ISSUE TITLE
Using single quotes for strings in bindings throws syntax error (Knockout 3.5 RC)

### ISSUE THREAD

**Issue by labago** [knockout/knockout#2375]
There must be something I am missing, but I just upgraded to 3.5 and am now getting a syntax error for the following simple binding:

`<div data-bind="text: FamilyAddressTypeName, css { 'overidden': IsOverride }"></div>`

The issue occurs at the 'overidden' string. Two ways I have gotten this to work is to remove the quotes (which isn't an option for multiple class names) or to swap them out with double quotes. This only occurs with single quotes, but I am trying to avoid having to change all my single quoted strings to double quoted ones. 

For this particular example, it is inside a foreach, if that makes a difference. I am not sure if this happens outside of a foreach yet.

Any thoughts?

**Comment by mbest** [comment]
I put together a small sample and did not find a problem. Perhaps you can work with this sample to try to reproduce the problem.

http://jsbin.com/qomemutesa/edit?html,js,console,output

**Comment by mbest** [comment]
While setting up my test, I fixed an "error" in your binding, and that's why it works fine. It was missing the colon after `css`. Apparently the missing colon worked okay in Knockout 3.2, but not since 3.3. Here's the relevant PR: #1434.

**Comment by labago** [comment]
@mbest thank you for pointing out that error, strange that it worked in previous versions, but including the colon has fixed the issue in 3.5. Thanks!
