### ISSUE TITLE
ko.utils array methods behavior change

### ISSUE THREAD

**Issue by fastfasterfastest** [knockout/knockout#2376]
The behavior of several `ko.utils` methods has changed between 3.4.2 and 3.5.0-rc.

- In 3.4.2 `ko.utils.arrayForEach` threw an error if passed `null`; in 3.5.0-rc `ko.utils.arrayForEach` silently does nothing
- In 3.4.2 `ko.utils.arrayIndexOf` threw an error if passed `null`; in 3.5.0-rc `ko.utils.arrayIndexOf` returns `-1`
- In 3.4.2 `ko.utils.arrayFirst` threw an error if passed `null`; in 3.5.0-rc `ko.utils.arrayFirst` returns undefined
- In 3.4.2 `ko.utils.arrayRemoveItem` threw an error if passed `null`; in 3.5.0-rc `ko.utils.arrayRemoveItem` silently does nothing
- In 3.4.2 `ko.utils.addOrRemoveItem` threw an error if passed `null`; in 3.5.0-rc `ko.utils.addOrRemoveItem` silently does nothing if passed `null` and 2nd argument ==`false`

I think this change of behavior can cause several problems and issues.  And, I think _not_ throwing an error, when perhaps/likely the method is called erroneously with an invalid argument, is unhelpful.

Fiddle showing the behavior in [3.4.2](https://jsfiddle.net/fastfasterfastest/pgaj9w16/)
Fiddle showing the behavior in [3.5.0-rc](https://jsfiddle.net/fastfasterfastest/pgaj9w16/1/)

(There is also another change - in 3.4.2 `ko.utils.arrayFirst` returned `null` if no element was found; in 3.5.0-rc `ko.utils.arrayFirst` returns `undefined`, but I think this was discussed, and I commented, elsewhere. Edit: I commented and it was discussed in https://github.com/knockout/knockout/pull/1448#issuecomment-309889033)

Also, the methods are implemented by checking if the passed array has a native method that can be used.  Assuming these methods are supposed to be called with arrays only, wouldn't it be better to do that check once, when the `ko.utils` object is created and install the correct/optimal implementation once and for all - then no need to check each time the method is called.  I.e., a'la
```
...
arrayForEach: Array.prototype.arrayForEach ?
		function (array, action, actionOwner) { array.forEach(action, actionOwner); } :
		function (array, action, actionOwner) { for (var i = 0, j = array.length; i < j; i++) { action.call(actionOwner, array[i], i, array); }
...
```

**Comment by mbest** [comment]
> wouldn't it be better to do that check once, when the `ko.utils` object is created and install the correct/optimal implementation once and for all

These function can be called with array-like (iterable) objects as well, which may not have "native" methods.

> I think not throwing an error, when perhaps/likely the method is called erroneously with an invalid argument, is unhelpful.

Knockout already ignored a `null` array value in some functions, such as `arrayMap` and `arrayFilter`. So I thought it would be okay to make the rest match. But I understand your concern about ignore errors. Let me mull it over a bit.

**Comment by fastfasterfastest** [comment]
> These function can be called with array-like (iterable) objects as well, which may not have "native" methods.

"array-like (iterable)", as in having a `length` property and a property accessor, I assume.

But, in 3.4.2:
- `ko.utils.arrayIndexOf` defers to `Array.prototype.indexOf` and thus does not work with a non-array "array-like" object
- `ko.utils.arrayRemoveItem` (indirectly) defers to `Array.prototype.indexOf` and does not work with a non-array "array-like" object
- `ko.utils.addOrRemoveItem` (indirectly) defers to `Array.prototype.indexOf` and does not work with a non-array "array-like" object

I don't think it makes sense to "expand the capability" of `ko.utils.arrayIndexOf` to allow it to handle non-array "array-like" objects - it didn't work in 3.4.2, why allow it in 3.5?
I think it would be better to install the correct/optimal implementation of (at least) `ko.utils.arrayIndexOf`, and avoid having it check if the passed value has an `indexOf` method at every invocation.  Especially since `ko.utils.arrayIndexOf` is called within loops in several places.
```
...
arrayIndexOf: Array.prototype.indexOf ?
		function (array, item) { return array.indexOf(item); } :
		function (array, item) { for (var i = 0, j = array.length; i < j; i++) if (array[i] === item) return i; return -1; }
...
```
Doing so, I believe, would be backward compatible and not change the behavior from 3.4.2 to 3.5.0.

I think one could argue for using a similar approach for `ko.utils.arrayFirst` piggy-backing on `Array.prototype.find`.  Doing that would change the behavior from 3.4.2, but does it make sense to call `ko.utils.arrayFirst` with a non-array "array-like" object?

Perhaps it makes sense to call `ko.utils.arrayMap` and `ko.utils.arrayforEach` with a non-array "array-like" object (although `ko.utils` already have `objectMap` and `objectForEach` methods) and they should remain as-is.  It makes sense if we want to be backward compatible to 3.4.2, but those methods are called `arrayXxx` after all...

**Comment by mbest** [comment]
@fastfasterfastest I'm tending to agree with you that we shouldn't change these functions too much. I'll upload a pull request soon for you to review.

**Comment by mbest** [comment]
See #2378

**Comment by fastfasterfastest** [comment]
#2378 looks ok.
As noted in my comment in #2378, I think it would be a good idea to also piggyback on the native implementations of `map` and `filter` for performance reasons (while being backward compatible with 3.4.2.)

```
arrayMap: Array.prototype.map ?
   function (array, mapping, mappingOwner) {
      return array ? Array.prototype.map.call(array, mapping, mappingOwner) : [];
   } :
   function (array, mapping, mappingOwner) {
      var result = [];
      if (array) {
         for (var i = 0, j = array.length; i < j; i++)
            result.push(mapping.call(mappingOwner, array[i], i, array));  //[note]
      }
      return result;
   },

arrayFilter: Array.prototype.filter ?
   function (array, predicate, predicateOwner) {
      return array ? Array.prototype.filter.call(array, predicate, predicateOwner) : [];
   } :
   function (array, predicate, predicateOwner) {
      var result = [];
      if (array) {
         for (var i = 0, j = array.length; i < j; i++)
            if (predicate.call(predicateOwner, array[i], i, array)) //[note]
               result.push(array[i]);
      }
      return result;
   },
```
