### ISSUE TITLE
You don't actually need to use computed in many instances

### ISSUE THREAD

**Issue by wallymathieu** [knockout/knockout#2381]
One of the nice things about KO, that is not highlighted enough in the docs...

In some cases you don't actually need to define computed property, instead you can use the fact that knockout creates a computed when binding an expression in the view:

http://jsfiddle.net/ozzymcduff/bLsfn9wz/3/ compared to http://knockoutjs.com/examples/clickCounter.html
I.e.
```
this.hasClickedTooManyTimes = function() {
    return this.numberOfClicks() >= 3;
  }.bind(this);
```

Another way is to use Object.defineProperty:
```
Object.defineProperty(this,'hasClickedTooManyTimes',{ get: function() {
    return this.numberOfClicks() >= 3;
}.bind(this) });
```

If you have a larger KO model functions or properties instead of computed properties can help avoid memory leaks.

**Comment by wallymathieu** [comment]
Unless there is something else I have misunderstood about KO?

**Comment by derrickb** [comment]
They do actually cover this under "When the computed observable is only used in your UI" on the computed page: http://knockoutjs.com/documentation/computedObservables.html

I suppose they could highlight this more by including it in more examples? But then they'd probably need to add a comment to every example reminding the reader that it works this way.

**Comment by mbest** [comment]
There are many examples showing binding to an expression, and calling a function is perfectly fine in an expression. The [text binding documentation](http://knockoutjs.com/documentation/text-binding.html) also talks about this, as do some of the other binding docs.

**Comment by wallymathieu** [comment]
Yes, I'm more trying to strongly hint at something I've seen people get confused about. Thanks for the attention.
