### ISSUE TITLE
ArrayFirst on 3.5 returns undefined

### ISSUE THREAD

**Issue by carlosagsmendes** [knockout/knockout#2385]
Hi there,

I'm trying out KO 3.5 and found that a lot of my code stops working since the `arrayFirst` now returns **undefined** instead of **null** when it doesn't find an item

```
  arrayFirst: function (array, predicate, predicateOwner) {
            for (var i = 0, j = array.length; i < j; i++) {
                if (predicate.call(predicateOwner, array[i], i, array))
                    return array[i];
            }
            return undefined;
        },
```

I imagine that more people use ko.utils so I would suggest including this in the changelog.

Could someone explain the rationale?

Here's the [link to the commit](https://github.com/knockout/knockout/commit/187788ad258e0d2e2601f782f3b0731434550caf#diff-2b4ca49d4bb0a774c4d4c1672d7aa781) where the change has been made

Thanks in advance

**Comment by bludev** [comment]
Hi,
it seems the same of #2376.

**Comment by carlosagsmendes** [comment]
Thank you @bludev. Closing since this was open already.

**Comment by fastfasterfastest** [comment]
No, the breaking change of behavior of `ko.utils.arrayFirst` is not an open issue - it is in fact a closed issue.  I brought this up in https://github.com/knockout/knockout/pull/1448#issuecomment-309889033
