### ISSUE TITLE
Issue with knockout custom binding while building image slider

### ISSUE THREAD

**Issue by harpreetadapty** [knockout/knockout#2392]
Please refer to this stackover flow link https://stackoverflow.com/questions/50703902/knockout-sliding-images-issue-with-custom-binding?noredirect=1#comment88440062_50703902

**Comment by fastfasterfastest** [comment]
What is the precise issue with the knockout library that you have identified?

**Comment by mbest** [comment]
I've answered your SO question: https://stackoverflow.com/a/50777021/1287183
