### ISSUE TITLE
oj.KnockoutTemplateUtils.getRenderer sometimes throw createChildContext undefined error

### ISSUE THREAD

**Issue by guanw** [knockout/knockout#2395]
Hi, notice this error that's not consistently reproducible on **IE**. It happens sometimes when I navigate from one page to another:
ojknockout.js: 
`
childContext = bindingContext["createChildContext"](context["data"], null,
      function(binding)
      {
        binding["$optionContext"] = context;
      }
    );
`

will throw error in IE like: **unable to get property 'createChildContext' of undefined or null reference**. I don't have a minimum demo to reproduce this one since our app is fairly complicated. Is there any intent here to fix this?

**Comment by mbest** [comment]
What kind of binding handler is this in? Can you provide the whole handler code?

**Comment by guanw** [comment]
Hi, We use Oracle JET with knockout so this is what I found:
   We have a oj-navigation-list which is JET navigation component. 
`<oj-navigation-list id="navBlockNavList" class="box-navigation-list"
            on-oj-before-select="[[confirmRouting.bind($data)]]"
            data="[[appNavDataSource]]"
            item.renderer="[[oj.KnockoutTemplateUtils.getRenderer('navBlockTemplate', true)]]"
            selection="{{appRouter.stateId}}">
        </oj-navigation-list>`

I think it's this `navBlockTemplate` rendered here having this error. It's just a html script:
`<script type="text/html" id="navBlockTemplate">
    <li>
        <a href="#">
            <span class="nav-title" data-bind="text: $data['name']"></span>
            
                <span class="nav-metric-value" data-bind="text: metric"></span>
                <span class="nav-metric-label" data-bind="text: label"></span>
            
        </a>
    </li>
</script>` 

like the following screenshot 
![image](https://user-images.githubusercontent.com/7311035/41667430-fa7b7496-747a-11e8-9812-49ae51dae20e.png)

**Comment by mbest** [comment]
If this is an issue in Knockout, feel free to continue discussing it here, but from your description, it's most likely from Oracle Jet: http://www.oracle.com/webfolder/technetwork/jet/index.html
