### ISSUE TITLE
data-binding 'html' and 'click' together breaks rendered anchor links.

### ISSUE THREAD

**Issue by cljacoby** [knockout/knockout#2402]
When data-binding an element with 'html' and 'click', anchor links will be properly rendered; however, clicking them only fires the bound 'click' function. The browser won't load the actual linked page.  I ran in to this while making a tooltip which receives text that includes encoded HTML anchors. The 'html' data-binding is an extremely convenient way to render the inner -html; however, I would also like to attach a click event handler on the parent container using the 'click' data-binding.

```html
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <div style="margin: 50px; height: 100px; border: 1px solid red;"
             data-bind="html: getTestHTML(), click: onClick">
        </div>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/knockout/3.4.2/knockout-min.js" type="text/javascript" charset="utf-8"></script>
        <script> 
            function VM() {
                
                this.getTestHTML = ko.computed(function() {
                    return '<a target="_blank" href="https://www.google.com">this</a> is a link to google';
                });
                
                this.onClick = function() {
                    console.log('clicked');
                };
                
            }
            
            var appview = new VM();
            ko.applyBindings(appview);
        </script>
    </body>
</html>
```

**Comment by chrisknoll** [comment]
is the closing ```<a>``` tag malformed? should it be ```<\a>```? Don't know if that makes a difference.

**Comment by cljacoby** [comment]
@chrisknoll Thanks, you're right it should be `</a>`, going to edit it in the OP. The issue still proliferates though.

**Comment by chrisknoll** [comment]
Ok, another thought is: is the clickBinding 'eating' the click event and therefore not letting the click event bubble up tot he browser?  Does the link work if you remove the click binding?

**Comment by cljacoby** [comment]
@chrisknoll Works https://jsfiddle.net/54ekcsxj/1/ . Many thanks.
