### ISSUE TITLE
Knockout component with an angular project

### ISSUE THREAD

**Issue by BrentKoepke** [knockout/knockout#2404]
I've got a knockout component I want to reuse in an angular based website. The way we currently use it in a knockout project is we've registered the viewModel and template together as a component, and then in our project we display it with an html tag named like the component. In angular I can add knockout, register the component binding, but I don't know how to get the html in the binding to display. Is there a way to render the UI from the angular js code, since I can't use the html tag binding?

**Comment by chrisknoll** [comment]
I think you just call 'applyBinding(model, element)' somewhere on your angular app startup, and knockout will apply to that DOM element and respond to observable changes (provided angular doesn't do something like destroy the element on you).

**Comment by mbest** [comment]
You may also try asking on StackOverflow.
