### ISSUE TITLE
Throw error if ko virtual comment expression is unvalid

### ISSUE THREAD

**Issue by miellaby** [knockout/knockout#2407]
A friend wrote `<!-- ko if: f(g(something) -->` by mistake. Please note the missing parenthesis.

KO doesn't throw any error, acting as if if: true. 

Is there a way to enable some meaningful parsing error?

**Comment by fastfasterfastest** [comment]
The same applies for bindings applied to DOM elements - there is no error for
`<div data-bind="if: f(g(something)"></div>`

Seems like it would be a good idea if this would generate an error.  Perhaps by `parseObjectLiteral` checking that `depth==0` before returning, and if not, throw `"Unbalanced parentheses, braces, or brackets"` (which would get caught by `parseBindingsString` which in turn would throw the `"Unable to parse bindings"` error.)

**Comment by mbest** [comment]
Thanks for the suggestions. Since this is such a simple, obvious fix, I've checked it in for the upcoming release.
