### ISSUE TITLE
Deprecation Issue, document.origin

### ISSUE THREAD

**Issue by mcarpenterjr** [knockout/knockout#2408]
Just got this warning in the console when using the `ko.toJS()` method,

`document.origin is deprecated and will be removed in M70, around October 2018. Please use self.origin (window.origin) instead. See https://www.chromestatus.com/features/5701042356355072 for more details.`

Anyone aware of this? the timeline seems a little short.

**Comment by brianmhunt** [comment]
Thanks @mcarpenterjr ; I can't seem to reproduce this.  It would be odd if `toJS` were accessing `document.origin` in the ordinary course.  Can you please provide a minimal test case?

**Comment by mcarpenterjr** [comment]
I'm having some trouble creating a test case for it at the moment, the conditions it occurred under seem to be very specific. But after scanning the knockout repo it looks like there is no use of `document.origin`. So at this point, I'm guessing it's another library not in compliance. Thanks for the quick response, sorry there's not more here.

**Comment by Jaafarnasrallah** [comment]
same happened while using ko.toJSON. Still running checks though
