### ISSUE TITLE
Please configure SSL on knockoutjs.com

### ISSUE THREAD

**Issue by sa7mon** [knockout/knockout#2409]
Currently, when attempting to visit https://knockoutjs.com the server presents a certificate valid only for *.github.com which leads me to believe the site is hosted on Github Pages. If this is the case, GitHub already has LetsEncrypt integrated and can easily generate a custom cert for the domain for free.  

Not only will this help protect users of the site, but it also enables Github to move your site into their CDN allowing the site to be loaded much faster.

More info here: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by brianmhunt** [comment]
Thanks @sa7mon .  For no apparent reason GitHub is showing this:

<img width="796" alt="screen shot 2018-08-28 at 7 50 04 am" src="https://user-images.githubusercontent.com/135528/44721164-0413f300-aa97-11e8-9581-7ebc63395455.png">

Investigating.

**Comment by brianmhunt** [comment]
Ah, I found the issue.

>  The custom domain for your GitHub Pages site is pointed at an outdated IP address. You must update your site's DNS records if you'd like it to be available via your custom domain. For more information, see https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/.

@SteveSanderson @mbest who has the knockoutjs DNS?

**Comment by SteveSandersonMS** [comment]
@brianmhunt I do. I'll update it as per GitHub docs.

**Comment by SteveSanderson** [comment]
OK the DNS config is updated, and GitHub no longer shows the warning that @brianmhunt mentioned.

It works correctly over HTTPS now. I've also turned on the "Enforce HTTPS" setting, but that doesn't seem to have taken effect yet - maybe it will do later.

**Comment by brianmhunt** [comment]
Excellent, thanks @SteveSanderson 

Thanks for the report, @sa7mon

**Comment by sa7mon** [comment]
No problem, thanks for the fast turnaround time!
