### ISSUE TITLE
Question: Cannot use koDescendantsComplete in 3.5.0-rc

### ISSUE THREAD

**Issue by sumitkm** [knockout/knockout#2411]
Quite possible I am doing something wrong here, but I can't seem to use the koDescendantsComplete function.

I have a KO component written in TS and loaded using RequireJS. I am typing the following out, so kindly forgive syntax typos.

```TypeScript
// mycomponent.ts
import * as ko from "knockout";

export var template = require("text!./mycomponent.html")

export class viewModel {
 title: KnockoutObservable<string> = ko.observable<string>("Hello world");
 id: KnockoutObservable<string> = ko.observable<string>("useinjquery" + (Math.random() * 1000).toFixed(0));

 constructor(params){
 }

 dispose(){
  console.log("Disposing stuff");
 }

 koDescendantsComplete(element: Node) {
  console.log("Do jQuery Stuff");
 }
} 
```

```HTML
<!-- mycomponent.html -->
<div data-bind="text: $component.title"></div>
<div data-bind="attr : { id: $component.id() }"></div>
```

```Typescript
// Elsewhere in code Component registered as
ko.components.register('mycomponent', { require: 'app/ui/components/mycomponent/mycomponent' });
```

My ```dispose``` function is logging correctly when I navigate away from the page but the ```koDescendantsComplete``` isn't logging anything.

What am I missing ?

As you can guess, I am trying to initialise jquery plugins reliably, and I am pretty tired of using setTimeout and other hacks :-(

I fully understand the documentation is still in the works and this is an ```rc``` feature, but any pointers will be helpful. I trawled through the code and @mbest 's [commit](https://github.com/knockout/knockout/commit/d913cf06d588df071b5ae13cdd0d8a975cd1ddc0) and can't figure out what I am doing wrong.

Thanks.

**Comment by sumitkm** [comment]
False Alarm!

Sorry folks, the event was not triggering because of issues in other parts of my component. I had to use the [Ryan Niemeyer](http://jsfiddle.net/rniemeyer/ecbn1dmy/) trick to force KO to spill all the binding errors for me to trace down issues in my code.

That said, this is the best thing in KO since KO Components itself... thank you @mbest and KO team.)

**Comment by mbest** [comment]
Thanks for the update. I'm glad you're liking the new features. I hoping to get out another RC release in the next few days, and then the final release soon after.

**Comment by sumitkm** [comment]
Thanks @mbest . I've pulled this version into my Dev environment, I might race you to production vs final release :-).

One thing I noticed is 3.5 seems stricter about  markup. It straightway found some stragglers in our code ;-)... its is a good thing though :+1:
