### ISSUE TITLE
Possible Regression - foreach binding for inline arrays not working

### ISSUE THREAD

**Issue by sumitkm** [knockout/knockout#2413]
Hi Team,

Using KO 3.5.0-rc
This [JS Fiddle](http://jsfiddle.net/L8Uy5/) doesn't work.

Basically we have some code that creates empty arrays in foreach binding as follows.

```HTML
<!-- ko foreach: new Array(7) -->
<span data-bind="text: $index()"></span>
<!-- /ko -->
```

I realise it is hacky, but this was working in KO 3.4.2 but no longer works. Is this a regression or has this been removed for a reason? 

After digging around further I see we can use 
```HTML 
<!-- ko foreach: Array.from(new Array(7)) -->
<span data-bind="text: $index()"></span>
<!-- /ko -->
```
If this is the recommended way forward please close this 👍

**Comment by mbest** [comment]
Thanks for the report.

It's working with RC 2: http://jsfiddle.net/L8Uy5/532/
