### ISSUE TITLE
Component's custom element inside html binding does not create component

### ISSUE THREAD

**Issue by ppath** [knockout/knockout#2418]
Since bindings work for html tags inside the value given to **html** binding, I would expect that a component's custom tag would work too (i.e. create an instance of the component).

It seems that this is not the case: [jsfiddle example](https://jsfiddle.net/akd8wjcn/13/).

**Comment by fastfasterfastest** [comment]
> Since bindings work for html tags inside the value given to html binding

Do you have a sample that demonstrates what you mean by that?

> I would expect that a component's custom tag would work too

[The "html" binding](https://knockoutjs.com/documentation/html-binding.html) says:
> sets the element’s content to your parameter value using jQuery’s html function...

I.e., the html binding does not "process" the value, it does not process any knockout bindings that may appear in the value.

**Comment by ppath** [comment]
You are right. I did something wrong when I tested and concluded that bindings are recognized inside a html binding value, since I cannot reproduce it.

Thanks! :) I'm closing the issue
