### ISSUE TITLE
knockout.validation module has stopped working in 3.5.0-rc

### ISSUE THREAD

**Issue by azaslonov** [knockout/knockout#2420]
Hi guys, knockout validation module has stopped working in 3.5.0-rc, saying this:

```
knockout-latest.js:84 Uncaught Error: ko.applyBindings: first parameter should be your view model; second parameter should be a DOM node
    at a.qc (knockout-latest.js:84)
    at Object.ko.applyBindings (knockout.validation.js:1472)
    at HTMLDocument.<anonymous> (startup.designtime.ts:50)
```

Simple repro: https://jsfiddle.net/azaslonov/4z62mw1r/

Considering they didn't release since 2015, there is probably something got broken in KO itself.
https://github.com/Knockout-Contrib/Knockout-Validation/releases

Can you guys please have a look?

**Comment by azaslonov** [comment]
Thank you, I think I can live with this for now.

**Comment by fastfasterfastest** [comment]
Alternatively, patch knockout-validation and change the call `origApplyBindings(viewModel, rootNode)` to `origApplyBindings.apply(this, arguments)`.
If you are using its `ko.applyBindingsWithValidation` you probably need to update it as well.

**Comment by mbest** [comment]
Issue was fixed in knockout-validataion
