### ISSUE TITLE
Unable to process binding afterRender due to Vue Collision(?)

### ISSUE THREAD

**Issue by f1729** [knockout/knockout#2422]
Hello!
We currently manage a Vue(2.x) application, which is injected into other web applications, so we do not have much control of the libraries they use. In this case (Magento 2.x) they use `knockout.js` and we have this problem, which I do not have much idea about and I would like them to help me understand what could be happening. 
Thank you.
Update: (this error is shown first)
<img width="741" alt="screen shot 2018-10-24 at 14 11 21" src="https://user-images.githubusercontent.com/23299193/47455164-bebe2a00-d796-11e8-990f-24931ffebd6e.png">

<img width="724" alt="screen shot 2018-10-23 at 12 29 45" src="https://user-images.githubusercontent.com/23299193/47379557-d7f4a700-d6c0-11e8-8b03-0a182e14aaeb.png">
<img width="325" alt="screen shot 2018-10-23 at 12 30 18" src="https://user-images.githubusercontent.com/23299193/47379565-db882e00-d6c0-11e8-8d00-226e41c581af.png">

**Comment by hdegues** [comment]
Hi
I have the same problem

**Comment by f1729** [comment]
@mbest This application injected into other pages has no problems, so it seems strange to me that this one with `knockout.js` has this error

**Comment by chrisknoll** [comment]
That may be, but the exception is buried inside main.js (from your stack trace) or somewhere below init in after-render.js.  Set a breakpoint in the main.js and try to understand why p.a is not a constructor. You have the breakpoint there, what is p.a?

**Comment by f1729** [comment]
@chrisknoll Thanks for read. 
p.a is ...
<img width="464" alt="screen shot 2018-10-24 at 14 06 17" src="https://user-images.githubusercontent.com/23299193/47454922-0ee8bc80-d796-11e8-8ede-b57f0b069871.png">
<img width="551" alt="screen shot 2018-10-24 at 14 06 09" src="https://user-images.githubusercontent.com/23299193/47454926-114b1680-d796-11e8-84c0-382c174bdd2c.png">

**Comment by PaulHuizer** [comment]
see here [example](https://github.com/Valve/fingerprintjs2)
Shouldn't the code be:
`FingerPrint2().get ...`

**Comment by mbest** [comment]
Please feel free to continue the discussion, but I'll close this since it's not an issue from Knockout.

**Comment by f1729** [comment]
@PaulHuizer to load it as a module we have to use the new
It seems to be related to this
https://github.com/Valve/fingerprintjs2/issues/233

**Comment by f1729** [comment]
@PaulHuizer to load it as a module we have to use the new
In addition to having problems with Webpack 😕
It seems to be related to this
https://github.com/Valve/fingerprintjs2/issues/233

**Comment by PaulHuizer** [comment]
Ok, good luck with it ;-) I just saw this remark and thought .. it might have been missed:

> Fingerprint2.get  is now a static function. It replaces new Fingerprint2().get.

**Comment by GrosSacASac** [comment]
What is the ouput of `npm ls --depth=0` ?
