### ISSUE TITLE
extend computed

### ISSUE THREAD

**Issue by more-urgent-jest** [knockout/knockout#2425]
if I try to extend a computed with the numeric extender from example 1 from https://knockoutjs.com/documentation/extenders.html it doesn't seem to apply the rounding to the value of the computed, e.g.:

`self.blih = ko.observableArray();`
`self.blah = ko.computed(function () {
`    return self.blih().reduce(function(result, item) { return result + item }, 0);`
`}).extend({ numeric: 4);`

if I put a breakpoint into the extender in chrome debugger it is only ever entered into at initialisation, but shouldn't it also executed when the values of the underlying observable array, blih, changes?

if I put a breakpoint into blah it is hit every time an item is added to the array.

using knockout-3.4.2.js

**Comment by chrisknoll** [comment]
No, your array needs to contain observables.  It will fire if you add elements to the array, but if you change the value of one of the elements in the array, no observable is observed.

Your reduce will need to be:

```
self.blih().reduce(function(result, item) { return result + item() }, 0);
```

The evaluation of `item()` will attach an observer tracker to the computed.  Remember, tho, the array contains observables.

**Comment by mbest** [comment]
That extender modifies the `write` behavior of an observable. That is, it changes what happens when you try to change the value of the observable externally, through a binding or by directly modifying its value, like `self.blah(newvalue)`.

**Comment by more-urgent-jest** [comment]
so if i make the computed writable will it work?

What I would like to know is, given that the extender as is won't work for a computed, how do you implement an extender that does work for a computed, is there a different construct that can be used to apply this behaviour to multiple computeds, or do you have to write the code to do so in every computed that requires it?

**Comment by mbest** [comment]
With your example computed, it doesn't make much sense to be able to write a value to it. If all you want is to convert the value to a number, you can just create an external function and call it in your computed function.

```javascript
self.blah = ko.computed(function () {
    return toNumber(self.blih().reduce(function(result, item) { return result + item(); }, 0));
});
```

If you want to do this with an extender, your extender will do its work in the "read" function of the computed and not the "write" function.

```
ko.extenders.numericResult = function(target, precision) {
    return ko.pureComputed(function() {
            var value = target(),
                roundingMultiplier = Math.pow(10, precision),
                valueAsNum = isNaN(value) ? 0 : +value;
            return Math.round(valueAsNum * roundingMultiplier) / roundingMultiplier;
        }
    });
};
```

**Comment by more-urgent-jest** [comment]
Is there no nice way to handle formatting of numbers? specifically, if I have a number of observables that I want to show with this kind of format "#,##0.0000", do I really need to create a writable computed for the formatted value and have a corresponding observable for the raw number? that seems very boilerplate and inefficient given the formatting / unformatting involved.

It would seem more efficient if you could hook into the updating / refreshing of the computed and update the observable with the raw value, or is that the read function?

or to have a formatted observable where you specify the formatting rules which are applied via a formatted function and you could bind an input field to the formatted value, but use the raw value in calculations without having to apply the formatting for read and remove the formatting for write.

I suppose it's not that straight forward since the raw value returned from the input field would be formatted unless the field was empty. It would actually be nicer to be able to specify a formatting rule for the input field that is purely used for display.

I will try having an extender for observables that format the number as a string and add a raw subobservable to the observable that returns the unformatted number, and for computeds the extender as suggested.

Except that the subobservable doesn't seem to be available in the extender or the extender is evaluated after the code where the subobservable is used and hence is not defined.

so unformatted observables with formatted computeds it is.

**Comment by more-urgent-jest** [comment]
would it be possible to do this via a custom binding? i.e. to have the input display the formatted value, and the observable be set to the unformatted value? much appreciated

**Comment by more-urgent-jest** [comment]
I ended up writing a custom binding that updates the field with the formatted value and the observable with the raw value.

found [this page](https://knockoutjs.com/documentation/custom-bindings.html) of the documentation mildly helpful. It would be more helpful if it had a slightly more complex example that registers an event handler [like in this article](http://www.knockmeout.net/2011/07/another-look-at-custom-bindings-for.html).
