### ISSUE TITLE
error when pop up bootstrap double data

### ISSUE THREAD

**Issue by pinchanna** [knockout/knockout#2430]
Html and script
<ul data-bind="foreach:product">
    <li class="displayFlex">
        <div class="width200px">
            <span data-bind="text:productName"></span>
        </div>
        <div class="width200px">
            <span data-bind="text:productCode"></span>
        </div>
        <div class="width200px">
            <a> Delete </a>
        </div>
        <div class="width200px">
            <a>Edit</a>
        </div>
    </li>
</ul>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/popup.js"></script>
<script src="~/Scripts/knockout-3.4.2.js"></script>
<script src="~/Scripts/product.js"></script>

![2018-12-18_114015](https://user-images.githubusercontent.com/34365919/50132776-a4796780-0280-11e9-8bd9-7c118cd71f57.png)

**Comment by brianmhunt** [comment]
Hi @pinchanna It's not clear how one might reproduce this issue.  I'm going to close this on the basis that it's not an issue with Knockout per-se, but please feel free to leave more details and if it is we can re-open.

I'd also suggest trying Stackoverflow for Q&A type support.
