### ISSUE TITLE
Feature Request: Single File Components

### ISSUE THREAD

**Issue by flyfishMT** [knockout/knockout#2432]
I'd like to see single file components for knockout, like vuejs does: [https://vuejs.org/v2/guide/single-file-components.html](https://vuejs.org/v2/guide/single-file-components.html)

I've often put components in one file:

my-component.ts/js:
```javascript
export default class myComponentViewModel {
}
ko.components.register('my-component', {
	viewModel: { createViewModel: (params, eventInfo) => new myComponent(params) },
	template: 
` <div>
. . . HTML . . .
</div>`
```
And it would be nice not to have the template be a string. And component scoped CSS would be even better. Something like this:

my-component.ko:
```javascript
<script lang="typescript">
export default class myComponentViewModel {
}
</script>

<template>
<div>
. . . HTML . . .
</div>
</template>

<css>
</css>
```

Thanks.

**Comment by brianmhunt** [comment]
TKO (in alpha) can use JSX and JSS, effectively providing single-file extensible components.  I’ll close this but feel free to raise any issues in the tko repository, or please let us know if there is something further or other knockout could do in this vein.
