### ISSUE TITLE
rateLimit extension UT

### ISSUE THREAD

**Issue by deveras** [knockout/knockout#2434]
Hi guys, 

I've got an observable being a query input field used to filter a pureComputed that is used on a foreach.
I need a way to ensure that the pureComputed was extended for UT (unit test) purposes.

The need arouse from the speed at which insertions and deletions are made on the collection computed (gets confused at times, so needs less calculations, hence rateLimit like 500ms). I wanted something along this lines:

subjectUnderTest.query("rd");
var returnValue = subjectUnderTest.filteredComputed()
expect(returnValue).toBeUndefined();

jasmine.clock().tick(100);
var returnValue = subjectUnderTest.filteredComputed()
expect(returnValue).toEqual(foo);

I'm aware that i'll be testing the framework more than my own code, but I need a way to ensure the extension was applied and have it reflected in a UT. Perhaps there's a property of the computed that i can check? Does it have a public accessor (something like subjectUnderTest.filteredComputed.isExtended())?

**Comment by mbest** [comment]
The `rateLimit` extender affects `change` notifications. So the best way to test it is to add a subscription and verify when it's called.

**Comment by deveras** [comment]
Thanks for the reply @mbest 

If i add a subscription to the query (the search field), the computed will not be notified (the results), it would not ensure that the extension would be in place, only the observable was called I believe

**Comment by mbest** [comment]
There is no public method to check if an observable has rate-limiting turned on. Here's a test from Knockout that may give you some ideas:

        it('Should delay change notifications', function() {
            var observable = ko.observable().extend({rateLimit:500});
            var notifySpy = jasmine.createSpy('notifySpy');
            observable.subscribe(notifySpy);

            // Observable is changed, but notification is delayed
            observable('a');
            expect(observable()).toEqual('a');
            expect(notifySpy).not.toHaveBeenCalled();

            // Second change notification is also delayed
            observable('b');
            expect(notifySpy).not.toHaveBeenCalled();

            // Advance clock; Change notification happens now using the latest value notified
            jasmine.Clock.tick(500);
            expect(notifySpy).toHaveBeenCalledWith('b');
        });

**Comment by deveras** [comment]
Thank you @mbest that was the clue I needed.
Much appreciated

**Comment by jasonlee114** [comment]
What can I do with this

**Comment by mbest** [comment]
@jasonlee114 What do you want to do?
