### ISSUE TITLE
ko and tko future

### ISSUE THREAD

**Issue by nmocruz** [knockout/knockout#2437]
Hi,  

I'm using this library for a long time, and last years I saw ko going down. Steve Sanderson is always playing with new stuff, left ko, then left javascript services, now is on blazor and soon when Microsoft figure out that there's to many good js options to compete with c# in the browser side, we will move and let to die blazor to. I'm not saying that is bad, that software libraries should live and be supported by the creators forever, but is sad seeing the impact on this on a library like a knockout. Only 1 or 2 contributors, 1 year to release 3.5.0. tko is also giving some hope, but again 1 or 2 contributors maybe not working on that all time. 
For a while, I was staying away from angular or react because I preferred features not big community or a big company behind (Microsoft ever supported somehow ko?), but now I'm kind of changing my view about this.

Anyway, there any expectation to release 3.5.0, 4.0 or tko in the future? there's any way we can help? I can spend sometime and contribute but is not clear where to start.

**Comment by mbest** [comment]
The last bit of work before releasing 3.5.0 is to update the documentation. See #2326. I'm already working on the last items, but they've been taking some time. You're welcome to look over the changes and give feedback or suggestions.

**Comment by brianmhunt** [comment]
@mbest btw (aside) someone posted on gitter.im:

> Afternoon All, I have just branched off our Development branch, for a Technical Spike to see what fallout we will have upgrading to 3.5.0-rc2. The only issue I am facing so far is with ko.ContextFor. Based on some parameters passed to our custom binding handlers or values on the model, we are rendering new elements via jQuery. in 3.4.2 we were able to get the context using ko.ContextFor, however since upgrading to 3.5.0-rc2. Inspecting the element in Dev Tools I can see that in the application using 3.4.2 the element has a context, but no in the application upgraded to 3.5.0-rc2. Any Ideas, thanks!

I've not seen a jsFiddle, but just wanted to pass this along in case it's apparent to you why this might be occurring.

**Comment by mbest** [comment]
There was a change related to `contextFor`: #2380

**Comment by Dmitri-Sintsov** [comment]
It would be so much great to have one repository to avoid the fragmentation of features. Such as tko's components with slots, can these be ported to main knockout repository, please?
