### ISSUE TITLE
is it possible to use another attribute for data binding?

### ISSUE THREAD

**Issue by bboydflo** [knockout/knockout#2442]
Hi everyone, 

I am maintaining a chrome extension built using knockout.js wrote by someone else and I get errors on pages that also use knockout. so I was thinking maybe I can tell my extension version of knockout to use `data-my-bind` attribute instead of the default one `data-bind`. is that even possible?

 I think if I can achieve this, I can have two knockout versions live on the same page without conflicting with each other

**Comment by mbest** [comment]
You can, but you would have to use a custom binding provider. You can get a good overview at http://www.knockmeout.net/2011/09/ko-13-preview-part-2-custom-binding.html, but if you're just looking to get the built-in functionality with just a different attribute name, you could copy the binding provider from Knockout and just use a different attribute name.

**Comment by doctorcode-co** [comment]
This may help you:

`
(function () {
    let provider = ko.bindingProvider.instance,
        previousPreprocessFn = provider.preprocessNode,
        rxRender = /^(data\-)?ko\-(not)?render$/,
        repeatAttr = ["ko-repeat", "data-ko-repeat"],
        attributes = ["ko-render", "data-ko-render", "ko-notrender", "data-ko-notrender"];

    ko.bindingProvider.instance.preprocessNode = function (node: Node) {
        let newNodes: Node[];

        if (!previousPreprocessFn || !(newNodes = previousPreprocessFn.call(this, node))) {
            let attrName: string,
                attrValue: string,
                temp: string,
                i = 0;

            if (dom.isElement(node)) {
                for (i = 0; i < repeatAttr.length; i++) {
                    attrName = repeatAttr[i];
                    if (node.hasAttribute(attrName)) {
                        attrValue = node.getAttribute(attrName);

                        let leadingComment = node.ownerDocument.createComment(`ko foreach: ${attrValue}`),
                            trailingComment = node.ownerDocument.createComment('/ko');

                        node.parentNode.insertBefore(leadingComment, node);
                        node.parentNode.insertBefore(trailingComment, node.nextSibling);
                        newNodes = [leadingComment, node, trailingComment];
                        node.removeAttribute(attrName);
                        return newNodes;
                    }
                }

                for (i = 0; i < attributes.length; i++) {
                    attrName = attributes[i];
                    if (node.hasAttribute(attrName)) {
                        attrValue = node.getAttribute(attrName);
                        temp = attrName.match(rxRender)[2] || "";

                        let leadingComment = node.ownerDocument.createComment(`ko if${temp}: ${attrValue}`),
                            trailingComment = node.ownerDocument.createComment('/ko');

                        node.parentNode.insertBefore(leadingComment, node);
                        node.parentNode.insertBefore(trailingComment, node.nextSibling);
                        newNodes = [leadingComment, node, trailingComment];
                        node.removeAttribute(attrName);
                        return newNodes;
                    }
                }
            }
        }

        return newNodes;
    };
}());
`
