### ISSUE TITLE
ko.toJS generates random "_ko_subscr_2" entries

### ISSUE THREAD

**Issue by AnReZa** [knockout/knockout#2443]
When calling the toJS or toJSON methods on a viewmodel, the generator adds some wierd _ko_subscr_2 entries. Does anybody know, why this happens? I'm using version 3.5.0-rc2.

**Comment by mbest** [comment]
I don't know where those would come from.

**Comment by AnReZa** [comment]
I see, they are coming from my global subscription plugin that I found on the web. Is there some easy way to exclude some properties from being serialized by ko.toJS(ON)?

    @* START GLOBAL SUBSCRIBE *@
    (function () {

        //stores the subscriptions
        var subscriptions = [];

        //maintains a unique identifier 
        var id = 0;

        ko.subscribe = function (vm, fnOnChange, throttle) {

            var myId = ++id;

            //store subscription - add throttle
            subscriptions.push({
                id: myId,
                change: _.throttle(function () {
                    fnOnChange(vm);
                }, throttle)
            });

            //subscripe model with id.
            _subscribe(vm, myId)
        };

        ko.unsubscribe = function (vm, fnOnChange) {
            _.remove(subscriptions, function (item) {
                return item.vm == vm && item.change == fnOnChange;
            });
        };

        function _subscribe(vm, id) {
            if (!vm)
                return;

            if (_.isArray(vm)) {

                //loop through array values and subscribe to each item
                for (var i = 0; i < vm.length; i++) {
                    _subscribe(vm[i], id);
                }
            }
            else {

                //prevent double subscriptions by checking
                //a 'magic' property:
                var subscriberId = '_ko_subscr_' + id;

                if (_.isUndefined(vm[subscriberId])) {

                    function subscribeTo (obs) {
                        obs.subscribe(function (newValue) {

                            //subscribe the new observable value
                            _subscribe(newValue, id);

                            //fire event, because something just changed
                            fire(id);
                        });

                        //subscribe to current value stored by observable
                        var currentValue = obs();
                        _subscribe(currentValue, id);
                    }

                    vm[subscriberId] = true;

                    //subscribe to each observable
                    for (var n in vm) {

                        var observable = vm[n];

                        if (ko.isObservable(observable) && !ko.isComputed(observable)) {
                            subscribeTo(observable);
                        }
                        @* OWN ADDITION *@
                        else if (observable && typeof (observable) === 'object' && observable.answerNodes) {
                            for (let prop in observable.answerNodes)
                                subscribeTo(observable.answerNodes[prop]);
                        }
                        @* END OWN ADDITION *@
                    }
                }
            }
        }

        function fire(id) {
            _.forEach(subscriptions, function (item) {
                if (item.id == id) {
                    item.change();
                }
            });
        }

    })();

    ko.isComputed = function (instance) {
        if ((instance === null) || (instance === undefined) || (instance.__ko_proto__ === undefined)) {
            return false;
        }

        if (instance.__ko_proto__ === ko.dependentObservable) {
            return true;
        }

        // Walk the prototype chain
        return ko.isComputed(instance.__ko_proto__);
    };

    @* END GLOBAL SUBSCRIBE *@

**Comment by chrisknoll** [comment]
I believe ko.toJS supports the same functionality as JSON.stringify, where you can pass a function where you can whitelist / blacklist fields, see: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify

**Comment by mbest** [comment]
`ko.toJS` does not provide any way to filter the object's properties, but `ko.toJSON` does support `JSON.stringify`'s `replacer` function.
