### ISSUE TITLE
Unhandled rejection Error: ko.applyBindings: first parameter should be your view model; second parameter should be a DOM node

### ISSUE THREAD

**Issue by pavelkarkh** [knockout/knockout#2444]
Last increment version not work with old knockout: 
Unhandled rejection Error: ko.applyBindings: first parameter should be your view model; second parameter should be a DOM node

**Comment by bludev** [comment]
See #2388

**Comment by mbest** [comment]
Thanks for the feedback. This is a purposeful change we made to create more visibility for which part of the DOM bindings will be applied to.
