### ISSUE TITLE
Regression in 3.5.0: empty template with if option throw an error "Anonymous template defined, but no template content was provided"

### ISSUE THREAD

**Issue by BarkovskiyMaxim** [knockout/knockout#2446]
We have prepared simple samples to demonstrate the issue (see console):
v3.4.2: https://jsfiddle.net/cLrdpshe/
v3.5.0: https://jsfiddle.net/5tc0u9y3/

**Comment by mbest** [comment]
A workaround is to include some content in the `<div>`:

https://jsfiddle.net/mbest/bn9sko7e/

**Comment by VolodymyrMoldovan** [comment]
> A workaround is to include some content in the `<div>`:
> 
> https://jsfiddle.net/mbest/bn9sko7e/

It will be fixed? I have a few hundred places like:

**Comment by mbest** [comment]
@VolodymyrMoldovan You're example should work just fine. The change should only cause an issue if you pass an empty string to the binding.

**Comment by hfinger** [comment]
@mbest Are you sure? I hope this will be fixed soon. We are having a problem with v3.5.0 and the following templates:


We use these anonymous templates everywhere to trigger some rendering functions of js libraries after knockout did it's rendering jobs. In previous knockout versions this was always working perfectly without problems. Now we get the errors "Anonymous template defined, but no template content was provided" everywhere...

**Comment by mbest** [comment]
@hfinger If all you want to do is call a function during the binding process, you don't need to use the `template` binding. It adds overhead for something very simple. The best option would be for you to create a custom binding that clearly indicates what you're trying to do. Here's an example:

```js
ko.bindingHandlers.runOnInit = {
    init: function(elem, valueAccessor) {
        var value = valueAccessor();
        if (typeof value == "function") {
            value();
        }
    }
};
ko.virtualElements.allowedBindings.runOnInit = true;
```

Then you can replace your `template` bindings like this:

```html
<!-- ko runOnInit: function() { $data.afterRenderInit($element) } --><!-- /ko -->
```

**Comment by fastfasterfastest** [comment]
FYI, https://github.com/rniemeyer/knockout-sortable/issues/199 - commits https://github.com/knockout/knockout/commit/0f0cb8e23fa3f01a9f845cb539f2b6521322664f and https://github.com/knockout/knockout/commit/a93358fb9e2e2ef285985df2015a442ad83fd09a breaks @rniemeyer's [`knockout-sortable`](https://github.com/rniemeyer/knockout-sortable) binding when it is used with anonymous templates, e.g.
```
<ul data-bind="sortable: items">
  <li data-bind="text: name"></li>
</ul>
```
The `knockout-sortable` binding currently passes `{ name: undefined, … }` as the value to the `template` binding when it is used with anonymous templates.

See https://jsfiddle.net/fastfasterfastest/3rekjytw/

**Comment by gregveres** [comment]
> @hfinger If all you want to do is call a function during the binding process, you don't need to use the `template` binding. It adds overhead for something very simple. The best option would be for you to create a custom binding that clearly indicates what you're trying to do. Here's an example:
> 
> ```js
> ko.bindingHandlers.runOnInit = {
>     init: function(elem, valueAccessor) {
>         valueAccessor();
>     }
> };
> ko.virtualElements.allowedBindings.runOnInit = true;
> ```
> 
> Then you can replace your `template` bindings like this:
> 
> ```
> 
> ```

@fastfasterfastest 
When would this run? I was just about to use the same technique as @hfinger because I have a component that brings up a dialog and I need to set focus on an element within that dialog, but all of my view model intialization code runs before the dialog is rendered on the screen. I found a suggestion from previous versions to put in an anonymous template like @hfinger is doing with an afterRender callback so I can then set the proper observable to force the focus to the correct element. 


This suggestion seems like it would run when the element is bound (because of the use of its Init() function).

**Comment by gregveres** [comment]
> > @hfinger If all you want to do is call a function during the binding process, you don't need to use the `template` binding. It adds overhead for something very simple. The best option would be for you to create a custom binding that clearly indicates what you're trying to do. Here's an example:
> > ```js
> > ko.bindingHandlers.runOnInit = {
> >     init: function(elem, valueAccessor) {
> >         valueAccessor();
> >     }
> > };
> > ko.virtualElements.allowedBindings.runOnInit = true;
> > ```
> > 
> > 
> > Then you can replace your `template` bindings like this:
> > ```
> > 
> > ```
> 
> @mbest
> When would this run? I was just about to use the same technique as @hfinger because I have a component that brings up a dialog and I need to set focus on an element within that dialog, but all of my view model intialization code runs before the dialog is rendered on the screen. I found a suggestion from previous versions to put in an anonymous template like @hfinger is doing with an afterRender callback so I can then set the proper observable to force the focus to the correct element.
> 
> This suggestion seems like it would run when the element is bound (because of the use of its Init() function).

Ah it seems like the afterRender on that embedded template isn't doing what I want it to do anyway. I figured out that if you add nodes: [] to the template binding you can get around the error, but the afterRender function is called  before the whole component is rendered on the page and my setFocus attempt doesn't work anyway.

**Comment by mbest** [comment]
@gregveres This might help you: https://knockoutjs.com/documentation/binding-lifecycle-events.html

**Comment by gregveres** [comment]
@mbest thanks for the link to the docs. I hadn't noticed that page before. 
But in the end there doesn't seem to be an event for what I am looking for. I need to know when the dom elements have been rendered so I can use the hasFocus binding to set focus through an observable. If I set the observable before the dom element has been rendered, then the focus setting is ignored. In the end I used the callback for koDescendantsComplete and then did a setTimeout from there. It isn't perfect but it works well enough.

**Comment by ajithvs** [comment]
Are you sure this is fixed in 3.5.1 build? 
We are still getting this error in 3.5.1 version.

Unable to process binding "foreach: function(){return _someList_  }" Message: Anonymous template defined, but no template content was provided /Scripts/jquery-3.4.1.js:3850

**Comment by fastfasterfastest** [comment]
Can you provide a sample that shows the problem.

https://knockoutjs.com/documentation/foreach-binding.html states that the main parameter to the `foreach` binding should be either an array or an object literal - you seem to specify a function.

**Comment by mbest** [comment]
@ajithvs Specifically, the change for this issue handles the case where a template binding references an empty or null template name. When using "anonymous" templates, the 3.5.0 behavior remains: it's reported as an error.

**Comment by ajithvs** [comment]
@mbest @fastfasterfastest 
Thanks for your reply. We do use template binding lot many places in our current project. Which is using a very old version 2.2.1 of Knockout. When I upgraded to 3.5.1 I saw only few issues mainly the dropdown binding. I need to evaluate whether the error is due to an empty value or not. 
I got the above error in Javascript notifier extension in chrome. 
Anyway will check it closely and get you back.. 
Thanks for the support.
Do you have any help doc to consider when upgrading to 3.5.1 from v 2.x.x

**Comment by fastfasterfastest** [comment]
Since you mention you are using a `foreach` binding with a function value issues https://github.com/knockout/knockout/issues/2466 and https://github.com/knockout/knockout/issues/2467 may be of interest.

**Comment by mbest** [comment]
@fastfasterfastest Knockout's binding parser wraps each binding in a function. So in @ajithvs's case, the original binding would have been `foreach: someList`, but then that becomes `foreach: function(){return someList }` for the binding handlers.
