### ISSUE TITLE
Apply custom BindingHandler after all BindingHandlers.

### ISSUE THREAD

**Issue by doctorcode-co** [knockout/knockout#2448]
Hi;
Are there any whay to force a custom BindingHandler apply after all BindingHandlers without their name?
```
 ko.bindingHandlers["binder"] = {
   //maybe <input data-bind="css: cssClass, binder: binding, click: doActin" />
   //after apply the css Binding is cleared.
   after: ["ALL"],
    init: function (element, valueAccessor, allBindingsAccessor, viewModel, bindingContext) {
       // The value accessor is a dynamic binding ex: binding = isTrue ? {value: this.value} : {text: this.text}
        let value = ko.unwrap(valueAccessor());
        ko.cleanNode(element);
        ko.applyBindingsToNode(element, value, bindingContext);
    }
};
```

**Comment by mbest** [comment]
No, there isn't a way to do that. Also why would you want to call `cleanNode` during your bindings?

**Comment by doctorcode-co** [comment]
> No, there isn't a way to do that. Also why would you want to call `cleanNode` during your bindings?

This work fine in all case but when use with template binding throw "You cannot apply bindings multiple times to the same element." error.
sample:
```
var model = {
    binding: {
        template: {name: self.template, foreach: self.items}
    }
};
<div data-bind="binder: binding"></div>
```

**Comment by mbest** [comment]
Perhaps you're looking for https://github.com/rniemeyer/knockout-classBindingProvider
