### ISSUE TITLE
knockout definition file error

### ISSUE THREAD

**Issue by doctorcode-co** [knockout/knockout#2459]
There was an error in definition file:
```
export class defaultLoader implements Loader {
    getConfig(componentName: string, callback: (config: Config | object) => void): void;
    loadComponent(componentName: string, config: Config, callback: (component: Component) => void): void;
    loadTemplate(componentName: string, config: TemplateConfig, callback: (resolvedTemplate: Node[]) => void): void;
    loadViewModel(componentName: string, config: ViewModelConfig, callback: (resolvedViewModel: CreateViewModel) => void): void;
} 
```
the right declaration is:
```
export class DefaultLoader extends Loader {
    getConfig(componentName: string, callback: (config: Config | object) => void): void;
    loadComponent(componentName: string, config: Config, callback: (component: Component) => void): void;
    loadTemplate(componentName: string, config: TemplateConfig, callback: (resolvedTemplate: Node[]) => void): void;
    loadViewModel(componentName: string, config: ViewModelConfig, callback: (resolvedViewModel: CreateViewModel) => void): void;
}

export const defaultLoader: DefaultLoader;
```

**Comment by mbest** [comment]
Can you explain what's wrong with the current definition?

**Comment by doctorcode-co** [comment]
> Can you explain what's wrong with the current definition?

The `export class defaultLoader implements Loader` is wrong because it define class not instance. if we want to add new ComponentLoader can not use `ko.component.defaultLoader` as variable, it point to a type. therefore first declare DefaultLoader class extends Loader then define a variable defaultLoader as:
`export const defaultLoader: DefaultLoader;`.

**Comment by doctorcode-co** [comment]
> Can you explain what's wrong with the current definition?

how you can call ` ko.components.defaultLoader.loadTemplate(name, { element: nodes }, callback);` in a custom ComponentLoader when it defined as type, not an instance.

**Comment by Sebazzz** [comment]
Correct, I also ran into this issue. 

It is currently defined as if you'd `new ()` it. But in practice it is already an instance and you can (need to) use it directly.
