### ISSUE TITLE
Dispose is called with dependency checking

### ISSUE THREAD

**Issue by dyue** [knockout/knockout#2461]
I have some strange situations where my component is instantiated twice when I only set the component observable once.  My component is declared like this:
```
<div data-bind="if: component, visible: component">
  <div data-bind="component: component, style: attr1, event: attr2"></div>
</div>
```
I traced the issue back to the if binding.  Basically, when the component is false, the internal computed within the if binding will try and remove the component element and eventually call viewModel.dispose with dependency checking on.   I happen to have some checks against global observables in the dispose, and I guess the if binding is re-evaluated when the component becomes true and the global observables change.  I tried hard to get a sample in jsfiddle working, but I just couldn't get the timing right to make the sample demonstrate the issue.

Would it make sense to ignore dependency checking while dispose is called?   As a workaround, I used ko.ignoreDependencies in my viewModel.dispose.

**Comment by chrisknoll** [comment]
Disclaimer: I do not know the details of your application logic and you are probably doing that you are doing for good reason.  At first glance, however, I'd say "Dispose is for disposing, not checking".  Disposal work really shouldn't be doing anything that would set up additional dependencies.  So, perhaps that's a bit of code-smell.  However, assuming you do know what you wanted to do, and you are doing it proper, is there something new that could be added to the framework that would let you do an action that would not be dependency tracked during disposal?  I was goign to sugest something like 'onAfterDispose' or something..

But honestly, if the rule is that 'dispose shouldn't add new depenencies' it might make perfect sense to trigger dispose as non-tracked dependency.  This probably applies to anything that is disposed as well:  components, data-bindings, view models, etc.

**Comment by mbest** [comment]
`dispose` is called by `ko.cleanNode`. In general we've tried to ensure that Knockout code that runs user-defined callbacks won't leak dependencies. I'll list this as a bug.
