### ISSUE TITLE
I want to know to add more data in xml file 

### ISSUE THREAD

**Issue by pinchanna** [knockout/knockout#2462]
When I try to use if else , it error at if 

![2019-03-23_182545](https://user-images.githubusercontent.com/34365919/54865525-2ce43880-4d99-11e9-8426-f1c999cc3554.png)
![2019-03-23_182612](https://user-images.githubusercontent.com/34365919/54865526-2ce43880-4d99-11e9-9c83-681b51bd02d3.png)

**Comment by chrisknoll** [comment]
Wrong repo, but thanks for visiting! :)
