### ISSUE TITLE
it is not neccessary to user ko.dependentObservable in method mapNodeAndRefreshWhenChanged

### ISSUE THREAD

**Issue by yusongjohn** [knockout/knockout#2468]
It is not neccessary to use ko.dependentObservable in method mapNodeAndRefreshWhenChanged.

I think , It is impossible to add any dependencies inside this dependentObservable.
If it can , could you show the possible code.

**Comment by fastfasterfastest** [comment]
I think this might do it:
```
<select data-bind="options: ['a', b, 'c']"></select>
<button data-bind="click: function(){b(b()==='b' ? 'B' :'b');}">change b</button>
...
ko.applyBindings({b: ko.observable("b")});
```

**Comment by yusongjohn** [comment]
thanks, it does work

**Comment by yusongjohn** [comment]
`<div data-bind="foreach: ['a', 'b', c]">
        <div data-bind="text:$data"></div>
    </div>
    <button data-bind="click: function(){c(c()==='c' ? 'C' :'c');}">change c</button>
...
ko.applyBindings({b: ko.observable("c")});
`

I read source code of  'foreach' part, I found that it won't work in this circumstances.  Now, I realized that in the usage of 'foreach' do not need dependencies, but in other circumstance such as 'options' need
