### ISSUE TITLE
Typescript definitions: Add overloads to observable factory functions

### ISSUE THREAD

**Issue by Sebazzz** [knockout/knockout#2473]
In [knockout.d.ts](https://github.com/knockout/knockout/blob/6591d0f801457166575c092ef0c2c9a93d914c19/build/types/knockout.d.ts#L65) this is the definitions for the `observable` factory function:

```
export function observable<T = any>(): Observable<T>;
export function observable<T = any>(initialValue: T): Observable<T>;
export module observable {
    export const fn: ObservableFunctions;
}
```

I propose to add two overloads to make it easier to use without the need to overspecifying the type parameters:

```
export function observable<T>(initialValue: null): Observable<T|null>;
export function observable<T>(initialValue: undefined): Observable<T|undefined>;
```

This allows:

``` 
const myObservable = ko.observable<MyModel>(null);
myObservable().toString(); // strictNullChecks compile time error!
```

instead of:

``` 
const myObservable = ko.observable<MyModel|null>(null);
myObservable().toString(); // strictNullChecks compile time error!
```

Sidenote: You can argue that `export function observable<T = any>(): Observable<T>;` leaves  the observable in a state where its value is null and `observable<T>` should actually return `Observable<T|undefined>`.

**Comment by mbest** [comment]
Fixed with #2458
