### ISSUE TITLE
Google chrome 75 content_script_bundle.js Uncaught TypeError: c.querySelectorAll is not a function at MutationObserver

### ISSUE THREAD

**Issue by hduchesn** [knockout/knockout#2489]
I updated google chrome to latest release _Version 75.0.3770.100 (Build officiel) (64 bits)_ and now I have this error in the console : content_script_bundle.js:16 Uncaught TypeError: c.querySelectorAll is not a function at MutationObserver.<anonymous> (content_script_bundle.js:16).

This error appears when ko apply bindings.
I have updated my ko to latest release from 3.4.1 to 3.5, but nothing change.

This error is also generated by other script. So not sure it is related to ko itself.

I don't know what does Google change and if this error is important or not.

Did you see this error also on your side?

**Comment by mbest** [comment]
I might be one of your extensions. Knockout doesn't call `querySelectorAll`.
