### ISSUE TITLE
BUG: extend({rateLimit: x}) on computed prevents notification of inner observables from bubbling

### ISSUE THREAD

**Issue by VladyslavBiletskyi** [knockout/knockout#2492]
let isLoading = ko.observable(false);
let isLoadingOrError = ko.computed(() => isLoading() || isError()).extend({ rateLimit: 50});
let isLoadingOrSuccess = ko.computed(() => isLoading() || isSuccess());

As you may see - **isLoadingOrError** and **isLoadingOrSuccess** are depend on **isLoading**. 
**isLoadingOrError** has rate limit and if **isLoading** is being modified faster than once in 50 seconds the computed should **NOT** be evaluated.
**isLoadingOrSuccess** has **NO** rate limits and should be evaluated every time when **isLoading** is modified.

for now rateLimit on **isLoadingOrError** affects **isLoadingOrSuccess** too, and both of the computeds are being evaluated once upon 50 ms after **isLoading** changed, and seems like rateLimit of **isLoadingOrError** prevents the subscribers of **isLoading** from getting the notification if evaluation of **isLoadingOrError** is omitted

**Comment by fastfasterfastest** [comment]
Do you have a sample that demonstrates this?

Here is a sample that seems to indicate `isLoadingOrError` is rate limited while `isLoadingOrSuccess` is not: https://jsfiddle.net/fastfasterfastest/gf41ak9b/

**Comment by mbest** [comment]
Without more info, there's nothing we can do. Please reopen if you can provide an example reproducing the problem.
