### ISSUE TITLE
text binding ignores carriage return

### ISSUE THREAD

**Issue by HeyJude1** [knockout/knockout#2498]
`text` binding seems to ignore carriage return (`\r`). Here's an example (`\u000d` is the hex for carriage return), and here's a [jsFiddle](https://jsfiddle.net/wd6m1yb4/):

Javascript:
```
// with knockout
var json = '[{ "message" : "first line\\u000dsecond line\\u000dthird line"}]';
var parsed = JSON.parse(json);
var master = { rows: ko.observableArray(parsed) };
ko.applyBindings(master);
     
// without knockout
document.getElementById('withCarriage').innerHTML = parsed[0].message;
```
CSS:
```
.formatted {
   white-space: pre-wrap;
}
```
HTML:
```
<strong>With Knockout:</strong>
<table data-bind="foreach: rows">
  <tr>
     <td class="formatted" data-bind="text: message" />
  </tr>
</table>
<strong>Without Knockout:</strong>
<table>
  <tr>
     <td id="withCarriage" class="formatted" />
  </tr>
</table>
```

Note that e.g. with `\u000a` (hex for `\n`) new lines are displayed as expected.

How can this be fixed?

**Comment by fastfasterfastest** [comment]
You are comparing the behavior of knockout's `text` binding vs. DOM's `.innerHTML`.  It is a little bit of an apples vs. oranges comparison.

A better/fairer comparison would be to compare knockout's `html` binding vs. DOM's `.innerHTML`.  Or alternatively knockout's `text` binding vs. DOM's `.textContent`.  See https://jsfiddle.net/fastfasterfastest/284y37me/

**Comment by HeyJude1** [comment]
I see. You're right, my comparison wasn't precise.
However, I'd still expect `text` binding to preserve `\r`, as it preserves `\n` (so that when, for example, `white-space: pre-wrap` is applied, `\r` would be rendered with line breaks as `\n` does). Is it not a fair expectation?

**Comment by fastfasterfastest** [comment]
How do you expect DOM's `.textContent` to behave with regards to \r?  Does your expectation correspond to browsers' behaviors (e.g. see https://jsfiddle.net/fastfasterfastest/284y37me/)?

If so, I think knockout's `text` binding may behave correctly (although knockout doesn't use `.textContent` for the `text` binding, it uses `.createTextNode`, the effect, I think, is the same).

**Comment by mbest** [comment]
Knockout doesn't control this. It's up to the browser.
