### ISSUE TITLE
Dose deferUpdates work for all observables?

### ISSUE THREAD

**Issue by doctorcode-co** [knockout/knockout#2499]
I look the observables source code and dont seen any where that 'ko.options.deferUpdates' is used only in computed observables. I noticed that when this option is enabled the default limit method is override but this happen only in computed observable initializer.
I want to know how enable global deferUpdates work for observables?

**Comment by fastfasterfastest** [comment]
https://knockoutjs.com/documentation/deferred-updates.html might be useful

**Comment by mbest** [comment]
Yes, it works for all observables.
