### ISSUE TITLE
observableArray.sorted() not recognized

### ISSUE THREAD

**Issue by BrittanyDilts** [knockout/knockout#2501]
The documentation includes a reference to a .sorted() that you can use to specify how to sort an observableArray, and the error I'm getting back is that sorted is not a function. I found a comment that included the word "sorted", but there is no defined function in knockout-debug.js called "sorted". Is this a deprecated function?

**Comment by vrad-joshuamckelvey** [comment]
I was able to [find it in the code.](https://github.com/knockout/knockout/blob/0bab98a69bd8d16ceffed368331e54a4afc0ecf5/src/subscribables/observableArray.js#L94)

Are you using the knockout 3.5?

**Comment by BrittanyDilts** [comment]
My version ends at replace. I'm using 3.4.2; but there was no indication that .sorted() was version-dependent.

**Comment by vrad-joshuamckelvey** [comment]
From the commit history, it appears that feature was added in the 3.5 release.

You can always access the array directly and sort it using the browsers built in sort function.
`var array = ko.observableArray();
 arrary().sort();`

**Comment by BrittanyDilts** [comment]
Okay. I'd recommend that the documentation be updated to mention the sorted() and reversed() fxns are new in 3.5. Mine is a commercial project and I don't get to make the choice to upgrade.

**Comment by avickers** [comment]
If what you want to do is sort an observableArray using a custom function, then you may pass the sort function to the .sort() method.  The documentation is a bit ambiguous.  It makes it sound like .sorted() is for use with a custom function; however, the difference between the two is that .sort() works on the observableArray itself and .sorted() works on a copy of the underlying array.

.sorted() is merely syntactic sugar for the code @vrad-joshuamckelvey provides above.

**Comment by mbest** [comment]
Actually to duplicate what `sorted` does, you'd use `var sortedArray = obsArray.slice().sort()`
