### ISSUE TITLE
Using knockout with unsafe-eval disabled

### ISSUE THREAD

**Issue by jeffreypolk** [knockout/knockout#2502]
I'm using the `Content-Security-Policy: script-src 'self' 'nonce-abcde'`.  KO fails to execute due to not allowed `'unsafe-eval'`.  Is there a way I can get KO to run?

**Comment by mbest** [comment]
https://github.com/brianmhunt/knockout-secure-binding might help.

**Comment by jeffreypolk** [comment]
Bummer.  I will close the issue.  This should be safe enough given that I am not allowing any external scripts to execute.
