### ISSUE TITLE
data-bind commands using on console panel

### ISSUE THREAD

**Issue by firstlord1** [knockout/knockout#2506]
Hi, im begginer in javascript. So i discovered your project and i like it. But i have a question may i use data-bind commands on browser console panel ? A web site and using knockout. There is a pager bar like ( Page 1 | Page 2 | Page 3 | Page 4 ). Each button has " `<a class="" data-bind="click: function(){$parent.GotoPage(2)}">Page 2</a>` this data-bind command. How can i use this code on browser console ? is it possible ? for example when i enter `$parent.GotoPage(2)` command on the console page will goto page 2. I hope you understand :( Thanks you all.

**Comment by miellaby** [comment]
It's not as simple as that, but there is a way. Have a look to this [article](https://devillers.nl/blog/quick-debugging-knockoutjs-in-chrome/) for example. Or [this one](https://riptutorial.com/knockout-js/example/17874/checking-the-binding-context-of-a-dom-element).
