### ISSUE TITLE
deferUpdates causes subscription to throttled computed fire too frequently

### ISSUE THREAD

**Issue by lzl124631x** [knockout/knockout#2510]
Related to https://github.com/knockout/knockout/issues/2509

I tried enabling `deferUpdates` and found it causes subscription to throttled computed fire too frequently.

[Demo here](https://codepen.io/lzl124631x/pen/oNgGzXZ)

Expected: In the above codepen, open the console, you'll see logs every 10 steps. It's because the computed is being throttled.

Actual: Uncomment the line `// ko.options.deferUpdates = true;`, you'll see logs every 1 step, firing too frequently.

Is this a bug or expected? (At least I don't expect this)

**Comment by mbest** [comment]
The `throttle` extender has been deprecated for a long time, and it's not likely to be compatible with other newer features of Knockout. It's been replaced by the [`rateLimit`](https://knockoutjs.com/documentation/rateLimit-observable.html) extender. The equivalent setting to `throttle: 1000` is `rateLimit: { timeout: 1000, method: "notifyWhenChangesStop" }`.

**Comment by lzl124631x** [comment]
Thanks! [Rate limit works perfectly with deferUpdates](https://codepen.io/lzl124631x/pen/eYmepgj) 😄
