### ISSUE TITLE
Remove "data-bind" attribute when binding gets applied.

### ISSUE THREAD

**Issue by azaslonov** [knockout/knockout#2511]
Hi guys, hope you're doing well.

Can you please tell what would be the proper approach to remove "data-bind" attribute, **when** (and only when) the binding declared by the attribute **gets applied**? Basically, I would like to cleanup HTML of a static website generated on the server. I know, I can just go through DOM and do the hand-picked removal, but ideally, it could be done through some kind of middleware (if something like this exists in KO).

Any help greatly appreciated.

**Comment by mbest** [comment]
Perhaps [this answer](https://stackoverflow.com/a/30077715/1287183) on SO will help.

**Comment by azaslonov** [comment]
Great! Thank you.
