### ISSUE TITLE
Expected behavior when setting value of options binding to null

### ISSUE THREAD

**Issue by jgscherber** [knockout/knockout#2512]
I wasn't able to find any clear description of what the expected behavior for setting an options binding value to `null`.

For example, [this CodePen](https://codepen.io/jgscherber-2/pen/OJPEZwy)  - I would expect that the value would be reset to value that is set when the observableArray is populated ("one"), but it remains at the previous value ("two).

This question is coming from a defect we experienced in version 3.0.0 ([CodePen](https://codepen.io/jgscherber-2/pen/YzPvagv)) where setting to `null` and then setting the value to what would have been the default doesn't update the UI. That defect appears to be resolved in 3.1.0 ([CodePen](https://codepen.io/jgscherber-2/pen/zYxajRW)) but we use that pattern occasionaly in our code and if it's wrong I want us to stop using it.

Thanks

**Comment by jgscherber** [comment]
For reference [this StackOverflow ](https://stackoverflow.com/questions/8137222/knockoutjs-clear-selected-value-in-combobox)says setting to `null` is the solution, but another answer says that it doesn't work always - which cases does it not work?

**Comment by fastfasterfastest** [comment]
> I wasn't able to find any clear description of what the expected behavior for setting an options binding value to `null`.

I think the answer is at https://knockoutjs.com/documentation/value-binding.html which says:
> ... what happens if you set the model value to something that has no corresponding entry in the list? The default behavior is for Knockout to overwrite your model value to reset it to whatever is already selected in the dropdown, thereby preventing the model and UI from getting out of sync.

You are setting the model value to `null`.  `null` is not one of the values in the array you have specified in the `options` binding, thus Knockout will overwrite the model value and reset it to the currently/already selected in the dropdown, which is `"twoKey"`.

**Comment by fastfasterfastest** [comment]
> setting an options binding value to `null`.

By the way, just to make sure we are on the same page here... in your CodePen examples you are not setting the `options` binding value to `null` - you are setting the model value that the `value` binding is bound to to `null`.

**Comment by jgscherber** [comment]
Ah thank you. Yes, that is what I was talking about. I'm not always sure on the terminology
