### ISSUE TITLE
Too many items rendered in if - foreach - template

### ISSUE THREAD

**Issue by pflaska** [knockout/knockout#2514]
See the example:
https://codepen.io/pflaska/pen/NWqKwwy

Starting from second item, every other is duplicated. Duplicates are rendered in opposite order. Moreover, the exception occurs when trying to remove some item.

There are ways how to rewrite html ko comments and model to handle the situation and make it work again properly. This is happening in 3.5.0/1.

**Comment by Standa666** [comment]
this is regression from 3.4.0 and it seems it happens only template consist of name+if+foreach:
https://codepen.io/Standa666/pen/poJzqGJ?editors=1010

**Comment by mbest** [comment]
Thanks for the report. I'm glad you found a workaround. I'll take a look soon.

**Comment by mbest** [comment]
I've fixed the problem with the above commit. Note, though, that including such an `if` condition negates the performance benefits you get normally from `foreach` using optimized `arrayChange` events.
