### ISSUE TITLE
Apply bindings multiple times to the same element.

### ISSUE THREAD

**Issue by mehdi123** [knockout/knockout#2516]
Hello,

I've recently upgraded knockout.js to 3.5.1 version and got the following error:

Uncaught Error: Unable to process binding "with: function(){return parent }"
Message: You cannot apply bindings multiple times to the same element.
    at applyBindingsToNodeInternal (knockout.debug.js:3620)
    at applyBindingsToNodeAndDescendantsInternal (knockout.debug.js:3573)
    at applyBindingsToDescendantsInternal (knockout.debug.js:3555)
    at applyBindingsToNodeAndDescendantsInternal (knockout.debug.js:3576)
    at applyBindingsToDescendantsInternal (knockout.debug.js:3555)
    at applyBindingsToNodeAndDescendantsInternal (knockout.debug.js:3576)
    at applyBindingsToDescendantsInternal (knockout.debug.js:3555)
    at applyBindingsToNodeAndDescendantsInternal (knockout.debug.js:3576)
    at applyBindingsToDescendantsInternal (knockout.debug.js:3555)
    at Object.ko.applyBindingsToDescendants (knockout.debug.js:3789)

The html code snippet is:

            
              <div class="panel panel-success">
                <div class="panel-heading">
                  <h4 class="panel-title settings-header" data-bind="page-accordion-item: {id: 'general'}">
                    <a role="button" href="#!/settings/general"><i class="fa fa-cog"></i> General Settings
                    </a>
                  </h4>
                </div>...
....

I've added a print statement in the knocout.debug.js and found that the following tag:
< a role="button" href="#!/settings/general"><i class="fa fa-cog"></i> General Settings
                    < / a >"
is traversed twice!

Can anyone help me?

Thanks

**Comment by mehdi123** [comment]
This code works fine with 3.4.2 version.

**Comment by mehdi123** [comment]
I tried version 3.5.0 it also shows the same error on my code.

**Comment by bludev** [comment]
If you think the problem is due to a KO bug, you should prepare an example (jsfiddle) so that we can reproduce it.

**Comment by mbest** [comment]
Knockout is complaining about the `with: parent` binding being applied twice. Like @bludev said, it would help if we had a running example that reproduces the problem.

**Comment by mehdi123** [comment]
Hello.

Thanks for your messages. 
I found that the problem is due to the tag and not the KO:
<h4 class="panel-title settings-header" data-bind="page-accordion-item: {id: 'general'}">

In the 'page-accordion-item' binding I am calling pager.js init function in which it calls 
ko.applyBindingsToDescendants(page.childBindingContext, page.element);

Since in the upper level, 'with: parent' has been applied, the above ko.applyBindingsToDescendants throws the exception.

I am going to patch the pager.js library so that when a tag/node has bindings, it does not call apply bindings again.

Thanks for your comments. It helped.

Regards
Mehdi

**Comment by mehdi123** [comment]
Hello.

Thanks for your messages. 
I found that the problem is due to the tag and not the KO:
<h4 class="panel-title settings-header" data-bind="page-accordion-item: {id: 'general'}">

In the 'page-accordion-item' binding I am calling pager.js init function in which it calls 
ko.applyBindingsToDescendants(page.childBindingContext, page.element);

Since in the upper level, 'with: parent' has been applied, the above ko.applyBindingsToDescendants throws the exception.

I am going to patch the pager.js library so that when a tag/node has bindings, it does not call apply bindings again.

Thanks for your comments. It helped.

Regards
Mehdi

**Comment by mehdi123** [comment]
I should use dataFor function to check whether a node has bindings?

**Comment by mbest** [comment]
`ko.contextFor` will work for your purposes.

**Comment by mehdi123** [comment]
Thanks for your help 
Regards
