### ISSUE TITLE
Issue with bindingContext property not existing at startup

### ISSUE THREAD

**Issue by ChelloApps** [knockout/knockout#2517]
I have inherited some code that works with 3.4.2 of knockout but after upgrading to 3.5.1 fails due to an attempt to add a custom function into the prototype at startup of the app.

The actual code snippet which is run during the app startup is as follows: -

```
var ko = require('knockout');
var ui = require('common/ui');
var defaultBindingContext;

defaultBindingContext = ko.bindingContext;

ko.bindingContext = function bindingContext() {
    defaultBindingContext.apply(this, arguments);
    this.$localize = ui.localize;
};

ko.bindingContext.prototype = defaultBindingContext.prototype;
```
ko.bindingContext exists when running against 3.4.2 but is undefined using 3.5.1 has some thing changed to impact this approach?

For clarifty the $localize function is then used with templates like so: -

```
<span data-bind="text: $localize('Menu', 'Header.Menu')"></span>
```

**Comment by mbest** [comment]
I don't think `ko.bindingContext` was ever exposed. If you want to extend the binding context, Knockout 3.5 has a new way to do that:

```js
ko.applyBindings(viewModel, element, function (rootContext) {
    /* do what you need with the content */
});
```

See  #2024

**Comment by ChelloApps** [comment]
Ah the chap must have hacked it in, I'll take a look at your suggestion but that looks like I'm going to need to change every applyBindings function call in some way, but if it works I'm a happy bunny!

**Comment by mbest** [comment]
You could use a similar method to override the `ko.applyBindings` call:

```js
var originalApplyBindings = ko.applyBindings;

ko.applyBindings = function (vm, node, extendCallback) {
    return originalApplyBindings(vm, node || document.body, function (context) {
        if (extendCallback) {
            extendCallback(context);
        }
        /* do what you need with the context */
    });
};
```

**Comment by ChelloApps** [comment]
Thanks for that help @mbest I really appreciate it, your solution resolved my issue perfectly.
