### ISSUE TITLE
Component data-bind="value" forces change + `subscribe`  to fire

### ISSUE THREAD

**Issue by alvarotrigo** [knockout/knockout#2524]
I don't quite understand why when we use a component element with an input that contains the binding `value`, then the variable asociated to that value gets changed and the `subscribe` method gets triggerd.

Here's an example. Why is the subscribe being fired and why does the `selectedCountry` changes to UK?
https://jsfiddle.net/ryuo35ns/1/

Notice the UK is marked by default.

Now, if we instead of using a component we use a normal HTML data-binging, we have this:
https://jsfiddle.net/ryuo35ns/2/

None selected by default.

**Comment by bludev** [comment]
You should add the `optionsCaption: 'Choose...'` even in select inside the component.

https://jsfiddle.net/q1mdn7h0/

**Comment by alvarotrigo** [comment]
Omg! What a silly mistake :D
Thanks for pointing it out @bludev !!

**Comment by mbest** [comment]
Another option is to add `valueAllowUnset: true`: https://jsfiddle.net/mbest/72sarzkb/1/

**Comment by alvarotrigo** [comment]
@mbest thanks! That's a good one too! Specially when we will pre-fill that by default once the element is shown on the screen.
