### ISSUE TITLE
Use document.documentMode before conditional comments and user agent check to detect IE 8+

### ISSUE THREAD

**Issue by jcfizzler** [knockout/knockout#2529]
I ran into an issue where the IE version/capabilities were being detected incorrectly. I am developing for a desktop environment which uses the WebBrowser IE control. This is a somewhat quirky control, where the document mode and IE rendering version are determined by a `<meta>` header tag. This allows you to change the actual IE document mode and rendering version, but the user agent is not updated. In my case, I'm using the most recent installed version of IE on the machine, which for our clients is IE 11, by setting the tag as follows: `<meta http-equiv="X-UA-Compatible" content="IE=edge">`. This makes IE use IE 11 rendering and feature support but the User Agent string is not changed (still says it's IE 7). This caused Knockout to throw this error in `registerEventHandler `for the `propertychange `event because IE 11 doesn't support the `attachEvent `function anymore:

> "Browser doesn't support addEventListener or attachEvent"

I ended up fixing this locally by relying on the `document.documentMode` property, which is supported from IE 8 and beyond. Specifically I ran into this in the `textInput` binding, so I made the following changes:

```
    (operaVersion = window.opera && window.opera.version && parseInt(window.opera.version()))
        || (edgeVersion = parseVersion(userAgent.match(/Edge\/([^ ]+)$/)))
        || (chromeVersion = parseVersion(userAgent.match(/Chrome\/([^ ]+)/)))
        || (safariVersion = parseVersion(userAgent.match(/Version\/([^ ]+) Safari/)))
        || (firefoxVersion = parseVersion(userAgent.match(/Firefox\/([^ ]+)/)))
        || (ieVersion = document.documentMode || ko.utils.ieVersion || parseVersion(userAgent.match(/MSIE ([^ ]+)/)))      // Detects up to IE 10
        || (ieVersion = parseVersion(userAgent.match(/rv:([^ )]+)/)));      // Detects IE 11
```
This should of course be more performant and should mean that between this check and the conditional comment check, you don't need to rely on user agent parsing to figure out the browser version. You could even bake this into the logic for `ko.utils.ieVersion`.

**Comment by mbest** [comment]
See #2548
