### ISSUE TITLE
solving typescript compile error on subscribable.fn

### ISSUE THREAD

**Issue by linuschinsay** [knockout/knockout#2533]
i've pointed tsconfig to use the definition file in the build/types folder, when I try to extend the fn property like this `ko.observableArray.fn.myCustomMethod`, it says that myCustomMethod does not exists. What is the proper way of solving this compile error? I can do something like `(ko.observableArray.fn as any).myCustomMethod` but I don't think its the right way

**Comment by mbest** [comment]
See the example here: https://github.com/knockout/knockout/blob/master/spec/types/module/test-module.ts#L299

```
declare module "knockout" {
    export interface ObservableArrayFunctions<T> {
        filterByProperty(propName: string, matchValue: boolean): ko.Computed<any>;
    }
}
```
