### ISSUE TITLE
Template binding 3.5.1 regression: Empty string value throws error

### ISSUE THREAD

**Issue by slashslash** [knockout/knockout#2534]
3.5.0 Worked if an empty string was passed: https://jsfiddle.net/4nyr2k80/1/
3.5.1 Now throws an error and stops processing: https://jsfiddle.net/geh5uf39/1/

**Comment by mbest** [comment]
Thanks. A workaround is to use `template: { name: '' }`

**Comment by mbest** [comment]
Related: #2446
