### ISSUE TITLE
`value` binding resolved before `options`, causing some computed changes to get rejected.

### ISSUE THREAD

**Issue by tomtheisen** [knockout/knockout#2535]
When a `<select>` has `value` and `options` bindings defined, if a shared dependency updates them both simultaneously, the new option list won't be used to validate the choice.

## Reproduction

https://codepen.io/recursive/pen/wvMdYVE?editors=1011

### HTML

```
<ol>
  <li>Type some stuff in the text box.
  <li>Click the button.
  <li>Observe the different status reported.
</ol>
<input data-bind="textInput: pref">
<button data-bind="click: assign">assign</button>
<select data-bind="options: options, value: choice">
</select>

<p id=status>
```

### Javascript
```
const pref = ko.observable();
const model = {
  pref,
  options: ko.pureComputed(() => ["anything else", pref()]),
  choice: ko.observable(),
  assign: () => doAssign(pref()),
};

pref.subscribe(doAssign);

function doAssign(val) {
  model.choice(val);
  document.getElementById("status").innerText = `Attempted to set ${val}, actually was ${model.choice()}`;
}

ko.applyBindings(model);
```

**Comment by webketje** [comment]
Hmm seems to work properly like this (and more idiomatic):

HTML
```html
<ol>
  <li>Type some stuff in the text box.
  <li>Click the button.
  <li>Observe the different status reported.
</ol>

<input data-bind="textInput: pref">
<button data-bind="click: choice">assign</button>
<select data-bind="value: choice, options: options">
</select>

<p id=status data-bind="text: text">
```
JS
```js
const pref = ko.observable();
const options = ko.pureComputed(() => ["anything else", pref()]);
const choice = ko.pureComputed(pref)
const model = {
  pref,
  options,
  choice,
  text: ko.pureComputed(() => `Attempted to set ${choice()}, actually was ${choice()}`)
};

ko.applyBindings(model);
```

**Comment by tomtheisen** [comment]
The essential difference seems to be the lack of the explicit `subscribe()` call.  I suppose it's possible to express explicit subscriptions in terms of side-effects in computed observables, which may affect the resolution order.  I'll give that a try.

**Comment by tomtheisen** [comment]
I learned there's a binding called `valueAllowUnset`, that's able to solve my immediate problem more directly. 

https://knockoutjs.com/documentation/value-binding.html#using-valueallowunset-with-select-elements

**Comment by mbest** [comment]
@tomtheisen Congrats on finding a simple solution to the problem. Really the only reason `valueAllowUnset` isn't the default behavior is for backwards compatibility, but I think that unless you really need the old behavior that you use it.
