### ISSUE TITLE
afterMove / afterAdd callbacks in forEach trigger 3 times

### ISSUE THREAD

**Issue by alvarotrigo** [knockout/knockout#2536]
I would expect the `afterMove` and `afterAdd` callbacks to only fire once per new item added. However i always get 3 triggers. 

```html
<div data-bind="foreach: {data: items, afterMove: afterMove}">
     <div data-bind="text: $data">
     </div>
</div>
<button data-bind="click: addItem">Add item in the middle</button>
```

```js
 function viewModel(){
 	var self = this;
    self.items = ko.observableArray([1, 2, 3, 4]);
   
   
   self.afterMove = function(){
       console.log("after move...");
   }
   
   self.addItem = function(){
        self.items.splice(3, 0, 10000);
   };
   return self;
 }

 ko.applyBindings(new viewModel());

```

Link to isolated reproduction:
https://jsfiddle.net/dacn046p/

https://jsfiddle.net/dacn046p/1/

**Comment by webketje** [comment]
I've updated your fiddle to show 2 cases: https://jsfiddle.net/sy2qod0a/ with or without whitespace (=textNodes) between the parent foreach element, and the child element. Apparently Knockout also fires afterMove for all textNodes.

given `items` is a ko.observableArray holding 4 items, and an `items.unshift` is done, compare:

````html
<div data-bind="foreach: items"><div></div></div>
<!-- fires afterMove 4x -->
````
````html
<div data-bind="foreach: items">
  <div></div>
</div>
<!-- fires afterMove 12x ((2 textNodes + 1 element)  * 4) -->
````
The second definitely looks like unintended behavior.

**Comment by alvarotrigo** [comment]
> Similarly, if you pushed it at the end of the array, you would get 0 afterMove's, and 1 afterAdd.

Here's afterAdd firing 3 times by pushing an element at the end of the array. 
https://jsfiddle.net/dacn046p/1/

**Comment by mbest** [comment]
`afterMove`, etc. are called for each node, which includes text nodes. If you're not interested in doing anything with the text nodes, you can just skip them in your handlers.
