### ISSUE TITLE
Allow bindings to be declared as multiple attributes

### ISSUE THREAD

**Issue by Adilson** [knockout/knockout#2539]
When an element has multiple bindings (as visible, css, text,...) we end up with a large `data-bind` attribute. It would be better if it as possible to write these multiple binding as multiple attributes, almost as Angular works.

So, instead of:
```HTML
<div data-bind="css: {xpto: model.rule}, text: model.field, visible: model.rule2"></div>
```

We would may write:
```HTML
<div data-bind-css="xpto: model.rule" data-bind-text="model.field" data-bind-visible="model.rule2"></div>
```

**Comment by rniemeyer** [comment]
There may be other options out there, but a while ago I wrote a small plugin to help: https://github.com/rniemeyer/knockout-attributeBinder

By default, it would enable bindings like `data-text`, `data-foreach`, etc., but it allows you to override the prefix to be `data-bind` or `ko` or whatever you want. Hope that might help.

**Comment by fastfasterfastest** [comment]
I _think_ you could accomplish that by implementing a [_node preprocessor_](https://knockoutjs.com/documentation/binding-preprocessing.html#preprocessing-dom-nodes), see
https://jsfiddle.net/fastfasterfastest/dLhxzp0y

**Comment by webketje** [comment]
Or simply in your VM:

```js
model.bindings = {
  css: { xpto: model.rule },
  text: model.field,
  visible: model.rule2
}
```

Then in the template:

```html
<div data-bind="bindings"></div>
```

**Comment by mbest** [comment]
Also check out my plugin https://mbest.github.io/knockout.punches/ which lets you bind many attributes directly.
