### ISSUE TITLE
Knockout can be 2.2 KB smaller

### ISSUE THREAD

**Issue by praisedpk** [knockout/knockout#2541]
I have added Knockout on PageCDN. Current size of `knockout-latest.min.js` on PageCDN is just 21.9 KB that is around 2.18 KB smaller than normal due to better compression. The files are available on CDN here: https://pagecdn.com/lib/knockout

Adding this CDN link on downloads page is helpful for users looking to reduce JS size.

Thanks.

**Comment by praisedpk** [comment]
Here are the files used in this comparison:
````
https://pagecdn.io/lib/knockout/3.5.1/knockout-latest.min.js
https://cdnjs.cloudflare.com/ajax/libs/knockout/3.5.1/knockout-latest.min.js
````

**Comment by the-djmaze** [comment]
Using brotli yourself it can be even smaller.
[knockout.min.js.br.zip](https://github.com/knockout/knockout/files/5486642/knockout.min.js.br.zip)
