### ISSUE TITLE
Additional arrayChanges for ObservableArray items swap if the items are not adjacent

### ISSUE THREAD

**Issue by anton-kanashkin** [knockout/knockout#2542]
Knockout 3.5.1

If I swap two items of an observable array which are not adjacent (i.e. there a few items between them), my `arrayChange` handler gets four changes:

```JavaScript
const a = ko.observableArray(['a', 'b', 'c']);
a.subscribe(arrayChanges => console.log(arrayChanges), null, "arrayChange");
a.valueWillMutate();
const from = 0;
const to = 2;
const temp = a()[from];
a()[from] = a()[to];
a()[to] = temp;
a.valueHasMutated();
```

```JavaScript
0: {status: "added", value: "c", index: 0, moved: 2}
1: {status: "deleted", value: "a", index: 0, moved: 2}
2: {status: "added", value: "a", index: 2, moved: 0}
3: {status: "deleted", value: "c", index: 2, moved: 0}
```

The observable array's contents are as expected:

```JavaScript
["c", "b", "a"]
```

If I understood correctly, these two pairs of changes effectively "undo" each other. The first pair is about my actual swap, and the second pair is about an opposite swap, which hasn't been executed by me. After the swap observable array's content is as expected - two items have been swapped.

However, for if I swap two adjacent items, there only two changes in `arrayChange` handler, as expected:

```JavaScript
const a = ko.observableArray(['a', 'b', 'c']);
a.subscribe(arrayChanges => console.log(arrayChanges), null, "arrayChange");
a.valueWillMutate();
const from = 0;
const to = 1;   // this has been changed from 2 to 1, so the two adjacent items will be swapped
const temp = a()[from];
a()[from] = a()[to];
a()[to] = temp;
a.valueHasMutated();
```

```JavaScript
0: {status: "added", value: "b", index: 0, moved: 1}
1: {status: "deleted", value: "b", index: 1, moved: 0}
```

I found this behavior in the first case strange and it breaks up my event handling for the swap. I expect that the array changes should be the same for the items swaps no matter if they next to each other or not.

**Comment by SContent44** [comment]
> If I understood correctly, these two pairs of changes effectively "undo" each other. The first pair is about my actual swap, and the second pair is about an opposite swap, which hasn't been executed by me. After the swap observable array's content is as expected - two items have been swapped.

No, all four are about moving the items. You should think of the _deleted_ item indexes as referring to the original array `['a', 'b', 'c']` and the _added_ item indexes as referring to the new array `['c', 'b', 'a']`.

### Non-adjacent
```javascript
0: {status: "added", value: "c", index: 0, moved: 2}
1: {status: "deleted", value: "a", index: 0, moved: 2}
2: {status: "added", value: "a", index: 2, moved: 0}
3: {status: "deleted", value: "c", index: 2, moved: 0}
```

I'm not fond of this mental model but for the purpose of thinking about these changes you can think of the "deleted" values as being removed from the original array to make a transitional array then the "added" items being inserted

`['a', 'b', 'c']` -> `['b']` ->  `['c', 'b', 'a']`

### Adjacent
The difference in behaviour between when you are swapping adjacent items is that it only needs to move 1 of the adjacent items to achieve the swap.

```javascript
0: {status: "added", value: "b", index: 0, moved: 1}
1: {status: "deleted", value: "b", index: 1, moved: 0}
```
So all the only "change" that needed to happens is to remove the item at index[1] in the original array and add a new item in the new array at index[0]

`['a', 'b', 'c']` -> `['a', 'c']` ->  `['b', 'a', 'c']`

**Comment by anton-kanashkin** [comment]
> > If I understood correctly, these two pairs of changes effectively "undo" each other. The first pair is about my actual swap, and the second pair is about an opposite swap, which hasn't been executed by me. After the swap observable array's content is as expected - two items have been swapped.
> 
> No, all four are about moving the items. You should think of the _deleted_ item indexes as referring to the original array `['a', 'b', 'c']` and the _added_ item indexes as referring to the new array `['c', 'b', 'a']`.
> 
> ### Non-adjacent
> ```js
> 0: {status: "added", value: "c", index: 0, moved: 2}
> 1: {status: "deleted", value: "a", index: 0, moved: 2}
> 2: {status: "added", value: "a", index: 2, moved: 0}
> 3: {status: "deleted", value: "c", index: 2, moved: 0}
> ```
> 
> I'm not fond of this mental model but for the purpose of thinking about these changes you can think of the "deleted" values as being removed from the original array to make a transitional array then the "added" items being inserted
> 
> `['a', 'b', 'c']` -> `['b']` -> `['c', 'b', 'a']`
> 
> ### Adjacent
> The difference in behaviour between when you are swapping adjacent items is that it only needs to move 1 of the adjacent items to achieve the swap.
> 
> ```js
> 0: {status: "added", value: "b", index: 0, moved: 1}
> 1: {status: "deleted", value: "b", index: 1, moved: 0}
> ```
> 
> So all the only "change" that needed to happens is to remove the item at index[1] in the original array and add a new item in the new array at index[0]
> 
> `['a', 'b', 'c']` -> `['a', 'c']` -> `['b', 'a', 'c']`

Thanks a lot, now I understand what is going on here. Adjusted my code so that it removes the items at first and then adds them back at new places.

Closing this issue.

**Comment by mbest** [comment]
It usually is easier to first handle the deletes and then the adds. That's what I did in my Isotope binding: https://gist.github.com/mbest/7577891

On the other hand, Knockout's own `foreach` binding just goes through the changes in order: https://github.com/knockout/knockout/blob/master/src/binding/editDetection/arrayToDomNodeChildren.js#L99
