### ISSUE TITLE
Option to set "this" when using "foreach" binding's "as" and "noChildContext" options

### ISSUE THREAD

**Issue by rouacke** [knockout/knockout#2543]
I'm converting some templates to use the `foreach` binding's `as` and `noChildContext` options. I found that the value of `this` doesn't correspond to the `as` object: instead, it corresponds to `$data`. I probably shouldn't have been surprised by this behavior as it seems consistent. Regardless, it makes the conversion more difficult and results in more verbose templates: every event handler needs an extra call to `bind`.

This does not behave as I expected:

```
<ul data-bind="foreach: { data: children, as: 'child', noChildContext: true }">
  <li data-bind="text: child.name, click: child.click"></li>
</ul>
```

This works:

```
<ul data-bind="foreach: { data: children, as: 'child', noChildContext: true }">
  <li data-bind="text: child.name, click: child.click.bind(child)"></li>
</ul>
```

Note the addition of `.bind(child)`.

I put together a Fiddle to demonstrate:

https://jsfiddle.net/Lpdve6bu/2/

Changing the behavior would probably be inconsistent and would certainly be a breaking change. It would be swell, however, if we could set `this` to correspond to the `as` object in the `foreach` binding.

```
<ul data-bind="foreach: { data: children, as: 'child', noChildContext: true, thisAsItem: true }">
  <li data-bind="text: child.name, click: child.click"></li>
</ul>
```

Hypothetically, the `click` method would be called with `this` set to `child`.

**Comment by SContent44** [comment]
I might be confused but isn't the whole purpose of `noChildContext: true` is that it does not change the context to bind to and only sets the name of the current item?

If you set `noChildContext: false` (which is the current default behaviour) you will have the context bound to the child and this will work as you expected?

**Comment by rouacke** [comment]
> ...isn't the whole purpose of `noChildContext: true` is that it does not change the context to bind to and only sets the name of the current item?

I've read the release notes and the linked issue: I honestly don't know the answer to this question. I was under the impression that the purpose of `noChildContext: true` is to prevent Knockout from _creating_ a child context, which has a cost and is usually unnecessary. Changing `this` seems like a consequence.

I think there are two somewhat orthogonal behaviors:

1. Creating a child context.
2. Binding `this`.

By default, Knockout creates a child context and changes the `this` binding. Setting `noChildContext: true` prevents Knockout from creating a child context and changing the `this` binding. It _seems_ to me that one flag affects both behaviors.

That's fair and reasonably consistent: I'm not arguing otherwise.

Nevertheless, I was confused by the behavior. I've updated the demo to try to better illustrate why I was confused:

https://jsfiddle.net/e1ogLmvd/2/

The "foreach noChildContext as" example does not behave as I expected it to. I expected it to behave the same as the other examples. Maybe my confusion has more to do with `as` than with `noChildContext`. I don't know, but I guess I'm still confused.

In any case, I've found that converting templates to use `noChildContext: true` requires peppering the templates with `.bind(child)`. This is undesirable as it convolutes the templates.

**Comment by SContent44** [comment]
It seems like it is just defaulted to the common use case of using the current $data context. 

From the [event binding](https://github.com/knockout/knockout/blob/master/src/binding/defaultBindings/event.js)

```javascript
// Take all the event args, and prefix with the viewmodel
var argsForHandler = ko.utils.makeArray(arguments);
viewModel = bindingContext['$data'];
argsForHandler.unshift(viewModel);
handlerReturnValue = handlerFunction.apply(viewModel, argsForHandler);
```

Anyways while having a look around because this all sounded familiar I remembered some notes about this in the knockout.punches plugin.
- You could use the [knockout.punches plugin](https://mbest.github.io/knockout.punches/#wrapped-event-callbacks) which will wrap the callback in anonymous function for you so it can bind the correct `this`
- The plugin has a link to #378 which has a good discussion around the issue  include [this response 
](https://github.com/knockout/knockout/issues/378#issuecomment-4431277) that details some options in regard to binding the correct `this`.

**Comment by rouacke** [comment]
Thanks for the followup. Appreciate the consideration.
