### ISSUE TITLE
Prevent HTML flood when using IF ELSE kind of conditions

### ISSUE THREAD

**Issue by alvarotrigo** [knockout/knockout#2545]
This is what the HTML DOM looks like:
![image](https://user-images.githubusercontent.com/1706326/94003225-42c22780-fd9b-11ea-9f95-5565af9c50aa.png)

When I display this:
![image](https://user-images.githubusercontent.com/1706326/94003429-7ef58800-fd9b-11ea-9aee-30647e8b7ef9.png)

By using this code:
```html
<div data-bind="foreach: items">
     <!--ko if: type === 'text' -->
         <input type="text" value="afadsfa"/>
     <!-- /ko -->
     
     <!--ko if: type === 'button' -->
         <input type="submit" value="submit"/>
     <!-- /ko -->
</div>
```

```js
 function viewModel(){
 	var self = this;
        self.items = [
             {type: 'text'},
             {type: 'button'}
        ]
   
       return self;
 }

 ko.applyBindings(new viewModel());
``` 

Reproduction online:
https://jsfiddle.net/89r5s0fd/

Any way to prevent this ugly DOM full of unnecessary comments / code?
I can do the same with `<div>` elements but then I end up with empty div elements all over as well.

**Comment by Standa666** [comment]
I guess, that this code is correct. 
The "ko if" transparently resolves not only plain values but also values in observable. If you switch the observable value the knockout model will react on such change and update DOM.

If there will be dropped empty comments, then there will be lost the place where the new content will be rendered.

**Comment by alvarotrigo** [comment]
So there's now to improve this somehow and get rid of all the unnecessary HTML comments or nodes?

**Comment by Standa666** [comment]
What I am trying to say is, that this is not bug, it is intentional and there is nothing to improve.

**Comment by webketje** [comment]
@alvarotrigo it is indeed clumsy, but it's the way Knockout's templating works I suppose (if Knockout doesn't keep the template specs in memory like, e.g. Vue does, the full template needs to be available in the DOM at all times).

For your example though, there is a cleaner alternative using the [component](https://knockoutjs.com/documentation/component-binding.html) binding:

````js
ko.components.register('button', {
  template: '<input type="submit" value="submit"/>'
});
ko.components.register('text', {
  template: '<input type="text" value="asdf"/>'
});
ko.applyBindings({
  type: 'text' // default type
}, document.body);
````

In your HTML you could do:

````html
<div data-bind="component: type"></div>
````

**Comment by mbest** [comment]
Since Knockout uses the DOM and comment nodes, there's no way to keep track of conditional rendering without them. Perhaps, in the case where a comment-based binding is rendered that doesn't access observables, we could remove the nodes.
