### ISSUE TITLE
A method to defer updates of observable till a particular event happens.

### ISSUE THREAD

**Issue by dsaw** [knockout/knockout#2553]
I have an observable which tracks the value of a custom search component. The custom component consists of a select2 input and an ellipsis button that opens a dialog to select the same items (an alternative flow to the select2). 
There are specific subscriptions on the value of the observables which among other things sets the select2 data value manually. (The custom component is used in multiple modules & turns out this manual setting isn't needed anywhere else) 
```
customCompObser.subscribe((newValue) => {
    // other stuff.
    let val = $('#select2Input').select2('data');
    // use val for comparing with new value etc
    $('#select2Input').select2('data', {value:'etc'});
})
```
The subscriber is set to null or a particular value **before the whole select2 is getting initialized since the component is loaded asynchronously**. Thus, the select2 data is null at that point.

I tried to tackle it by using `afterRender` callback & setting the data again here.
```
componentVM.afterRender = () => {
  if (customCompObser() === null) {
      // set select2 manually again
  }
 else {
    // retrigger subscription using valueHasMutated
}
}
```

This kind of works, but is hacky and probably will cause side effects.

Is there a way to defer the updates of the observable till some event is finished, say render of component is complete?
That would be much cleaner I think.

**Comment by mbest** [comment]
In general, Knockout is designed to use a binding to connect an observable to something in the view. Thus you should not be setting DOM values in a subscribe function, unless that subscribe function is in a binding. In the binding, any waiting, subscribing to events, etc. is fair game in order to correctly link the observable to the view.
