### ISSUE TITLE
Style binding is not working

### ISSUE THREAD

**Issue by harakiri-cat** [knockout/knockout#2554]
Documentation:
https://knockoutjs.com/documentation/style-binding.html

Code:
https://jsfiddle.net/5xnL8sa1/

Image:
![image](https://user-images.githubusercontent.com/1329901/101634530-868b0b80-3a31-11eb-9c84-b06646669ffd.png)

**Comment by rniemeyer** [comment]
@harakiri-cat - to apply Knockout to your page, you need to call `ko.applyBindings(viewModel);`  in your case. Then, the bindings will be active. Here is it added to your page https://jsfiddle.net/noL7xge1/. Here is a link with some additional info from the docs: https://knockoutjs.com/documentation/observables.html#activating-knockout. Thanks!
