### ISSUE TITLE
In beforeRemove callback, index is always 0

### ISSUE THREAD

**Issue by marcovdb** [knockout/knockout#2560]
When using the `beforeRemove` callback with the foreach binding, the supplied index parameter is always 0. Bug seems to have been introduced with KO 3.5.0 Beta; it wasn't present in 3.4.2.

See here for reproduction: https://codepen.io/gxzzin/pen/KKNPKeO

**Comment by mbest** [comment]
You are correct that the "index" values changed between 3.4.2 and 3.5.0. But even in 3.4.2, they didn't match the index in the array but instead the index in the change list. In 3.5.0, we changed the `foreach` binding to use a "sparse" change list, which doesn't include "retained" items, so we didn't have a good way to maintain the existing "index" values. So, for 3.5.0 we simply redefined the "index" to mean the index into that particular type of action. Thus, the index for the first deleted item will be 0, the second, etc.
