### ISSUE TITLE
observableArray.removeAll() -> c is null

### ISSUE THREAD

**Issue by sirber** [knockout/knockout#2568]
![image](https://user-images.githubusercontent.com/3911428/116869612-08492480-abdf-11eb-9af1-03a9f46067c8.png)

**Comment by sirber** [comment]
![image](https://user-images.githubusercontent.com/3911428/116870068-d1274300-abdf-11eb-84bf-e2ef0d9e050f.png)

**Comment by sirber** [comment]
my code is at problem here, but a null check could be nice. or a (falsy) => [ ]

**Comment by mbest** [comment]
There was a discussion at one point about not allowing a null or undefined value for an observable array, but since it was a breaking change we decided against it. I think throwing an exception in this case is fine.
