### ISSUE TITLE
knockout not working with jquery 3.5.1 or 3.6.0 when it did with 3.4.1

### ISSUE THREAD

**Issue by cblaze22** [knockout/knockout#2569]
I tried to upgrade to jquery 3.5.1 and 3.6.0 and I get this error below on one of my pages that worked fine in jquery 3.4.1.  I am trying to pinpoint the issue currently but thought I'd post it here while I do that.

![image](https://user-images.githubusercontent.com/556494/117665501-e74d7a00-b170-11eb-83d7-1f9099e5d457.png)

> knockout-3.5.0.min.js:formatted:260 Uncaught TypeError: Cannot read property 'length' of undefined
>     at Object.fixUpContinuousNodeArray (knockout-3.5.0.min.js:formatted:260)
>     at tt (knockout-3.5.0.min.js:formatted:3796)
>     at h.utils.setDomNodeChildrenFromArrayMapping (knockout-3.5.0.min.js:formatted:3840)
>     at Object.ignore (knockout-3.5.0.min.js:formatted:1082)
>     at a (knockout-3.5.0.min.js:formatted:3630)
>     at r.beforeRemove.h.isObservableArray.h.dependentObservable.disposeWhenNodeIsRemoved (knockout-3.5.0.min.js:formatted:3639)
>     at Function.evaluateImmediate_CallReadThenEndDependencyDetection (knockout-3.5.0.min.js:formatted:1539)
>     at Function.evaluateImmediate_CallReadWithDependencyDetection (knockout-3.5.0.min.js:formatted:1524)
>     at Function.evaluateImmediate (knockout-3.5.0.min.js:formatted:1503)
>     at Function.evaluatePossiblyAsync (knockout-3.5.0.min.js:formatted:1486)

**Comment by cblaze22** [comment]
I dont know why but I had /> at the end of this select statement instead of ></select>.   Once I did that it worked fine.

**Bad**

` <select class="mr-1" data-bind="value: place, css: { hidden: !$parent.edit() }, optionsCaption: '- Place -', options: $root.members.divisionPools.places, optionsText: 'Key', optionsValue: 'Value'"/>`

**Good**

` <select class="mr-1" data-bind="value: place, css: { hidden: !$parent.edit() }, optionsCaption: '- Place -', options: $root.members.divisionPools.places, optionsText: 'Key', optionsValue: 'Value'"></select>`

**Comment by rambabueadara** [comment]
i'm also facing same issue.Can you help me..

**Comment by cblaze22** [comment]
Be careful, they changed stuff that will break older versions unfortunately.
