### ISSUE TITLE
options default/not selected value

### ISSUE THREAD

**Issue by yauhen** [knockout/knockout#257]
It seem to me it will be nice to have possibility to specify default value for not selected item (optionsCaption).
On current moment it is undefined according documentation.

 In many cases we don't want  this. for example in C# class I have not nullable property TemplateID. value 0 means no selected (I could not patch database and inside it field is not nullable and 0 is illegal value). So I want to use 0 as not selected. I have logic that serialize default (empty, just after calling new) object from C# to javascript. Then I have clear button on form. When pressing on it I would like to reset all controls to values in this default instance. But for select it is not possible as 0 !=== undefnined. Please note that in future I may change some default values. Making TemplateID in C# nullable seem to me not good. Because as I said in database field is not nullable. Here is short sample.

http://jsfiddle.net/yauhen/JJAyS/

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
