### ISSUE TITLE
Use Knockout on Replit

### ISSUE THREAD

**Issue by subtra3t** [knockout/knockout#2573]
How do I use Knockout.js on [Replit](https://replit.com/)? Simply linking the library does not seem to work.

**Comment by webketje** [comment]
Replit works with Node/NPM. You need to `npm init` (which will set up a package.json), then `npm i serve`, configure the `npm start` script to run `serve ./public`, create a `.replit` file like this one in the root dir: https://github.com/webketje/metalsmith-starter-resume/blob/master/.replit, and link the knockout script (e.g. from CDN) in your HTML file at `./public/index.html`

**Comment by subtra3t** [comment]
Thanks!
