### ISSUE TITLE
Is tko/ko4 compatible with punches?

### ISSUE THREAD

**Issue by jfrank14** [knockout/knockout#2592]
I'm a long time user of knockout, up to version 3.x. I'm trying to decide on a MVVM library for a new project and I would like to use tko/ko4, but I can't tell if it's compatible with or perhaps even includes ko.punches. I like the basic philosophy of knockout much more than any of the alternatives, but only when using punches; without it, the parentheses and property setter syntax is just too cumbersome for me. 

So can you use punches with tko? Is there an updated version of punches that you need, or is it already included in tko?

**Comment by mbest** [comment]
Perhaps this question is better asked at [knockout/tko](https://github.com/knockout/tko)?
