### ISSUE TITLE
Question: Event handler function expressions - alternative to bind?

### ISSUE THREAD

**Issue by Jan-Thes** [knockout/knockout#2593]
Hello,

up until now we have been using `bind` to create functions for event bindings with the specific arguments like this:
```js
function my_drag(event, arg1, arg2) {..}
```
```html
<div draggable='true' data-bind="event: {
    dragstart: my_drag.bind(null, event, $data.arg1, $data.arg2)
}">
```

However **this effectively creates bugs when combined with optional parameters**. For example, if we redefine `my_drag` to:
```js
function my_drag(event, arg1, arg2, arg3_optional) {..}
```

We now have a bug. The reason is that `bind` will create a new function that passes its own arguments into the original function because `bind` implements partial application of parameters / currying. Since knockout then passes `$data, event` to the result of `bind`, this means that `$data` gets passed as `arg3_optional` to `my_drag` even though we did not want to pass anything.

---
Solutions / Workarounds:

A) Use function declaration instead of `bind`:
```html
<div draggable='true' data-bind="event: {
    dragstart: function(data, event) { return my_drag(event, $data.arg1, $data.arg2) }
}">
```

B) Simply don't use optional arguments for any event handlers or always pass `undefined` to optional parameters (this is of course easy to forget and hard to enforce):
```html
<div draggable='true' data-bind="event: {
    dragstart: my_drag.bind(null, event, $data.arg1, $data.arg2, undefined)
}">
```

C) Use my own alternative to bind that does not implement partial currying:
```js
// use like: event: { dragstart: my_drag.wrap(null, event, $data.arg1, $data.arg2) }
Function.prototype.wrap = function(thisObject, ...args) {
	return () => this.call(thisObject, args);
}
```
---
My questions:
- I think that A) would be ideal if i could use arrow function syntax to make it shorter, but i think data-bind does not support that syntax, right? Does TKO support this?
- I think that C) should work, but it does not seem to (no error, but neither `wrap` nor `my_drag` is called). Did i do something wrong or does data-bind only support `bind` for function expressions?

And maybe it would be a good to warn about this problem in the documentation, where 'bind' is mentioned.

**Comment by mbest** [comment]
[TKO](https://github.com/knockout/tko), the successor to Knockout, supports arrow functions. You can also check out [Knockout.Punches](https://github.com/mbest/knockout.punches)
