### ISSUE TITLE
knockout.js 3.5 not working with ratelimit and arrayChange for same element

### ISSUE THREAD

**Issue by cblaze22** [knockout/knockout#2597]
Any help on this answer?

https://stackoverflow.com/questions/73307951/knockout-js-3-5-not-working-with-ratelimit-and-arraychange-for-1-element

**Comment by mbest** [comment]
The SO answer is correct. If you make a change to an array and then immediately undo it, the change detection will see that nothing changed and won't notify the subscribers.
