### ISSUE TITLE
Only run visible/hidden binding once on init

### ISSUE THREAD

**Issue by josh08h** [knockout/knockout#2603]
I'd like to run the default `hidden` KO binding once when knockout renders my template. [According to the documentation ](https://knockoutjs.com/documentation/visible-binding.html) you can pass in a non-observable as the first param and updates should no longer be applied if the model value changes.

Looking at the code here https://github.com/knockout/knockout/blob/master/src/binding/defaultBindings/visibleHidden.js I don't think that is the case.

Please can someone advise how I can invoke the `hidden` and `visible` handlers only once and ignore future updates to the model?

Thanks

**Comment by fastfasterfastest** [comment]
Please provide a simple, complete sample (e.g. at [jsfiddle.net](https://jsfiddle.net/)) showing the issue.

**Comment by mbest** [comment]
I you do something like this `data-bind="hidden: someNonObservable"`, it will initialize based on the value of `someNonObservable`, but there's nothing to trigger the binding later, so it won't change.
