### ISSUE TITLE
Browser doesn't support addEventListener or attachEvent on propertychange binding

### ISSUE THREAD

**Issue by jeanie77** [knockout/knockout#2606]
I've just updated from knockout 3.4.2 to the latest 3.5.1.
Unfortunately I'm getting this error on _propertychange_ binding: "Browser doesn't support addEventListener or attachEvent".
```
<input id="txtDesc" class="form-control form-control-sm" 
       data-bind="value: $root.element.description,valueUpdate:['afterkeydown','propertychange','input']">
```
It seems that the odd behaviour is caused by this change:
```
var eventsThatMustBeRegisteredUsingAttachEvent = { 'propertychange': true }; // Workaround for an IE9 issue - https://github.com/SteveSanderson/knockout/issues/406

var mustUseAttachEvent = ieVersion && eventsThatMustBeRegisteredUsingAttachEvent[eventType];    // ko 3.4.2 
var mustUseAttachEvent = eventsThatMustBeRegisteredUsingAttachEvent[eventType];                 // ko 3.5.1
```

As you can see, in the latest version there is no _ieVersion_ check so _mustUseAttachEvent_ on "propertychange" is always true and knockout tries to register event using _attachEvent,_ instead of _addEventListener,_ hence the error.

I'm wondering why this error never happened to others during these 4 years and if this library is still maintained.
Maybe i'm using an obsolete binding event? Can someone suggest me how to proceed? Thanks a lot!

This issue is related to the fix: https://github.com/knockout/knockout/issues/406

**Comment by jeanie77** [comment]
Investigating on _propertychange_ event, I've found a reasonable solution. 

Quoting from comments inside knockout:
> Internet Explorer <= 8 doesn't support the 'input' event, but does include 'propertychange' that fires whenever
> any property of an element changes.

So _propertychange_ is a IE only event and it should be removed from _valueUpdate_ binding:
```
valueUpdate:['afterkeydown','propertychange','input']"
valueUpdate:['afterkeydown','input']"
```

**Comment by mbest** [comment]
In general, if you need the observable updated on each keypress, you should use the `textInput` binding, which intelligently handles different browser quirks.

**Comment by jeanie77** [comment]
Thank you, it seems better indeed. The problem is that i'm using the parameter valueUpdate also for custom binder. Anyway, i'll have a try!
