### ISSUE TITLE
learn.knockoutjs.com is offline.

### ISSUE THREAD

**Issue by parasparmar** [knockout/knockout#2607]
@mbest , Hi Michael,

I just wanted to inform you that when I visited my favourite section of the knockoutjs site, I found a "Page Not Found" message. I hope that this is something worth looking into. It has saved my life over the years. I hope to still train a few devs to use KO and be able to get them to do something useful in under an hour using your excellent series of learning tasks at the url below.

url : [http://learn.knockoutjs.com](http://learn.knockoutjs.com) 

And for those who ask: Does KO have a future, rest assured it does.

**Comment by mbest** [comment]
I reached out to Steve Sanderson, who has the code for that site. It looks like the hosting provider shut down, so we'll try to find a new home for it.

**Comment by parasparmar** [comment]
https://learn.knockoutjs.com/#/?tutorial=intro is back online. Much appreciated. Thank you so much @mbest. Closing the issue as resolved.
