### ISSUE TITLE
Containerless control flow escaped by Go proxy

### ISSUE THREAD

**Issue by cblaettl** [knockout/knockout#2610]
I have a Go reverse proxy running in front of a knockout.js application.
The Go proxy uses the [`go/x/net/html`](https://pkg.go.dev/golang.org/x/net@v0.22.0/html) package to parse, analyze and render html content passing though it. 
This leads to the following comment beeing escaped.

This control flow comment
```html
<!-- ko if: !hasMessages() && displayTabbed() --><!-- /ko -->
```
is escaped to
```html
<!-- ko if: !hasMessages() &amp;&amp; displayTabbed() -->
```
which breaks the application with the following error message:
```
Uncaught SyntaxError: Unable to parse bindings.
Bindings value: if: !hasMessages() &amp;&amp; displayTabbed() 
Message: expected expression, got '&'
```

I can't imagine I'm the first person to encounter an issue like this. But I couln't find a similar issue using the search function.

Is there a solution within the knockout.js library to solve or work around this?

Note that [`go/x/net/html`](https://pkg.go.dev/golang.org/x/net@v0.22.0/html) explicitly [mentions they _have to_ escape](https://cs.opensource.google/go/x/net/+/master:html/escape.go;l=201) every `&` in a comment (also see: https://github.com/golang/go/issues/58246).

**Comment by webketje** [comment]
I can think of 3 solutions to this:

- Storing the 2 conditions in JS
  ```js
  this.emptyTabbedDisplay = ko.computed(function() { return !this.hasMessages() && this.displayTabbed() }, this)
  ```
  then you can do:  `<!-- ko if: emptyTabbedDisplay -->`
- Using Knockout components loaded after initial page load with eg requirejs or in a  JS bundle (essentially bypassing the HTML Content-Type proxy filter by storing it as a string in JS)
- Keeping it on the initial HTML, but applying a preprocessing step to your page *before* Knockout is initialized, e.g.
  ```js
  const app = document.getElementById('app')
  app.innerHTML = app.innerHTML.replace(/%KOAND%/g, '&&')
  ko.applyBindings(...)
 ```

Then you could write it in your HTML like 
```html
<!-- ko if: !hasMessages() %KOAND% displayTabbed() --><!-- /ko -->
```

**Comment by cblaettl** [comment]
Hi @webketje, thanks for your quick reply!
Sadly, I'm not able to modify the code of the knockout.js app, since it's supplied by a third-party, so I guess I'm out of luck?

**Comment by mbest** [comment]
This seems like a bug in [go/x/net/html](https://pkg.go.dev/golang.org/x/net@v0.22.0/html) since HTML comments should not be escaped.
