### ISSUE TITLE
ko.utils.extend

### ISSUE THREAD

**Issue by michalporeba** [knockout/knockout#305]
the current ko.utils.extend implementation is very simle and when compared to jQuery.extend, one most of us is familiar with, it lacks two things:
- variable number of arguments, so it can be used like that ko.utils.extend(object1, object2, object3, {});
- deep option that will extend not only immediate properties but will work its way recursively down the tree

Don't you think it would be a good thing to improve that function? 
The reason I'm thinking about it is that such the functionality is very common need in any javascript project and even if not directly needed by knockout.js it would be a very handy addition to developers working with KO or developing plugins to KO. Especially the latter. Obviously simplicity and performance could be the reasons not to do so.

Tell me what you think. I can do the coding (adapt some other open source code) for that one.

**Comment by mika76** [comment]
I think adding a deep function could be quite useful, if only for helping people make plugins which don't depend on external utilities like jquery.
