### ISSUE TITLE
Is there any closure extern file for knockoutjs?

### ISSUE THREAD

**Issue by sriharshav** [knockout/knockout#311]
I am using Jquery and Knockoutjs in an embedded web application. I could get <a href="http://closure-compiler.googlecode.com/svn/trunk/contrib/externs/jquery-1.7.js">Jquery extern file</a>. Is there any similar one for ko?
I currently am using 2.0.

**Comment by lgandras** [comment]
@shalecraig: it's not about the properties being read by KnockoutJS, is about the functions and utility being used by compiled code. This ticket is indeed is about externs and not exports. You'll still need exports if your object's properties are _dot_ accessed in the compiled code, but that's a another matter.

**Comment by shalecraig** [comment]
Wow, I don't even remember opening this, but thanks for looping back.
