### ISSUE TITLE
Add $templateData to all contexts below a bound template

### ISSUE THREAD

**Issue by contentfree** [knockout/knockout#342]
It would be very useful to have another context variable called $templateData that always pointed to the data given in an ancestors template binding. For example, imagine this nested setup:
    
    <div data-bind="with: selectedView">
      <div data-bind="template: { name: templateName, data: data }">
        <div data-bind="foreach: rounds">
          <div data-bind="foreach: scores">

It would be useful and more readable to be able to, at this nested level, reference `$templateData.someVar` instead of `$parents[1].someVar`. The former tells you exactly where you're looking, as `$parent` and `$root` do. The latter can get you lost trying to track how many levels you're nested. And it (obviously) gets more complicated if you have additional markup interspersed between the foreachs.

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
