### ISSUE TITLE
Native Template Engine: foreach; templateOptions

### ISSUE THREAD

**Issue by troyji** [knockout/knockout#365]
This is a spin off of issue #246

In short, there is not way to pass additional arguments into a named template when using the 'foreach' binding.

Below is a use case for 'templateOptions'.  In particular, the workaround suggested in the issue above does not work for passing options while using 'foreach' instead of 'data'.  Imagine a tree of nodes where each node consists of an item and children.  We will use a recursive template to generate the tree.  The root binding would look like this:

```
data-bind="template: { name: 'nodeTemplate', data: rootNode }"
```

The template would render a node's children using this binding:

```
data-bind="template: { name: 'nodeTemplate', foreach: children }"
```

Now if we want to pass options for the root, we can do:

```
data-bind="template: { name: 'nodeTemplate', data: { node: rootNode, options: '...'}"
```

However, there is no way to pass additional options when using 'foreach'.

We could do this before like this:

```
data-bind="template: { name: 'nodeTemplate', foreach: children, templateOptions: '...' }"
```

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
