### ISSUE TITLE
API Inconsistencies

### ISSUE THREAD

**Issue by troyji** [knockout/knockout#366]
I have been using Knockout for some time and have noticed several inconsistencies across the API.  I recommend standardizing these items in order to accomplish a more polished feel and to reduce the learning curve.  Here are some of the more outstanding items.

## Keyword Case
Some multi-word bindings use lower case (e.g. 'foreach', 'ifnot', 'hasfocus'), while some use camel case (e.g. 'dependentObservable', 'selectedOptions', 'uniqueName').

## Binding Options
Some bindings take an optional options object (e.g. "template: { name: 'myTmpl', foreach: myList }") while others take multiple bindings as options (e.g. "options: myOpts, optionsCaption: 'My Capt', optionsText: 'Text'" ).

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
