### ISSUE TITLE
event binding: no way to return values

### ISSUE THREAD

**Issue by haberman** [knockout/knockout#385]
Some custom events use the return values from the event handler, for example the events in this jQuery drag-and-drop plugin: http://threedubmedia.com/code/event/drag

Knockout's "event" binding wraps the user's handler and doesn't pass the user's return value to the true handler.  "true" is handled specially to tell Knockout to allow the default handler, but could Knockout pass other return values through?

It's tricky finding a way to support this while still allowing the user to allow or cancel.  One possible solution that would be backward-compatible is:

```js
function handler1() {
  return true;  // Allows default, like now.
}

function handler2() {
  // Returns "val" to the actual handler, while allowing or preventing
  // the default, as specified (could default to not allowing it).
  return ko.ReturnValue({value: val, allowDefault: true});
}
```

**Comment by jods4** [comment]
Maybe consider this as a work-around: 

I usually wrap all my ui plugins into their own custom binding handlers. Something like this:
`<div data-bind="drag: /* whatever methods, options from your vm you need to pass */">`

Besides the other benefits of this approach, it implies that I would register the events manually inside the `drag` binding handler and have full control.

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
