### ISSUE TITLE
Multiple Binding Providers

### ISSUE THREAD

**Issue by gilesbradshaw** [knockout/knockout#392]
A limitation of Knockout is that you can only have one binding provider active at a time.  This makes it rather monolithic.  I might want to use it in the same application for completely different purposes with very different configurations.  I've modified it so it is capable of having multiple binding providers.  These can be versions of the default provider or completely new ones.

I've changed the existing binding provider so it can define its 'namespace'  - ie the 'ko' and the 'data-bind'.

Each binding provider stores its own set of binding contexts in the DOM.  This means that one binding can produce a binding for another namespace which then operates in a different binding context.

See this fiddle http://jsfiddle.net/GilesBradshaw/YcK7V/1/ for an example of using multiple providers the meta data is configuring fields in the data to be displayed.  So the ko-ns binding provider is producing a binding on a td tag that the ko-nss binding provider runs in a different context.  The way it uses the attribute binding to make a binding for the other provider is slightly odd this should be done with templating I should think but it is just meant as an illustration.

To do this with the existing knockout I am pretty sure you would have to do a lot of manipulation in your view model.

This concept could be extended so different binding providers could use different binding handlers, templating engines and any other swappable binding aspects.

I think that this would make knockout more powerful and it could be done in a backwardly compatible way.  The modified version passes all existing specs.

I've not done it as a plugin and I'm not sure that you could.

At the moment the code is a bit ropey and 'hacked' however if people thought this was a worthwhile avenue I'd be interested in re working it as a possible enhancement to knockout.

code is here https://github.com/GilesBradshaw/knockout

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
