### ISSUE TITLE
organize specs for "Binding attribute syntax"

### ISSUE THREAD

**Issue by mbest** [knockout/knockout#399]
There are currently 28 spec tests for "Binding attribute syntax" and it keeps growing. Let's look at how we can divide the tests into separate categories.

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
