### ISSUE TITLE
Closure Compiler Externs File

### ISSUE THREAD

**Issue by paultyng** [knockout/knockout#407]
This is the same as issue #311 (I can't reopen and original author doesn't seem to be).

Using closure compiler: http://closure-compiler.appspot.com/home

If you compile your own custom library similar to the following:

    // ==ClosureCompiler==
    // @compilation_level ADVANCED_OPTIMIZATIONS
    // @output_file_name test.js
    // ==/ClosureCompiler==
    
    var viewModel = {a: 1};
    
    ko.applyBindings(viewModel);

You get this output along with warnings:

    ko.b({a:1});

Instead using an externs file (I created a sample one, I can finish it up if you like and submit a pull):

    // ==ClosureCompiler==
    // @compilation_level ADVANCED_OPTIMIZATIONS
    // @output_file_name test.js
    // @code_url https://raw.github.com/paultyng/knockout/master/other/externs.js
    // ==/ClosureCompiler==
    
    var viewModel = {a: 1};
    
    ko.applyBindings(viewModel);

You get this output and no warnings:

    ko.applyBindings({a:1});

The use of the externs file is more for people consuming knockout who want to use closure compiler but not compile knockout in to their library.

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
