### ISSUE TITLE
Add ko.observableArray.fn.pushAll

### ISSUE THREAD

**Issue by johnpapa** [knockout/knockout#416]
I'd like to have a pushAll function added to observableArray that appends items to the array. The use case is for when I have a list of items and I want to poll the server for additional records without blowing away my observableArray. Another simpler use case is for when I want to add multiple selected items to another selectedItems array. If there is another way to do this and keep observability, I'm all for it. Currently I am adding this to my code, though:

ko.observableArray.fn.pushAll = function(valuesToPush) {
    var items = this;
    for (var i = 0, j = valuesToPush.length; i < j; i++) {
        items.push(valuesToPush[i]);
    }
    return items;
};

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
