### ISSUE TITLE
Options Binding Stops Click Bubble, breaks in Chrome

### ISSUE THREAD

**Issue by deltreey** [knockout/knockout#431]
See this chrome bug tracker http://code.google.com/p/chromium/issues/detail?id=7423
I'm not sure if it's to be considered more of a bug in chrome or in knockout, but I thought it might be important to be aware of.

The options binding in certain situations (floating div in the example linked) stop the bubbling of click events to the select box, so that google chrome (and safari) won't allow the user to make selections.  It works in IE (HAH!).

**Comment by mbest** [comment]
It appears the bug in Chrome is now fixed.
