### ISSUE TITLE
Knockout corrupting template HTML in IE7-8

### ISSUE THREAD

**Issue by danielcrisp** [knockout/knockout#450]
Knockout appears to be removing HTML from within <object> tags when attempting to embed Flash within a page.

I have set up a basic demo here, using exactly the same HTML embed method. The first video is within a Knockout foreach loop, the second is just straight HTML. The HTML within the Knockout loop doesn't have any data bindings.

http://labs.danielcrisp.com/knockout/

The Flash video embed code and videos are from http://mediaelementjs.com/ however for simplicity I have not included the javascript.

In all modern browsers I see both videos correctly, however in IE7 and IE8 (probably also IE6) the first video does not display. If you right-click in the white space you will see "Movie not loaded" in the context menu.

If you use F12 Developer Tools to inspect the HTML you will see that the `<param>` tags are not present within the `<object>`, however they are present in the second video's code.

Without the following element IE doesn't know where to find the SWF file:

`<param name="movie" value="flashmediaelement.swf" />`

It appears that Knockout is removing this element for some reason, but only in older versions of IE. IE9 appears to be fine.

I've tested this with Knockout 2.0.0 and 2.1.0rc2 and the bug is present in both.

Any ideas?

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
