### ISSUE TITLE
computed should be able to access its object through `this`

### ISSUE THREAD

**Issue by mbest** [knockout/knockout#451]
To allow setting up a view model using object literal notation:

```javascript
var vm = {
    obs1: ko.observable(),
    comp1: ko.computed(function() {
        return this.obs1() + 1;
    });
};
...
var a = vm.comp1();   // vm object will be passed to computed via `this`
```

This will only work if `deferEvaluation` is assumed when a `computed` observable is set up this way. One way around changing the default behavior of `computed` would be to use a different name, like `computedProperty`, that wraps `computed` and sets `deferEvaluation`.

The change to set `this` would be pretty simple:

```javascript
function dependentObservable() {
    if (!_hasBeenEvaluated && !evaluatorFunctionTarget)
        evaluatorFunctionTarget = this;
    if (arguments.length > 0) {
        set.apply(dependentObservable, arguments);
    } else {
        return get();
    }
}
```

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
