### ISSUE TITLE
Style bindings should infer units when absent

### ISSUE THREAD

**Issue by steveluscher** [knockout/knockout#455]
If you try to assign a unit-less value (say, an integer) to a CSS property through a Knockout style binding, Knockout won't apply the style. See http://jsfiddle.net/Ujp2Z/4/

**HTML:**
```html
<!-- Top and left do not get set because they're missing "px" -->
<div data-bind="style: {top: y, left: x}"></div>
```
**Javascript:**
```javascript
var viewModel = { x: ko.observable(50), y: ko.observable(50) };
ko.applyBindings(viewModel);​
```
When using unit-less values, I would prefer it if Knockout (like jQuery) assumed that you mean `{foo}px` when setting a CSS property that accepts a length, and perhaps even to assume `#{foo}` when using a string that matches `/^([0-9a-f]{1,2}){3}$/i` to set a CSS property that accepts a color.

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
