### ISSUE TITLE
ie8 template: foreach+if (or data+if) doesn't work

### ISSUE THREAD

**Issue by szkrd** [knockout/knockout#456]
I'm not sure if it works unintentionally in FF/Chrome/IE9, but it's pretty helpful (because this way I won't need another extra tag):

``` html
<div data-bind="template: { name: 'person-template', foreach: buyers, if: showBuyers}"></div>
<div data-bind="template: { name: 'person-template', foreach: sellers, if: showSellers}"></div>
```

Unfortunately this doesn't work in IE7/IE8:

```
SCRIPT5022: Unable to parse bindings.
Message: SyntaxError: Expected identifier, string or number;
Bindings value: template: { name: 'person-template', foreach: buyers, if: showBuyers} 
knockout-min.js, line 6 character 15
```

Example:
http://jsfiddle.net/szabi/ajqEm/

**Comment by mbest** [comment]
The only way to fix this is to preprocess the binding to add the quotes. Given the age and the simple workaround, I'll close this.
