### ISSUE TITLE
options binding on ios 5.1(iphone)

### ISSUE THREAD

**Issue by joeldart** [knockout/knockout#472]
1. go to http://jsfiddle.net/85FQC/10/ on an iphone
2. change the month 
3. try to select the day
4. in the native ios selctor see how all the options are purple and checked 

this doesn't appear to be a problem on ipad. tested iphone 5.1 and iphone simulator 4.3.

**Comment by SteveSanderson** [comment]
I know that technically this might still count as a bug (in iOS 5 Safari, not KO) that in theory KO could take steps to work around, but realistically I don't think any of us are going to prioritise working around iOS 5 issues, so I'll close this now.

If this is still an active concern for anyone (especially someone with a pull request that fixes it), please reopen!
