### ISSUE TITLE
computed can be attached to multiple nodes and dispose when all are removed

### ISSUE THREAD

**Issue by mbest** [knockout/knockout#484]
Many times, a computed is used to track dependencies that affect bindings of multiple nodes. Currently there's not a good way to handle this in Knockout. A single node is tracked directly (usually a parent node, or the first of sibling nodes) and the others are handled by a `disposeWhen` function.

This change will improve the existing code that needs to track multiple nodes and will provide a way to handle observable view models as part of #321.

**Comment by SteveSanderson** [comment]
@mbest, can we close this or are you aware of scenarios where we'd still have an issue?

**Comment by mbest** [comment]
Yeah, no need to keep this open.
