### ISSUE TITLE
jquery mobile checkbox list issue: cannot check

### ISSUE THREAD

**Issue by gonglei** [knockout/knockout#491]
With knockoutjs and jquery mobile, I need to create a list of checkboxes from an array. It seems the checkbox list is rendered, but it did not respond to click. http://jsfiddle.net/9zx7F/

I used a fieldset tag with data-role of controlgroup to build the list. I tried ul with listview as well, same issue.

Edit: further details - I found it seems related to timing of ko.applyBindings happens. I created a page with same code running on my localhost, it was okay. Then added a timer around ko.applyBindings, the issue happened again. http://jsfiddle.net/gonglei/9zx7F/12/

**Comment by SteveSanderson** [comment]
I'm guessing it's OK to close this now, but please reopen if you disagree.
