### ISSUE TITLE
Knockout property binding is interupted if a property value is invalid.

### ISSUE THREAD

**Issue by eugentorica** [knockout/knockout#525]
Browser IE 8
Observed behaviour after executing the code bellow a exception occurs that interrupts setting other properties from value array thus making page unsable.

Code starting with line 2409 in knockout-2.1.0-debug.js
```
ko.bindingHandlers['style'] = {
    'update': function (element, valueAccessor) {
        var value = ko.utils.unwrapObservable(valueAccessor() || {});
        for (var styleName in value) {
            if (typeof styleName == "string") {
                var styleValue = ko.utils.unwrapObservable(value[styleName]);
                element.style[styleName] = styleValue || ""; // Empty string removes the value, whereas null/undefined have no effect				
            }
        }
    }
};
```
Line where error occured:
```element.style[styleName] = styleValue || ""; ```

Value of the property: "#FFECA8   "
Normal property: "#FFECA8"

**Comment by SteveSanderson** [comment]
Agreed with @jrsearles, hence closing as duplicate.
