### ISSUE TITLE
When attribute is converted to ko_code, entities not un-escaped

### ISSUE THREAD

**Issue by scriby** [knockout/knockout#534]
If I have an escaped HTML entity in a data-bind, attribute, it breaks the rendered ko javascript. The following shows an example of the rendered source. The &lt; in the for loop causes a syntax error.

I don't normally escape less than and greater than signs in attributes, but it's necessary in this case to work around an issue in an html parser I'm using.

```
{{ko_code ((function() { return ko.templateRewriting.applyMemoizedBindingsToNextSibling(function() {             return (function() { return { 'options': $parent.matchingTerms,'optionsText': function(item) {
                                    var index;
                                    for (index = 0; index &lt; $parent.matchingTerms().length; index++) {
                                        if ($parent.matchingTerms()[index] === item) {
                                            return index;
                                        }
                                    }
                               },'optionsValue': 'termId','value': termId, '_ko_property_writers' : { 'options' : function(__ko_value) {  $parent.matchingTerms = __ko_value; }, 'value' : function(__ko_value) {  termId = __ko_value; } }  } })()         }) })()) }}<select >
```

**Comment by SteveSanderson** [comment]
Thanks for reporting this, and sorry you didn't get a timely response. I'm guessing this is no longer an active concern, but could you let us know if it is?

**Comment by SteveSanderson** [comment]
For anyone else reading, there's pretty much zero chance this would affect you, as this relates to the ancient string-based templating technique that has been out of use since KO 2.0.
