### ISSUE TITLE
Copying a binding handler doesn't copy all properties

### ISSUE THREAD

**Issue by mbest** [knockout/knockout#566]
For example, if I do something like this

```
ko.bindingHandlers.when = ko.bindingHandlers.if;
```

the new `when` binding won't act exactly like `if`. It won't be usable in virtual elements and won't be blocked in rewritten templates.

It has to be copied like this

```
ko.bindingHandlers.when = ko.bindingHandlers.if;
ko.expressionRewriting.bindingRewriteValidators.when = ko.expressionRewriting.bindingRewriteValidators.if;
ko.virtualElements.allowedBindings.when = ko.virtualElements.allowedBindings.if;
```

which isn't exactly obvious.

Although I understand the reasons for some properties of the binding being in other objects, it makes this particular pattern difficult to do cleanly.

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
