### ISSUE TITLE
Template 'if' condition causes leak in IE7 on observable update

### ISSUE THREAD

**Issue by johnhunter** [knockout/knockout#596]
When a template contains an if condition on an observable, and that observable value changes from its initial state, a memory leak is triggered in IE7. The leak is due to refs to elements that do not get recovered after the page unloads. It appears that any dom element that has a binding is leaked once the trigger condition occurs.

This occurs with both jQuery templates and Underscore templates.

* Browser: IE7
* Libaries: Knockout 2.1.0, JQuery 1.7.2,  jQuery Templates 1.0.0pre (classed as v2 in ko)
* Test environment: sIEve-0.0.8 (http://home.wanadoo.nl/jsrosman/) 
* Test case: http://jsfiddle.net/johnhunter/DPcnH/  (will need to run this outside of jsfiddle to avoid side effects in IE7)

**Steps to reproduce:**

1. Save test case to local server.
2. Load in sIEve.
3. Reload page.

**Expected result:**
'testval true' displayed after 1 sec. No leaked elements detected.

**Actual result:**
'testval true' displayed after 1 sec. Four elements leaked: body, div and 2 p tags.

The test case gist is:

	<script type="text/html" id="test-template">
	    <p>template rendered</p>
	    {{if testval }}
	        <p>testval true</p>
	    {{/if}}
	</script>
	<script>
	var vm = {
	    testval: ko.observable(false)
	};
	setTimeout(function(){
	    // the following triggers the leak
	    vm.testval(true);
	}, 1000);
	ko.applyBindings(vm);
	</script>

The change in testval triggers leaking of elements in the template and in other parts of the page. When the testval is not modifed then no leaks occur.

The leaked body and div elements may to be due to manipulation of those elements by jQuery following the template re-render. See related jQuery issue (http://bugs.jquery.com/ticket/12171).

Changing the test case to use ko native templates causes the leak even if the observable value is not modified.

* KO template case: (http://jsfiddle.net/johnhunter/L2CfF/)
* Underscrore template case: (http://jsfiddle.net/johnhunter/GP65p/)

Since this seems to happen with several templating engines it seems likely to be either an issue with Knockout or Jquery.

**Comment by SteveSanderson** [comment]
Thanks for reporting this, and sorry we didn't follow up on this when it was first posted. Over the years we've addressed various memory leaks and I'm not aware of any actively remaining ones (at least, not in such a mainstream case as described here).

I'll close this to tidy up, but please reopen if you think there is still an issue here!

**Comment by johnhunter** [comment]
No problem Steve. Its an avoidable issue if IE7 is an important target.
