### ISSUE TITLE
Need a way to define alias with 'as' for '$root'

### ISSUE THREAD

**Issue by DzenisevichK** [knockout/knockout#613]
What about a way to define alias for `$root` keyword? May be via some options for `ko.applyBinding`?
With this we will have possibility to avoid using `$*` keywords at all in html markup...

This related to [this commit](https://github.com/SteveSanderson/knockout/commit/548a2450eb518b0ffdbfa8c82ee341834fe39e3e)...

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!

**Comment by homer2** [comment]
https://github.com/knockout/knockout/issues/1792 is a related issue also discussing this.
