### ISSUE TITLE
Native support for Handlebars template engine

### ISSUE THREAD

**Issue by levani** [knockout/knockout#622]
I think knockout should have native support for some of the most popular template engines out there and Handlebars would be definitely the best choice. Knockout documentation only covers the integration process with jquery tmpl which is in beta state and isn't actively developed any more and Underscore.js, which, in my opinion isn't so powerful as Handlebars in terms of to be used as a template engine.

**Comment by frialex** [comment]
On thing I've noticed over the years about the knockout data-bind syntax that have has an advantage over the handlebars format is for exploring the DOM of an unfamilar app:

if for example I see the following in the DOM

 `<input data-bind="value: cashToSendToFri" />`

I know where the data is coming from and going to with just a glance. I know that if an initial value is filled out then it must come from the viewmodel property "cashToSendToFri" and if change happens thats where it also ends up.

This is just awesome information when your dealing with an application that you did not write.

Just my two cents

**Comment by fluffysquirrels** [comment]
For those that find this thread with a web search, [Knockout.Punches](https://mbest.github.io/knockout.punches/) has many cool features, including Handlebars-style templates that it converts to Knockout bindings before binding.
