### ISSUE TITLE
Consider adding toString or render method to computed observables

### ISSUE THREAD

**Issue by AndersMalmgren** [knockout/knockout#631]
I've made an extender for numbers in our system to ensure that numbers are formated correctly using the Globalize library, it looks like this

```javascript
    ko.extenders.isNumeric = function (target, opt) {
        var result = ko.computed({
            read: function () {
                return Globalize.format(target());
            },
            write: function (value) {
                if (value.substr) {
                    value = Globalize.parseFloat(value);
                }

                target(value);
            }
        });

        result.raw = target;
        return result;
    };
```
The read function will make sure that the returned string is formated correctly, and the write function will ensure that only numbers are written to the observable (If a user input numbers from a textbox etc)

The problem is if logic in the viewmodel tries to read the observable it will get the formatted string not the actual number, I've added the raw member on the computed observable that exposes the actual number, this is ugly and prone to bugs if other dev's in the team misses this.

Cant we add a render or toString function on the computed observable, if this function is defined use it when rendering the view if not use the read function. This way the view gets the correct formated value, but if you from the viewmodel do this.myNumber() it will get the actual number

**Comment by SteveSanderson** [comment]
Glad you got a satisfactory way of doing this! Closing to tidy up.
