### ISSUE TITLE
move toString in ko.utils.setHtml

### ISSUE THREAD

**Issue by greggreenhaw** [knockout/knockout#637]
In this function if you moved the 

  if (typeof html != 'string')
                html = html.toString();

into the non jquery condition then you could pass dom elements and other items into this binding. jQuery handles this anyway

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
