### ISSUE TITLE
Update 'Control types examples' to show 1-2 more LOB scenarios

### ISSUE THREAD

**Issue by dealproc** [knockout/knockout#659]
http://knockoutjs.com/examples/controlTypes.html

I'm trying to construct a checklist from an ObservableArray and I don't see how you go about assigning IDs to the checkboxes so that you can do the ```<label for="..."> text</label>``` to attach it as you would expect.

The way I've done it to-date is to wrap the label around the input, which is fine, but jQuery UI doesn't seem to be able to handle that to create the toggle buttons.

Any advice?

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
