### ISSUE TITLE
Obtain containing list from contextFor

### ISSUE THREAD

**Issue by brianmhunt** [knockout/knockout#662]
It would be helpful to have a way to access the containing list for an object based on the current context. For example, from [Using unobtrusive event handlers](http://knockoutjs.com/documentation/unobtrusive-event-handling.html):

```javascript
$(".remove").live("click", function() {
    viewModel.items.remove(ko.dataFor(this));
});
```

Would ideally become, where `$list` is an attribute added that contains the current list (if there is one):

```javascript
$(".remove").live("click", function() {
    ko.contextFor(this).$list.remove(ko.dataFor(this));
});
```

In this way the changing of lists could become more generic.

At present the only way to accomplish the above seems to be (and I stand to be corrected) by passing the name of the list to the event somehow e.g. using a `data-remove-from="list-name"` attribute on the clicked tag, and you end up with something like this:

```javascript
$(".remove").live("click", function() {
    list_name = $(this).attr("data-remove-from");
    ko.contextFor(this).$parent[list_name].remove(ko.dataFor(this));
});
```

This would seem to violate the DRY principle (i.e. re-typing the list name that would invariably be repeated from the `foreach: list_name`).

I am of course open to suggestions, but since `$index` is in the bindings context, it would also seem to be intuitive that the list containing the current binding would also be there. (And perhaps it is somehow and I have overlooked it).

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
