### ISSUE TITLE
Need for versioned documentation

### ISSUE THREAD

**Issue by sebmartin** [knockout/knockout#689]
There is an increasing need for the site documentation to be versioned, or at least keep a snapshot of older versions.  We cannot always upgrade right away and it is difficult to tell which portion of the documentation is relevant with which version.

Perhaps having links to the documentation as it was before each release would be sufficient.  Alternatively, new features should be decorated with the minimum version required.

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
