### ISSUE TITLE
Need to set value of an observable silently

### ISSUE THREAD

**Issue by majidkorai** [knockout/knockout#711]
I saw there was another similiar kind of requrest made almost 2 years ago. I am going to make this request once again.

Sometimes you want to set value of an observable and dont want it notify the change to its subscribers.

The situation where i needed this was that, in my view model i have two observables, i have set an extender on them, which checks duplication by making an ajax call. 
Now i needed to set the default value for them and want there should go only one ajax request, i tried throttle too, but it didnt solve my problem, I think there must be some other cases too when we need to set the value of an observable and dont want it to trigger the change.

this can be like folliwng:

var a = ko.observable("foo");
a("bar",false); // Doesn't trigger notification to subscribers

**Comment by gitn00b1337** [comment]
Hi, I have this issue too. It's not a major problem, but with this ability I could cut down code.

For example, I have an observable "roomDetails". In it I store an object with all the details of the current room. However, different rooms require different properties, so if a user changes rooms (e.g. a group to an event room) then the properties within the object don't match the current page bindings and knockout screams. 

Now you could argue that it's not the best to merge models, but IMO on a small thing like this it saves plenty of time. What would actually be great is a deferred binding - 

so in the example I just gave you do something like

ko.utils.deferred( 
.... add code to update knockout properties e.g. app.roomDetails( myNewDetails ); app.currentRoomTemplateName('event');
)

// and NOW they all bind along with the HTML. I don't know if that's a possibility, but I prefer the "don't ask, don't get" methodology ;)

Thanks
