### ISSUE TITLE
foreach binding requires dense array

### ISSUE THREAD

**Issue by johnjbarton** [knockout/knockout#726]
The knockout documentation: 
http://knockoutjs.com/documentation/foreach-binding.html
generally leads me to think that the foreach binding can handle any JS array. But an array that has no entry at index 0 (zero) fails:
http://jsfiddle.net/johnjbarton/Wzs4E/2/
I assume that any sparse array will fail.

If this were clear in the documentation I would have avoided wasting some time...

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
