### ISSUE TITLE
Request for Information: Cross Window Bindings

### ISSUE THREAD

**Issue by obezuk** [knockout/knockout#735]
Hey everyone,

I'm looking to add cross window bindings to my Knockout application. I found an article from over a year ago https://groups.google.com/forum/?fromgroups=#!topic/knockoutjs/Q7MEy0Rh3H8 which explores a fix added to provide the functionality.

However this is for a much older version of Knockout, and I'm struggling to information on how to do this with Knockout 2.2.0.

At the moment I am trying to apply the binding to the external window in this way:

````var ExternalWindow = window.open('window.html','secondary','width=640,height=480');````

````// Knockout View Model Logic````

````ko.applyBindings(viewModel); // Bindings are behaving normally on the main window.````
````ko.applyBindings(viewModel, ExternalWindow.document.body); No updates on the external window.````

I am wondering how this feature has developed since it was first addressed in January of 2011.

Thanks for your assistance,

-- Tim

**Comment by SteveSanderson** [comment]
Seems like this was resolved adequately. Thanks everyone!
