### ISSUE TITLE
foreach binding's afterRenderItem has wrong this

### ISSUE THREAD

**Issue by EisenbergEffect** [knockout/knockout#740]
The 'this' modifier inside of afterRenderItem is bound to the binding object on which foreach lives. This causes it to lose it's proper context. If, for example, you have an object with your afterRenderItem callback declared on the prototype, and it references this, it will break when used with foreach's afterRenderItem setting. It would be nice to see the current context preserved.

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
