### ISSUE TITLE
hasfocus doesn't honor an undefined value

### ISSUE THREAD

**Issue by evoskuil** [knockout/knockout#770]
It would be easier to work with hasfocus if it didn't force a result of focus or blur. Currently one must generate the entire binding within a function in order to conditionally set the focus (without blur).

When hasfocus is false, the focus will be lost *as a person types* into the input, making the false behavior seem most pointless in the first place. So it's hard to imagine a practical compatibility issue with such a change.

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
