### ISSUE TITLE
Mapping 'copy' option - can't get it to work

### ISSUE THREAD

**Issue by johnwest80** [knockout/knockout#771]
I'm sure it must be me, but I can't for the life of me get the copy option to work.  Please take a look at the fiddle below and see if you can tell what I'm doing wrong.  It seems to be ignoring my mapping options and converting the test property into an observable anyway.

I'd appreciate any insight.  Thx.  

http://jsfiddle.net/johnwest80/EzaLL/1/

* As an aside, my hope is that mapping 2700 javascript objects with 6 properties apiece will map faster if I copy most of them.  We'll see...

**Comment by SteveSanderson** [comment]
Thanks for posting, and sorry we never responded.

I'll close this as it's an issue about the mapping plugin rather than KO itself, and it's very unlikely you're still waiting for an answer :)
