### ISSUE TITLE
Easy "hide until rendered" option

### ISSUE THREAD

**Issue by scriby** [knockout/knockout#773]
Hi,

We use inline templates, and with base knockout there's a flashing effect as the base HTML gets bound into the rendered template. An approach I've adopted is to add this to the root element I'm binding against:

`<div id="binding-start" style="visibility:hidden" data-bind="attr: { 'style': 'visibility:visible' }" />`
(I used to do style: '', but oddly it doesn't work in IE8, so I had to go with the more verbose form shown)

I would love it if knockout could provide some base way to the "hide until rendered" functionality. Something like this would work well for us, but there are probably some other options:

`<div id="binding-start" class="ko-not-rendered">`

We can define the ko-not-rendered class to be hidden in our stylesheet, and knockout can remove the class when it binds.

Thanks for considering this,

Chris

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
