### ISSUE TITLE
Binding not causing reflow in Chrome & FF

### ISSUE THREAD

**Issue by Narnain** [knockout/knockout#774]
I am combining knockout, knockout mapping, and Zurb Foundation, and am not sure which of these is causing this issue.

If I bind to a viewmodel where the mapping happens within the class and update an observable binding with a value with a space in it, the binding works as expected, but Chrome and Firefox do not reflow on the content change causing the text to wrap.  

Fiddle below will explain it better!

http://jsfiddle.net/narnain/HgSzZ/

**Comment by SteveSanderson** [comment]
Thanks for posting, and sorry we never responded. I tried your jsFiddle just now and don't see any problems, so presumably this is fixed by newer browsers and was not a KO issue.

Please reopen if you think there's still an issue!
