### ISSUE TITLE
Allow access to the current array through the binding context

### ISSUE THREAD

**Issue by ashmind** [knockout/knockout#780]
In `foreach` binding, it would be useful to provide any way to find out what array binding is in.
If that is implemented, code similar to
  `<button type="button" data-bind="click: ???.remove" class="delete">×</button>`
or an unobtrusive implementation with `contextFor` would be reusable in any `foreach`.

My proposal would be to use `$array` for that.
It seems that implementation would be quite easy, just another line in `executeTemplateForArrayItem`.

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
