### ISSUE TITLE
Empty text nodes in webkit causing slow foreach rendering

### ISSUE THREAD

**Issue by rniemeyer** [knockout/knockout#793]
There have been a couple of examples lately demonstrating that empty text nodes in named or anonymous templates can cause a performance issue when rendering lots of items in a `foreach`.

Examples:
<http://stackoverflow.com/questions/14124372/ko-observablearray-is-very-slow-for-1000-div-elements>

<https://groups.google.com/d/topic/knockoutjs/gJYItfxSy-g/discussion>

We had a previous pull request that aimed to address it at #709 that was eventually closed.

I think that we need to revisit whether we can at least safely identify and strip leading and trailing empty text nodes.

**Comment by SteveSanderson** [comment]
I'll close this now, but please reopen if there's still an issue!
