### ISSUE TITLE
Improve support for components (Feature Request / Proposal)

### ISSUE THREAD

**Issue by ghost** [knockout/knockout#794]
Currently, if you want to create a reusable UI component with KnockoutJS, you need at least 2 things:

1. manually create the stopBinding handler and add to the root of the component - This is required because we don't know where the component will be used and if it is inside another model. The stopBinding is required because if the markup is there when the page is loaded, it will throw errors about binding things it shouldn't know about.

2. replace all the "with" with "template : { if: ... data: ... afterRender: ... }" - This is necessary because if you bind events to anything inside your component (and if it is a component, you will have them), you don't know when the nodes will be removed by another parent viewmodel.

Those are completely doable in the current versions, but require us having to deal with issues that don't need to be there in the first place, and add time to developement and complexity to the code. There are some simple additions that could really help.

Here are my proposals:

1. Include "stopBinding" in the official package or similar functionality - this should be core functionality and not a custom binding. We really need to be able to add something to the page and don't worry if a parent model will try to bind to it. I would go with something like "context: root/new/empty" instead of "stopBinding: true", as it would make more sense when reading root markup of a component

2. Add new "if/with" binding handlers or an option to the current ones that instead of removing the elements, will just apply "display: none", and when in that state, will use the "stopBinding" functionality to avoid binding to its children. Maybe something like "with: someObject, removeChldren: false". This would solve 90% of our constantly rebinding of events to elements that don't need to be removed from screen.

3. Make "afterRender" available for any bindingHandler that causes elements to be re-rendered (like if/with), as sometimes we won't have the option to just hide them.

**Comment by SteveSanderson** [comment]
Yay, we did this :) This functionality is in KO 3.2.0+.
