### ISSUE TITLE
Publish an "edge" Knockout build automatically

### ISSUE THREAD

**Issue by mbest** [knockout/knockout#808]
For some time, we haven't been publishing an edge build. Previously we could manually "publish" this by committing an update to the build output files in Github. But since #761, that's not possible anymore.

One thought is to have an automatic "edge" build that would be updated by Travis CI. I found [an article](http://about.travis-ci.org/blog/2012-12-18-travis-artifacts/) that talks about doing something like this.

If we do set this up through Travis CI, we'd need to make sure that the the "master" branch build isn't overwritten by builds for other branches.

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
