### ISSUE TITLE
afterAdd fires on remove

### ISSUE THREAD

**Issue by TheHaff** [knockout/knockout#812]
Hi i have two separate lists of elements, they both have afterAdd bindings and they fire on remove as well... is there anything i can do to avoid the remove triggering?

**Comment by SteveSanderson** [comment]
Thanks for posting, and sorry we never really answered.

I'm pretty sure `afterAdd` doesn't behave badly in current KO versions, and I'm also pretty confident you aren't still waiting for an answer on this after so long! So I'll close this now, but please reopen if you still think there's a KO bug.
