### ISSUE TITLE
Add shortcut "ifdata" option to the template binding

### ISSUE THREAD

**Issue by NickLeippe** [knockout/knockout#817]
For the simple case where you want if: and data: options to pass the same value to the template binding, add an "ifdata" option that combines their functionalities into one--saving having to type the value twice in the data-bind (which may also save some duplicate evaluations if the value is nested).

**Comment by SteveSanderson** [comment]
Isn't that what `with` does?

I'll close this because it was such a long time ago that you're unlikely still to be waiting, and others haven't reported a similar need, but please reopen and let us know if you think there's still something we should do here.

**Comment by NickLeippe** [comment]
I should hope they are *not* the same.
If data contains an falsy value with should *not* behave like if! It should still show the inner template and allow the falsy value to be used.
The idea for "ifdata" is just that, if data is falsy then behave like if and don't render the inner template, but combined with data to eliminate an additional evaluation.
