### ISSUE TITLE
publish non minified and non debug build

### ISSUE THREAD

**Issue by paglias** [knockout/knockout#835]
I think that along with the current minified and debug build a version of knockout non minified but also non debug should be published.

I, and I think a lot of people, like to use a non minified file in development and then minify the source for production use. 

But actually there isn't a non minified build except the debug build that I don't like to use and it is also discouraged on the knockout website

**Comment by SteveSanderson** [comment]
I think any changes we make to the build mechanism in #1369 will change the picture so much that this particular discussion will no longer be applicable, and we aren't likely to implement this (#835) before #1369. Therefore I'll close this to keep us focused on the build changes we plan more imminently, but if anyone disagrees, please reopen this!
