### ISSUE TITLE
Observable Array must be string type in order to bind to input control checked value

### ISSUE THREAD

**Issue by KitchenPC** [knockout/knockout#838]
Some background: http://stackoverflow.com/questions/14823093/nothing-selected-when-creating-data-bound-check-boxes-with-knockout-js

Repro:

Using the following model:

var ViewModel = function ()
{
   this.areas = [{AreaId: 1, Name: 'Test 1'}, {AreaId: 2, Name: 'Test 2'}, {AreaId: 3, Name: 'Test 3'}];
   this.AreasImpacted = ko.observableArray([1, 2]);
};

And the following HTML:

<span class="areas" data-bind="foreach: areas">
  <label><input type="checkbox" data-bind="value: AreaId, checked: $parent.AreasImpacted" /><span data-bind="text: Name"></span></label>
</span>

I expect the first and second checkboxes to be checked.  However, nothing is checked.

If you change the model to:

 this.AreasImpacted = ko.observableArray(['1', '2']);

Then it will work.

This is due to a binding bug in checked.js:

element.checked = ko.utils.arrayIndexOf(value, element.value) >= 0;

element.value will always be a string.

Fix: Knockout.js should implement a better comparison to compare numeric values to strings.

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
