### ISSUE TITLE
[Feature Request] Support child elements for template binding

### ISSUE THREAD

**Issue by smmousavi1** [knockout/knockout#842]
Currently, I am using Knockout templates, and it is well-designed & well-implemented for GUI components. Nice Job!
However, I see the lack of support for "Container components" (components that can have children components which are defined when they are used). Sample can be "table" or "panel" and so on.

Since the above explanation is a little difficult to understand, I show it with an example.
Suppose we have a template like following code:

	<script id="template1" type="text/html">
		Some template contents here ...
		<span id = "insertChildren"/>
	</script>

=> Point is that the above template has defined a place to insert children (span with id: "insertChildren").

Then when we want to use above template, we will have a code like:

	<div data-bind="template: { name: 'template1'}">  
		<table><tr><td>Children to be added</td></tr></table>
	</div>              		

=> Point is that the above div tag has some children.

Then when Knockout renders the above template, it will add the following line:

		<table><tr><td>Children to be added</td></tr></table>

in the place of span with id: "insertChildren".

Using the above approach, it will be possible to have "Container Components" to be implemented by Knockout templates.

I know that "afterRender" can be used to implement above matter, and the implementation will be something like following:

	<div data-bind="template: { name: 'template1', afterRender: addChildrenFunc}">  
		<table><tr><td>Children to be added</td></tr></table>
	</div>              		

	viewModel.addChildrenFunc= function(elements) {
		var targetElement = // use JQuery to find the span with id: "insertChildren"
		var addElements = // use JQuery to find the children of template
		targetElement.append(addElements);
		// Refresh Dom Node strucutet, like following
		ko.utils.emptyDomNode( ... );
	} 

The basic idea is like above, but, I have not been successful to implement it yet. I will be thankful if you can give me some advice. Or introduce me if there is any Knockout plugin that can do this job (I know about "Knockout.External-Template-Engine", but it can't solve my problem).

P.S.: It may be irrelevant, but, the above idea is like the idea of "Composite Components" of JSF 2.0 (Java Server Faces) for JAVA. The "composite:insertChildren" tag in following URL of JSF 2.0 does the above job, but, it is for server side, but, I need same implementation in client side:

http://docs.oracle.com/javaee/6/tutorial/doc/giqzr.html

Thanks in advance ...

**Comment by SteveSanderson** [comment]
Thanks for the suggestion. We did implement this functionality with "components" in KO 3.2.0 :)
