### ISSUE TITLE
arrayIndexOf twice as fast when using for loop instead of native method

### ISSUE THREAD

**Issue by cspotcode** [knockout/knockout#854]
`arrayIndexOf` seems to be much faster when it uses a for loop than when it calls the native `indexOf` method.

http://jsperf.com/knockout-arrayindexof-variants/2

I noticed that `arrayIndexOf` checks for the existence of a native `indexOf` method each and every time it's called.  I figured I would make it faster by only performing the test once when knockout is loaded, which prompted me to create the jsperf benchmark.

Has this already been discussed?  If not, I can investigate further, hopefully testing on more browsers.  I currently only have access to Firefox, Chrome, Opera, Mobile Safari 5, and IE9.

I can also look at LoDash and see how it chooses to implement `indexOf`.  It's possible that my benchmark is too simplistic.

**Comment by SteveSanderson** [comment]
Thanks for discussing this! Given that we didn't conclusively find any one technique to be universally faster, I'll close this. But if anyone has views on perf improvements targetted at 2015 browsers please let us know.
