### ISSUE TITLE
optionsText binding uses innerHTML, but should use innerText

### ISSUE THREAD

**Issue by mikeeast** [knockout/knockout#88]
When using option data that contains ampersand characters, the optionsText binding does not properly handle the value since it is unencoded. 

This is because the optionsText binding uses innerHTML to set the option text. If changed to innerText, it would be encoded properly. 

Found in build 1.2.0 in file defaultBindings.js, row 204.

Change 
option.innerHTML = optionText.toString();
To
option.innerText = optionText.toString();

**Comment by harrjm** [comment]
@mbest you are amazing, this is exactly what I needed and I thought it to be impossible (or atleast it is to me) to implement. You just saved boatloads of time and struggle.
