### ISSUE TITLE
CSP compliancy

### ISSUE THREAD

**Issue by paglias** [knockout/knockout#903]
I don't really know if this is something workable or not: using KO with the new Chrome apps (and I think some other environment too) require to use a sandbox page which doesn't have access to all the powerful `chrome` specific apis because it uses `new Function` I think for the execution of template code.

It would be possible to give an option to disable the usage of this? I mean the context of `data-bind` could be parsed in some other way, we would lost the ability to use inline javascript in `data-bind` but that, I think, is only a good thing because using inline javascript is not exactly the best practice.

**Comment by tHBp** [comment]
Is there any plan to support CSP out of the box in future versions of Knockout JS?
@mbest @rniemeyer

**Comment by holietenk** [comment]
Any updates on this issue?

**Comment by brianmhunt** [comment]
TKO, in alpha now, supports CSP out of the box.

**Comment by KarstenDambekalns-eaton** [comment]
> TKO, in alpha now, supports CSP out of the box.

Years later, I come and wonder what "TKO" might have been…
