### ISSUE TITLE
Value binding on two dropdowns with partially shared options breaks selection

### ISSUE THREAD

**Issue by tyrsius** [knockout/knockout#923]
I am not sure why anyone would ever do something like this (I found the fiddle on StackOverflow), but there is a bug in the `value` binding when applied to multiple `select` nodes with partially common options. Here is [the fiddle](http://jsfiddle.net/tyrsius/HSLmX/). 

Notice that if you pick an option that is not common, the label updates and the other `select` is fine. You can continue to change the options of either until you pick a common option. 

If you pick an option that _is_ common, you cannot change the selection to a non-common option after that. The `value` binding stops the change from happening.

``` html
<select class="string-match-dropdown" data-bind='value: qualifier'>
    <option value="*">contains</option>
    <option value="^">starts with</option>
    <option value="$">ends with</option>
    <option value="=">is exactly</option>            
</select>
<select class="date-money-match-dropdown" data-bind='value: qualifier'>
    <option value="gt">></option>
    <option value="lteq">&lt;=</option>
    <option value="=">is exactly</option>
    <option value="$">ends with</option>
</select>
<label class="match-label" data-bind='html: qualifier'></label>
```

``` javascript
var vm = {
    qualifier: ko.observable()
}
ko.applyBindings(vm);
```

**Comment by mbest** [comment]
The fix is to use `valueAllowUnset: true`. http://jsfiddle.net/mbest/HSLmX/1/

Perhaps we will make `valueAllowUnset` default to true in a future release.
