### ISSUE TITLE
KO has "special AMD handling, and I'm not sure that's playing well"...

### ISSUE THREAD

**Issue by thinkloop** [knockout/knockout#938]
Hello, I asked a question on stack regarding loading the KnockoutFire plugin using RequireJS and it was mentioned that KO has "special AMD handling, and I'm not sure that's playing well with the things I've tried (using shim and exports)": http://stackoverflow.com/questions/16227151/how-to-load-a-js-lib-that-defines-a-global-and-depends-on-another-3rd-party-lib

What is the cleanest way to load KO and KnockoutFire using RequireJS? Are there simple modifications KnockoutFire could do to make it easier for everyone?

**Comment by AlexGodofsky** [comment]
Just spent a couple hours figuring out that this was my problem, in exactly the same situation as @slaneyrw.
