### ISSUE TITLE
Passing array index in observableArray.remove

### ISSUE THREAD

**Issue by vicary** [knockout/knockout#948]
We have a script porting from underscore JS to knockout, and want to make use of the convenient `observableArray.remove()` method.

But in contrast to many iterator implementations `function(item, index, list)`, the `.remove()` only gives the first parameter... which somewhat limits the usability.

Code sample:
```JavaScript
var view = {
    list: ko.observableArray('item1', 'item2', 'item3')
  };

view.remove(function(item, index, list) {
  return index > 2; // working with index
});
```

Is this possible?

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
