### ISSUE TITLE
comment syntax shorthands

### ISSUE THREAD

**Issue by mbest** [knockout/knockout#961]
I'm proposing two forms of shortened syntax for control-flow comments, or virtual elements.

The first is for when the virtual element has no content. Instead of 

    

You could use

    

The second is for when a virtual element is immediately followed by another. Instead of 

    
        <td data-bind="text: units"></td>
    
    
        <td>none</td>
    

You could use

    
        <td data-bind="text: units"></td>
    
        <td>none</td>
    

Please discuss.

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!
