### ISSUE TITLE
detach elements in foreach binded list stopped working after upgrade

### ISSUE THREAD

**Issue by ahmadhisham** [knockout/knockout#978]
Dears,

I recently upgraded knockout from v2.1.0 to v2.2.1

I created http://jsfiddle.net/8fTLq/ to help re-produce the issue. The whole idea is that I need to be able to append elements to a foreach binded list and temporarily remove them from the beginning. Later I have to re-insert the removed elements at their original position (at beginning).

Now this was running with the old version 2.1.0 (check the jsfiddle). However after upgrade to 2.2.1, it stopped working (specifically deleting elements at beginning).

Any idea about how to handle this is highly appreciated. 

Thanks

**Comment by SteveSanderson** [comment]
Thanks for reporting this, and sorry we never really responded. KO 2.2.1 is extremely outdated now, and I've no idea whether you'd still face any issues with current KO, and you're probably not still waiting for an answer. So, I'll close this for tidiness, but please repoen if you think there's still an issue!
