### ISSUE TITLE
extend arrayGetDistinctValues to support predicate for comparison

### ISSUE THREAD

**Issue by danatcofo** [knockout/knockout#996]
be able to pass a predicate function into arrayGetDisntinctValues so that its possible to get distinct based upon attribute of objects in the array.

This is my implementation => https://github.com/danatcofo/knockout/commit/c9b9753f7bf617adc961d3a60c86a2a529609cee

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!

**Comment by courtenay** [comment]
@danatcofo can you make a PR for this? :)

**Comment by danatcofo** [comment]
@courtenay I can, its been a long time since I've touched this however and haven't added any test cases or such.  On the other hand we've been using this at Stackify for almost a year here without issue or error.  Do you require the test cases to accept the pull request?

**Comment by courtenay** [comment]
@danatcofo I'm just another user here like you.. I misread the dates, this is all from over a year ago! I had to look up why I'm using this, too. (found it!) I think it's a super useful addition to KO. 

If you make a PR from your fork/patch, I'll add some tests to it :)
